import { Activity, Bot, Cable, Clock3, KeyRound, RefreshCcw, ShieldCheck, Webhook } from "lucide-react";
import { ProviderLogs, RetryQueue, SecretsTable, SyncTimeline, WebhookTable } from "@/features/platform/integrations/components/IntegrationUI";
import { WorkforceChatPanel } from "@/features/platform/openai/runtime/ChatPanel";
import type { OpenAIHealth } from "@/features/platform/openai/domain/models";
import type { ConversationSnapshot } from "@/features/platform/openai/runtime/models";
import type { EnterpriseIntegrationSnapshot } from "../types";
import { BusinessConnectionsDirectory } from "./BusinessConnectionsDirectory";

const card = "rounded-3xl border border-vds-border/70 bg-vds-surface/70 shadow-xl shadow-vds-shadow/10 backdrop-blur-xl";
export function EnterpriseIntegrationDashboard({ data, history, health }: { data: EnterpriseIntegrationSnapshot; history: ConversationSnapshot; health: OpenAIHealth }) {
  return <main className="mx-auto w-full max-w-[120rem] space-y-8 px-4 py-7 sm:px-6 lg:px-8"><header className={`${card} relative overflow-hidden p-6 sm:p-8`}><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_10%_10%,var(--vds-color-primary-soft),transparent_40%)]"/><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-vds-primary">Founder Portal · AI workforce infrastructure</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Business Connections</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-vds-muted">One executive control center for the business systems powering your AI workforce. Review connection health, synchronization evidence, and the capabilities each provider unlocks.</p><p className="mt-4 text-xs text-vds-subtle" aria-live="polite">Updated {new Date(data.generatedAt).toLocaleString()} · {data.dataAvailable ? "Workspace telemetry available" : data.degradedReason}</p></header>
  <BusinessConnectionsDirectory providers={data.providers} generatedAt={data.generatedAt}/>
  <section className="grid gap-6 xl:grid-cols-2"><div><Heading icon={Webhook} title="Webhook Center" detail="Incoming events, failures, retries and dead-letter visibility"/><WebhookTable items={data.dashboard.webhooks}/></div><div><Heading icon={RefreshCcw} title="Retry queue" detail="Provider-aware retry metadata and safe replay operations"/><RetryQueue items={data.dashboard.retries}/></div></section>
  <section className="grid gap-6 xl:grid-cols-2"><div><Heading icon={Clock3} title="Sync engine" detail="Incremental, full, manual and scheduled provider operations"/><div className="grid gap-3 sm:grid-cols-2">{["Incremental sync","Full sync","Manual sync","Scheduled sync"].map((label)=><article className={`${card} p-4`} key={label}><h3 className="text-sm font-medium">{label}</h3><p className="mt-2 text-xs leading-5 text-vds-muted">Rate limited, conflict-aware, audited and queued for retry when the provider reports a retryable failure.</p></article>)}</div><SyncTimeline items={[...data.syncHistory]}/></div><div><Heading icon={KeyRound} title="Secret management" detail="Metadata only; secret values are never returned"/><SecretsTable items={data.dashboard.secrets}/></div></section>
  <section><Heading icon={Activity} title="Structured provider diagnostics" detail="Sanitized operations, latency and failure evidence"/><ProviderLogs items={data.dashboard.logs}/></section>
  <section><Heading icon={Bot} title="AI Integration Assistant" detail="Founder-only, evidence-based and recommendation-only"/><WorkforceChatPanel employee="executive-ai" initial={history} health={health} initialPrompt="Which providers are disconnected or failing, and what evidence-based action should I take?"/></section>
  <aside className={`${card} flex items-start gap-3 p-5 text-sm text-vds-muted`}><ShieldCheck className="mt-0.5 size-5 shrink-0 text-vds-success" aria-hidden="true"/><p>Credentials remain environment-managed or encrypted by the existing secret service. Feature flags, consent, tenant isolation, audit logging, rate limits and provider-specific authorization remain enforced.</p></aside></main>;
}
function Heading({icon:Icon,title,detail}:{icon:typeof Cable;title:string;detail:string}){return <div className="mb-4"><div className="flex items-center gap-2"><Icon className="size-4 text-vds-primary" aria-hidden="true"/><h2 className="text-lg font-semibold">{title}</h2></div><p className="mt-1 text-xs text-vds-muted">{detail}</p></div>}
