import { Activity, Bot, Cable, Clock3, KeyRound, RefreshCcw, ShieldCheck, Webhook } from "lucide-react";
import { ProviderLogs, RetryQueue, SecretsTable, SyncTimeline, WebhookTable } from "@/features/platform/integrations/components/IntegrationUI";
import { WorkforceChatPanel } from "@/features/platform/openai/runtime/ChatPanel";
import type { OpenAIHealth } from "@/features/platform/openai/domain/models";
import type { ConversationSnapshot } from "@/features/platform/openai/runtime/models";
import type { EnterpriseIntegrationSnapshot, FounderProviderState } from "../types";

const card = "rounded-3xl border border-vds-border/70 bg-vds-surface/70 shadow-xl shadow-vds-shadow/10 backdrop-blur-xl";
export function EnterpriseIntegrationDashboard({ data, history, health }: { data: EnterpriseIntegrationSnapshot; history: ConversationSnapshot; health: OpenAIHealth }) {
  const healthy = data.providers.filter((item) => item.state === "Healthy").length, errors = data.providers.filter((item) => item.state === "Error").length, queued = data.dashboard.retries.filter((item) => item.status === "queued").length, failedWebhooks = data.dashboard.webhooks.filter((item) => ["failed", "dead_letter"].includes(item.status)).length, averageLatency = average(data.providers.map((item) => item.latencyMs)), averageErrors = average(data.providers.map((item) => item.errorRate === null ? null : item.errorRate * 100));
  const kpis = [["Connected providers", healthy],["Disconnected providers",data.providers.filter((item)=>item.state==="Disconnected").length],["Provider health",errors ? `${errors} errors` : healthy ? "Operational" : "Awaiting connections"],["Last sync",latest(data.providers.map((item)=>item.lastSync))],["API latency",averageLatency===null?"Unavailable":`${averageLatency} ms`],["Error rate",averageErrors===null?"Unavailable":`${averageErrors.toFixed(1)}%`],["Webhook status",failedWebhooks?`${failedWebhooks} require review`:"Operational"],["Retry queue",queued],["Token expiration",data.providers.some((item)=>item.tokenExpiration)?"Review required":"Not reported"],["Sync history",data.syncHistory.length]] as const;
  return <main className="mx-auto w-full max-w-[120rem] space-y-8 px-4 py-7 sm:px-6 lg:px-8"><header className={`${card} relative overflow-hidden p-6 sm:p-8`}><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_10%_10%,var(--vds-color-primary-soft),transparent_40%)]"/><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-vds-primary">Founder Portal · Enterprise integrations</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Integration Hub</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-vds-muted">Provider-neutral connections, health, webhooks, retries, sync operations and secret metadata. Disconnected adapters never simulate production traffic.</p><p className="mt-4 text-xs text-vds-subtle" aria-live="polite">Updated {new Date(data.generatedAt).toLocaleString()} · {data.dataAvailable ? "Workspace telemetry available" : data.degradedReason}</p></header>
  <section aria-label="Integration key performance indicators" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{kpis.map(([label,value], index)=><article className={`${card} min-h-28 p-4 motion-safe:animate-[fade-in_.45s_ease-out_both]`} style={{animationDelay:`${index*30}ms`}} key={label}><p className="text-[10px] uppercase tracking-[.13em] text-vds-subtle">{label}</p><p className="mt-4 text-xl font-semibold">{value}</p></article>)}</section>
  <section><Heading icon={Cable} title="Provider directory" detail="Live health is authoritative; configured-but-unvalidated providers remain Warning."/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.providers.map((item)=><article className={`${card} p-5`} key={item.code}><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{item.name}</h3><p className="mt-1 text-xs text-vds-subtle">{item.category} · v{item.version}</p></div><Status state={item.state}/></div><p className="mt-4 min-h-10 text-xs leading-5 text-vds-muted">{item.reason}</p><dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><Metric label="Last sync" value={item.lastSync?new Date(item.lastSync).toLocaleString():"Never"}/><Metric label="Latency" value={item.latencyMs===null?"Unavailable":`${item.latencyMs} ms`}/><Metric label="Error rate" value={item.errorRate===null?"Unavailable":`${(item.errorRate*100).toFixed(1)}%`}/><Metric label="Webhook" value={item.webhookStatus}/></dl></article>)}</div></section>
  <section className="grid gap-6 xl:grid-cols-2"><div><Heading icon={Webhook} title="Webhook Center" detail="Incoming events, failures, retries and dead-letter visibility"/><WebhookTable items={data.dashboard.webhooks}/></div><div><Heading icon={RefreshCcw} title="Retry queue" detail="Provider-aware retry metadata and safe replay operations"/><RetryQueue items={data.dashboard.retries}/></div></section>
  <section className="grid gap-6 xl:grid-cols-2"><div><Heading icon={Clock3} title="Sync engine" detail="Incremental, full, manual and scheduled provider operations"/><div className="grid gap-3 sm:grid-cols-2">{["Incremental sync","Full sync","Manual sync","Scheduled sync"].map((label)=><article className={`${card} p-4`} key={label}><h3 className="text-sm font-medium">{label}</h3><p className="mt-2 text-xs leading-5 text-vds-muted">Rate limited, conflict-aware, audited and queued for retry when the provider reports a retryable failure.</p></article>)}</div><SyncTimeline items={[...data.syncHistory]}/></div><div><Heading icon={KeyRound} title="Secret management" detail="Metadata only; secret values are never returned"/><SecretsTable items={data.dashboard.secrets}/></div></section>
  <section><Heading icon={Activity} title="Structured provider diagnostics" detail="Sanitized operations, latency and failure evidence"/><ProviderLogs items={data.dashboard.logs}/></section>
  <section><Heading icon={Bot} title="AI Integration Assistant" detail="Founder-only, evidence-based and recommendation-only"/><WorkforceChatPanel employee="executive-ai" initial={history} health={health} initialPrompt="Which providers are disconnected or failing, and what evidence-based action should I take?"/></section>
  <aside className={`${card} flex items-start gap-3 p-5 text-sm text-vds-muted`}><ShieldCheck className="mt-0.5 size-5 shrink-0 text-vds-success" aria-hidden="true"/><p>Credentials remain environment-managed or encrypted by the existing secret service. Feature flags, consent, tenant isolation, audit logging, rate limits and provider-specific authorization remain enforced.</p></aside></main>;
}
function Heading({icon:Icon,title,detail}:{icon:typeof Cable;title:string;detail:string}){return <div className="mb-4"><div className="flex items-center gap-2"><Icon className="size-4 text-vds-primary" aria-hidden="true"/><h2 className="text-lg font-semibold">{title}</h2></div><p className="mt-1 text-xs text-vds-muted">{detail}</p></div>}
function Status({state}:{state:FounderProviderState}){const tone=state==="Healthy"?"bg-vds-success-soft text-vds-success":state==="Error"?"bg-vds-danger-soft text-vds-danger":state==="Warning"?"bg-vds-warning/10 text-vds-warning":"bg-vds-elevated text-vds-muted";return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${tone}`}>{state}</span>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-vds-elevated/70 p-2"><dt className="text-vds-subtle">{label}</dt><dd className="mt-1 truncate text-vds-muted" title={value}>{value}</dd></div>}
function average(values:readonly (number|null)[]){const available=values.filter((item):item is number=>item!==null);return available.length?Math.round(available.reduce((sum,item)=>sum+item,0)/available.length):null}
function latest(values:readonly (string|null)[]){const available=values.filter((item):item is string=>Boolean(item)).sort().at(-1);return available?new Date(available).toLocaleString():"Never"}
