import type{CatalogItem}from"@/features/vayon/domain/shared";export const propertyStatuses:readonly CatalogItem[]=["available","reserved","sold","rented","under_negotiation","off_market","archived"].map((code,sortOrder)=>({code,label:{default:code.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ")},active:true,sortOrder}));export const propertyTypes:readonly CatalogItem[]=["apartment","villa","independent_house","penthouse","plot","land","commercial","office","retail","warehouse","industrial","farm_house"].map((code,sortOrder)=>({code,label:{default:code.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ")},active:true,sortOrder}));export const listingTypes:readonly CatalogItem[]=["sale","rent","sale_or_rent"].map((code,sortOrder)=>({code,label:{default:code.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ")},active:true,sortOrder}));export const propertyTabs=["overview","gallery","documents","timeline","activity","internal-notes","leads","offers","marketing","analytics","ai-assistant"]as const;

export const amenityGroups = [
  { label: "Residential", options: [["balcony","Balcony"],["clubhouse","Clubhouse"],["gym","Gym"],["swimming_pool","Swimming Pool"],["play_area","Children’s Play Area"],["garden","Garden"],["servant_room","Staff Room"]] },
  { label: "Building & Security", options: [["elevator","Elevator"],["power_backup","Power Backup"],["security","24/7 Security"],["cctv","CCTV"],["fire_safety","Fire Safety"],["parking","Reserved Parking"],["visitor_parking","Visitor Parking"]] },
  { label: "Commercial", options: [["reception","Reception"],["conference_room","Conference Room"],["loading_dock","Loading Dock"],["freight_elevator","Freight Elevator"],["server_room","Server Room"],["cafeteria","Cafeteria"],["central_air_conditioning","Central Air Conditioning"]] },
  { label: "Utilities", options: [["water_supply","Continuous Water Supply"],["gas_pipeline","Gas Pipeline"],["internet_ready","Internet Ready"],["solar_power","Solar Power"],["waste_management","Waste Management"],["other","Other"]] },
] as const;
export const viewingInstructionGroups = [{ label: "Viewing access", options: [["appointment_required","Appointment Required"],["vacant","Vacant"],["occupied","Occupied"],["contact_agent","Contact Agent"],["contact_owner","Contact Owner"],["notice_24_hours","24 Hours Notice"],["notice_48_hours","48 Hours Notice"],["key_at_office","Key at Office"],["lockbox","Lockbox"],["under_construction","Under Construction"],["anytime","Anytime"],["other","Other"]] }] as const;
export const propertyDocuments = [["sale_deed","Sale Deed"],["occupancy_certificate","Occupancy Certificate"],["completion_certificate","Completion Certificate"],["khata","Khata"],["rera","RERA"],["tax_receipt","Tax Receipt"],["encumbrance","Encumbrance"],["building_approval","Building Approval"],["noc","NOC"],["floor_plan","Floor Plan"],["identity","Identity"],["utility_bills","Utility Bills"],["other","Other"]] as const;
