import "server-only";

import { getBuildMetadata } from "@/lib/infrastructure/build-metadata";
import { log } from "@/lib/observability/logger";
import { FounderRepository } from "../repositories/founder.repository";
import type { FounderChart, FounderInsight, FounderKpi, FounderMarketingChannel, PlatformMetricRow } from "../types";
import { founderContext } from "./founder-context";

const channels = ["Google Ads", "Meta", "LinkedIn", "YouTube", "Organic", "Referral", "Affiliate", "Email", "Direct"] as const;
const metricAliases: Readonly<Record<string, readonly string[]>> = {
  mrr: ["mrr", "monthly_recurring_revenue"], arr: ["arr", "annual_recurring_revenue"], todayRevenue: ["today_revenue", "revenue_today"], totalRevenue: ["total_revenue", "revenue"], conversionRate: ["conversion_rate", "paid_conversion_rate"], ltv: ["customer_lifetime_value", "ltv"], churn: ["monthly_churn", "churn_rate"], aiTokens: ["ai_tokens", "tokens_used"], traffic: ["visitors", "sessions"], retention: ["retention", "retention_rate"], dau: ["daily_active_users", "dau"], mau: ["monthly_active_users", "mau"], pipeline: ["pipeline_value", "pipeline"], winRate: ["win_rate"], averageDeal: ["average_deal", "average_deal_value"], forecast: ["forecast", "forecast_revenue"], demoRequests: ["demo_requests"], enterpriseLeads: ["enterprise_leads"], responseTime: ["api_latency", "response_time"], errorRate: ["error_rate", "api_error_rate"], failedLogins: ["failed_logins"], suspicious: ["suspicious_activity", "suspicious_requests"], auditEvents: ["audit_events"], apiErrors: ["api_errors"],
};

export class FounderService {
  async snapshot() {
    const started = performance.now();
    const { client, user } = await founderContext();
    const repository = new FounderRepository(client);
    const [metrics, activity, organizations, users, activeSubscriptions, trials, expiredSubscriptions, aiConversations, tickets, unreadNotifications] = await Promise.all([
      repository.metrics().catch(() => []), repository.activity(), repository.count("organizations"), repository.count("user_profiles"), repository.count("subscriptions", { status: "active" }), repository.count("subscriptions", { status: "trialing" }), repository.count("subscriptions", { status: "expired" }), repository.count("ai_conversations", { status: "active" }), repository.count("support_sessions", { status: "open" }), repository.count("notification_events", { status: "unread" }),
    ]);
    const latest = latestMetrics(metrics);
    const kpis: FounderKpi[] = [
      kpi("mrr", "Monthly Recurring Revenue", metric(latest, "mrr"), "currency"), kpi("arr", "Annual Recurring Revenue", metric(latest, "arr"), "currency"), kpi("today-revenue", "Today's Revenue", metric(latest, "todayRevenue"), "currency"), kpi("total-revenue", "Total Revenue", metric(latest, "totalRevenue"), "currency"), kpi("organizations", "Total Organizations", organizations, "count"), kpi("users", "Total Users", users, "count"), kpi("active-subscriptions", "Active Subscriptions", activeSubscriptions, "count"), kpi("trials", "Trial Organizations", trials, "count"), kpi("expired", "Expired Subscriptions", expiredSubscriptions, "count"), kpi("conversion", "Conversion Rate", metric(latest, "conversionRate"), "percent"), kpi("ltv", "Customer Lifetime Value", metric(latest, "ltv"), "currency"), kpi("churn", "Monthly Churn", metric(latest, "churn"), "percent"), kpi("ai-conversations", "Active AI Conversations", aiConversations, "count"), kpi("ai-tokens", "AI Tokens Used", metric(latest, "aiTokens"), "count"), kpi("tickets", "Open Support Tickets", tickets, "count"), kpi("notifications", "Unread Notifications", unreadNotifications, "count"),
    ];
    const sales = [kpi("pipeline", "Pipeline", metric(latest, "pipeline"), "currency"), kpi("deals", "Deals", latest.get("deals")?.value ?? null, "count"), kpi("win-rate", "Win Rate", metric(latest, "winRate"), "percent"), kpi("average-deal", "Average Deal", metric(latest, "averageDeal"), "currency"), kpi("forecast", "Forecast", metric(latest, "forecast"), "currency"), kpi("demo-requests", "Demo Requests", metric(latest, "demoRequests"), "count"), kpi("enterprise-leads", "Enterprise Leads", metric(latest, "enterpriseLeads"), "count")];
    const security = [kpi("failed-logins", "Failed Logins", metric(latest, "failedLogins"), "count"), kpi("suspicious", "Suspicious Activity", metric(latest, "suspicious"), "count"), kpi("audit", "Audit Events", metric(latest, "auditEvents"), "count"), kpi("api-errors", "API Errors", metric(latest, "apiErrors"), "count")];
    const snapshot = { kpis, activity, charts: charts(metrics), marketing: marketing(latest), sales, health: health(latest), security, insights: insights(kpis, sales), generatedAt: new Date().toISOString() };
    log("founder.dashboard.viewed", { actorId: user.id, latencyMs: Math.round(performance.now() - started), unavailableMetrics: [...kpis, ...sales, ...security].filter((item) => item.status === "unavailable").length });
    return snapshot;
  }
}

function latestMetrics(rows: readonly PlatformMetricRow[]) { const map = new Map<string, PlatformMetricRow>(); for (const row of rows) if (!map.has(row.metric)) map.set(row.metric, row); return map; }
function metric(rows: ReadonlyMap<string, PlatformMetricRow>, key: string) { for (const alias of metricAliases[key] ?? [key]) { const value = rows.get(alias)?.value; if (value !== undefined && Number.isFinite(value)) return value; } return null; }
function kpi(id: string, label: string, value: number | null, unit: string): FounderKpi { return { id, label, value, unit, status: value === null ? "unavailable" : "measured" }; }
function charts(rows: readonly PlatformMetricRow[]): FounderChart[] { return ["mrr", "arr", "revenue", "subscriptions", "customers", "dau", "mau", "retention", "churn_rate", "traffic"].map((id) => ({ id, label: id.replaceAll("_", " "), unit: rows.find((row) => row.metric === id)?.unit ?? "count", points: rows.filter((row) => row.metric === id).slice(0, 12).reverse().map((row) => ({ label: new Date(row.recordedAt).toLocaleDateString("en", { month: "short", day: "numeric" }), value: row.value })) })); }
function marketing(rows: ReadonlyMap<string, PlatformMetricRow>): FounderMarketingChannel[] { return channels.map((channel) => { const key = channel.toLowerCase().replaceAll(" ", "_"); const value = (name: string) => rows.get(`marketing_${key}_${name}`)?.value ?? null; const spend = value("spend"), revenue = value("revenue"), conversions = value("conversions"); return { channel, spend, revenue, roas: spend && revenue !== null ? revenue / spend : null, roi: spend && revenue !== null ? ((revenue - spend) / spend) * 100 : null, clicks: value("clicks"), ctr: value("ctr"), conversions, costPerLead: spend && conversions ? spend / conversions : null, costPerCustomer: value("cost_per_customer") }; }); }
function health(rows: ReadonlyMap<string, PlatformMetricRow>) { const build = getBuildMetadata(); return ["Database", "Realtime", "Storage", "Functions", "Queues", "Workers", "Cron", "API"].map((name) => { const value = rows.get(`${name.toLowerCase()}_health`)?.value; return { name, state: value === undefined ? "unavailable" as const : value >= 1 ? "healthy" as const : "degraded" as const, value: value === undefined ? "No live measurement" : value >= 1 ? "Operational" : "Attention required" }; }).concat([{ name: "Response Time", state: metric(rows, "responseTime") === null ? "unavailable" as const : "healthy" as const, value: metric(rows, "responseTime") === null ? "No live measurement" : `${metric(rows, "responseTime")} ms` }, { name: "Error Rate", state: metric(rows, "errorRate") === null ? "unavailable" as const : "healthy" as const, value: metric(rows, "errorRate") === null ? "No live measurement" : `${metric(rows, "errorRate")}%` }, { name: "Build Version", state: "healthy" as const, value: build.version }]); }
function insights(kpis: readonly FounderKpi[], sales: readonly FounderKpi[]): FounderInsight[] { const unavailable = [...kpis, ...sales].filter((item) => item.status === "unavailable").length; return [{ id: "daily-brief", title: "Daily brief", summary: unavailable ? `${unavailable} executive measurements are unavailable. Connect authoritative sources before making decisions.` : "Executive measurements are available for review.", severity: unavailable ? "medium" : "low", recommendationOnly: true }, { id: "revenue-forecast", title: "Revenue forecast", summary: sales.find((item) => item.id === "forecast")?.value === null ? "Forecast is unavailable until authoritative pipeline evidence is recorded." : "Review the measured forecast against current pipeline coverage.", severity: "medium", recommendationOnly: true }, { id: "risk-detection", title: "Risk detection", summary: "Review churn, failed payments, support demand, and platform health before approving growth actions.", severity: "high", recommendationOnly: true }, { id: "growth", title: "Growth suggestion", summary: "Compare measured channel ROAS and conversion before reallocating spend. No campaign changes are automatic.", severity: "low", recommendationOnly: true }]; }
