import { forwardRef, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { Search } from "lucide-react";
const field = "vds-focus min-h-11 w-full rounded-xl border border-[var(--vds-color-border)] bg-vds-input px-3 py-2.5 text-sm leading-5 text-[var(--vds-color-foreground)] shadow-sm shadow-vds-shadow outline-none transition duration-200 placeholder:text-[var(--vds-color-subtle)] hover:border-vds-border-strong disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-vds-danger aria-invalid:ring-1 aria-invalid:ring-vds-danger";
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function Input({ className = "", ...props }, ref) { return <input ref={ref} className={`${field} ${className}`} {...props}/> });
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({ className = "", ...props }, ref) { return <textarea ref={ref} className={`${field} min-h-28 resize-y ${className}`} {...props}/> });
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(function Select({ className = "", children, ...props }, ref) { return <select ref={ref} className={`${field} ${className}`} {...props}>{children}</select> });
export const MultiSelect = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(function MultiSelect({ className = "", children, ...props }, ref) { return <select ref={ref} multiple className={`${field} min-h-32 ${className}`} {...props}>{children}</select> });
export const SearchInput = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function SearchInput({ className = "", ...props }, ref) { return <span className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--vds-color-subtle)]" aria-hidden="true"/><input ref={ref} type="search" className={`${field} pl-10 ${className}`} {...props}/></span> });
interface ChoiceProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "type"> { readonly label: ReactNode }
export const Checkbox = forwardRef<HTMLInputElement, ChoiceProps>(function Checkbox({ label, className = "", ...props }, ref) { return <label className="inline-flex items-center gap-2 text-sm text-[var(--vds-color-muted)]"><input ref={ref} type="checkbox" className={`vds-focus size-4 rounded border-[var(--vds-color-border)] ${className}`} {...props}/><span>{label}</span></label> });
export const Radio = forwardRef<HTMLInputElement, ChoiceProps>(function Radio({ label, className = "", ...props }, ref) { return <label className="inline-flex items-center gap-2 text-sm text-[var(--vds-color-muted)]"><input ref={ref} type="radio" className={`vds-focus size-4 border-[var(--vds-color-border)] ${className}`} {...props}/><span>{label}</span></label> });
export function Switch({ checked, onCheckedChange, label, disabled }: { readonly checked: boolean; readonly onCheckedChange: (checked: boolean) => void; readonly label: string; readonly disabled?: boolean }) { return <button type="button" role="switch" aria-checked={checked} aria-label={label} disabled={disabled} onClick={() => onCheckedChange(!checked)} className={`vds-focus relative h-6 w-11 rounded-full border border-[var(--vds-color-border)] transition ${checked ? "bg-[var(--vds-color-primary)]" : "bg-vds-surface/[.07]"}`}><span className={`absolute top-0.5 size-5 rounded-full bg-vds-surface shadow transition-transform ${checked ? "translate-x-4.5" : "translate-x-0.5"}`}/></button> }
