import { Button } from "@/features/platform/design-system";
import { BrandIcon } from "@/components/brand";
import Link from"next/link";import type{ReactNode}from"react";import type{Brand,Feature,Module,NavigationItem,SettingsSection}from"../types";
export function BuilderPage({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:ReactNode}){return <div className="mx-auto w-full max-w-[96rem] px-5 py-7 sm:px-8 sm:py-9 xl:px-10"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-vds-primary">{eyebrow}</p><div className="mt-3 flex flex-col gap-3 border-b border-vds-border/[0.07] pb-7"><h1 className="text-3xl font-semibold tracking-[-0.04em] text-vds-foreground sm:text-4xl">{title}</h1><p className="max-w-3xl text-sm leading-6 text-vds-muted">{description}</p></div><div className="mt-7">{children}</div></div>}
export function MetricCard({label,value,detail,href}:{label:string;value:string|number;detail:string;href?:string}){const content=<div className="rounded-3xl border border-vds-border/[0.08] bg-vds-surface/[0.035] p-5 transition hover:border-vds-accent-border hover:bg-vds-surface/[0.05]"><p className="text-xs font-medium uppercase tracking-[0.14em] text-vds-muted">{label}</p><p className="mt-4 text-3xl font-semibold tracking-tight text-vds-foreground">{value}</p><p className="mt-2 text-xs leading-5 text-vds-muted">{detail}</p></div>;return href?<Link href={href}>{content}</Link>:content}
export function ModuleGrid({items}:{items:readonly Module[]}){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className="rounded-3xl border border-vds-border/[0.08] bg-[var(--vds-color-surface)] p-5"><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-2xl bg-vds-primary-soft text-sm font-bold text-vds-primary">{item.icon}</span><Status value={item.status}/></div><h2 className="mt-5 text-lg font-semibold text-vds-foreground">{item.name}</h2><p className="mt-2 text-sm leading-6 text-vds-muted">{item.description}</p><div className="mt-5 flex flex-wrap gap-2 text-[11px] text-vds-muted"><Chip>{item.category}</Chip><Chip>v{item.version}</Chip><Chip>{item.dependencies.length} dependencies</Chip><Chip>{item.enabled?"Enabled":"Disabled"}</Chip></div></article>)}</div>}
export function FeatureGrid({items}:{items:readonly Feature[]}){return <div className="grid gap-4 md:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-3xl border border-vds-border/[0.08] bg-vds-surface/[0.035] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-vds-foreground">{item.name}</h2><Status value={item.enabled?"enabled":"disabled"}/></div><p className="mt-2 text-sm text-vds-muted">{item.description}</p><div className="mt-4 flex flex-wrap gap-2">{item.beta&&<Chip>Beta</Chip>}{item.premium&&<Chip>Premium</Chip>}{item.enterprise&&<Chip>Enterprise</Chip>}{item.aiEnabled&&<Chip>AI enabled</Chip>}{!item.visible&&<Chip>Hidden</Chip>}</div></article>)}</div>}
export function NavigationCanvas({items}:{items:readonly NavigationItem[]}){return <div className="grid gap-6 lg:grid-cols-[18rem_1fr]"><div className="rounded-3xl border border-vds-border/[0.08] bg-[var(--vds-color-surface)] p-4"><p className="px-3 pb-3 text-xs uppercase tracking-widest text-vds-subtle">Sidebar preview</p>{[...items].sort((a,b)=>a.order-b.order).map((item,index)=><div key={item.id} className="mb-2 flex items-center gap-3 rounded-2xl border border-vds-border/[0.06] bg-vds-surface/[0.035] px-3 py-3"><span className="text-vds-subtle">⋮⋮</span><span className="grid size-7 place-items-center rounded-lg bg-vds-primary-soft text-xs text-vds-primary">{item.icon}</span><span className="text-sm text-vds-secondary">{item.label}</span><span className="ml-auto text-[10px] text-vds-subtle">{index+1}</span></div>)}</div><div className="rounded-3xl border border-dashed border-vds-accent-border bg-vds-primary/[0.025] p-6"><p className="text-sm font-medium text-vds-foreground">Drag-and-drop ready surface</p><p className="mt-2 text-sm leading-6 text-vds-muted">Items expose stable IDs, surface, order, visibility, feature, module, and permission metadata. Reordering is presentation-only until a persistence adapter is approved.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{["Topbar","Quick Actions","Dashboard Cards","Tabs","Menus","Context Menus"].map(x=><div key={x} className="rounded-2xl border border-vds-border/[0.06] p-4 text-xs text-vds-muted">{x}</div>)}</div></div></div>}
export function BrandPreview({brand}:{brand:Brand}){return <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-vds-border/[0.08] bg-[var(--vds-color-surface)] p-6"><p className="text-xs uppercase tracking-widest text-vds-subtle">Brand preview</p><div className="mt-8 flex items-center gap-4"><BrandIcon size="lg"/><div><h2 className="text-xl font-semibold text-vds-foreground">{brand.companyName}</h2><p className="text-sm text-vds-muted">{brand.supportEmail}</p></div></div><Button variant="primary" disabled title="Preview only" className="mt-8 rounded-2xl px-5 py-3 text-sm font-semibold">Primary action</Button></div><dl className="grid grid-cols-2 gap-3">{Object.entries({Typography:brand.typography,"Border radius":brand.borderRadius,Icons:brand.icons,Theme:brand.themeId}).map(([k,v])=><div key={k} className="rounded-2xl border border-vds-border/[0.07] p-4"><dt className="text-xs text-vds-subtle">{k}</dt><dd className="mt-2 text-sm text-vds-secondary">{v}</dd></div>)}</dl></div>}
export function SettingsGrid({sections}:{sections:readonly SettingsSection[]}){return <div className="grid gap-5 lg:grid-cols-2">{sections.map(section=><section key={section.id} className="rounded-3xl border border-vds-border/[0.08] bg-vds-surface/[0.03] p-5"><h2 className="font-semibold text-vds-foreground">{section.title}</h2><p className="mt-1 text-sm text-vds-muted">{section.description}</p><div className="mt-5 space-y-3">{section.fields.map(field=><div key={field.id} className="rounded-2xl border border-vds-border/[0.06] bg-vds-input px-4 py-3"><div className="flex justify-between gap-3"><span className="text-sm text-vds-secondary">{field.label}</span><Chip>{field.type}</Chip></div><p className="mt-1 text-xs text-vds-subtle">{String(field.defaultValue??"Configurable")}</p></div>)}</div></section>)}</div>}
function Status({value}:{value:string}){return <span className="rounded-full border border-vds-success bg-vds-success-soft px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-vds-success">{value}</span>}
function Chip({children}:{children:ReactNode}){return <span className="rounded-full border border-vds-border/[0.07] bg-vds-surface/[0.03] px-2.5 py-1 text-[10px] uppercase tracking-wide text-vds-muted">{children}</span>}

