import { Bot, CalendarDays, Cloud, Contact, Database, HardDrive, KeyRound, MessageCircle, Plug, Share2, WalletCards } from "lucide-react";
import { Badge, Button, ButtonLink } from "@/features/platform/design-system";
import type { IntegrationCenterItem, IntegrationCenterModel } from "./contracts";

const icons = { identity: KeyRound, communication: MessageCircle, calendar: CalendarDays, productivity: Contact, social: Share2, crm: Database, payments: WalletCards, storage: HardDrive, ai: Bot, future: Plug } as const;
const shown = (value: string | null, fallback = "No activity recorded") => value ? (/^\d{4}-\d{2}-\d{2}T/.test(value) ? new Date(value).toLocaleString() : value) : fallback;
const operationalRows = (item: IntegrationCenterItem): readonly [string, string][] => {
  const details = item.operational;
  if (item.definition.code === "google_identity") return [["Connected account", shown(details.connectedAccount, "Not connected")], ["Connected email", shown(details.connectedEmail, "Not connected")], ["Last authentication", shown(details.lastAuthentication)]];
  if (item.definition.code === "gmail") return [["Sync status", item.displayStatus], ["Last sync", shown(item.lastSync)], ["Connected email", shown(details.connectedEmail, "Not connected")]];
  if (item.definition.code === "google_calendar") return [["Selected calendar", shown(details.selectedCalendar, "Connect to select a calendar")], ["Last sync", shown(item.lastSync)], ["Connected email", shown(details.connectedEmail, "Not connected")]];
  if (item.definition.code === "whatsapp_business") return [["Registration", item.connected ? "Connected" : "Registration Pending"], ["Availability", item.connected ? "Connected" : "Coming Soon"]];
  if (item.definition.code === "openai") return [["Connection health", item.displayStatus], ["Configured model", shown(details.configuredModel, "Not configured")], ["Credit availability", shown(details.creditAvailability)], ["Recent request", shown(details.recentRequestStatus)]];
  if (item.definition.code === "paddle") return [["Environment", shown(details.environmentMode)], ["Webhook health", shown(details.webhookHealth)], ["Customer portal", shown(details.portalHealth)]];
  if (item.definition.code === "transactional_email") return [["Configured provider", shown(details.configuredProvider, "Not configured")], ["Delivery health", shown(details.deliveryHealth)], ["Last successful send", shown(details.lastSuccessfulSend)]];
  return [["Last validation", shown(item.lastValidation)], ["Last sync", shown(item.lastSync)]];
};

export function IntegrationCenter({ model, query = "", category = "all", status = "all" }: { model: IntegrationCenterModel; query?: string; category?: string; status?: string }) {
  const term = query.trim().toLowerCase();
  const items = model.providers.filter((item) => (category === "all" || item.definition.category === category) && (status === "all" || item.displayStatus.toLowerCase().replaceAll(" ", "_") === status) && (!term || [item.definition.name, item.definition.code, item.definition.category].some((value) => value.toLowerCase().includes(term))));
  const summary = model.systemHealth;
  return <main className="mx-auto max-w-[96rem] px-5 py-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Operations</p><h1 className="mt-2 text-3xl font-semibold">Integration Center</h1><p className="mt-2 text-vds-muted">Connection, synchronization, and service health for this workspace.</p></div><Badge>{items.length} services</Badge></div>
    <section aria-labelledby="system-health-heading" className="mt-7 rounded-2xl border border-vds-border bg-vds-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Workspace operations</p><h2 id="system-health-heading" className="mt-1 text-xl font-semibold">System Health</h2></div><Badge>{summary.status}</Badge></div><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Connected", summary.connected], ["Syncing", summary.syncing], ["Needs Attention", summary.needsAttention], ["Not Connected", summary.notConnected], ["Coming Soon", summary.comingSoon]].map(([label, value]) => <div key={label} className="rounded-xl bg-vds-elevated p-3"><dt className="text-xs text-vds-subtle">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>)}</dl></section>
    <form className="mt-5 grid gap-3 rounded-2xl border border-vds-border p-4 md:grid-cols-[1fr_12rem_12rem_auto]"><input name="q" defaultValue={query} placeholder="Search services" aria-label="Search services" className="h-11 rounded-xl border border-vds-border bg-vds-input px-4"/><select name="category" defaultValue={category} aria-label="Filter category" className="h-11 rounded-xl border border-vds-border bg-vds-input px-3"><option value="all">All categories</option>{["communication", "ai", "crm", "payments", "storage", "identity", "calendar", "social", "productivity", "future"].map((value) => <option key={value} value={value}>{value}</option>)}</select><select name="status" defaultValue={status} aria-label="Filter status" className="h-11 rounded-xl border border-vds-border bg-vds-input px-3"><option value="all">All statuses</option><option value="connected">Connected</option><option value="syncing">Syncing</option><option value="needs_attention">Needs Attention</option><option value="not_connected">Not Connected</option><option value="coming_soon">Coming Soon</option></select><Button type="submit">Filter</Button></form>
    <section aria-label="Integration services" className="mt-6 grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{items.map((item) => { const Icon = icons[item.definition.category] ?? Cloud; const specialGoogle = ["google_identity", "gmail", "google_calendar"].includes(item.definition.code); return <article key={item.definition.code} className="rounded-2xl border border-vds-border bg-vds-surface p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-vds-primary-soft text-vds-primary"><Icon className="size-5" aria-hidden="true"/></span><div><h2 className="font-semibold">{item.definition.name}</h2><p className="mt-1 text-xs capitalize text-vds-subtle">{item.definition.category}</p></div></div><Badge>{item.displayStatus}</Badge></div><dl className="mt-5 grid gap-3 text-sm">{operationalRows(item).map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 border-b border-vds-border pb-2 last:border-0"><dt className="text-vds-subtle">{label}</dt><dd className="break-all text-right font-medium">{value}</dd></div>)}</dl><div className="mt-5 flex flex-wrap gap-2">{item.definition.settingsHref && item.displayStatus !== "Coming Soon" ? <ButtonLink href={item.definition.settingsHref} size="sm">{item.connected ? "Manage" : "Connect"}</ButtonLink> : <ButtonLink href="/contact?intent=early-access" size="sm">Join Early Access</ButtonLink>}{specialGoogle && item.connected && <ButtonLink href="/vayon/settings/integrations/google" variant="outline" size="sm">Reconnect / Disconnect</ButtonLink>}{["gmail", "google_calendar"].includes(item.definition.code) && item.connected && <ButtonLink href="/platform/integrations/health" variant="outline" size="sm">Test connection</ButtonLink>}</div>{item.diagnostics.lastError && <p role="status" className="mt-4 text-xs text-vds-warning">{item.diagnostics.lastError}</p>}</article>; })}</section>
  </main>;
}
