"use client";
import { WorkspaceContent } from "@/features/platform/design-system/layout/WorkspaceLayouts";


import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/features/platform/design-system";
import { workflowTemplates } from "../library/templates";
import { workflowNodeRegistry } from "../registry/node-registry";
import { WorkflowExecutionPlanner } from "../services/execution-planner.service";
import { WorkflowValidationService } from "../services/validation.service";
import type { WorkflowDefinition, WorkflowNode } from "../domain/contracts";
import { publishWorkflowAction, saveWorkflowAction } from "../actions";

const initial=structuredClone(workflowTemplates[0].definition) as WorkflowDefinition;

export function WorkflowDesigner({definition=initial}:{definition?:WorkflowDefinition}){
  const [workflow,setWorkflow]=useState(definition),[selected,setSelected]=useState<string[]>([]),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[history,setHistory]=useState<WorkflowDefinition[]>([]),[future,setFuture]=useState<WorkflowDefinition[]>([]),[grid,setGrid]=useState(true);
  const validation=useMemo(()=>new WorkflowValidationService().validate(workflow),[workflow]);
  const plan=useMemo(()=>new WorkflowExecutionPlanner().plan(workflow),[workflow]);
  const commit=useCallback((next:WorkflowDefinition)=>{setHistory(items=>[...items,workflow].slice(-30));setFuture([]);setWorkflow(next)},[workflow]);
  const undo=useCallback(()=>{const previous=history.at(-1);if(!previous)return;setFuture(items=>[workflow,...items]);setWorkflow(previous);setHistory(items=>items.slice(0,-1))},[history,workflow]);
  const redo=useCallback(()=>{const next=future[0];if(!next)return;setHistory(items=>[...items,workflow]);setWorkflow(next);setFuture(items=>items.slice(1))},[future,workflow]);
  useEffect(()=>{const handle=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();if(event.shiftKey)redo();else undo()}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="y"){event.preventDefault();redo()}if(event.key==="Escape")setSelected([])};window.addEventListener("keydown",handle);return()=>window.removeEventListener("keydown",handle)},[redo,undo]);
  const addNode=(kind:WorkflowNode["kind"],label:string)=>{const id=`${kind}-${workflow.nodes.length+1}`;commit({...workflow,nodes:[...workflow.nodes,{id,kind,label,position:{x:120+(workflow.nodes.length%3)*240,y:100+Math.floor(workflow.nodes.length/3)*150},configuration:{proposalOnly:true},variableReferences:[]} ]})};
  const select=(id:string,multiple:boolean)=>setSelected(items=>multiple?(items.includes(id)?items.filter(item=>item!==id):[...items,id]):[id]);
  const move=(id:string,x:number,y:number)=>commit({...workflow,nodes:workflow.nodes.map(node=>node.id===id?{...node,position:{x:Math.max(0,Math.round(x/20)*20),y:Math.max(0,Math.round(y/20)*20)}}:node)});
  const connectSelected=()=>{if(selected.length!==2)return;const [sourceNodeId,targetNodeId]=selected;if(workflow.connections.some(edge=>edge.sourceNodeId===sourceNodeId&&edge.targetNodeId===targetNodeId))return;commit({...workflow,connections:[...workflow.connections,{id:`edge-${sourceNodeId}-${targetNodeId}`,sourceNodeId,targetNodeId}]});setSelected([])};
  const loadTemplate=(id:string)=>{const template=workflowTemplates.find(item=>item.id===id);if(template)commit(structuredClone(template.definition) as WorkflowDefinition)};
  return <WorkspaceContent >
    <aside className="rounded-2xl border border-vds-border bg-vds-surface p-4"><h2 className="font-semibold">Node library</h2><p className="mt-1 text-xs text-vds-muted">Drag nodes onto the canvas. State-changing actions remain approval-governed.</p><div className="mt-4 grid grid-cols-2 gap-2">{workflowNodeRegistry.map(node=><Button key={node.kind} type="button" variant="outline" draggable onDragEnd={()=>addNode(node.kind,node.label)} onClick={()=>addNode(node.kind,node.label)} className="min-h-11 justify-start px-3 text-left text-xs">{node.label}</Button>)}</div></aside>
    <section className="min-w-0"><div className="flex flex-wrap items-center gap-2 rounded-2xl border border-vds-border bg-vds-surface p-3"><Button size="sm" variant="outline" onClick={undo} disabled={!history.length}>Undo</Button><Button size="sm" variant="outline" onClick={redo} disabled={!future.length}>Redo</Button><Button size="sm" variant="outline" onClick={()=>setZoom(value=>Math.min(1.75,value+.1))}>Zoom in</Button><Button size="sm" variant="outline" onClick={()=>setZoom(value=>Math.max(.5,value-.1))}>Zoom out</Button><Button size="sm" variant="outline" onClick={()=>setPan({x:0,y:0})}>Center</Button><Button size="sm" variant="outline" onClick={()=>setGrid(value=>!value)}>Grid {grid?"on":"off"}</Button><Button size="sm" variant="outline" onClick={connectSelected} disabled={selected.length!==2}>Connect</Button><Button size="sm" variant="outline" onClick={()=>selected.length&&commit({...workflow,nodes:workflow.nodes.map(node=>selected.includes(node.id)?{...node,groupId:"group-1"}:node)})}>Group</Button><span className="ml-auto text-xs text-vds-muted">{Math.round(zoom*100)}% · {selected.length} selected</span></div>
      <div aria-label="Workflow canvas" tabIndex={0} className={`relative mt-3 h-[38rem] overflow-hidden rounded-2xl border border-vds-border bg-vds-canvas focus-visible:ring-2 focus-visible:ring-vds-focus ${grid?"bg-[radial-gradient(var(--vds-border)_1px,transparent_1px)] bg-[size:20px_20px]":""}`} onWheel={event=>{if(event.ctrlKey){event.preventDefault();setZoom(value=>Math.max(.5,Math.min(1.75,value-event.deltaY*.001)))}else setPan(value=>({x:value.x-event.deltaX,y:value.y-event.deltaY}))}}>
        <div className="absolute inset-0 origin-top-left" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>{workflow.connections.map(edge=>{const source=workflow.nodes.find(node=>node.id===edge.sourceNodeId),target=workflow.nodes.find(node=>node.id===edge.targetNodeId);if(!source||!target)return null;return <svg key={edge.id} className="pointer-events-none absolute inset-0 size-full overflow-visible" aria-hidden="true"><line x1={source.position.x+176} y1={source.position.y+34} x2={target.position.x} y2={target.position.y+34} className="stroke-vds-primary" strokeWidth="2"/></svg>})}{workflow.nodes.map(node=><Button key={node.id} type="button" variant="outline" draggable onDragEnd={event=>move(node.id,(event.clientX-pan.x)/zoom-280,(event.clientY-pan.y)/zoom-190)} onClick={event=>select(node.id,event.shiftKey)} className={`absolute h-auto w-44 flex-col items-start rounded-xl p-3 text-left shadow-vds-sm ${selected.includes(node.id)?"border-vds-accent-border bg-vds-primary-soft":"bg-vds-elevated"}`} style={{left:node.position.x,top:node.position.y}}><span className="text-[10px] uppercase tracking-wider text-vds-muted">{node.kind}</span><strong className="mt-1 block text-sm">{node.label}</strong><span className="mt-2 block text-[10px] text-vds-subtle">Planning only</span></Button>)}</div>
        <div aria-label="Mini-map" className="absolute bottom-3 right-3 h-24 w-36 rounded-xl border border-vds-border bg-vds-overlay/95 p-2"><span className="text-[10px] text-vds-muted">Mini-map</span><div className="relative mt-1 h-14">{workflow.nodes.map(node=><span key={node.id} className="absolute size-2 rounded-sm bg-vds-primary" style={{left:Math.min(120,node.position.x/6),top:Math.min(48,node.position.y/8)}}/>)}</div></div>
      </div>
    </section>
    <aside className="space-y-4"><section className="rounded-2xl border border-vds-border bg-vds-surface p-4"><h2 className="font-semibold">Workflow library</h2><select aria-label="Load workflow template" value={workflowTemplates.find(item=>item.definition.id===workflow.id)?.id??""} onChange={event=>loadTemplate(event.target.value)} className="mt-3 h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3"><option value="">Choose template</option>{workflowTemplates.map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select><p className="mt-3 text-xs text-vds-muted">Version {workflow.version} · {workflow.status}</p></section>
      <section className="rounded-2xl border border-vds-border bg-vds-surface p-4"><h2 className="font-semibold">Validation</h2><p className={`mt-2 text-sm ${validation.valid?"text-vds-success":"text-vds-warning"}`}>{validation.valid?"Valid planning graph":`${validation.issues.length} issue(s)`}</p><ul className="mt-3 space-y-2">{validation.issues.map((issue,index)=><li key={`${issue.code}-${issue.subjectId}-${index}`} className="text-xs text-vds-muted">{issue.severity.toUpperCase()} · {issue.message}</li>)}</ul></section>
      <section className="rounded-2xl border border-vds-border bg-vds-surface p-4"><h2 className="font-semibold">Execution plan</h2><p className="mt-1 text-xs text-vds-muted">Provider-neutral plan with approval checkpoints.</p><ol className="mt-3 space-y-2">{plan.steps.map(step=><li key={step.nodeId} className="rounded-lg bg-vds-elevated p-2 text-xs">{step.order}. {step.kind} · {step.nodeId}</li>)}</ol><form action={saveWorkflowAction} className="mt-4"><input type="hidden" name="definition" value={JSON.stringify(workflow)}/><Button className="w-full">Save definition</Button></form><form action={publishWorkflowAction} className="mt-2"><input type="hidden" name="workflowId" value={workflow.id}/><input type="hidden" name="version" value={workflow.version}/><Button variant="outline" className="w-full" disabled={!validation.valid||workflow.status==="published"}>Publish workflow</Button></form></section>
    </aside>
  </WorkspaceContent>
}
