import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { HubNotification, HubSearchResult, HubTimelineEvent } from "../types";
type Row = Record<string, unknown>;
const sources = [
  ["Organizations", "organizations", "name", "/platform/organizations"], ["Users", "user_profiles", "display_name", "/platform/users"], ["Properties", "properties", "title", "/vayon/properties"], ["Projects", "property_projects", "name", "/vayon/properties/projects"], ["Leads", "leads", "name", "/vayon/leads"], ["Deals", "deals", "name", "/vayon/deals"], ["Campaigns", "creative_campaigns", "name", "/vayon/creative-studio"], ["Invoices", "invoices", "invoice_number", "/vayon/settings/invoices"], ["Payments", "billing_events", "event_type", "/vayon/settings/billing"], ["Subscriptions", "subscriptions", "status", "/vayon/settings/subscription"], ["Knowledge", "knowledge_documents", "title", "/vayon/knowledge"], ["Documents", "documents", "name", "/vayon/storage"], ["Tasks", "tasks", "title", "/vayon/tasks"], ["AI Conversations", "ai_workforce_conversations", "title", "/vayon/ai/history"], ["AI Employees", "ai_employees", "name", "/vayon/ai/employees"], ["Creative Assets", "creative_assets", "name", "/vayon/creative-studio/assets"], ["Support Tickets", "support_sessions", "reason", "/platform/support"], ["Meetings", "meetings", "title", "/vayon/meetings"], ["Site Visits", "site_visits", "customer_label", "/vayon/site-visits"], ["Messages", "communications", "subject", "/vayon/communications"], ["Reports", "executive_reports", "title", "/vayon/analytics/executive"],
] as const;
export class IntelligenceHubRepository {
  constructor(private readonly client: SupabaseClient) {}
  async search(query: string): Promise<readonly HubSearchResult[]> { const terms = query.toLowerCase().replace(/[^a-z0-9\s-]/g, " ").split(/\s+/).filter((term) => term.length > 1).slice(0, 8), needle = terms.join(" ").slice(0, 100); if (!needle) return []; const groups = await Promise.all(sources.map(async ([category, table, label, href]) => { const result = await this.client.from(table).select(`id,${label}`).ilike(label, `%${needle}%`).limit(8); if (result.error) return []; return ((result.data ?? []) as Row[]).map((row) => ({ id: `${table}-${String(row.id)}`, category, title: String(row[label] ?? "Untitled"), description: `Matched ${category.toLowerCase()} evidence`, href: `${href}?q=${encodeURIComponent(String(row[label] ?? needle))}` })); })); return groups.flat(); }
  async notifications(): Promise<readonly HubNotification[]> { const { data, error } = await this.client.from("notification_events").select("id,category,title,body,priority,source_type,read_at,archived_at,created_at").order("created_at", { ascending: false }).limit(100); if (error) return []; return ((data ?? []) as Row[]).map((row) => ({ id: String(row.id), category: category(String(row.category ?? row.source_type ?? "platform")), title: String(row.title ?? "Notification"), body: String(row.body ?? ""), priority: String(row.priority ?? "normal"), severity: severity(String(row.priority ?? "normal")), read: Boolean(row.read_at), archived: Boolean(row.archived_at), createdAt: String(row.created_at) })); }
  async timeline(filters: { organization?: string; workspace?: string; user?: string; module?: string; from?: string; to?: string }): Promise<readonly HubTimelineEvent[]> { let query = this.client.from("activity_events").select("id,organization_id,workspace_id,actor_id,event_type,title,occurred_at").order("occurred_at", { ascending: false }).limit(250); if (filters.organization) query = query.eq("organization_id", filters.organization); if (filters.workspace) query = query.eq("workspace_id", filters.workspace); if (filters.user) query = query.eq("actor_id", filters.user); if (filters.module) query = query.ilike("event_type", `${filters.module}.%`); if (filters.from) query = query.gte("occurred_at", filters.from); if (filters.to) query = query.lte("occurred_at", filters.to); const { data, error } = await query; if (error) return []; return ((data ?? []) as Row[]).map((row) => ({ id: String(row.id), organizationId: row.organization_id ? String(row.organization_id) : null, workspaceId: row.workspace_id ? String(row.workspace_id) : null, userId: row.actor_id ? String(row.actor_id) : null, module: String(row.event_type ?? "platform").split(".")[0] ?? "platform", title: String(row.title ?? "Business activity"), occurredAt: String(row.occurred_at) })); }
}
function category(value: string) { const normalized = value.toLowerCase(); for (const item of ["marketing", "sales", "customer_success", "billing", "security", "platform", "ai", "founder"]) if (normalized.includes(item)) return item.replace("_", " "); return "platform"; }
function severity(priority: string) { return priority === "urgent" || priority === "critical" ? "critical" : priority === "high" ? "high" : priority === "low" ? "low" : "normal"; }
