import type { FounderHealthItem, FounderKpi, FounderSnapshot } from "@/features/platform/founder/types";
import type { MarketingDirectorSnapshot } from "@/features/platform/marketing-director/types";
import type { SalesDirectorSnapshot } from "@/features/platform/sales-director/types";
import type { CustomerGrowthSnapshot } from "@/features/platform/customer-growth/types";

export interface FounderAISignal { readonly name: string; readonly score: number | null; readonly weight: number; readonly reason: string; }
export interface FounderAIPriority { readonly id: string; readonly title: string; readonly impact: "critical" | "high" | "medium" | "low"; readonly expectedImpact: number; readonly confidence: number; readonly evidence: string; readonly recommendationOnly: true; }
export interface FounderAICorrelation { readonly id: string; readonly statement: string; readonly evidence: string; readonly confidence: number; readonly causationClaimed: false; }
export interface MorningBrief { readonly revenue: FounderKpi | null; readonly mrr: FounderKpi | null; readonly arr: FounderKpi | null; readonly newOrganizations: FounderKpi | null; readonly newUsers: FounderKpi | null; readonly trialsStarted: FounderKpi | null; readonly trialsConverted: FounderKpi | null; readonly renewalsDue: FounderKpi | null; readonly renewalsCompleted: FounderKpi | null; readonly churnRisks: number; readonly topCampaign: string; readonly pipelineForecast: FounderKpi | null; readonly supportSummary: string; readonly platformAlerts: number; readonly systemHealth: readonly FounderHealthItem[]; readonly upcomingTasks: FounderKpi | null; }
export interface FounderAISnapshot { readonly founder: FounderSnapshot; readonly marketing: MarketingDirectorSnapshot; readonly sales: SalesDirectorSnapshot; readonly customerSuccess: CustomerGrowthSnapshot; readonly morningBrief: MorningBrief; readonly healthScore: number | null; readonly healthSignals: readonly FounderAISignal[]; readonly priorities: readonly FounderAIPriority[]; readonly correlations: readonly FounderAICorrelation[]; readonly summary: string; readonly reports: readonly { id: string; label: string; formats: readonly ["PDF", "PowerPoint"] }[]; readonly reportKpis: readonly FounderKpi[]; readonly generatedAt: string; }
