"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { leadMutationSchema } from "../validation/lead";
import { LeadService } from "../services/lead.service";
import { LeadAssignmentService } from "../services/lead-assignment.service";
const s=(form:FormData,key:string)=>String(form.get(key)??""), n=(form:FormData,key:string)=>s(form,key)===""?undefined:Number(s(form,key));
function input(form:FormData){return{name:s(form,"name"),phone:s(form,"phone"),email:s(form,"email")||undefined,whatsapp:s(form,"whatsapp")||undefined,preferredLanguage:s(form,"preferredLanguage")||undefined,source:s(form,"source"),budget:n(form,"budget"),currency:s(form,"currency"),buyingPurpose:s(form,"buyingPurposeOther")||s(form,"buyingPurpose")||undefined,propertyType:s(form,"propertyTypeOther")||s(form,"propertyType")||undefined,preferredLocations:s(form,"preferredLocations").split(",").map(value=>value.trim()).filter(Boolean),bedrooms:n(form,"bedrooms"),timeline:s(form,"timeline")||undefined,financing:s(form,"financing")||undefined,propertyInterestIds:form.getAll("propertyInterestIds").map(String).filter(Boolean),assignedAgentId:s(form,"assignedAgentId")||undefined,priority:s(form,"priority"),tags:s(form,"tags").split(",").map(value=>value.trim()).filter(Boolean),status:s(form,"status"),expectedClosing:s(form,"expectedClosing")||undefined}}
function fail(path:string,message:string):never{redirect(`${path}?error=${encodeURIComponent(message)}`)}
function friendly(error:unknown){const raw=error instanceof Error?error.message:String(error);if(/DUPLICATE_LEAD_DETECTED/i.test(raw))return"A lead with this email, phone, or WhatsApp number already exists. Open the existing lead instead of creating a duplicate.";if(/uuid/i.test(raw))return"Please select a valid record from the available choices.";if(/permission|rls|policy/i.test(raw))return"You do not have permission to complete this action.";if(/supabase|database|relation|column|internal|next_redirect/i.test(raw))return"This change could not be saved. Please retry or contact support.";return raw.slice(0,180)||"This change could not be saved."}
export async function createLeadAction(form:FormData){const parsed=leadMutationSchema.safeParse(input(form));if(!parsed.success)fail("/vayon/leads/new",parsed.error.issues[0]?.message??"Please review the lead information.");let id:string;try{id=await new LeadService().create(parsed.data);revalidatePath("/vayon/leads")}catch(error){fail("/vayon/leads/new",friendly(error))}redirect(`/vayon/leads/${id}?success=Lead%20created`)}
export async function updateLeadAction(id:string,form:FormData){const parsed=leadMutationSchema.safeParse(input(form));if(!parsed.success)fail(`/vayon/leads/${id}/edit`,parsed.error.issues[0]?.message??"Please review the lead information.");try{await new LeadService().update(id,Number(s(form,"version")),parsed.data);revalidatePath(`/vayon/leads/${id}`)}catch(error){fail(`/vayon/leads/${id}/edit`,friendly(error))}redirect(`/vayon/leads/${id}?success=Lead%20updated`)}
export async function bulkLeadAction(form:FormData){const ids=form.getAll("leadId").map(String),intent=s(form,"intent");if(!ids.length)fail("/vayon/leads","Select at least one lead.");try{const service=new LeadAssignmentService();if(intent==="assign")await service.assign(ids,s(form,"agentId"));else if(intent==="status")await service.changeStatus(ids,s(form,"bulkStatus"));else await new LeadService().archive(ids);revalidatePath("/vayon/leads")}catch(error){fail("/vayon/leads",friendly(error))}redirect("/vayon/leads?success=Leads%20updated")}
