"use server";
import { randomBytes } from "node:crypto";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { EnvironmentFeatureFlagProvider } from "@/lib/infrastructure/feature-flags";
import { googleCalendarScopes,googleContactsScopes,googleDriveScopes,googleGmailScopes } from "@/features/platform/integrations/identity";
import { integrationContext } from "@/features/platform/integrations/services/integration-context";
import { GoogleOAuthService } from "./services/google-oauth.service";
import { GmailService } from "./services/gmail.service";
import { GoogleCalendarService } from "./services/calendar.service";
import { emailDraftSchema,calendarEventSchema } from "./validation";
import { GmailProductionSyncService } from "@/features/platform/gmail/services/gmail-production-sync.service";
import { CalendarProductionSyncService } from "@/features/platform/google-calendar/services/calendar-production-sync.service";
function val(f:FormData,k:string){return String(f.get(k)??"")}

export async function connectGoogleAction(){const ctx=await integrationContext(),flag=await new EnvironmentFeatureFlagProvider().evaluate(ctx.workspaceId,"google_identity");if(!flag.enabled)redirect("/vayon/settings/integrations/google?error=Google%20Identity%20is%20disabled%20for%20this%20workspace.");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax" as const,path:"/integrations/google/callback",maxAge:600};store.set("google_oauth_state",state,options);store.set("google_oauth_nonce",nonce,options);store.set("google_oauth_verifier",verifier,options);redirect(new GoogleOAuthService().authorizationUrl({state,nonce,codeChallenge:GoogleOAuthService.codeChallenge(verifier)}))}
export async function connectGmailAction(){const ctx=await integrationContext(),flag=await new EnvironmentFeatureFlagProvider().evaluate(ctx.workspaceId,"gmail");if(!flag.enabled)redirect("/vayon/email?error=Gmail%20is%20disabled%20for%20this%20workspace.");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax" as const,path:"/integrations/google/callback",maxAge:600};store.set("google_oauth_state",state,options);store.set("google_oauth_nonce",nonce,options);store.set("google_oauth_verifier",verifier,options);store.set("google_oauth_product","gmail",options);redirect(new GoogleOAuthService().authorizationUrl({state,nonce,codeChallenge:GoogleOAuthService.codeChallenge(verifier),additionalScopes:googleGmailScopes}))}
export async function connectGoogleCalendarAction(){const ctx=await integrationContext(),flag=await new EnvironmentFeatureFlagProvider().evaluate(ctx.workspaceId,"google_calendar");if(!flag.enabled)redirect("/vayon/calendar?error=Google%20Calendar%20is%20disabled%20for%20this%20workspace.");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax" as const,path:"/integrations/google/callback",maxAge:600};store.set("google_oauth_state",state,options);store.set("google_oauth_nonce",nonce,options);store.set("google_oauth_verifier",verifier,options);store.set("google_oauth_product","calendar",options);redirect(new GoogleOAuthService().authorizationUrl({state,nonce,codeChallenge:GoogleOAuthService.codeChallenge(verifier),additionalScopes:googleCalendarScopes}))}
export async function connectGoogleDriveAction(){const ctx=await integrationContext(),flag=await new EnvironmentFeatureFlagProvider().evaluate(ctx.workspaceId,"google_drive");if(!flag.enabled)redirect("/vayon/documents/drive?error=Google%20Drive%20is%20disabled%20for%20this%20workspace.");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax" as const,path:"/integrations/google/callback",maxAge:600};store.set("google_oauth_state",state,options);store.set("google_oauth_nonce",nonce,options);store.set("google_oauth_verifier",verifier,options);store.set("google_oauth_product","drive",options);redirect(new GoogleOAuthService().authorizationUrl({state,nonce,codeChallenge:GoogleOAuthService.codeChallenge(verifier),additionalScopes:googleDriveScopes}))}
export async function connectGoogleContactsAction(){const ctx=await integrationContext(),flag=await new EnvironmentFeatureFlagProvider().evaluate(ctx.workspaceId,"google_contacts");if(!flag.enabled)redirect("/vayon/contacts/google?error=Google%20Contacts%20is%20disabled%20for%20this%20workspace.");const state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),verifier=randomBytes(64).toString("base64url"),store=await cookies(),options={httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax" as const,path:"/integrations/google/callback",maxAge:600};store.set("google_oauth_state",state,options);store.set("google_oauth_nonce",nonce,options);store.set("google_oauth_verifier",verifier,options);store.set("google_oauth_product","contacts",options);redirect(new GoogleOAuthService().authorizationUrl({state,nonce,codeChallenge:GoogleOAuthService.codeChallenge(verifier),additionalScopes:googleContactsScopes}))}
export async function disconnectGoogleAction(){await new GoogleOAuthService().disconnect();revalidatePath("/vayon/settings/integrations/google");redirect("/vayon/settings/integrations/google?success=Google%20Workspace%20disconnected")}
export async function modifyGmailMessageAction(form:FormData){await integrationContext();const id=val(form,"messageId"),operation=val(form,"operation");if(!id)redirect("/vayon/email?error=Invalid%20message");const changes=operation==="archive"?{removeLabels:["INBOX"]}:operation==="delete"?{addLabels:["TRASH"]}:operation==="restore"?{addLabels:["INBOX"],removeLabels:["TRASH","SPAM"]}:operation==="star"?{addLabels:["STARRED"]}:operation==="unstar"?{removeLabels:["STARRED"]}:operation==="important"?{addLabels:["IMPORTANT"]}:operation==="unread"?{addLabels:["UNREAD"]}:{addLabels:[val(form,"label")].filter(Boolean)};await new GmailService().modify(id,changes);revalidatePath("/vayon/email");redirect("/vayon/email?success=Message%20updated")}
export async function createDraftAction(form:FormData){const parsed=emailDraftSchema.safeParse({to:val(form,"to"),subject:val(form,"subject"),body:val(form,"body"),threadId:val(form,"threadId")||undefined,inReplyTo:val(form,"inReplyTo")||undefined});if(!parsed.success)redirect(`/vayon/email?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid email")}`);const state=await new GmailProductionSyncService().state();if(!state.permissions.draftReplies)redirect("/vayon/email?error=Draft%20Replies%20permission%20is%20disabled");await new GmailService().createDraft(parsed.data);revalidatePath("/vayon/email");redirect("/vayon/email?success=Draft%20created")}
export async function sendEmailAction(form:FormData){const parsed=emailDraftSchema.safeParse({to:val(form,"to"),subject:val(form,"subject"),body:val(form,"body"),threadId:val(form,"threadId")||undefined,inReplyTo:val(form,"inReplyTo")||undefined});if(!parsed.success)redirect(`/vayon/email?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid email")}`);const state=await new GmailProductionSyncService().state();if(!state.permissions.sendEmail)redirect("/vayon/email?error=Send%20Email%20permission%20is%20disabled");await new GmailService().send({...parsed.data,to:[parsed.data.to]});revalidatePath("/vayon/email");redirect("/vayon/email?success=Email%20sent")}
export async function createGoogleMeetingAction(form:FormData){const parsed=calendarEventSchema.safeParse({summary:val(form,"summary"),description:val(form,"description")||undefined,start:new Date(val(form,"start")).toISOString(),end:new Date(val(form,"end")).toISOString(),timeZone:val(form,"timeZone"),location:val(form,"location")||undefined,attendees:val(form,"attendees").split(",").map(x=>x.trim()).filter(Boolean)});if(!parsed.success)redirect(`/vayon/calendar?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid event")}`);const state=await new CalendarProductionSyncService().state();if(!state.permissions.createEvents)redirect("/vayon/calendar?error=Create%20Events%20permission%20is%20disabled");await new GoogleCalendarService().create(parsed.data);revalidatePath("/vayon/calendar");redirect("/vayon/calendar?success=Meeting%20created")}
export async function deleteGoogleMeetingAction(form:FormData){await integrationContext();const eventId=val(form,"eventId"),calendarId=val(form,"calendarId")||"primary";if(!eventId)redirect("/vayon/calendar?error=Invalid%20event");const state=await new CalendarProductionSyncService().state();if(!state.permissions.updateEvents)redirect("/vayon/calendar?error=Update%20Events%20permission%20is%20disabled");await new GoogleCalendarService().remove(calendarId,eventId);revalidatePath("/vayon/calendar");redirect("/vayon/calendar?success=Meeting%20deleted")}
