import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
const read=path=>readFileSync(path,"utf8"),properties=read("features/vayon/demo-workspace/property-portfolio/properties.ts"),contracts=read("features/vayon/demo-workspace/property-portfolio/contracts.ts"),service=read("features/vayon/demo-workspace/property-portfolio/portfolio.service.ts"),search=read("features/vayon/demo-workspace/property-portfolio/search.provider.ts"),context=read("features/vayon/demo-workspace/property-portfolio/context.registry.ts"),bar=read("features/vayon/universal-bar/components/UniversalBar.tsx"),home=read("app/vayon/home/page.tsx");

test("portfolio creates exactly 250 uniquely named property identities",()=>{const roots=[...properties.matchAll(/"([^"]+)"/g)].slice(0,25).map(match=>match[1]);assert.equal(roots.length,25);assert.equal(new Set(roots).size,25);assert.equal((properties.match(/type:"[a-z-]+",suffix:/g)??[]).length,10);assert.match(properties,/types\.flatMap\(\(definition,typeIndex\)=>roots\.map/);assert.equal(25*10,250);assert.match(properties,/aurora-property-\$\{slug\(name\)\}/)});
test("all required property types and categories are represented",()=>{for(const value of ["residential-apartment","luxury-villa","commercial-office","retail-space","warehouse","industrial","plot","farm-land","investment-asset","rental-property","ready-to-move","under-construction","pre-launch","luxury","affordable","commercial","investment","rental","premium","featured"])assert.match(contracts+properties,new RegExp(`\\"${value}\\"`))});
test("portfolio validates company sales organization and identity integrity",()=>{for(const evidence of ["Duplicate Aurora property identity","Invalid company relationship","Invalid sales assignment","Invalid organization relationship","developerCompanyId","builderCompanyId","ownerCompanyId","assignedSalesManagerId","assignedSalesAgentId"])assert.match(service+contracts,new RegExp(evidence));assert.match(properties,/company\.category==="developer"/);assert.match(properties,/person\.departmentId==="sales"/)});
test("all business units cities and filters are covered",()=>{for(const unit of ["residential","commercial","luxury","rentals","land","investment"])assert.match(properties,new RegExp(`unit:\\"${unit}\\"`));for(const city of ["Bengaluru","Mumbai","Hyderabad","Pune","Chennai","Delhi"])assert.match(properties,new RegExp(`\\"${city}\\"`));for(const filter of ["city","businessUnit","status","propertyType","priceBand","bedrooms","developerCompanyId","tags"])assert.match(service,new RegExp(`filters\\.${filter}`))});
test("every property is discoverable and context identity is registration only",()=>{assert.match(search,/implements UniversalSearchProvider/);assert.match(search,/readonly scopes=\["properties"\]/);assert.match(search,/auroraPropertyPortfolio\.properties\.filter/);assert.match(bar,/new AuroraPropertySearchProvider\(\)/);assert.match(context,/property\.identity\.context/);assert.doesNotMatch(context,/assemble|generate|createClient|fetch\(/)});
test("deal lead and timeline references remain immutable and empty",()=>{assert.match(contracts,/futureDealReferences:readonly never\[\]/);assert.match(contracts,/futureLeadReferences:readonly never\[\]/);assert.match(contracts,/timelineEvents:readonly never\[\]/);assert.match(properties,/futureDealReferences:Object\.freeze\(\[\]\)/);assert.match(properties,/futureLeadReferences:Object\.freeze\(\[\]\)/);assert.match(properties,/timelineEvents:Object\.freeze\(\[\]\)/)});
test("legacy home redirects and portfolio uses explicit evidence-safe empty guidance",()=>{assert.match(home,/redirect\(destination\)/);assert.match(service,/featuredProperties:Object\.freeze\(\[\]\)/);assert.match(service,/recentlyAddedProperties:Object\.freeze\(\[\]\)/);assert.match(service,/state:"awaiting-connected-business-data"/);assert.match(service,/analytics:"none"/)});
test("portfolio has no persistence external calls AI or event production",()=>{const source=[properties,contracts,service,search,context].join("\n");for(const forbidden of ["createClient(",".from(",".insert(",".update(","fetch(","EventFactory","publish(","openai","anthropic","gemini"])assert.equal(source.includes(forbidden),false,forbidden)});
test("documentation ADR and all local thumbnails exist",()=>{assert.equal(existsSync("docs/RELEASE_1_8_3_PROPERTY_PORTFOLIO.md"),true);assert.equal(existsSync("docs/ADR-0021-property-portfolio.md"),true);for(let index=1;index<=4;index++)assert.equal(existsSync(`public/vayon/demo/properties/property-${index}.svg`),true)});
