import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import ts from 'typescript';
const require=createRequire(import.meta.url);
const record={id:'a1111111-1111-4111-8111-111111111111',title:'Broker QA Property',reference:'QA-EXPERIENCE',propertyType:'apartment',status:'available',description:'',address:{lines:['123 Test Street'],city:'Los Angeles',countryCode:'US'},salePrice:{amount:250000,currency:'USD'},specification:{area:1200,areaUnit:'sqft',amenities:[]},published:false,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-02T00:00:00Z'};
function load(file,stubs){const resolved=resolve(file),filename=existsSync(resolved)?resolved:resolved+'x',mod={exports:{}};const code=ts.transpileModule(readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;new Function('require','module','exports',code)(name=>{if(Object.hasOwn(stubs,name))return stubs[name];if(name.startsWith('@/'))return load(name.slice(2)+'.ts',stubs);if(name.startsWith('.'))return load(resolve(dirname(filename),name+'.ts'),stubs);return require(name);},mod,mod.exports);return mod.exports;}
const stubs={
 'next/link':({children,...props})=>React.createElement('a',props,children),
 'next/navigation':{notFound:()=>{throw new Error('NOT_FOUND')}},
 '@/features/platform/design-system':load('features/platform/design-system/components/core/Actions.tsx',{'next/link':({children,...props})=>React.createElement('a',props,children)}),
 '@/features/vayon/workspace-engine/components/WorkspaceEngine':{WorkspaceTimeline:({events})=>React.createElement('div',null,events.map(e=>React.createElement('p',{key:e.id},e.title)))},
 '@/features/vayon/cross-module-intelligence/ContextualAIActions':{ContextualAIActions:()=>React.createElement('aside',null,'Contextual property actions')},
 '@/features/vayon/enterprise-collaboration/CollaborationSurfaces':{EntityCollaboration:()=>null},
};
async function render(tab,property=record){const {default:Page}=load('app/vayon/properties/[propertyId]/page.tsx',{...stubs,'@/features/vayon/property/services/property.service':{PropertyService:class{async detail(){return property}}}});return renderToStaticMarkup(await Page({params:Promise.resolve({propertyId:record.id}),searchParams:Promise.resolve({tab,success:'Property created'})}));}
test('post-create property renders next actions, real details and no AI welcome or placeholder intelligence',async()=>{const html=await render();for(const label of ['Complete property details','Generate Brochure','Match Buyers','Schedule Viewing','Property details'])assert.ok(html.includes(label),label);for(const absent of ['Meet Your AI Team','Ready for approved','Unavailable','Property Sales Copilot','Recorded listing score'])assert.ok(!html.includes(absent),absent);assert.equal((html.match(/aria-label="Breadcrumb"/g)||[]).length,1);assert.ok(html.indexOf('What should I do next?')<html.indexOf('Property details'));for(const href of ['/vayon/creative/documents','/vayon/property-matching','/vayon/site-visits','/vayon/properties/analytics'])assert.ok(existsSync('app'+href+'/page.tsx'),href);mkdirSync('test-results/property-experience',{recursive:true});writeFileSync('test-results/property-experience/detail.html',html);});
test('insights require evidence and history is secondary',async()=>{assert.ok(!(await render('insights')).includes('Recorded listing score'));assert.ok((await render('insights',{...record,aiScore:82})).includes('Recorded listing score'));const history=await render('history');assert.ok(history.includes('Property Created'));assert.ok(!history.includes('What should I do next?'));await assert.rejects(render(undefined,null),/NOT_FOUND/);});
test('property shell cannot launch welcome and renders only one assistant or action launcher',()=>{const shell=readFileSync('features/vayon/components/ProductExperience.tsx','utf8');assert.match(shell,/showWelcome = path === "\/vayon\/dashboard" && params.get\("welcome"\) === "1" && !feedback/);assert.match(shell,/showWelcome && <PremiumWelcomeExperience/);assert.match(shell,/!propertyHeader && <div/);assert.match(shell,/!propertyRoute \|\| !intelligenceEnabled/);assert.match(shell,/maxWidth: "none"/);const assistant=readFileSync('features/vayon/intelligence-core/components/VayonIntelligence.tsx','utf8');assert.match(assistant,/!route.startsWith\("\/vayon\/properties"\)/);});
test('inventory uses only existing list data and omits placeholder dashboards and imports',()=>{const source=readFileSync('app/vayon/properties/page.tsx','utf8');assert.match(source,/Needs attention on this page/);assert.doesNotMatch(source,/PropertyIntelligenceService|PropertyDashboard|ImportCenter|MapPreview/);assert.match(source,/sticky top-16/);assert.match(source,/!property.description\?\.trim\(\) \|\| !property.assignedAgentId/);});

test('property inventory renders actionable cards without unavailable intelligence',async()=>{const {default:Page}=load('app/vayon/properties/page.tsx',{...stubs,'@/features/vayon/property/services/property.service':{PropertyService:class{async list(){return {items:[record,{...record,id:'b1111111-1111-4111-8111-111111111111',title:'Second QA Property',description:'A recorded description'}],count:2,page:1,pageSize:20}}}},'@/features/vayon/property/actions/property.actions':{archivePropertiesAction:()=>{}}});const html=renderToStaticMarkup(await Page({searchParams:Promise.resolve({view:'grid'})}));assert.ok(html.includes('Needs attention on this page'));assert.ok(!html.includes('Unavailable'));assert.ok(!html.includes('AI listing score'));writeFileSync('test-results/property-experience/inventory.html',html);});
