import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read = path => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("every named employee has role-specific natural language questions", async()=>{const source=await read("features/platform/openai/runtime/ChatPanel.tsx");for(const value of ["Show me today's hottest leads","Match buyers to listings","What campaign should we launch next","Do I have scheduling conflicts","Which customers are inactive"])assert.match(source,new RegExp(value));});
test("assistant responses expose the governed executive answer format",async()=>{const source=await read("features/platform/openai/runtime/ChatPanel.tsx");for(const value of ["Summary","Reasoning","Evidence Panel","Confidence","Business Impact","Recommended Actions","Approval Required","Related Customer","Related Property","Related Task","Related Campaign","Related Meeting","Last Activity","Source Module"])assert.match(source,new RegExp(value));for(const action of ["Approve","Modify","Reject","Explain","View Related Record"])assert.match(source,new RegExp(action));});
test("conversation experience has session memory context search follow-ups and limitations",async()=>{const source=await read("features/platform/openai/runtime/ChatPanel.tsx");for(const value of ["Session Memory","Recent Questions","Recent Topics","Recent Recommendations","Workspace Context","Follow-up questions","Search conversations","I don't have enough verified information to answer that yet","Typing","reviewing verified evidence"])assert.match(source,new RegExp(value,"i"));});
test("headquarters reuses existing workforce and collaboration projections without another repository",async()=>{const route=await read("app/vayon/ai/workforce/[employeeId]/page.tsx"),source=await read("features/platform/openai/runtime/ChatPanel.tsx");assert.match(route,/WorkforceService\.production/);assert.match(route,/AICollaborationService\.production/);assert.match(route,/conversationContext/);assert.doesNotMatch(source,/createSupabaseServerClient|\.from\(|insert\(|update\(|delete\(/);});
test("existing API contract and approval-first execution boundary remain unchanged",async()=>{const route=await read("app/api/ai/workforce/chat/route.ts"),source=await read("features/platform/openai/runtime/ChatPanel.tsx");assert.match(route,/enforceApiPermission/);assert.match(source,/No CRM mutations, workflow execution, outbound communication, or autonomous action/);assert.doesNotMatch(source,/sendEmail|publishCampaign|executeWorkflow|updateCrm/);});
