import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(path, "utf8");

test("Founder AI route is server-authorized and reuses the Executive AI runtime", () => { const page = read("app/platform/founder/ai/page.tsx"), service = read("features/platform/founder-ai/services/founder-ai.service.ts"); assert.match(service, /founderContext/); assert.match(page, /FounderAccessError/); assert.match(page, /notFound/); assert.match(page, /WorkforceRuntimeService/); assert.match(page, /executive-ai/); });
test("executive home composes every existing director snapshot", () => { const service = read("features/platform/founder-ai/services/founder-ai.service.ts"), ui = read("features/platform/founder-ai/components/FounderAIHome.tsx"); for (const dependency of ["FounderService", "MarketingDirectorService", "SalesDirectorService", "CustomerGrowthService"]) assert.match(service, new RegExp(dependency)); for (const surface of ["Executive summary", "Business Health Score", "Today's priorities", "Revenue", "Marketing", "Sales forecast", "Customer health", "Product and platform health", "Cross-module insights"]) assert.match(ui, new RegExp(surface, "i")); });
test("morning brief includes every requested operating signal", () => { const types = read("features/platform/founder-ai/types.ts"), service = read("features/platform/founder-ai/services/founder-ai.service.ts"); for (const field of ["revenue", "mrr", "arr", "newOrganizations", "newUsers", "trialsStarted", "trialsConverted", "renewalsDue", "renewalsCompleted", "churnRisks", "topCampaign", "pipelineForecast", "supportSummary", "platformAlerts", "systemHealth", "upcomingTasks"]) assert.match(types + service, new RegExp(field)); });
test("decision engine prioritizes impact and remains recommendation only", () => { const service = read("features/platform/founder-ai/services/founder-ai.service.ts"), types = read("features/platform/founder-ai/types.ts"); for (const action of ["Review churn-risk accounts", "Contact enterprise-ready prospects", "Review inefficient campaign allocation", "Follow up high-value pipeline", "Improve operating health", "Upgrade or repair infrastructure", "Improve onboarding"]) assert.match(service, new RegExp(action)); assert.match(service, /sort\(\(a, b\) => b\.expectedImpact - a\.expectedImpact\)/); assert.match(types, /recommendationOnly: true/); });
test("weighted health score explains all requested signals and excludes unavailable values", () => { const service = read("features/platform/founder-ai/services/founder-ai.service.ts"); for (const signal of ["Marketing", "Sales", "Customer Success", "Billing", "Product usage", "Platform reliability", "Support", "Growth"]) assert.ok(service.includes(`signal("${signal}"`), signal); assert.match(service, /filter\(\(item\) => item\.score !== null\)/); assert.match(service, /totalWeight/); });
test("cross-module insights never overstate causation", () => { const types = read("features/platform/founder-ai/types.ts"), service = read("features/platform/founder-ai/services/founder-ai.service.ts"), ui = read("features/platform/founder-ai/components/FounderAIHome.tsx"); assert.match(types, /causationClaimed: false/); assert.match(service, /co-occur/); assert.match(service, /not proof/); assert.match(ui, /no causation claimed/i); assert.match(ui, /never overstate causation/i); });
test("streaming executive chat and board exports are complete", () => { const ui = read("features/platform/founder-ai/components/FounderAIHome.tsx"), service = read("features/platform/founder-ai/services/founder-ai.service.ts"); assert.match(ui, /WorkforceChatPanel/); assert.match(ui, /employee="executive-ai"/); assert.match(ui, /supporting evidence/); assert.match(ui, /do not execute actions/); for (const report of ["Daily CEO Report", "Weekly Executive Report", "Monthly Board Report", "Quarterly Investor Summary"]) assert.match(service, new RegExp(report)); assert.match(ui, /FounderReportExports/); });
