import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(path, "utf8");

test("Sales Director route is Founder-only and reuses governed runtimes", () => { const page = read("app/platform/founder/sales/page.tsx"), service = read("features/platform/sales-director/services/sales-director.service.ts"); assert.match(service, /founderContext/); assert.match(page, /FounderAccessError/); assert.match(page, /notFound/); assert.match(page, /SalesAIService/); assert.match(page, /WorkforceRuntimeService/); assert.match(page, /PipelineService/); });
test("executive dashboard exposes every requested measured KPI", () => { const service = read("features/platform/sales-director/services/sales-director.service.ts"); for (const label of ["Today's Revenue", "Monthly Revenue", "Forecast Revenue", "Pipeline Value", "New Leads", "Qualified Leads", "Won Deals", "Lost Deals", "Active Site Visits", "Average Deal Size", "Conversion Rate", "Sales Velocity"]) assert.match(service, new RegExp(label)); assert.match(service, /unavailable/); });
test("pipeline reuses canonical tenant-scoped drag and drop board", () => { const ui = read("features/platform/sales-director/components/SalesDirectorDashboard.tsx"), board = read("features/vayon/deal/components/DealBoard.tsx"), repository = read("features/vayon/deal/repositories/deal.repository.ts"); assert.match(ui, /DealBoard/); assert.match(board, /draggable/); assert.match(board, /moveDealStageAction/); assert.match(repository, /organization_id/); assert.match(repository, /workspace_id/); });
test("lead scoring and copilot remain evidence based and recommendation only", () => { const ui = read("features/platform/sales-director/components/SalesDirectorDashboard.tsx"); for (const label of ["Purchase probability", "Budget fit", "Engagement score", "Buying intent", "Follow-up urgency", "Preferred property profile"]) assert.match(ui, new RegExp(label)); assert.match(ui, /employee="sales-ai"/); assert.match(ui, /authoritative workspace evidence/); assert.match(ui, /do not execute actions/); });
test("timeline automation and reporting cover governed sales operations", () => { const ui = read("features/platform/sales-director/components/SalesDirectorDashboard.tsx"), service = read("features/platform/sales-director/services/sales-director.service.ts"); for (const evidence of ["marketing attribution", "calls", "emails", "meetings", "site visits", "documents", "proposals", "payments"]) assert.match(ui, new RegExp(evidence, "i")); for (const workflow of ["Call reminders", "Email reminders", "Proposal reminders", "Site visit reminders", "Renewal reminders"]) assert.match(service, new RegExp(workflow)); for (const report of ["Daily Sales Report", "Weekly Sales Report", "Monthly Sales Report"]) assert.match(service, new RegExp(report)); assert.match(ui, /FounderReportExports/); });
