import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("Sprint 125 exposes the Creative Studio 2.0 route through existing access", () => { const page=read("app/vayon/creative/page.tsx"), service=read("features/vayon/creative-studio-2/service.ts"); assert.match(page,/CreativeStudio2Service\.production/); assert.match(service,/CreativeStudioService\.production/); assert.doesNotMatch(service,/createClient|service_role/i); });
test("Creative foundation includes all requested modules and governed capabilities", () => { const service=read("features/vayon/creative-studio-2/service.ts"); for(const value of ["Brand Studio","Marketing Studio","Presentation Studio","Image Studio","Video Studio","Website Studio","Document Studio","Asset Library","Template Marketplace","Creative Projects","autosave","versions","duplicate","archive","restore","share","export"]) assert.ok(service.includes(value),value); assert.match(service,/providerConnected: false/); });
test("Creative home provides natural-language creation, assistant, assets, and future exports", () => { const ui=read("features/vayon/creative-studio-2/CreativeStudioHome.tsx"), service=read("features/vayon/creative-studio-2/service.ts"); for(const value of ["Create a luxury real estate brochure.","Create a fintech logo.","Create social media campaign.","Create pitch deck.","Create product mockups.","Creative Assistant"]) assert.ok(ui.includes(value),value); for(const format of ["PNG","PPTX","DOCX","MP4"]) assert.ok(service.includes(format),format); });
test("Creative 2.0 participates in existing permission-filtered navigation", () => { const navigation=read("features/vayon/product-shell/navigation.ts"), permissions=read("features/platform/permissions/runtime/navigation.ts"); assert.match(navigation,/href: "\/vayon\/creative"/); assert.match(permissions,/prefix:"\/vayon\/creative",module:"creative_studio"/); });
