import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(path, "utf8");

test("Customer Growth route is Founder-only and reuses existing platform services", () => { const page = read("app/platform/founder/customer-success/page.tsx"), service = read("features/platform/customer-growth/services/customer-growth.service.ts"); assert.match(service, /founderContext/); assert.match(service, /CustomerRepository/); assert.match(service, /HealthRepository/); assert.match(page, /FounderAccessError/); assert.match(page, /notFound/); assert.match(page, /WorkforceRuntimeService/); });
test("executive growth dashboard exposes all requested evidence-backed KPIs", () => { const service = read("features/platform/customer-growth/services/customer-growth.service.ts"); for (const label of ["Active Trials", "Trial → Paid Conversion", "Active Customers", "Renewals Due", "Renewals Completed", "Expansion Revenue", "Customer Health Score", "Churn Risk", "Net Revenue Retention", "Gross Revenue Retention", "Customer Lifetime Value", "Average Revenue Per Account", "Product Adoption", "Feature Adoption"]) assert.match(service, new RegExp(label)); assert.match(service, /unavailable/); });
test("health and churn classification exposes reasons confidence risks and actions", () => { const service = read("features/platform/customer-growth/services/customer-growth.service.ts"), types = read("features/platform/customer-growth/types.ts"); for (const factor of ["Login activity", "AI usage", "Workspace active", "Team adoption", "support interaction", "Subscription plan"]) assert.match(service, new RegExp(factor, "i")); for (const classification of ["Healthy", "Needs Attention", "At Risk", "Critical"]) assert.match(types + service, new RegExp(classification)); for (const field of ["churnProbability", "riskFactors", "confidence", "recommendedActions"]) assert.match(types, new RegExp(field)); });
test("renewal expansion and journey remain evidence based", () => { const ui = read("features/platform/customer-growth/components/CustomerGrowthDashboard.tsx"), repository = read("features/platform/customer-growth/repositories/customer-growth.repository.ts"); for (const table of ["subscriptions", "invoices", "activity_events"]) assert.match(repository, new RegExp(`\"${table}\"`)); for (const opportunity of ["Additional users", "Higher subscription plans", "AI feature upgrades", "Storage upgrades", "Enterprise onboarding"]) assert.match(read("features/platform/customer-growth/services/customer-growth.service.ts"), new RegExp(opportunity)); for (const event of ["first website visit", "trial", "product and feature adoption", "AI interactions", "billing", "support", "marketing", "sales", "renewals"]) assert.match(ui, new RegExp(event, "i")); });
test("copilot automation reporting realtime and responsive loading are governed", () => { const ui = read("features/platform/customer-growth/components/CustomerGrowthDashboard.tsx"), service = read("features/platform/customer-growth/services/customer-growth.service.ts"), realtime = read("features/platform/founder/components/FounderRealtime.tsx"), loading = read("app/platform/founder/customer-success/loading.tsx"); assert.match(ui, /employee="executive-ai"/); assert.match(ui, /do not execute actions/i); for (const workflow of ["Trial onboarding", "Feature adoption nudges", "Renewal reminders", "Customer check-ins", "Expansion campaigns", "Win-back campaigns"]) assert.match(service, new RegExp(workflow)); for (const report of ["Daily Customer Success Report", "Weekly Executive Report", "Monthly Growth Report"]) assert.match(service, new RegExp(report)); for (const guard of ["consentRequired", "unsubscribeRequired", "approvalRequired"]) assert.match(service, new RegExp(guard)); assert.match(ui, /FounderReportExports/); assert.match(realtime, /customer_health/); assert.match(loading, /sm:grid-cols-2/); });
