import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("launch readiness route is founder protected and reuses the existing service", () => { const page = read("app/vayon/platform/launch-readiness/page.tsx"); assert.match(page, /founderContext/); assert.match(page, /LaunchReadinessService/); assert.doesNotMatch(page, /\.from\(/); });
test("center exposes evidence-backed executive scorecards", () => { const ui = read("features/platform/launch-readiness/components/LaunchReadinessDashboard.tsx"); for (const label of ["Overall launch score","Commercial readiness","Security","Performance","AI readiness","Integrations","Customer journey","Documentation & support"]) assert.match(ui, new RegExp(label, "i")); assert.match(ui, /data\.checks/); assert.match(ui, /data\.providerHealth/); });
test("customer journeys and provider diagnostics use explicit states", () => { const ui = read("features/platform/launch-readiness/components/LaunchReadinessSecondary.tsx"); for (const label of ["Signup","Workspace Creation","Onboarding","Founder Dashboard","Business Connections","AI Conversations","Approval Center","Complete","Needs Attention","Blocked"]) assert.match(ui, new RegExp(label)); });
test("center is accessible, reduced-motion aware, and lazy loaded", () => { const primary = read("features/platform/launch-readiness/components/LaunchReadinessDashboard.tsx"), secondary = read("features/platform/launch-readiness/components/LaunchReadinessSecondary.tsx"); assert.match(primary, /dynamic\(\(\) => import/); assert.match(primary, /motion-reduce/); assert.match(primary, /aria-label/); assert.match(secondary, /role="tablist"/); assert.match(secondary, /aria-selected/); });
test("center does not create provider calls, repositories, execution, or mutations", () => { const source = read("features/platform/launch-readiness/components/LaunchReadinessDashboard.tsx") + read("features/platform/launch-readiness/components/LaunchReadinessSecondary.tsx"); assert.doesNotMatch(source, /fetch\(|supabase|\.from\(|execute\(|insert\(|update\(|delete\(/i); });
