import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
const read = (path) => readFileSync(path, "utf8");

test("AI Marketing Director is founder-only and linked from Founder Portal", () => { const page=read("app/platform/founder/marketing/page.tsx"),founder=read("features/platform/founder/components/FounderDashboard.tsx");assert.match(page,/FounderAccessError/);assert.match(page,/notFound\(\)/);assert.match(founder,/\/platform\/founder\/marketing/); });
test("marketing command center exposes measured KPIs campaigns and attribution",()=>{const service=read("features/platform/marketing-director/services/marketing-director.service.ts"),ui=read("features/platform/marketing-director/components/MarketingDirectorDashboard.tsx");for(const item of["Marketing Spend","Revenue","ROI","ROAS","CAC","CPL","Trial Conversion","Paid Conversion","Monthly Growth","Daily Growth","Google Ads","Meta","LinkedIn","Organic","Direct","Referral","Email","Affiliate","draft","scheduled","running","paused","completed"])assert.match(service+ui,new RegExp(item,"i"));assert.match(service,/status: value === null \? "unavailable"/);assert.doesNotMatch(service,/mock|faker|Math\.random/i);});
test("AI builder and assistant reuse existing Marketing AI and Creative Studio",()=>{const page=read("app/platform/founder/marketing/page.tsx"),ui=read("features/platform/marketing-director/components/MarketingDirectorDashboard.tsx"),chat=read("features/platform/openai/runtime/ChatPanel.tsx");assert.match(page,/WorkforceRuntimeService/);assert.match(ui,/employee="marketing-ai"/);assert.match(ui,/creative-studio\/wizard\?goal=/);for(const value of["Campaign strategy","Headlines","Descriptions","CTAs","Audience recommendations","Budget suggestions","Keywords","UTM parameters"])assert.match(ui,new RegExp(value,"i"));assert.match(chat,/initialPrompt/);});
test("automation is consent aware and reports export PDF and PowerPoint",()=>{const service=read("features/platform/marketing-director/services/marketing-director.service.ts"),exports=read("features/platform/marketing-director/components/MarketingReportExports.tsx");for(const value of["Welcome emails","Trial onboarding","Trial reminders","Renewal reminders","Win-back campaigns","consentRequired","unsubscribeRequired","approvalRequired"])assert.match(service,new RegExp(value,"i"));assert.match(exports,/window\.print/);assert.match(exports,/application\/vnd\.ms-powerpoint/);});
test("module is responsive lazy realtime and documented",()=>{const ui=read("features/platform/marketing-director/components/MarketingDirectorDashboard.tsx"),realtime=read("features/platform/founder/components/FounderRealtime.tsx");assert.match(ui,/LazyFounderCharts/);assert.match(ui,/sm:grid-cols|lg:grid-cols/);assert.match(realtime,/creative_campaigns/);assert.ok(existsSync("docs/AI_MARKETING_DIRECTOR.md"));});
