import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");
test("Sprint 106 Integration Hub is Founder-only", async () => { const page=await read("app/platform/founder/integrations/page.tsx"); assert.match(page,/FounderAccessError/); assert.match(page,/notFound\(\)/); assert.match(await read("features/platform/enterprise-integrations/services/enterprise-integration.service.ts"),/founderContext\(\)/); });
test("all requested production adapters are registered", async () => { const source=await read("features/platform/integrations/provider/registry.ts"); for(const code of ["google_ads","google_analytics_4","google_search_console","google_business_profile","meta_ads","linkedin_ads","stripe","razorpay","google_calendar","microsoft_365","outlook_calendar","gmail","microsoft_graph","whatsapp_business","twilio","resend","sendgrid","zoom","microsoft_teams","openai","anthropic"]) assert.match(source,new RegExp(`\\"${code}\\"`),code); });
test("provider contract includes real health, validation, sync and structured failures", async () => { const source=await read("features/platform/integrations/provider/contracts.ts"); for(const token of ["testConnection()","validateCredentials()","sync(request","ProviderStructuredError","ProviderRateLimiter","IntegrationAuditSink"]) assert.ok(source.includes(token),token); assert.match(await read("features/platform/integrations/provider/adapters.ts"),/have not been validated by a live provider request/); });
test("sync engine is rate-limited, audited and retry-aware", async () => { const source=await read("features/platform/integrations/services/sync-engine.service.ts"); for(const token of ["rateLimiter.acquire","audit.record","retries.enqueue","retryable","conflicts"]) assert.ok(source.includes(token),token); });
test("Founder UI exposes health, webhooks, sync, retry, secret metadata and AI help", async () => { const source=await read("features/platform/enterprise-integrations/components/EnterpriseIntegrationDashboard.tsx"); for(const token of ["Provider directory","Webhook Center","Retry queue","Sync engine","Secret management","Structured provider diagnostics","AI Integration Assistant","WorkforceChatPanel"]) assert.ok(source.includes(token),token); });
test("secrets remain masked and never selected as values", async () => { const repository=await read("features/platform/integrations/repositories/secrets.repository.ts"); assert.match(repository,/maskedValue:\"••••••••\"/); assert.doesNotMatch(repository,/encrypted_value|secret_value|ciphertext/); });
test("realtime and documentation cover integration operations", async () => { assert.match(await read("features/platform/founder/components/FounderRealtime.tsx"),/integration_webhooks/); const docs=await read("docs/ENTERPRISE_INTEGRATION_PLATFORM.md"); assert.match(docs,/Graceful degradation/); assert.match(docs,/No live credentials/); });
