import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("authenticated application shell has fixed header sidebar and responsive content",async()=>{const[shell,experience,header,sidebar]=await Promise.all([read("features/vayon/components/VayonShell.tsx"),read("features/vayon/components/ProductExperience.tsx"),read("features/vayon/product-shell/ShellHeader.tsx"),read("features/vayon/product-shell/ShellSidebar.tsx")]);assert.match(shell,/ProductExperience/);assert.match(header,/fixed inset-x-0 top-0/);assert.match(sidebar,/fixed inset-y-0 left-0/);assert.match(experience,/lg:pl-20/);assert.match(experience,/lg:pl-64/)});
test("sidebar exposes business hierarchy and collapsed developer mode",async()=>{const[config,sidebar]=await Promise.all([read("features/vayon/product-shell/navigation.ts"),read("features/vayon/product-shell/ShellSidebar.tsx")]);for(const group of ["Home","CRM","Operations","Marketing","Communications","AI","Platform","Developer"])assert.match(config,new RegExp(`label: "${group}"`));assert.match(config,/developer: true/);assert.match(sidebar,/useState\(false\)/);assert.match(sidebar,/aria-expanded=\{developerOpen\}/)});
test("sidebar collapse is locally persisted and mobile drawer is accessible",async()=>{const source=await read("features/vayon/components/ProductExperience.tsx"),sidebar=await read("features/vayon/product-shell/ShellSidebar.tsx");assert.match(source,/localStorage\.setItem/);assert.match(source,/useSyncExternalStore/);assert.match(sidebar,/aria-label="Business navigation"/);assert.match(sidebar,/aria-label="Close navigation"/);assert.match(sidebar,/lg:hidden/)});
test("top header integrates one Universal Bar with required placeholder and shortcuts",async()=>{const[header,bar]=await Promise.all([read("features/vayon/product-shell/ShellHeader.tsx"),read("features/vayon/universal-bar/components/UniversalBar.tsx")]);assert.equal((header.match(/<UniversalBar/g)??[]).length,1);assert.match(bar,/Ask, search or create anything\.\.\./);assert.match(bar,/event\.metaKey \|\| event\.ctrlKey/)});
test("workspace profile and notifications menus are navigation only",async()=>{const[workspace,menus]=await Promise.all([read("features/vayon/product-shell/WorkspaceSwitcher.tsx"),read("features/vayon/product-shell/ShellMenus.tsx")]);assert.match(workspace,/Current workspace/);assert.match(workspace,/Recent workspaces/);assert.match(workspace,/Create workspace/);assert.match(workspace,/disabled/);for(const label of ["Profile","Appearance","Workspace","Keyboard Shortcuts","Help","Sign Out","No notifications yet."])assert.match(menus,new RegExp(label));assert.doesNotMatch(workspace+menus,/fetch\(|\.from\(|insert\(|update\(|upsert\(/)});
test("breadcrumbs and quick create cover required navigation",async()=>{const[crumbs,quick]=await Promise.all([read("features/vayon/product-shell/Breadcrumbs.tsx"),read("features/vayon/product-shell/QuickCreate.tsx")]);assert.match(crumbs,/aria-label="Breadcrumb"/);for(const label of ["Lead","Deal","Property","Meeting","Task","Campaign","Document"])assert.match(quick,new RegExp(`label:"${label}"`));assert.match(quick,/role="menu"/)});
test("Executive Home presents real identity workspace date and local time without metrics",async()=>{const[greeting,page]=await Promise.all([read("features/vayon/executive-home/components/ExecutiveGreeting.tsx"),read("app/vayon/home/page.tsx")]);assert.match(greeting,/Good morning/);assert.match(greeting,/Welcome back\./);assert.match(greeting,/Intl\.DateTimeFormat/);assert.match(page,/AuthenticationService/);assert.match(page,/OrganizationService/)});
test("release documentation and ADR record permanent shell decisions",async()=>{const[docs,adr]=await Promise.all([read("docs/RELEASE_1_7_5_PRODUCT_EXPERIENCE.md"),read("docs/ADR-0017-product-experience.md")]);assert.match(docs,/Application shell/);assert.match(docs,/Accessibility/);assert.match(adr,/Developer Mode/);assert.match(adr,/business navigation/i)});
