import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("authenticated application shell has fixed header sidebar and responsive content",async()=>{const[shell,experience,header,sidebar,layout,css]=await Promise.all([read("features/vayon/components/VayonShell.tsx"),read("features/vayon/components/ProductExperience.tsx"),read("features/vayon/product-shell/ShellHeader.tsx"),read("features/vayon/product-shell/ShellSidebar.tsx"),read("features/vayon/product-shell/AppShell.tsx"),read("app/globals.css")]);assert.match(shell,/ProductExperience/);assert.match(header,/fixed inset-x-0 top-0/);assert.match(sidebar,/fixed inset-y-0 left-0/);assert.match(experience,/AppShell sidebarCollapsed/);assert.match(layout,/AppShellLayoutContext/);assert.match(css,/padding-left:var\(--vayon-sidebar-width\)/)});
test("sidebar exposes the real estate hierarchy and founder platform mode",async()=>{const[config,sidebar]=await Promise.all([read("features/vayon/product-shell/navigation.ts"),read("features/vayon/product-shell/ShellSidebar.tsx")]);for(const group of ["CRM","Operations","Growth","Insights","AI Team","Settings","Platform"])assert.match(config,new RegExp(`label: "${group}"`));for(const item of ["Dashboard","Properties","Leads","Clients","Agencies / Builders","Transactions","Real Estate Approval Center","AI Assistant"])assert.match(config,new RegExp(`label: "${item.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}"`));assert.match(sidebar,/useState\(false\)/)});
test("sidebar collapse is locally persisted and mobile drawer is accessible",async()=>{const source=await read("features/vayon/components/ProductExperience.tsx"),sidebar=await read("features/vayon/product-shell/ShellSidebar.tsx");assert.match(source,/localStorage\.setItem/);assert.match(source,/useSyncExternalStore/);assert.match(sidebar,/aria-label="Business navigation"/);assert.match(sidebar,/aria-label="Close navigation"/);assert.match(sidebar,/lg:hidden/)});
test("top header integrates one Universal Bar with required placeholder and shortcuts",async()=>{const[header,bar]=await Promise.all([read("features/vayon/product-shell/ShellHeader.tsx"),read("features/vayon/universal-bar/components/UniversalBar.tsx")]);assert.equal((header.match(/<UniversalBar/g)??[]).length,1);assert.match(bar,/Ask, search or create anything\.\.\./);assert.match(bar,/event\.metaKey \|\| event\.ctrlKey/)});
test("workspace profile and notifications menus are navigation only",async()=>{const[workspace,menus]=await Promise.all([read("features/vayon/product-shell/WorkspaceSwitcher.tsx"),read("features/vayon/product-shell/ShellMenus.tsx")]);assert.match(workspace,/Current workspace/);assert.match(workspace,/Recent workspaces/);assert.match(workspace,/Create workspace/);assert.match(workspace,/disabled/);for(const label of ["Profile","Appearance","Workspace","Keyboard Shortcuts","Help","Sign Out","No notifications yet."])assert.match(menus,new RegExp(label));assert.doesNotMatch(workspace+menus,/fetch\(|\.from\(|insert\(|update\(|upsert\(/)});
test("breadcrumbs and global Create cover required navigation",async()=>{const[crumbs,quick]=await Promise.all([read("features/vayon/product-shell/Breadcrumbs.tsx"),read("features/vayon/product-shell/QuickCreate.tsx")]);assert.match(crumbs,/aria-label="Breadcrumb"/);for(const label of ["Customer","Proposal","Campaign","AI Employee","Image","Video","Meeting","Task","Workflow","Website","Presentation","Document"])assert.match(quick,new RegExp(`label:"${label}"`));assert.match(quick,/role="menu"/)});
test("Executive Home presents the AI Team with real identity workspace date and local time",async()=>{const[greeting,page]=await Promise.all([read("features/vayon/executive-home/components/ExecutiveGreeting.tsx"),read("app/vayon/home/page.tsx")]);assert.match(greeting,/Meet Your AI Team/);assert.match(greeting,/Your AI Team is already working/);assert.match(greeting,/Intl\.DateTimeFormat/);assert.match(page,/AuthenticationService/);assert.match(page,/OrganizationService/)});
test("release documentation and ADR record permanent shell decisions",async()=>{const[docs,adr]=await Promise.all([read("docs/RELEASE_1_7_5_PRODUCT_EXPERIENCE.md"),read("docs/ADR-0017-product-experience.md")]);assert.match(docs,/Application shell/);assert.match(docs,/Accessibility/);assert.match(adr,/Developer Mode/);assert.match(adr,/business navigation/i)});
