import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import ts from 'typescript';
const require=createRequire(import.meta.url);
function load(file,stubs={}){const resolved=path.resolve(file),filename=fs.existsSync(resolved)?resolved:resolved+'x',mod={exports:{}};const code=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;new Function('require','module','exports',code)(name=>Object.hasOwn(stubs,name)?stubs[name]:name.startsWith('@/')?load(name.slice(2)+'.ts',stubs):name.startsWith('.')?load(path.resolve(path.dirname(filename),name+'.ts'),stubs):require(name),mod,mod.exports);return mod.exports;}
const link=({children,...props})=>React.createElement('a',props,children);
const stubs={'next/link':link};stubs['@/features/platform/design-system']=load('features/platform/design-system/components/core/Actions.tsx',stubs);
test('client empty guidance explains existing lead origin and has one relevant destination',()=>{const {ContactDirectory}=load('features/vayon/crm-company/ContactDirectory.tsx',stubs);const html=renderToStaticMarkup(React.createElement(ContactDirectory,{items:[]}));assert.match(html,/Client profiles are created from people recorded in Leads/);assert.match(html,/Go to Leads/);assert.doesNotMatch(html,/Import Clients|Create Lead|AI Team/);assert.equal((html.match(/href=/g)||[]).length,1);fs.mkdirSync('test-results/workflow-consistency',{recursive:true});fs.writeFileSync('test-results/workflow-consistency/clients.html',html);});
test('shared empty states render supplied context without generic cross-workflow or tutorial actions',()=>{const {UniversalEmptyState}=load('features/vayon/empty-states/UniversalEmptyState.tsx',stubs);const html=renderToStaticMarkup(React.createElement(UniversalEmptyState,{module:'tasks',title:'No tasks yet',description:'Plan your next task',primary:{label:'Add task',href:'/vayon/tasks'}}));assert.match(html,/Add task/);assert.doesNotMatch(html,/first property|first lead|campaign|AI Team|Watch tutorial|Documentation/);assert.equal((html.match(/href=/g)||[]).length,1);});
test('empty states cannot produce inert buttons without a destination or handler',()=>{const {SmartEmptyState}=load('features/vayon/components/SmartEmptyState.tsx',stubs);const html=renderToStaticMarkup(React.createElement(SmartEmptyState,{title:'No work',description:'Check this view later',primaryLabel:'Missing action'}));assert.doesNotMatch(html,/<button|Missing action/);});
test('workspace search treats client and company contexts separately and preserves route boundaries',()=>{const {sameSearchWorkspace}=load('features/vayon/universal-bar/config/adaptive-suggestions.ts');assert.equal(sameSearchWorkspace('/vayon/crm/contacts/abc','/vayon/crm/contacts'),true);assert.equal(sameSearchWorkspace('/vayon/crm/companies','/vayon/crm/contacts'),false);assert.equal(sameSearchWorkspace('/vayon/properties/new','/vayon/properties/abc'),true);assert.equal(sameSearchWorkspace('/vayon/properties-extra','/vayon/properties'),false);assert.equal(sameSearchWorkspace('/vayon/settings/members','/vayon/settings'),true);});
test('role form preserves existing authorization, excludes new fields and retains selected role payload',()=>{const source=fs.readFileSync('features/platform/organization/components/RoleManagementUI.tsx','utf8');assert.match(source,/disabled=\{!canManage\}/);assert.match(source,/assignableWorkspaceRoles/);assert.match(source,/name="role" value=\{selected\}/);assert.match(source,/action=\{inviteMemberAction\}/);assert.doesNotMatch(source,/max-h-\[28rem\]/);assert.match(source,/Invite summary/);assert.match(source,/Responsibilities and permissions/);});

test('search prioritizes current workspace then recent and frequently used actions',()=>{const {prioritizeWorkspaceResults}=load('features/vayon/universal-bar/config/adaptive-suggestions.ts');const now=Date.parse('2026-09-12T00:00:00Z');const result=(id,href)=>({id,label:id,href,kind:'quick-create',scope:'properties',keywords:[]});const recent=(id,days,visits)=>({id,kind:'recently-opened',recordedAt:new Date(now-days*86400000).toISOString(),visits});const items=[result('other','/vayon/leads/new'),result('unused','/vayon/properties'),result('frequent','/vayon/properties/new'),result('recent','/vayon/properties/media')];assert.deepEqual(prioritizeWorkspaceResults(items,'/vayon/properties',[recent('other',0,100),recent('frequent',10,5),recent('recent',1,1)],now).map(item=>item.id),['recent','frequent','unused','other']);});
test('filtered client empty state keeps recovery within Clients',()=>{const {ContactDirectory}=load('features/vayon/crm-company/ContactDirectory.tsx',stubs);const html=renderToStaticMarkup(React.createElement(ContactDirectory,{items:[],search:'missing'}));assert.match(html,/No clients match this search/);assert.match(html,/Clear client search/);assert.doesNotMatch(html,/Go to Leads|Import Clients/);});
