import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("workforce defines executive sales and operations advisors", () => { const source = read("features/platform/intelligence/workforce-mvp/services/advisor.service.ts"); for (const advisor of ["Executive Advisor", "Sales Advisor", "Operations Advisor"]) assert.match(source, new RegExp(advisor)) });
test("executive advisor covers required advisory surfaces", () => { const source = read("features/platform/intelligence/workforce-mvp/services/advisor.service.ts"); for (const capability of ["executive-summary", "business-health", "priorities", "risks", "opportunities", "recommended-actions"]) assert.match(source, new RegExp(capability)) });
test("sales and operations advisors cover required reviews", () => { const source = read("features/platform/intelligence/workforce-mvp/services/advisor.service.ts"); for (const capability of ["lead-prioritization", "deal-health", "stalled-pipeline", "follow-ups", "data-quality", "pipeline-improvement", "overdue-work", "workflow-bottlenecks", "record-completeness", "operations-recommendations", "productivity"]) assert.match(source, new RegExp(capability)) });
test("advisors consume only brain gateway and cognitive engine", () => { const ports = read("features/platform/intelligence/workforce-mvp/contracts/ports.ts"), service = read("features/platform/intelligence/workforce-mvp/services/advisor.service.ts"); assert.match(ports, /BrainGateway/); assert.match(ports, /CognitiveEngine/); for (const source of [ports, service]) assert.doesNotMatch(source, /supabase|createClient|\.from\(|\.rpc\(|fetch\(|OpenAI|Anthropic|Gemini/i) });
test("workforce remains advisory and non executable", () => { const domain = read("features/platform/intelligence/workforce-mvp/domain/contracts.ts"), service = read("features/platform/intelligence/workforce-mvp/services/advisor.service.ts"); assert.match(domain, /executionAvailable: false/); assert.match(domain, /executable: false/); assert.match(service, /executionAvailable: false/); assert.doesNotMatch(service, /execute\(|approve\(|mutate\(|update\(|insert\(/i) });
test("workforce shell provides all customer-facing architecture surfaces", () => { const shell = read("features/platform/intelligence/workforce-mvp/components/WorkforceShell.tsx"), drawer = read("features/platform/intelligence/workforce-mvp/components/ExplainabilityDrawer.tsx"); for (const surface of ["AdvisorSelector", "ConversationPanel", "InsightCard", "RecommendationTimeline", "Activity history", "ExplainabilityDrawer"]) assert.match(shell, new RegExp(surface)); for (const detail of ["Data sources", "Citations", "Limitations"]) assert.match(drawer, new RegExp(detail)) });
test("workforce route navigation and release documentation are registered", () => { assert.match(read("app/vayon/workforce/page.tsx"), /WorkforceShell/); assert.match(read("features/platform/builder/config/vayon-navigation.ts"), /href: "\/vayon\/ai\/workforce"/); assert.match(read("docs/RELEASE_0_7_VAYON_WORKFORCE_MVP.md"), /Vayon Workforce MVP/) });

