import Link from "next/link";
import type { WorkforceSnapshot } from "@/features/vayon/operational-workforce/domain/models";
import type { CollaborationDashboard, RecommendationNode } from "../types";

const card = "rounded-3xl border border-vds-border bg-vds-surface p-5 sm:p-6";
const managers = [{ code: "sales-ai", name: "Sarah", area: "Sales" }, { code: "crm-ai", name: "Emma", area: "Marketing" }, { code: "operations-ai", name: "Alex", area: "Operations" }, { code: "finance-ai", name: "David", area: "Finance" }, { code: "whatsapp-ai", name: "Olivia", area: "Customer Success" }] as const;
const urgent = /urgent|today|overdue|risk|blocked|delay|missing|follow.?up/i;
const opportunity = /opportunity|growth|buyer|listing|revenue|close|referral/i;
function rank(item: RecommendationNode) { return (item.approvalStatus === "pending" ? 30 : 0) + (urgent.test(item.requestedRecommendation) ? 25 : 0) + (opportunity.test(item.requestedRecommendation) ? 20 : 0) + Math.round((item.confidence ?? 0) * 20) + (item.relatedCustomer ? 5 : 0); }

export function ExecutiveCollaborationBoard({ data, workforce }: { readonly data: CollaborationDashboard; readonly workforce: WorkforceSnapshot }) {
  const ranked = data.recommendationPipeline.slice().sort((a, b) => rank(b) - rank(a)), pending = ranked.filter((item) => item.approvalStatus === "pending"), risks = ranked.filter((item) => urgent.test(item.requestedRecommendation)), opportunities = ranked.filter((item) => opportunity.test(item.requestedRecommendation) && !urgent.test(item.requestedRecommendation)), conflicts = detectConflicts(ranked), names = new Map<string, string>(managers.map((manager) => [manager.code, manager.name]));
  return <section className="space-y-5" aria-labelledby="executive-board-title">
    <header className={card}><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Executive Collaboration Board</p><h1 id="executive-board-title" className="mt-2 text-3xl font-semibold">One company. One coordinated morning brief.</h1><p className="mt-2 text-sm text-vds-muted">Sarah, Emma, Alex, David, and Olivia combine verified workspace evidence. Conflicts remain visible and every decision requires human approval.</p></header>
    <section className={card} aria-labelledby="unified-brief"><h2 id="unified-brief" className="text-xl font-semibold">Unified Morning Brief</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{managers.map((manager) => { const employee = workforce.employees.find((item) => item.code === manager.code), recommendations = ranked.filter((item) => item.employee === manager.code); return <article className="rounded-2xl bg-vds-elevated p-4" key={manager.code}><p className="text-xs text-vds-primary">{manager.name} · {manager.area}</p><p className="mt-2 text-sm font-medium">{recommendations[0]?.requestedRecommendation ?? "Awaiting verified recommendation"}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {recommendations.length} recommendation records · health {employee?.health ?? "unavailable"}</p></article>; })}</div><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Top Priorities", pending.length], ["Key Risks", risks.length], ["Key Opportunities", opportunities.length], ["Expected Revenue", "Unavailable"], ["Pending Decisions", data.pendingApprovals]].map(([label, value]) => <div className="rounded-2xl border border-vds-border p-4" key={label}><dt className="text-xs text-vds-muted">{label}</dt><dd className="mt-2 font-semibold">{value}</dd></div>)}</dl><p className="mt-3 text-xs text-vds-muted">Expected revenue is unavailable because this collaboration projection contains no transaction forecast.</p></section>
    <section className={card} aria-labelledby="executive-discussion"><h2 id="executive-discussion" className="text-xl font-semibold">Executive Discussion</h2><p className="mt-2 text-sm text-vds-muted">One coordinated recommendation, grouped by the managers who contributed.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{managers.map((manager) => <article className="rounded-2xl bg-vds-elevated p-4" key={manager.code}><h3 className="font-medium">{manager.name} recommends</h3><p className="mt-2 text-sm text-vds-muted">{ranked.find((item) => item.employee === manager.code)?.requestedRecommendation ?? "No evidence-backed contribution recorded."}</p></article>)}</div></section>
    <section className={card} aria-labelledby="conflict-detection"><h2 id="conflict-detection" className="text-xl font-semibold">Conflict Detection</h2>{conflicts.length ? <div className="mt-4 space-y-3" role="alert">{conflicts.map((conflict) => <article className="rounded-2xl border border-vds-warning p-4" key={conflict.id}><p className="font-medium">Conflicting recommendations require executive review</p><p className="mt-2 text-sm text-vds-muted">{conflict.first} ↔ {conflict.second}</p><p className="mt-2 text-xs text-vds-muted">No automatic resolution is applied.</p></article>)}</div> : <p className="mt-4 text-sm text-vds-muted">No explicit conflict is supported by current recommendation text.</p>}</section>
    <section className={card} aria-labelledby="decision-queue"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="decision-queue" className="text-xl font-semibold">Executive Decision Queue</h2><p className="mt-1 text-sm text-vds-muted">Ranked by business impact, urgency, confidence, evidence completeness, and approval dependency.</p></div><Link className="focus-ring text-sm font-medium text-vds-primary" href="/vayon/approvals">Open Approval Center</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{pending.slice(0, 10).map((item, index) => <article className="rounded-2xl bg-vds-elevated p-4" key={item.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">{index + 1}. {item.requestedRecommendation}</h3><span className="text-xs">Score {rank(item)}</span></div><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div><dt className="text-vds-muted">Originating AI manager(s)</dt><dd>{names.get(item.employee) ?? item.employee}</dd></div><div><dt className="text-vds-muted">Confidence</dt><dd>{item.confidence === null ? "Unknown" : `${Math.round(item.confidence * 100)}%`}</dd></div><div><dt className="text-vds-muted">Evidence</dt><dd>Workspace recommendation {item.id}</dd></div><div><dt className="text-vds-muted">Expected outcome</dt><dd>Human-reviewed business decision</dd></div><div><dt className="text-vds-muted">Required approvals</dt><dd>Approval Center review</dd></div><div><dt className="text-vds-muted">Related CRM records</dt><dd>{item.relatedCustomer ?? "Unavailable"}</dd></div></dl><Link className="mt-3 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href={`/vayon/approvals?recommendation=${encodeURIComponent(item.id)}`}>Review decision</Link></article>)}{!pending.length && <p className="text-sm text-vds-muted">No pending executive decision is recorded.</p>}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card}><h2 className="text-xl font-semibold">Executive Timeline</h2><ol className="mt-4 space-y-3">{data.timeline.slice(0, 10).map((event) => <li className="border-l border-vds-primary pl-4 text-sm" key={event.id}>{names.get(event.agent) ?? event.agent} · {event.summary}<time className="mt-1 block text-xs text-vds-muted">{new Date(event.occurredAt).toLocaleString()}</time></li>)}{ranked.slice(0, 5).map((item) => <li className="border-l border-vds-border pl-4 text-sm" key={item.id}>{item.approvalStatus} · {item.requestedRecommendation}<time className="mt-1 block text-xs text-vds-muted">{new Date(item.createdAt).toLocaleString()}</time></li>)}</ol></section><section className={card}><h2 className="text-xl font-semibold">Executive Scorecard</h2><dl className="mt-4 grid grid-cols-2 gap-3">{managers.map((manager) => { const employee = workforce.employees.find((item) => item.code === manager.code); return <div className="rounded-2xl bg-vds-elevated p-4" key={manager.code}><dt className="text-xs text-vds-muted">{manager.area} Health</dt><dd className="mt-2 capitalize">{employee?.health ?? "Unavailable"}</dd></div>; })}<div className="rounded-2xl bg-vds-elevated p-4"><dt className="text-xs text-vds-muted">Overall Business Health</dt><dd className="mt-2">{workforce.employees.some((item) => item.health === "degraded") ? "Needs Attention" : workforce.employees.some((item) => item.health === "healthy") ? "Healthy" : "Unavailable"}</dd></div></dl></section></div>
    <section className={card}><h2 className="text-xl font-semibold">Board Insights</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Biggest Opportunity", opportunities[0]?.requestedRecommendation ?? "Unavailable"], ["Biggest Risk", risks[0]?.requestedRecommendation ?? "Unavailable"], ["Most Urgent Approval", pending[0]?.requestedRecommendation ?? "Unavailable"], ["Most Valuable Property", "Unavailable"], ["Most Valuable Buyer", "Unavailable"], ["Most Valuable Deal", "Unavailable"]].map(([label, value]) => <div className="rounded-2xl bg-vds-elevated p-4" key={label}><dt className="text-xs text-vds-muted">{label}</dt><dd className="mt-2 text-sm font-medium">{value}</dd></div>)}</dl></section>
  </section>;
}
function detectConflicts(items: readonly RecommendationNode[]) { const conflicts: { id: string; first: string; second: string }[] = []; for (let index = 0; index < items.length; index += 1) for (let other = index + 1; other < items.length; other += 1) { const first = items[index].requestedRecommendation, second = items[other].requestedRecommendation, increase = /increase|expand|accelerate|launch|spend more/i, reduce = /reduce|pause|delay|decrease|cut spend/i; if (increase.test(first) && reduce.test(second) || reduce.test(first) && increase.test(second)) conflicts.push({ id: `${items[index].id}-${items[other].id}`, first, second }); if (conflicts.length === 5) return conflicts; } return conflicts; }
