import Link from "next/link";
import type { SalesAIDashboard as Dashboard } from "../types";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const actionLabel = (action: Dashboard["dailyPriorities"][number]["action"]) => ({ call: "Prepare Call", whatsapp: "Prepare WhatsApp", email: "Prepare Email", schedule_viewing: "Prepare Viewing", send_brochure: "Prepare Brochure", prepare_offer: "Prepare Offer", request_documents: "Request Documents", mortgage_follow_up: "Mortgage Follow-up", registration_follow_up: "Registration Follow-up" })[action];
export function SalesAIDashboard({ data }: { data: Dashboard }) {
  return <section className="space-y-5" aria-labelledby="sales-intelligence-title">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Sales AI intelligence</p><h2 id="sales-intelligence-title" className="mt-2 text-2xl font-semibold">Today&apos;s sales command center</h2><p className="mt-1 text-sm text-vds-muted">Evidence-backed advice only. Every proposed action requires human approval.</p></div><Link className="rounded-xl border border-vds-border px-4 py-2 text-sm" href="/vayon/approvals">{data.pendingApprovals} pending approvals</Link></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Today’s priorities", data.briefing.priorities.length], ["Meetings", data.briefing.upcomingMeetings], ["Overdue follow-ups", data.briefing.overdueFollowUps], ["Deals at risk", data.briefing.dealsAtRisk], ["Top opportunities", data.briefing.highValueOpportunities], ["Revenue forecast", money(data.forecast.expectedMonthlyRevenue)]].map(([label, value]) => <article className={card} key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-3 text-xl font-semibold">{value}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><article className={card}><h3 className="font-semibold">Today&apos;s priorities</h3><ol className="mt-4 space-y-3">{data.briefing.priorities.map((item, index) => <li className="flex gap-3 text-sm" key={item}><span className="text-vds-primary">{index + 1}</span><span>{item}</span></li>)}{!data.briefing.priorities.length && <li className="text-sm text-vds-muted">No urgent priority is supported by current workspace evidence.</li>}</ol></article><article className={card}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">Revenue forecast</h3><p className="mt-1 text-sm capitalize text-vds-muted">Pipeline health: {data.forecast.pipelineHealth}</p></div><span className="text-sm">{Math.round(data.forecast.confidence * 100)}% confidence</span></div><p className="mt-5 text-3xl font-semibold">{money(data.forecast.expectedMonthlyRevenue)}</p><p className="mt-3 text-sm text-vds-muted">{data.forecast.explanation}</p><p className="mt-3 text-xs text-vds-muted">Likely closes: {data.forecast.likelyClosedDeals} · At-risk value: {money(data.forecast.atRiskRevenue)}</p></article></div>
    <article className={card} aria-labelledby="next-best-actions"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="next-best-actions" className="font-semibold">Next Best Actions</h3><p className="mt-1 text-sm text-vds-muted">Prepared recommendations only. Nothing is sent, scheduled, or changed without approval.</p></div><span className="rounded-full bg-vds-elevated px-3 py-1 text-xs">Approval required</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.dailyPriorities.map((item) => <section className="rounded-xl bg-vds-elevated p-4" key={item.id}><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{item.title}</h4><span className="text-xs uppercase text-vds-muted">{item.confidence} confidence</span></div><p className="mt-2 text-sm">{item.reason}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {item.evidence.join(" · ")}</p>{item.missingInformation.length > 0 && <p className="mt-2 text-xs text-vds-warning">Missing information: {item.missingInformation.join(", ")}</p>}<Link className="mt-3 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm font-medium focus-ring" href={item.approvalHref}>{actionLabel(item.action)} for approval</Link></section>)}{!data.dailyPriorities.length && <p className="text-sm text-vds-muted">No next action is supported by current evidence.</p>}</div></article>
    <article className={card} aria-labelledby="conversation-summary"><h3 id="conversation-summary" className="font-semibold">Conversation summary &amp; follow-up detection</h3><p className="mt-2 text-sm text-vds-muted">{data.conversation.conversationSummary}</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Action items", data.conversation.actionItems], ["Risks", data.conversation.risks], ["Next steps", data.conversation.nextSteps], ["Pending questions", data.conversation.pendingQuestions]].map(([label, values]) => <section key={label as string}><h4 className="text-sm font-medium">{label as string}</h4><ul className="mt-2 space-y-2 text-xs text-vds-muted">{(values as readonly string[]).map((value) => <li key={value}>• {value}</li>)}{!(values as readonly string[]).length && <li>None supported by current evidence.</li>}</ul></section>)}</div></article>
    <div className="grid gap-5 xl:grid-cols-2"><article className={card}><h3 className="font-semibold">Top opportunities</h3><div className="mt-4 space-y-3">{data.leads.slice().sort((a,b) => b.confidence-a.confidence).slice(0,6).map((lead) => <div className="rounded-xl bg-vds-elevated p-3" key={lead.id}><div className="flex justify-between gap-3"><p className="font-medium">{lead.name}</p><span className="text-xs font-semibold uppercase">{lead.temperature} · {Math.round(lead.confidence*100)}%</span></div><p className="mt-2 text-xs text-vds-muted">{lead.explanation}</p></div>)}</div></article><article className={card}><h3 className="font-semibold">Deals at risk</h3><div className="mt-4 space-y-3">{data.deals.filter((deal) => deal.risk !== "low").slice(0,6).map((deal) => <div className="rounded-xl bg-vds-elevated p-3" key={deal.id}><div className="flex justify-between gap-3"><p className="font-medium">{deal.title}</p><span className="text-xs uppercase">{deal.risk} risk</span></div><p className="mt-1 text-xs text-vds-muted">{deal.stage} · {deal.daysInStage} days · {deal.probability}% close probability</p><p className="mt-2 text-sm">{deal.nextAction}</p></div>)}{!data.deals.some((deal) => deal.risk !== "low") && <p className="text-sm text-vds-muted">No deal risk is supported by current data.</p>}</div></article></div>
    <div className="grid gap-5 xl:grid-cols-3"><article className={card}><h3 className="font-semibold">CRM cleanup</h3><ul className="mt-4 space-y-2 text-sm">{data.crmCleanup.map((item) => <li key={item}>• {item}</li>)}{!data.crmCleanup.length && <li className="text-vds-muted">No cleanup issue detected.</li>}</ul></article><article className={card}><h3 className="font-semibold">Recent recommendations</h3><div className="mt-4 space-y-3">{data.recommendations.slice(0,5).map((item) => <div key={item.id}><p className="text-sm font-medium">{item.title}</p><p className="text-xs capitalize text-vds-muted">{item.status.replaceAll("_", " ")} · approval governed</p></div>)}{!data.recommendations.length && <p className="text-sm text-vds-muted">No recommendation has been recorded.</p>}</div></article><article className={card}><h3 className="font-semibold">AI observability</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Prompt tokens", data.observability.promptTokens], ["Completion tokens", data.observability.completionTokens], ["Latency", data.observability.latencyMs == null ? "—" : `${data.observability.latencyMs} ms`], ["Estimated cost", `$${data.observability.estimatedCost.toFixed(6)}`], ["Model", data.observability.model ?? "No response"], ["Recommendations", data.observability.recommendationCount]].map(([label,value]) => <div key={label}><dt className="text-xs text-vds-muted">{label}</dt><dd className="mt-1">{value}</dd></div>)}</dl></article></div>
    <article className={card}><h3 className="font-semibold">AI activity timeline</h3><div className="mt-4 space-y-3">{data.timeline.slice(0,8).map((item) => <div className="border-l border-vds-primary pl-4" key={item.id}><p className="text-sm">{item.title}</p><time className="text-xs text-vds-muted">{new Date(item.occurredAt).toLocaleString()}</time></div>)}{!data.timeline.length && <p className="text-sm text-vds-muted">No Sales AI activity has been recorded.</p>}</div></article>
  </section>;
}
