import Link from "next/link";
import type { SalesAIDashboard } from "../types";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";
const unavailable = "Unavailable — supporting repository evidence is not connected";
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export function SarahSalesManagerDashboard({ data }: { data: SalesAIDashboard }) {
  const urgentBuyers = data.leads.filter((lead) => lead.temperature === "hot");
  const expectedClosings = data.deals.filter((deal) => deal.probability >= 70 && deal.risk !== "high");
  const stalledDeals = data.deals.filter((deal) => deal.risk === "high");
  const highestProbability = data.deals.slice().sort((a, b) => b.probability - a.probability)[0];
  const leadPriorities = data.leads.slice().sort((a, b) => b.confidence - a.confidence).slice(0, 8);

  return <section className="space-y-5" aria-labelledby="sarah-manager-title">
    <header className={card}><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Sarah · AI Sales Manager</p><h2 id="sarah-manager-title" className="mt-2 text-2xl font-semibold">Good Morning</h2><p className="mt-2 text-sm text-vds-muted">Here is the evidence-backed sales plan. Sarah observes, analyses, and recommends; humans approve every action.</p></header>
    <section className={card} aria-labelledby="morning-briefing"><h3 id="morning-briefing" className="font-semibold">Morning Sales Briefing</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Today’s Priorities", data.dailyPriorities.length, `${data.dailyPriorities.length} evidence-backed recommendations`], ["Expected Closings", expectedClosings.length, "Recorded probability ≥70% and not high risk"], ["Urgent Buyers", urgentBuyers.length, "Leads classified hot from recorded qualification evidence"], ["Urgent Sellers", "Unavailable", unavailable], ["Follow-ups Due", data.briefing.overdueFollowUps, "Open tasks past their recorded due date"], ["Viewings", data.briefing.upcomingMeetings, "Upcoming meetings in the workspace calendar"], ["Registrations", "Unavailable", unavailable], ["Pending Approvals", data.pendingApprovals, "Pending approval queue records"], ["Revenue Forecast", money(data.forecast.expectedMonthlyRevenue), data.forecast.explanation],
    ].map(([label, value, evidence]) => <article className="rounded-xl bg-vds-elevated p-4" key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {evidence}</p></article>)}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card} aria-labelledby="lead-prioritization"><h3 id="lead-prioritization" className="font-semibold">Lead Prioritization</h3><div className="mt-4 space-y-3">{leadPriorities.map((lead, index) => <article className="rounded-xl bg-vds-elevated p-4" key={lead.id}><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{index + 1}. {lead.name}</h4><span className="text-xs uppercase">{lead.temperature} · {Math.round(lead.confidence * 100)}% confidence</span></div><p className="mt-2 text-sm">Reason: {lead.explanation}</p><p className="mt-2 text-xs text-vds-muted">Recommended agent: Unavailable — assignment and performance evidence are not part of this projection.</p></article>)}{!leadPriorities.length && <p className="text-sm text-vds-muted">No lead evidence is available to rank.</p>}</div></section>
      <section className={card} aria-labelledby="agent-coaching"><h3 id="agent-coaching" className="font-semibold">Agent Coaching</h3><p className="mt-3 text-sm text-vds-muted">{unavailable}. Sarah will not rank or recognize agents without ownership, response-time, viewing, and progression evidence.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{["Leads untouched", "Average response time", "Viewings booked", "Deals progressing", "Deals stalled", "Pipeline health", "Suggestions", "Recognition"].map((label) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 text-xs text-vds-muted">Unavailable</dd></div>)}</dl></section></div>
    <div className="grid gap-5 xl:grid-cols-3"><section className={card}><h3 className="font-semibold">Pipeline Health</h3><ul className="mt-4 space-y-2 text-sm"><li>Stalled deals: {stalledDeals.length}</li><li>Inactive buyers: {data.leads.filter((lead) => lead.temperature === "cold").length}</li><li>Overdue tasks: {data.briefing.overdueFollowUps}</li><li>Inactive sellers: Unavailable</li><li>Listings without interest: Unavailable</li><li>Offers waiting: Unavailable</li><li>Missing documents: {data.deals.reduce((sum, deal) => sum + deal.missingActivities.filter((item) => /document/i.test(item)).length, 0)}</li><li>Registrations delayed: Unavailable</li></ul></section>
      <section className={card}><h3 className="font-semibold">Property Advisor</h3><p className="mt-3 text-sm text-vds-muted">Performance, price, marketing, photo, and buyer-interest reviews require a selected property and verified listing evidence.</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href="/vayon/properties">Review properties with Emma</Link></section>
      <section className={card}><h3 className="font-semibold">Executive Insights</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-vds-muted">Highest Closing Probability</dt><dd>{highestProbability ? `${highestProbability.title} · ${highestProbability.probability}%` : "Unavailable"}</dd></div><div><dt className="text-vds-muted">Revenue at Risk</dt><dd>{money(data.forecast.atRiskRevenue)}</dd></div>{["Top Performing Agent", "Most Active Buyer", "Most Active Seller", "Most Valuable Listing"].map((label) => <div key={label}><dt className="text-vds-muted">{label}</dt><dd>Unavailable</dd></div>)}</dl></section></div>
    <section className={card} aria-labelledby="risk-center"><h3 id="risk-center" className="font-semibold">Risk Center</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{data.dailyPriorities.filter((item) => item.confidence !== "unknown").map((item) => <article className="rounded-xl bg-vds-elevated p-4" key={item.id}><h4 className="font-medium">{item.title}</h4><p className="mt-2 text-sm"><strong>Why:</strong> {item.reason}</p><p className="mt-2 text-xs text-vds-muted"><strong>Supporting evidence:</strong> {item.evidence.join(" · ")}</p><p className="mt-2 text-xs text-vds-muted"><strong>Expected outcome:</strong> A human-reviewed next commitment.</p><p className="mt-2 text-xs text-vds-muted"><strong>Confidence:</strong> {item.confidence}</p><p className="mt-2 text-xs text-vds-muted"><strong>Alternative:</strong> Review the record with its owner before preparing contact.</p><Link className="mt-3 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href={item.approvalHref}>Prepare for approval</Link></article>)}</div></section>
  </section>;
}
