import "server-only";

import { CustomerGrowthService } from "@/features/platform/customer-growth/services/customer-growth.service";
import { FounderService } from "@/features/platform/founder/services/founder.service";
import type { FounderKpi } from "@/features/platform/founder/types";
import { MarketingDirectorService } from "@/features/platform/marketing-director/services/marketing-director.service";
import { SalesDirectorService } from "@/features/platform/sales-director/services/sales-director.service";
import { log } from "@/lib/observability/logger";
import { founderContext } from "@/features/platform/founder/services/founder-context";
import type { FounderAICorrelation, FounderAIPriority, FounderAISignal, FounderAISnapshot } from "../types";

export class FounderAIService {
  async snapshot(): Promise<FounderAISnapshot> {
    const started = performance.now(), { user } = await founderContext();
    const [founder, marketing, sales, customerSuccess] = await Promise.all([new FounderService().snapshot(), new MarketingDirectorService().snapshot(), new SalesDirectorService().snapshot(), new CustomerGrowthService().snapshot()]);
    const fk = (id: string) => founder.kpis.find((item) => item.id === id) ?? null, sk = (id: string) => sales.kpis.find((item) => item.id === id) ?? null, ck = (id: string) => customerSuccess.kpis.find((item) => item.id === id) ?? null;
    const signals: FounderAISignal[] = [signal("Marketing", percent(marketing, "roi"), .15, "Measured marketing ROI normalized to a 0–100 operating signal."), signal("Sales", percent(sales, "conversion"), .2, "Measured sales conversion; unavailable values are excluded."), signal("Customer Success", number(ck("health")), .2, "Average organization customer-health evidence."), signal("Billing", retention(ck("nrr")), .15, "Net revenue retention normalized around the 100% target."), signal("Product usage", percent(customerSuccess, "product-adoption"), .1, "Measured product adoption."), signal("Platform reliability", platformScore(founder.health), .1, "Share of measured platform services reporting healthy."), signal("Support", inverseCount(fk("tickets"), 20), .05, "Open support demand normalized against an operational review threshold."), signal("Growth", growthScore(marketing), .05, "Available monthly and daily growth signals.")];
    const available = signals.filter((item) => item.score !== null), totalWeight = available.reduce((sum, item) => sum + item.weight, 0), healthScore = totalWeight ? Math.round(available.reduce((sum, item) => sum + (item.score ?? 0) * item.weight, 0) / totalWeight) : null;
    const churnRisks = customerSuccess.organizations.filter((item) => item.classification === "At Risk" || item.classification === "Critical").length, topCampaign = topCampaignName(marketing), priorities = prioritize(founder, marketing, sales, customerSuccess, healthScore), correlations = correlate(marketing, sales, customerSuccess);
    const morningBrief = { revenue: fk("today-revenue"), mrr: fk("mrr"), arr: fk("arr"), newOrganizations: find(founder.kpis, "New Organizations", "Total Organizations"), newUsers: find(founder.kpis, "New Users", "Total Users"), trialsStarted: ck("trials"), trialsConverted: ck("trial-paid"), renewalsDue: ck("renewals-due"), renewalsCompleted: ck("renewals-completed"), churnRisks, topCampaign, pipelineForecast: sk("forecast-revenue") ?? founder.sales.find((item) => item.id === "forecast") ?? null, supportSummary: metricText(fk("tickets"), "open support tickets"), platformAlerts: Number(fk("notifications")?.value ?? 0), systemHealth: founder.health, upcomingTasks: founder.kpis.find((item) => item.id === "tasks") ?? null };
    const summary = healthScore === null ? "Business health is unavailable until authoritative cross-module signals are recorded." : `Business health is ${healthScore}/100 from ${available.length} available weighted signals. ${priorities.filter((item) => item.impact === "critical" || item.impact === "high").length} high-impact recommendation(s) require founder review.`;
    log("founder.ai.viewed", { actorId: user.id, healthScore, availableSignals: available.length, priorities: priorities.length, latencyMs: Math.round(performance.now() - started) });
    return { founder, marketing, sales, customerSuccess, morningBrief, healthScore, healthSignals: signals, priorities, correlations, summary, reports: ["Daily CEO Report", "Weekly Executive Report", "Monthly Board Report", "Quarterly Investor Summary"].map((label) => ({ id: label.toLowerCase().replaceAll(" ", "-"), label, formats: ["PDF", "PowerPoint"] as const })), reportKpis: [...founder.kpis.slice(0, 12), ...sales.kpis.slice(0, 4), ...customerSuccess.kpis.slice(0, 4)], generatedAt: new Date().toISOString() };
  }
}
function signal(name: string, score: number | null, weight: number, reason: string): FounderAISignal { return { name, score: score === null ? null : Math.max(0, Math.min(100, score)), weight, reason }; }
function number(item: FounderKpi | null) { return item?.value ?? null; }
function percent(snapshot: { kpis: readonly FounderKpi[] }, id: string) { return snapshot.kpis.find((item) => item.id === id)?.value ?? null; }
function retention(item: FounderKpi | null) { return item?.value === null || item?.value === undefined ? null : Math.max(0, Math.min(100, item.value)); }
function inverseCount(item: FounderKpi | null, threshold: number) { return item?.value === null || item?.value === undefined ? null : Math.max(0, 100 - item.value / threshold * 100); }
function platformScore(items: readonly { state: string }[]) { const measured = items.filter((item) => item.state !== "unavailable"); return measured.length ? measured.filter((item) => item.state === "healthy").length / measured.length * 100 : null; }
function growthScore(marketing: { kpis: readonly FounderKpi[] }) { const values = ["monthly-growth", "daily-growth"].map((id) => marketing.kpis.find((item) => item.id === id)?.value).filter((value): value is number => value !== null && value !== undefined); return values.length ? Math.max(0, Math.min(100, 50 + values.reduce((sum, value) => sum + value, 0) / values.length)) : null; }
function find(items: readonly FounderKpi[], ...labels: string[]) { return items.find((item) => labels.includes(item.label)) ?? null; }
function metricText(item: FounderKpi | null, suffix: string) { return item?.value === null || item?.value === undefined ? `Unavailable ${suffix}` : `${item.value.toLocaleString()} ${suffix}`; }
function topCampaignName(marketing: { campaigns: readonly { name: string }[]; attribution: readonly { source: string; roas: number | null }[] }) { const channel = [...marketing.attribution].filter((item) => item.roas !== null).sort((a, b) => (b.roas ?? 0) - (a.roas ?? 0))[0]; return channel ? `${channel.source} by measured ROAS` : marketing.campaigns[0]?.name ?? "Unavailable"; }
function prioritize(founder: FounderAISnapshot["founder"], marketing: FounderAISnapshot["marketing"], sales: FounderAISnapshot["sales"], customer: FounderAISnapshot["customerSuccess"], health: number | null): FounderAIPriority[] { const items: FounderAIPriority[] = [], add = (id: string, title: string, impact: FounderAIPriority["impact"], expectedImpact: number, confidence: number, evidence: string) => items.push({ id, title, impact, expectedImpact, confidence, evidence, recommendationOnly: true }); const atRisk = customer.organizations.filter((item) => item.classification === "At Risk" || item.classification === "Critical").length, highValueTrials = customer.organizations.filter((item) => item.plan !== "Enterprise" && item.score >= 75).length, marketingWaste = marketing.attribution.filter((item) => item.roas !== null && item.roas < 1).length; if (atRisk) add("churn", "Review churn-risk accounts", "critical", atRisk * 10, .9, `${atRisk} account(s) are classified At Risk or Critical.`); if (highValueTrials) add("enterprise", "Contact enterprise-ready prospects", "high", highValueTrials * 8, .75, `${highValueTrials} healthy non-Enterprise account(s) show expansion signals.`); if (marketingWaste) add("marketing", "Review inefficient campaign allocation", "high", marketingWaste * 7, .8, `${marketingWaste} measured channel(s) report ROAS below 1.`); const pipeline = sales.kpis.find((item) => item.id === "pipeline-value")?.value; if (pipeline) add("pipeline", "Follow up high-value pipeline", "high", Math.min(100, pipeline / 100000), .78, `Measured pipeline value is ${pipeline.toLocaleString()}.`); if (health !== null && health < 70) add("platform", "Improve operating health", "high", 70 - health, .85, `Weighted business health is ${health}/100.`); if (founder.health.some((item) => item.state === "degraded")) add("infrastructure", "Upgrade or repair infrastructure", "critical", 90, .95, "One or more measured platform services are degraded."); if (!items.length) add("onboarding", "Improve onboarding and maintain operating cadence", "low", 20, .6, "No measured signal crossed a high-risk threshold; validate unavailable evidence."); return items.sort((a, b) => b.expectedImpact - a.expectedImpact); }
function correlate(marketing: FounderAISnapshot["marketing"], sales: FounderAISnapshot["sales"], customer: FounderAISnapshot["customerSuccess"]): FounderAICorrelation[] { const results: FounderAICorrelation[] = [], best = [...marketing.attribution].filter((item) => item.leads !== null && item.paidCustomers !== null).sort((a, b) => ((b.paidCustomers ?? 0) / Math.max(1, b.leads ?? 0)) - ((a.paidCustomers ?? 0) / Math.max(1, a.leads ?? 0)))[0]; if (best) results.push({ id: "channel-conversion", statement: `${best.source} currently has the strongest observed lead-to-paid ratio among measured channels.`, evidence: `${best.leads} leads and ${best.paidCustomers} paid customers are attributed.`, confidence: .75, causationClaimed: false }); const adopted = customer.organizations.filter((item) => item.reasons.some((reason) => reason.includes("AI usage recorded"))), retained = adopted.filter((item) => item.score >= 80); if (adopted.length) results.push({ id: "adoption-retention", statement: "Accounts with recorded AI usage currently co-occur with stronger health in the observed customer set.", evidence: `${retained.length} of ${adopted.length} AI-active accounts are Healthy.`, confidence: Math.min(.85, .5 + adopted.length * .02), causationClaimed: false }); const conversion = sales.kpis.find((item) => item.id === "conversion")?.value; if (conversion !== null && conversion !== undefined) results.push({ id: "sales-conversion", statement: "Sales conversion is an observed operating signal, not proof that a specific campaign caused closed revenue.", evidence: `Measured sales conversion is ${conversion}%.`, confidence: .9, causationClaimed: false }); if (!results.length) results.push({ id: "unavailable", statement: "Cross-module correlations are unavailable until comparable cohort evidence is recorded.", evidence: "No causal relationship is inferred from missing data.", confidence: 1, causationClaimed: false }); return results; }
