import type { LucideIcon } from "lucide-react";
import { Archive, BarChart3, CalendarRange, FileSearch, Handshake, Landmark, Megaphone, Newspaper, Settings, Share2, Sparkles, UsersRound } from "lucide-react";

export const growthSections = {
  campaigns: { title: "Campaigns", description: "Plan and review coordinated growth initiatives before anything is scheduled or published.", icon: Megaphone, action: "Plan a campaign", actionHref: "/vayon/creative-studio", groups: [{ title: "Campaign pipeline", items: ["Planning", "Draft", "Review", "Scheduled", "Published", "Completed"] }, { title: "Campaign types", items: ["Product Launch", "Feature Release", "Educational", "Founder Story", "Case Study", "Webinar", "Podcast", "Community", "Recruitment", "Investor Update"] }] },
  "content-calendar": { title: "Content Calendar", description: "Review planned content across day, week, and month without connecting publishing providers.", icon: CalendarRange, action: "Prepare content", actionHref: "/vayon/creative-studio", groups: [{ title: "Content details", items: ["Platform", "Status", "Objective", "Audience", "Campaign", "Owner", "Approval", "Publishing date"] }] },
  "social-media": { title: "Social Media", description: "Prepare channel-specific content and approvals. Social APIs and auto-publishing remain disconnected.", icon: Share2, action: "Prepare a social post", actionHref: "/vayon/creative-studio", groups: [{ title: "Supported channels", items: ["LinkedIn", "X", "Instagram", "Threads", "Facebook", "TikTok", "YouTube"] }] },
  "brand-assets": { title: "Brand Assets", description: "Keep the approved building blocks for consistent campaigns and executive communications discoverable.", icon: Archive, action: "Open Creative Studio", actionHref: "/vayon/creative-studio/brand-kits", groups: [{ title: "Brand library", items: ["Logos", "Colors", "Typography", "Brand voice", "Messaging", "Value propositions", "Company boilerplates", "Media kit"] }] },
  seo: { title: "SEO", description: "Organize search opportunities while measurements remain unavailable until governed sources are connected.", icon: FileSearch, action: "Draft search content", actionHref: "/vayon/creative-studio", groups: [{ title: "Search workspace", items: ["Keyword ideas", "Content opportunities", "Competitors", "Internal linking", "Top pages"] }] },
  pr: { title: "PR", description: "Prepare announcements and outreach with human review at every external communication boundary.", icon: Newspaper, action: "Draft an announcement", actionHref: "/vayon/creative-studio", groups: [{ title: "Public relations", items: ["Press Releases", "Media List", "Podcast Outreach", "Journalists", "Announcements"] }] },
  community: { title: "Community", description: "Plan community initiatives across owned and third-party spaces without connecting provider APIs.", icon: UsersRound, action: "Plan an initiative", actionHref: "/vayon/tasks", groups: [{ title: "Community channels", items: ["Discord", "Slack", "Reddit", "Facebook Groups", "LinkedIn Groups", "Community initiatives"] }] },
  influencers: { title: "Influencers", description: "Prepare creator research, fit reviews, briefs, and outreach for approval.", icon: Sparkles, action: "Prepare a creator brief", actionHref: "/vayon/creative-studio", groups: [{ title: "Creator workflow", items: ["Discovery", "Brand fit", "Briefs", "Outreach", "Approvals", "Deliverables"] }] },
  referrals: { title: "Referrals", description: "Design referral programs using the existing Growth contracts; tracking and payouts remain unavailable.", icon: Handshake, action: "Design a referral program", actionHref: "/vayon/workflows", groups: [{ title: "Referral planning", items: ["Program brief", "Audience", "Rewards", "Partner list", "Codes", "Approval"] }] },
  analytics: { title: "Analytics", description: "See which evidence sources are needed before growth performance can be calculated.", icon: BarChart3, action: "Review integration readiness", actionHref: "/vayon/settings/integrations", groups: [{ title: "Growth evidence", items: ["Traffic", "Engagement", "Leads", "Conversions", "Revenue attribution", "Campaign performance"] }] },
  "investor-relations": { title: "Investor Relations", description: "Prepare consistent investor communications and fundraising materials with explicit ownership and approval.", icon: Landmark, action: "Prepare an investor update", actionHref: "/vayon/creative/documents", groups: [{ title: "Investor workspace", items: ["Investor updates", "Fundraising timeline", "Milestones", "Pitch assets", "Meeting tracker", "Due diligence checklist"] }] },
  settings: { title: "Growth Settings", description: "Review growth readiness and approval boundaries without changing workspace integrations or permissions.", icon: Settings, action: "Review integrations", actionHref: "/vayon/settings/integrations", groups: [{ title: "Governance", items: ["Brand defaults", "Approval expectations", "Channel readiness", "Owners", "Connected evidence"] }] },
} as const satisfies Record<string, GrowthSection>;

export type GrowthSection = { title: string; description: string; icon: LucideIcon; action: string; actionHref: string; groups: readonly { title: string; items: readonly string[] }[] };
export type GrowthSectionSlug = keyof typeof growthSections;
export const growthSectionSlugs = Object.keys(growthSections) as GrowthSectionSlug[];
