import type { LucideIcon } from "lucide-react";
import { BarChart3, Building2, ContactRound, FileSearch, Handshake, LineChart, Megaphone, Palette, Share2, Target, Users } from "lucide-react";

type GrowthSection = { readonly title: string; readonly description: string; readonly icon: LucideIcon; readonly action: string; readonly actionHref: string; readonly groups: readonly { readonly title: string; readonly items: readonly string[] }[] };

export const growthSections = {
  "lead-generation": { title: "Lead Generation", description: "Plan property campaigns and connect every response to an enquiry, appointment, viewing, offer, and transaction.", icon: Target, action: "Create a property campaign", actionHref: "/vayon/creative-studio", groups: [{ title: "Acquisition channels", items: ["Meta Ads", "Google Ads", "Landing Pages", "WhatsApp Campaigns", "SMS Campaigns", "Email Campaigns", "Referral Campaigns", "Property Portals", "QR Campaigns", "Open House Campaigns"] }, { title: "Evidence tracked", items: ["Leads Generated", "Cost Per Lead", "Appointments", "Site Visits", "Offers", "Sales", "ROI"] }] },
  "listing-performance": { title: "Listing Performance", description: "Find the listings that need attention before enquiries slow down or mandates expire.", icon: Building2, action: "Review property inventory", actionHref: "/vayon/properties", groups: [{ title: "Listing signals", items: ["Most Viewed Properties", "Lowest Viewed Properties", "Trending Listings", "Expiring Listings", "Inactive Listings", "Properties Without Enquiries", "Average Days On Market", "Listing Score", "AI Recommendations"] }] },
  "buyer-intelligence": { title: "Buyer Intelligence", description: "Understand verified buyer demand so agents can prioritize the right conversations and property matches.", icon: Users, action: "Review buyer leads", actionHref: "/vayon/leads", groups: [{ title: "Buyer demand", items: ["Budget Distribution", "Location Demand", "Bedroom Demand", "Property Type Demand", "Investment Buyers", "Luxury Buyers", "Returning Buyers", "High Intent Buyers", "Buyer Activity Heatmap", "Conversion Funnel"] }] },
  "seller-intelligence": { title: "Seller Intelligence", description: "Track seller acquisition from valuation request through published listing and accepted offer.", icon: ContactRound, action: "Review seller pipeline", actionHref: "/vayon/leads", groups: [{ title: "Seller pipeline", items: ["Valuation Requests", "Listing Pipeline", "Listing Performance", "Listing Quality", "Average Selling Time", "Price Reduction Alerts", "High Potential Sellers"] }] },
  marketing: { title: "Property Marketing", description: "Prepare real-estate creative that helps agents win instructions, promote listings, and generate enquiries.", icon: Palette, action: "Open Creative Studio", actionHref: "/vayon/creative-studio", groups: [{ title: "Property marketing tools", items: ["Luxury Brochure", "Flyer Generator", "Property Reel", "Instagram Post", "Facebook Campaign", "Google Ads", "WhatsApp Campaign", "Email Campaign", "QR Flyer", "Open House Invitation", "Virtual Tour Landing Page"] }] },
  advertising: { title: "Advertising", description: "Prepare approval-ready property advertising and review the evidence required to measure results.", icon: Megaphone, action: "Prepare an advertising brief", actionHref: "/vayon/creative-studio", groups: [{ title: "Advertising workspace", items: ["Listing Campaigns", "Buyer Campaigns", "Seller Campaigns", "Open House Ads", "Retargeting", "Audience", "Budget", "Approval", "Lead Attribution"] }] },
  "social-media": { title: "Social Media", description: "Review property content and the real-estate outcomes it produces. Publishing always remains subject to approval.", icon: Share2, action: "Prepare a property post", actionHref: "/vayon/creative-studio", groups: [{ title: "Real estate performance", items: ["Published Listings", "Reels Published", "Videos", "Reach", "Engagement", "Leads Generated", "Clicks", "Appointments"] }] },
  "property-seo": { title: "Property SEO", description: "Improve how buyers discover listings, locations, agents, builders, rentals, commercial space, and luxury homes.", icon: FileSearch, action: "Review property pages", actionHref: "/vayon/properties", groups: [{ title: "Pages to optimize", items: ["Property Pages", "Location Pages", "Agent Pages", "Builder Pages", "Commercial Pages", "Rental Pages", "Luxury Pages"] }, { title: "Search readiness", items: ["SEO Score", "Keyword Ranking", "AI Suggestions", "Missing Metadata"] }] },
  "referral-network": { title: "Referral Network", description: "Organize partners who introduce buyers and sellers, with transparent commission and revenue evidence.", icon: Handshake, action: "Review agencies and partners", actionHref: "/vayon/crm/companies", groups: [{ title: "Property partner network", items: ["Referral Partners", "Mortgage Brokers", "Banks", "Lawyers", "Interior Designers", "Architects", "Moving Companies", "Insurance Partners", "Commission Tracking", "Referral Revenue"] }] },
  "market-intelligence": { title: "Market Intelligence", description: "Turn governed property and location evidence into practical acquisition, pricing, and inventory decisions.", icon: LineChart, action: "Review property analytics", actionHref: "/vayon/properties/analytics", groups: [{ title: "Market signals", items: ["Neighborhood Heatmaps", "Average Prices", "Rental Trends", "Inventory", "Demand", "Supply", "Market Absorption", "Price Growth", "Competitor Listings"] }] },
  analytics: { title: "Analytics", description: "Connect real-estate growth activity to enquiries, viewings, offers, transactions, revenue, and commission.", icon: BarChart3, action: "Open analytics", actionHref: "/vayon/analytics", groups: [{ title: "Growth evidence", items: ["Lead Sources", "Conversion Funnel", "Listing Performance", "Appointments", "Site Visits", "Offers", "Sales", "Revenue", "Commission", "ROI"] }] },
  reports: { title: "Reports", description: "Prepare evidence-backed reports for brokers, managers, agents, sellers, and property owners.", icon: BarChart3, action: "Review analytics", actionHref: "/vayon/analytics", groups: [{ title: "Real estate reports", items: ["Sales Report", "Commission Report", "Agent Performance", "Property Performance", "Buyer Report", "Seller Report", "Marketing ROI", "Revenue Report", "Listing Performance", "Lead Conversion", "Viewing Analytics", "Closing Analytics"] }] },
} as const satisfies Record<string, GrowthSection>;

export const founderGrowthSections = {
  campaigns: { title: "Campaigns", description: "Plan platform campaigns before scheduling or publishing.", icon: Megaphone, action: "Plan a campaign", actionHref: "/vayon/creative-studio", groups: [{ title: "Campaign pipeline", items: ["Planning", "Draft", "Review", "Scheduled", "Published", "Completed"] }] },
  "content-calendar": { title: "Content Calendar", description: "Review the platform content calendar.", icon: Megaphone, action: "Prepare content", actionHref: "/vayon/creative-studio", groups: [{ title: "Content details", items: ["Platform", "Status", "Objective", "Audience", "Campaign", "Owner", "Approval", "Publishing date"] }] },
  "brand-assets": { title: "Brand Assets", description: "Manage platform-level brand foundations.", icon: Palette, action: "Open brand kits", actionHref: "/vayon/creative-studio/brand-kits", groups: [{ title: "Brand library", items: ["Logos", "Colors", "Typography", "Brand voice", "Messaging", "Value propositions", "Company boilerplates", "Media kit"] }] },
  seo: { title: "Generic SEO", description: "Review cross-industry search opportunities.", icon: FileSearch, action: "Draft search content", actionHref: "/vayon/creative-studio", groups: [{ title: "Search workspace", items: ["Keyword ideas", "Content opportunities", "Competitors", "Internal linking", "Top pages"] }] },
  pr: { title: "PR", description: "Prepare platform announcements and outreach.", icon: Megaphone, action: "Draft an announcement", actionHref: "/vayon/creative-studio", groups: [{ title: "Public relations", items: ["Press Releases", "Media List", "Podcast Outreach", "Journalists", "Announcements"] }] },
  community: { title: "Community", description: "Plan platform community initiatives.", icon: Users, action: "Plan an initiative", actionHref: "/vayon/tasks", groups: [{ title: "Community channels", items: ["Discord", "Slack", "Reddit", "Facebook Groups", "LinkedIn Groups", "Community initiatives"] }] },
  influencers: { title: "Influencer Management", description: "Prepare creator research and outreach for approval.", icon: Users, action: "Prepare a creator brief", actionHref: "/vayon/creative-studio", groups: [{ title: "Creator workflow", items: ["Discovery", "Brand fit", "Briefs", "Outreach", "Approvals", "Deliverables"] }] },
  referrals: { title: "Generic Referrals", description: "Maintain the cross-industry referral planning surface.", icon: Handshake, action: "Review workflows", actionHref: "/vayon/workflows", groups: [{ title: "Referral planning", items: ["Program brief", "Audience", "Rewards", "Partner list", "Codes", "Approval"] }] },
  "investor-relations": { title: "Investor Relations", description: "Prepare investor communications and fundraising materials.", icon: Building2, action: "Prepare an investor update", actionHref: "/vayon/creative/documents", groups: [{ title: "Investor workspace", items: ["Investor updates", "Fundraising timeline", "Milestones", "Pitch assets", "Meeting tracker", "Due diligence checklist"] }] },
  settings: { title: "Platform Growth Settings", description: "Review platform growth governance and approval boundaries.", icon: BarChart3, action: "Review integrations", actionHref: "/vayon/settings/integrations", groups: [{ title: "Governance", items: ["Brand defaults", "Approval expectations", "Channel readiness", "Owners", "Connected evidence"] }] },
} as const satisfies Record<string, GrowthSection>;

export const allGrowthSections = { ...growthSections, ...founderGrowthSections } as const;
export type GrowthSectionSlug = keyof typeof allGrowthSections;
export const growthSectionSlugs = Object.keys(allGrowthSections) as GrowthSectionSlug[];
export const customerGrowthSectionSlugs = Object.keys(growthSections) as (keyof typeof growthSections)[];
