"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Check, ClipboardList, FileImage, ShieldCheck } from "lucide-react";
import { Button } from "@/features/platform/design-system";
import { brandVoices, communityRecommendations, creativeAssetTypes, investorUpdateSections, prepareCampaignPlan, reviewStatuses, strategyTypes, type BrandVoice, type ReviewStatus, type StrategyType } from "./strategy-engine";

type QueueItem = { id: string; title: string; type: string; status: ReviewStatus; why: string; evidence: readonly string[]; missing: readonly string[]; confidence: "Low" | "Medium" | "High"; dependencies: readonly string[] };

export function StrategyWorkspace() {
  const [strategy, setStrategy] = useState<StrategyType>("Product Launch");
  const [voice, setVoice] = useState<BrandVoice>("Professional");
  const [goal, setGoal] = useState("");
  const [audience, setAudience] = useState("");
  const [assetType, setAssetType] = useState<(typeof creativeAssetTypes)[number]>("LinkedIn Carousel");
  const [queue, setQueue] = useState<QueueItem[]>([]);
  const plan = useMemo(() => goal.trim() && audience.trim() ? prepareCampaignPlan(strategy, goal.trim(), audience.trim(), voice) : null, [audience, goal, strategy, voice]);
  function addRecommendation(title: string, type: string, why: string, dependencies: readonly string[]) {
    setQueue((current) => [...current, { id: crypto.randomUUID(), title, type, status: "Draft", why, evidence: [], missing: ["Verified performance evidence", "Named approval owner"], confidence: "Low", dependencies }]);
  }
  function updateStatus(id: string, status: ReviewStatus) { setQueue((current) => current.map((item) => item.id === id ? { ...item, status } : item)); }
  return <div className="space-y-6">
    <section className="rounded-3xl border border-vds-border bg-vds-surface p-5 sm:p-6" aria-labelledby="strategy-generator-title"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-vds-primary-soft text-vds-primary"><ClipboardList className="size-5" aria-hidden="true" /></span><div><h2 id="strategy-generator-title" className="font-semibold">Strategy Generator</h2><p className="mt-1 text-sm text-vds-muted">Decide what to create, why it matters, who it serves, and when it should launch.</p></div></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Strategy"><select value={strategy} onChange={(event) => setStrategy(event.target.value as StrategyType)} className="vds-focus h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm">{strategyTypes.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Brand voice"><select value={voice} onChange={(event) => setVoice(event.target.value as BrandVoice)} className="vds-focus h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm">{brandVoices.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Goal"><input value={goal} onChange={(event) => setGoal(event.target.value)} className="vds-focus h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm" placeholder="Describe the business outcome" /></Field><Field label="Target audience"><input value={audience} onChange={(event) => setAudience(event.target.value)} className="vds-focus h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm" placeholder="Describe the intended audience" /></Field></div>
      {plan ? <div className="mt-5 rounded-2xl border border-vds-accent-border bg-vds-primary-soft p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-vds-primary">Draft campaign plan</p><h3 className="mt-1 font-semibold">{plan.strategy}</h3></div><span className="rounded-full border border-vds-border px-3 py-1 text-xs">{plan.status}</span></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><PlanField label="Goal" value={plan.goal} /><PlanField label="Target audience" value={plan.targetAudience} /><PlanField label="Primary message" value={plan.primaryMessage} /><PlanField label="CTA" value={plan.cta} /><PlanField label="Success criteria" value={plan.successCriteria} /><PlanField label="Estimated effort" value={plan.estimatedEffort} /><PlanField label="Supporting messages" value={plan.supportingMessages.join(" · ")} /><PlanField label="Channels" value={plan.channels.join(" · ")} /><PlanField label="Creative requirements" value={plan.creativeRequirements.join(" · ")} /><PlanField label="Timeline" value={plan.timeline.join(" → ")} /><PlanField label="Dependencies" value={plan.dependencies.join(" · ")} /><PlanField label="Approvals" value={plan.approvals.join(" · ")} /></dl><Button className="mt-5" onClick={() => addRecommendation(`${strategy}: ${goal}`, "Campaign", "The user defined a campaign goal and audience for strategic review.", plan.dependencies)}>Add to review queue</Button></div> : <ActionableEmpty title="Define the campaign goal and audience." detail="The AI CMO will prepare a complete plan without publishing or executing anything." />}
    </section>

    <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-3xl border border-vds-border bg-vds-surface p-5"><h2 className="font-semibold">Creative Studio Request</h2><p className="mt-1 text-sm text-vds-muted">Prepare a structured brief. Creative Studio remains the generation engine.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Asset type"><select value={assetType} onChange={(event) => setAssetType(event.target.value as typeof assetType)} className="vds-focus h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm">{creativeAssetTypes.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Attached brand voice"><div className="flex h-11 items-center rounded-xl border border-vds-border bg-vds-input px-3 text-sm">{voice}</div></Field></div><div className="mt-4 rounded-2xl bg-vds-input p-4 text-sm"><p><strong>Purpose:</strong> {goal || "Required before approval"}</p><p className="mt-2"><strong>Audience:</strong> {audience || "Required before approval"}</p><p className="mt-2"><strong>Visual style:</strong> Align with the {voice} profile</p><p className="mt-2"><strong>Required assets:</strong> Brand-approved logo, colors, and copy</p><p className="mt-2"><strong>Dimensions:</strong> Confirm in Creative Studio for the selected channel</p><p className="mt-2"><strong>Priority and deadline:</strong> Assign during review</p></div><Button className="mt-4" disabled={!goal.trim() || !audience.trim()} onClick={() => addRecommendation(`${assetType} for ${strategy}`, "Creative brief", "The planned campaign requires a review-ready creative asset.", ["Campaign approval", "Brand assets", "Creative Studio generation"])}><FileImage className="size-4" />Prepare creative brief</Button></div>
      <div className="rounded-3xl border border-vds-border bg-vds-surface p-5"><h2 className="font-semibold">Investor Update Planner</h2><p className="mt-1 text-sm text-vds-muted">A monthly structure that accepts verified narrative only—no invented numbers.</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{investorUpdateSections.map((item) => <li key={item} className="rounded-xl bg-vds-input px-3 py-2 text-sm"><Check className="mr-2 inline size-4 text-vds-success" aria-hidden="true" />{item}</li>)}</ul><Button className="mt-4" variant="secondary" onClick={() => addRecommendation("Monthly investor update", "Investor communication", "A consistent update keeps verified progress, risks, and milestones reviewable.", ["Verified milestones", "Customer evidence", "Fundraising status", "Executive approval"])}>Prepare update structure</Button></div></section>

    <section className="rounded-3xl border border-vds-border bg-vds-surface p-5"><h2 className="font-semibold">Community Recommendations</h2><p className="mt-1 text-sm text-vds-muted">Each activity enters review before any external action.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{communityRecommendations.map((item) => <Button type="button" variant="control" key={item} onClick={() => addRecommendation(item, "Community", "This activity can create a useful audience touchpoint once the community need is verified.", ["Community evidence", "Owner", "Content approval"])} className="flex items-center justify-between rounded-2xl border border-vds-border bg-vds-input p-4 text-left text-sm font-medium hover:border-vds-accent-border">{item}<ArrowRight className="size-4 text-vds-primary" /></Button>)}</div></section>

    <section className="rounded-3xl border border-vds-border bg-vds-surface p-5" aria-labelledby="review-queue-title"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-vds-success" aria-hidden="true" /><div><h2 id="review-queue-title" className="font-semibold">Review Queue & AI Decision Log</h2><p className="mt-1 text-sm text-vds-muted">Nothing executes automatically. Every recommendation exposes its reasoning and evidence gaps.</p></div></div>{queue.length ? <div className="mt-5 grid gap-4">{queue.map((item) => <article key={item.id} className="rounded-2xl border border-vds-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.14em] text-vds-primary">{item.type}</p><h3 className="mt-1 font-semibold">{item.title}</h3></div><select aria-label={`Review status for ${item.title}`} value={item.status} onChange={(event) => updateStatus(item.id, event.target.value as ReviewStatus)} className="vds-focus h-10 rounded-xl border border-vds-border bg-vds-input px-3 text-sm">{reviewStatuses.map((status) => <option key={status}>{status}</option>)}</select></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><PlanField label="Why suggested" value={item.why} /><PlanField label="Evidence used" value={item.evidence.length ? item.evidence.join(" · ") : "No performance evidence is available yet."} /><PlanField label="Missing information" value={item.missing.join(" · ")} /><PlanField label="Confidence" value={`${item.confidence} — limited by missing evidence`} /><PlanField label="Dependencies" value={item.dependencies.join(" · ")} /></dl></article>)}</div> : <ActionableEmpty title="Your review queue is ready." detail="Prepare a campaign, creative brief, investor update, or community activity to add the first recommendation." />}</section>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-medium">{label}{children}</label>; }
function PlanField({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-[.12em] text-vds-subtle">{label}</dt><dd className="mt-1 leading-6 text-vds-muted">{value}</dd></div>; }
function ActionableEmpty({ title, detail }: { title: string; detail: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-vds-border p-6 text-center"><p className="font-medium">{title}</p><p className="mt-1 text-sm text-vds-muted">{detail}</p></div>; }
