import Link from "next/link";
import { ArrowUpRight, Bot, CalendarClock, ChartNoAxesCombined, Megaphone, Sparkles, Workflow } from "lucide-react";
import { Button } from "@/features/platform/design-system";
import type { OpenAIHealth } from "@/features/platform/openai/domain/models";
import { WorkforceChatPanel } from "@/features/platform/openai/runtime/ChatPanel";
import type { ConversationSnapshot } from "@/features/platform/openai/runtime/models";
import { FounderRealtime } from "@/features/platform/founder/components/FounderRealtime";
import { LazyFounderCharts } from "@/features/platform/founder/components/LazyFounderCharts";
import type { FounderChart, FounderKpi } from "@/features/platform/founder/types";
import type { MarketingDirectorSnapshot } from "../types";
import { MarketingReportExports } from "./MarketingReportExports";

const card = "rounded-3xl border border-vds-border/70 bg-vds-surface/70 shadow-xl shadow-vds-shadow/10 backdrop-blur-xl";
export function MarketingDirectorDashboard({ data, history, health, goal }: { data: MarketingDirectorSnapshot; history: ConversationSnapshot; health: OpenAIHealth; goal: string }) {
  return <main className="relative mx-auto max-w-[120rem] space-y-8 overflow-hidden px-4 py-6 sm:px-6 lg:px-8"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[34rem] bg-[radial-gradient(circle_at_18%_8%,var(--vds-color-primary-soft),transparent_35%),radial-gradient(circle_at_82%_14%,var(--vds-color-info-soft),transparent_28%)]" aria-hidden="true"/><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.22em] text-vds-primary"><Megaphone className="size-4" aria-hidden="true"/>Founder Portal</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">AI Marketing Director</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-vds-muted sm:text-base">Campaign performance, acquisition attribution, governed AI planning, automation, and reporting from authoritative VAYON evidence.</p></div><div className="flex flex-col items-end gap-2"><FounderRealtime/><Link className="text-xs text-vds-primary" href="/platform/founder">← Founder Operating System</Link></div></header>
    <section><h2 className="sr-only">Marketing KPIs</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{data.kpis.map((item, index) => <Kpi item={item} index={index} key={item.id}/>)}</div></section>
    <section><Heading icon={ChartNoAxesCombined} title="Growth and conversion trends"/><LazyFounderCharts charts={charts(data)}/></section>
    <section><Heading icon={CalendarClock} title="Campaign manager"/><div className={`${card} overflow-x-auto`}><table className="w-full min-w-[50rem] text-left text-sm"><caption className="sr-only">Marketing campaigns</caption><thead><tr className="border-b border-vds-border text-xs uppercase tracking-[.12em] text-vds-subtle"><th className="px-5 py-4">Campaign</th><th>Channel</th><th>State</th><th>Updated</th><th>Workspace</th></tr></thead><tbody>{data.campaigns.map((campaign) => <tr className="border-b border-vds-border/50 last:border-0" key={campaign.id}><th className="px-5 py-4 font-medium">{campaign.name}</th><td className="text-vds-muted">{campaign.channel}</td><td><span className="rounded-full border border-vds-border px-2.5 py-1 text-xs capitalize">{campaign.state}</span></td><td className="text-vds-muted">{new Date(campaign.updatedAt).toLocaleString()}</td><td><Link className="inline-flex items-center gap-1 text-vds-primary" href="/vayon/creative-studio">Manage <ArrowUpRight className="size-3.5"/></Link></td></tr>)}{!data.campaigns.length && <tr><td className="px-5 py-14 text-center text-vds-muted" colSpan={5}>No authorized campaigns are available. Create a governed draft in Creative Studio.</td></tr>}</tbody></table></div></section>
    <section id="campaign-builder"><Heading icon={Sparkles} title="AI campaign builder"/><div className={`${card} p-5 sm:p-6`}><form className="grid gap-3 lg:grid-cols-[1fr_auto]" method="get"><div><label className="text-sm font-medium" htmlFor="marketing-goal">Marketing goal</label><textarea className="mt-2 min-h-24 w-full rounded-2xl border border-vds-border bg-vds-elevated p-3 text-sm" id="marketing-goal" name="goal" defaultValue={goal} maxLength={1000} required placeholder="Example: Increase qualified enterprise demo requests in the next 30 days."/></div><Button className="self-end" type="submit">Prepare AI brief</Button></form><div className="mt-4 flex flex-wrap gap-2 text-xs text-vds-muted">{["Campaign strategy","Headlines","Descriptions","CTAs","Audience recommendations","Budget suggestions","Keywords","UTM parameters"].map((item) => <span className="rounded-full border border-vds-border px-3 py-1.5" key={item}>{item}</span>)}</div>{goal && <Link className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-vds-primary" href={`/vayon/creative-studio/wizard?goal=${encodeURIComponent(goal)}`}>Continue to Creative Studio asset generation <ArrowUpRight className="size-4"/></Link>}</div></section>
    <section><Heading icon={ChartNoAxesCombined} title="Acquisition attribution"/><div className={`${card} overflow-x-auto`}><table className="w-full min-w-[65rem] text-left text-sm"><caption className="sr-only">Acquisition source attribution</caption><thead><tr className="border-b border-vds-border text-xs uppercase tracking-[.1em] text-vds-subtle">{["Source","Visitors","Leads","Trials","Paid customers","Revenue","CAC","ROAS"].map((item) => <th className="px-4 py-4" key={item}>{item}</th>)}</tr></thead><tbody>{data.attribution.map((row) => <tr className="border-b border-vds-border/50 last:border-0" key={row.source}><th className="px-4 py-4 font-medium">{row.source}</th>{[row.visitors,row.leads,row.trials,row.paidCustomers,row.revenue,row.cac,row.roas].map((value, index) => <td className="px-4 py-4 text-vds-muted" key={index}>{value === null ? "Unavailable" : value.toLocaleString(undefined, { maximumFractionDigits: 2 })}</td>)}</tr>)}</tbody></table></div></section>
    <section><Heading icon={Bot} title="AI Marketing Assistant"/><WorkforceChatPanel employee="marketing-ai" initial={history} health={health} initialPrompt={goal ? `Build a recommendation-only campaign for this founder goal: ${goal}. Include strategy, headlines, descriptions, CTAs, audience recommendations, budget suggestions, keywords, and UTM parameters. Use only authoritative evidence and identify unavailable performance data.` : ""}/></section>
    <section><Heading icon={Workflow} title="Marketing automation"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{data.automations.map((item) => <article className={`${card} p-5`} key={item.id}><h3 className="font-medium">{item.name}</h3><p className="mt-2 text-xs text-vds-muted">Trigger: {item.trigger}</p><p className="mt-4 text-[10px] uppercase tracking-[.12em] text-vds-primary">Consent required · Unsubscribe enforced · Approval required</p><Link className="mt-4 inline-flex items-center gap-1 text-xs text-vds-primary" href="/vayon/workflows">Open workflow framework <ArrowUpRight className="size-3"/></Link></article>)}</div></section>
    <section><Heading icon={ChartNoAxesCombined} title="Reporting"/><MarketingReportExports data={data}/></section>
  </main>;
}
function Kpi({ item, index }: { item: FounderKpi; index: number }) { return <article className={`${card} min-h-32 p-4 transition hover:-translate-y-0.5 motion-safe:animate-[fade-in_.45s_ease-out_both]`} style={{ animationDelay: `${index * 35}ms` }}><p className="text-[10px] uppercase tracking-[.13em] text-vds-subtle">{item.label}</p><p className="mt-4 text-2xl font-semibold">{item.value === null ? "—" : `${item.unit === "currency" ? "$" : ""}${item.value.toLocaleString(undefined, { maximumFractionDigits: 2 })}${item.unit === "percent" ? "%" : ""}`}</p><p className="mt-2 text-[10px] uppercase text-vds-subtle">{item.status}</p></article>; }
function Heading({ icon: Icon, title }: { icon: typeof Megaphone; title: string }) { return <div className="mb-4 flex items-center gap-2"><Icon className="size-4 text-vds-primary" aria-hidden="true"/><h2 className="text-lg font-semibold">{title}</h2></div>; }
function charts(data: MarketingDirectorSnapshot): FounderChart[] { const keys = ["marketing_spend","marketing_revenue","marketing_roi","trial_conversion","paid_conversion","monthly_growth","daily_growth"]; return keys.map((key) => ({ id: key, label: key.replaceAll("_", " "), unit: data.metrics.find((row) => row.metric === key)?.unit ?? "count", points: data.metrics.filter((row) => row.metric === key).slice(0, 12).reverse().map((row) => ({ label: new Date(row.recordedAt).toLocaleDateString(undefined, { month: "short", day: "numeric" }), value: row.value })) })); }
