import Link from "next/link";
import type { RecommendationNode } from "@/features/platform/ai-collaboration";
import type { WorkforceActivity, WorkforceTask } from "../domain/models";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";
const unavailable = "Unavailable — supporting operational evidence is not connected";
const approvalHref = (intent: string) => `/vayon/approvals?intent=${intent}&source=alex-operations-manager`;

export function AlexOperationsManagerDashboard({ tasks, activity, recommendations, asOf }: { readonly tasks: readonly WorkforceTask[]; readonly activity: readonly WorkforceActivity[]; readonly recommendations: readonly RecommendationNode[]; readonly asOf: string }) {
  const open = tasks.filter((task) => task.status === "pending" || task.status === "running");
  const asOfTime = new Date(asOf).getTime();
  const overdue = open.filter((task) => task.deadline && new Date(task.deadline).getTime() < asOfTime);
  const highPriority = open.filter((task) => task.priority === "high" || task.priority === "urgent");
  const blocked = tasks.filter((task) => task.status === "failed" || (task.dependencies?.length ?? 0) > 0 && (task.progress ?? 0) === 0);
  const unassigned = open.filter((task) => !task.owner.trim());
  const viewings = open.filter((task) => task.type === "Meeting Scheduling" && /viewing|inspection|property/i.test(task.title));
  const meetings = open.filter((task) => task.type === "Meeting Scheduling");
  const documents = tasks.filter((task) => task.type === "Document Review");
  const pendingApprovals = tasks.filter((task) => task.approvalState === "pending").length + recommendations.filter((item) => item.approvalStatus === "pending").length;
  const risks = [...blocked.map((task) => ({ id: task.id, title: task.title, evidence: `Recorded status ${task.status}; ${task.dependencies?.length ?? 0} dependencies`, intent: "escalate_issue", confidence: "High" })), ...overdue.map((task) => ({ id: `overdue-${task.id}`, title: task.title, evidence: `Deadline ${task.deadline}`, intent: "reschedule_meeting", confidence: "High" })), ...highPriority.filter((task) => !blocked.includes(task) && !overdue.includes(task)).map((task) => ({ id: `priority-${task.id}`, title: task.title, evidence: `Recorded ${task.priority} priority`, intent: task.type === "Meeting Scheduling" ? "schedule_viewing" : "assign_task", confidence: "Medium" }))].slice(0, 8);

  return <section className="space-y-5" aria-labelledby="alex-operations-title">
    <header className={card}><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Alex · AI Operations Manager</p><h2 id="alex-operations-title" className="mt-2 text-2xl font-semibold">Today&apos;s Operations Brief</h2><p className="mt-2 text-sm text-vds-muted">Operational recommendations from recorded tasks and approvals. Alex never schedules, assigns, contacts, or escalates without human approval.</p></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Upcoming Viewings", viewings.length, "Open meeting tasks identified as viewings"], ["Pending Tasks", open.length, "Recorded pending or running tasks"], ["Pending Approvals", pendingApprovals, "Task and collaboration approval records"], ["Registrations", "Unavailable", unavailable], ["Document Status", documents.length ? `${documents.filter((task) => task.status === "completed").length}/${documents.length} reviewed` : "Unavailable", documents.length ? "Recorded document-review tasks" : unavailable], ["Operational Risks", risks.length, "Blocked, overdue, or high-priority task evidence"], ["Upcoming Deadlines", open.filter((task) => task.deadline).length, "Open tasks with recorded deadlines"], ["Activity Signals", activity.length, "Verified operations activity events"],
    ].map(([label, value, evidence]) => <article className={card} key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {evidence}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card} aria-labelledby="task-coordination"><h3 id="task-coordination" className="font-semibold">Task Coordination</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Overdue Tasks", overdue.length], ["High Priority Tasks", highPriority.length], ["Blocked Tasks", blocked.length], ["Unassigned Tasks", unassigned.length], ["Duplicate Tasks", "Unavailable"]].map(([label, value]) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-2">{[["assign_task", "Prepare Assignment"], ["reschedule_meeting", "Prepare Rescheduling"], ["escalate_issue", "Prepare Escalation"]].map(([intent, label]) => <Link className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(intent)} key={intent}>{label}</Link>)}</div></section>
      <section className={card} aria-labelledby="calendar-coordination"><h3 id="calendar-coordination" className="font-semibold">Calendar Coordination</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-vds-elevated p-3"><dt>Property Viewings</dt><dd className="mt-1">{viewings.length}</dd></div><div className="rounded-xl bg-vds-elevated p-3"><dt>Client Meetings</dt><dd className="mt-1">{meetings.length}</dd></div>{["Agent Availability", "Double Bookings", "Conflicts", "Travel Gaps"].map((label) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 text-xs text-vds-muted">Unavailable</dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-2">{[["reschedule_meeting", "Prepare Reschedule"], ["merge_meetings", "Prepare Merge"], ["delegate_meeting", "Prepare Delegation"]].map(([intent, label]) => <Link className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(intent)} key={intent}>{label}</Link>)}</div></section></div>
    <div className="grid gap-5 xl:grid-cols-3"><section className={card}><h3 className="font-semibold">Viewing Management</h3><ul className="mt-4 space-y-2 text-sm"><li>Upcoming: {viewings.length}</li><li>Pending confirmations: Unavailable</li><li>Cancelled: {tasks.filter((task) => task.status === "cancelled" && task.type === "Meeting Scheduling").length}</li><li>Missed: Unavailable</li><li>Required documents: Unavailable</li></ul></section><section className={card}><h3 className="font-semibold">Document Readiness</h3><ul className="mt-4 space-y-2 text-sm">{["Property Documents", "Buyer Documents", "Seller Documents", "Loan Documents", "Registration Documents"].map((label) => <li key={label}>{label}: {unavailable}</li>)}</ul><p className="mt-3 text-xs text-vds-muted">Missing, expired, and pending classifications require document metadata.</p></section><section className={card}><h3 className="font-semibold">Workflow Monitor</h3><ul className="mt-4 space-y-2 text-sm">{["Lead Qualification", "Property Verification", "Negotiation", "Booking", "Registration", "Handover"].map((label) => <li key={label}>{label}: {tasks.filter((task) => task.title.toLowerCase().includes(label.toLowerCase())).length || "No recorded stage task"}</li>)}</ul><p className="mt-3 text-xs text-vds-muted">Blocked and long-running stages are reported only from recorded tasks and dependencies.</p></section></div>
    <section className={card} aria-labelledby="operational-insights"><h3 id="operational-insights" className="font-semibold">Operational Insights &amp; Next Best Actions</h3><p className="mt-2 text-sm text-vds-muted">Bottlenecks, repeated delays, approval backlog, scheduling conflicts, document issues, and capacity concerns remain evidence constrained.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{risks.map((risk) => <article className="rounded-xl bg-vds-elevated p-4" key={risk.id}><h4 className="font-medium">{risk.title}</h4><p className="mt-2 text-xs text-vds-muted"><strong>Evidence:</strong> {risk.evidence}</p><p className="mt-2 text-xs text-vds-muted"><strong>Expected Outcome:</strong> A reviewed operational owner and next commitment.</p><p className="mt-2 text-xs text-vds-muted"><strong>Confidence:</strong> {risk.confidence}</p><Link className="mt-3 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href={approvalHref(risk.intent)}>Prepare for approval</Link></article>)}{!risks.length && <p className="text-sm text-vds-muted">No operational risk is supported by current evidence.</p>}</div><div className="mt-4 flex flex-wrap gap-2">{[["schedule_viewing", "Schedule Viewing"], ["collect_documents", "Collect Documents"], ["approve_request", "Approve Request"], ["assign_task", "Assign Task"], ["reschedule_meeting", "Reschedule Meeting"], ["contact_buyer", "Contact Buyer"], ["contact_seller", "Contact Seller"], ["escalate_issue", "Escalate Issue"]].map(([intent, label]) => <Link className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(intent)} key={intent}>{label}</Link>)}</div></section>
  </section>;
}
