import Link from "next/link";
import type { SalesAIDashboard } from "@/features/platform/sales-ai/types";
import type { RecommendationNode } from "@/features/platform/ai-collaboration";
import type { WorkforceTask } from "../domain/models";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";
const unavailable = "Unavailable — supporting finance evidence is not connected";
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const approvalHref = (intent: string) => `/vayon/approvals?intent=${intent}&source=david-finance-manager`;

export function DavidFinanceManagerDashboard({ sales, tasks, recommendations }: { readonly sales: SalesAIDashboard; readonly tasks: readonly WorkforceTask[]; readonly recommendations: readonly RecommendationNode[] }) {
  const highConfidence = sales.deals.filter((deal) => deal.probability >= 70 && deal.risk !== "high");
  const lowConfidence = sales.deals.filter((deal) => deal.probability < 50 || deal.risk === "high");
  const upcomingClosings = sales.deals.filter((deal) => deal.probability >= 70);
  const financeTasks = tasks.filter((task) => task.type === "Deal Analysis" || task.type === "Document Review");
  const approvalBacklog = recommendations.filter((item) => item.approvalStatus === "pending").length + tasks.filter((task) => task.approvalState === "pending").length;
  const riskItems = sales.deals.filter((deal) => deal.risk !== "low").slice(0, 8);

  return <section className="space-y-5" aria-labelledby="david-finance-title">
    <header className={card}><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">David · AI Finance Manager</p><h2 id="david-finance-title" className="mt-2 text-2xl font-semibold">Today&apos;s Financial Brief</h2><p className="mt-2 text-sm text-vds-muted">Evidence-backed financial intelligence only. David never moves money, changes commission, or approves financial requests automatically.</p></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Revenue Pipeline", money(sales.deals.reduce((sum, deal) => sum + deal.value, 0)), `${sales.deals.length} active deal records`], ["Expected Revenue", money(sales.forecast.expectedMonthlyRevenue), sales.forecast.explanation], ["Pending Revenue", money(sales.forecast.atRiskRevenue), "Recorded value of high-risk active deals"], ["Expected Commission", "Unavailable", unavailable], ["Released Commission", "Unavailable", unavailable], ["Pending Commission", "Unavailable", unavailable], ["Outstanding Payments", "Unavailable", unavailable], ["Outstanding Receivables", "Unavailable", unavailable], ["Upcoming Closings", upcomingClosings.length, "Deals with recorded probability of at least 70%"], ["Financial Risks", riskItems.length, "Active deals with medium or high recorded risk"], ["Cash Flow Indicators", "Unavailable", unavailable], ["Approval Backlog", approvalBacklog, "Pending workforce and collaboration approvals"],
    ].map(([label, value, evidence]) => <article className={card} key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {evidence}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card} aria-labelledby="commission-analytics"><h3 id="commission-analytics" className="font-semibold">Commission Analytics</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{["Commission earned", "Commission pending", "Commission delayed", "Commission released", "Commission at risk"].map((label) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 text-xs text-vds-muted">Unavailable</dd></div>)}</dl><p className="mt-4 text-xs text-vds-muted">Evidence: no commission ledger projection. Confidence: unknown. Dependencies: transaction-linked commission records and release status.</p></section>
      <section className={card} aria-labelledby="revenue-forecast"><h3 id="revenue-forecast" className="font-semibold">Revenue Forecast</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Monthly Forecast", money(sales.forecast.expectedMonthlyRevenue)], ["Quarterly Forecast", "Unavailable"], ["Revenue At Risk", money(sales.forecast.atRiskRevenue)], ["Expected Closings", sales.forecast.likelyClosedDeals], ["High Confidence Closings", highConfidence.length], ["Low Confidence Closings", lowConfidence.length], ["Pipeline Value", money(sales.deals.reduce((sum, deal) => sum + deal.value, 0))]].map(([label, value]) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl><p className="mt-4 text-xs text-vds-muted">Projection explanation: {sales.forecast.explanation}</p></section></div>
    <div className="grid gap-5 xl:grid-cols-3"><section className={card}><h3 className="font-semibold">Payment Intelligence</h3><ul className="mt-4 space-y-2 text-sm">{["Pending Buyer Payments", "Pending Seller Payments", "Brokerage", "Registration Fees", "Outstanding Balances", "Delayed Payments", "Deposit Status"].map((label) => <li key={label}>{label}: {unavailable}</li>)}</ul></section><section className={card}><h3 className="font-semibold">Profitability</h3><ul className="mt-4 space-y-2 text-sm">{["Most Profitable Listings", "Highest Commission Transactions", "Highest Revenue Agents", "Revenue Per Agent", "Revenue Per Property", "Revenue Trends"].map((label) => <li key={label}>{label}: {unavailable}</li>)}</ul></section><section className={card}><h3 className="font-semibold">Financial Executive Summary</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-vds-muted">Today&apos;s Summary</dt><dd>{sales.forecast.explanation}</dd></div><div><dt className="text-vds-muted">Week Summary</dt><dd>Unavailable — periodized revenue evidence missing</dd></div><div><dt className="text-vds-muted">Month Summary</dt><dd>{money(sales.forecast.expectedMonthlyRevenue)} weighted forecast</dd></div><div><dt className="text-vds-muted">Biggest Opportunities</dt><dd>{highConfidence.length} high-confidence closings</dd></div><div><dt className="text-vds-muted">Biggest Risks</dt><dd>{money(sales.forecast.atRiskRevenue)} recorded at-risk value</dd></div></dl></section></div>
    <section className={card} aria-labelledby="financial-risks"><h3 id="financial-risks" className="font-semibold">Financial Risks &amp; Next Best Actions</h3><p className="mt-2 text-sm text-vds-muted">Delayed payments, outstanding documents, commission risks, revenue delays, registration delays, and approval bottlenecks are shown only when supported.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{riskItems.map((deal) => <article className="rounded-xl bg-vds-elevated p-4" key={deal.id}><h4 className="font-medium">{deal.title}</h4><p className="mt-2 text-xs text-vds-muted"><strong>Evidence:</strong> {deal.daysInStage} days in {deal.stage} · {deal.probability}% close probability · {deal.missingActivities.join(", ") || "No missing activity recorded"}</p><p className="mt-2 text-xs text-vds-muted"><strong>Confidence:</strong> {deal.missingActivities.length ? "Medium" : "High"}</p><p className="mt-2 text-xs text-vds-muted"><strong>Expected Outcome:</strong> Verified financial readiness and an accountable next commitment.</p><Link className="mt-3 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href={approvalHref("verify_transaction")}>Prepare Verify Transaction</Link></article>)}{!riskItems.length && <p className="text-sm text-vds-muted">No financial risk is supported by current deal evidence.</p>}</div><div className="mt-4 flex flex-wrap gap-2">{[["follow_up_payment", "Follow-up Payment"], ["review_commission", "Review Commission"], ["prepare_settlement", "Prepare Settlement"], ["verify_transaction", "Verify Transaction"], ["approve_financial_request", "Approve Financial Request"], ["collect_outstanding_documents", "Collect Outstanding Documents"]].map(([intent, label]) => <Link className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(intent)} key={intent}>{label}</Link>)}</div><p className="mt-4 text-xs text-vds-muted">{financeTasks.length} recorded finance-relevant workforce tasks provide additional review context.</p></section>
  </section>;
}
