import Link from "next/link";
import type { WorkforceActivity, WorkforceEmployee, WorkforceTask } from "../domain/models";

const card = "rounded-3xl border border-vds-border bg-vds-surface/90 p-5 backdrop-blur sm:p-6";

export default function EmployeeHeadquartersSecondary({ item, tasks, activity }: { readonly item: WorkforceEmployee; readonly tasks: readonly WorkforceTask[]; readonly activity: readonly WorkforceActivity[] }) {
  const active = tasks.filter((task) => task.status === "pending" || task.status === "running");
  const capacity = active.length > 7 ? "Busy" : active.length > 3 ? "Normal" : "Light";
  const completed = tasks.filter((task) => task.status === "completed");
  const pipeline = pipelineFor(item.code);
  return <div className="space-y-6">
    <section className={card} aria-labelledby="workload-title"><div className="flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-vds-primary">Workload</p><h2 id="workload-title" className="mt-2 text-xl font-semibold">Capacity · {capacity}</h2></div><span className="text-sm text-vds-muted">{active.length} active</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-vds-elevated"><span className="block h-full rounded-full bg-vds-primary transition-[width] motion-reduce:transition-none" style={{width:`${Math.min(100, active.length * 12)}%`}}/></div><dl className="mt-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Assigned Leads", item.memory.assignedCustomers],["Properties", item.code === "crm-ai" ? item.memory.knowledgeReferences : 0],["Meetings", tasks.filter((task) => task.type === "Meeting Scheduling").length],["Tasks", active.length],["Campaigns", tasks.filter((task) => task.type === "Campaign Suggestion").length],["Documents", tasks.filter((task) => task.type === "Document Review").length]].map(([label,value])=><div className="rounded-2xl bg-vds-elevated p-3" key={label}><dt className="text-xs text-vds-muted">{label}</dt><dd className="mt-2 text-lg font-semibold">{value}</dd></div>)}</dl></section>
    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className={card} aria-labelledby="pipeline-title"><p className="text-xs uppercase tracking-[.18em] text-vds-primary">Role workspace</p><h2 id="pipeline-title" className="mt-2 text-xl font-semibold">{pipeline.title}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{pipeline.items.map((label)=><div className="rounded-2xl bg-vds-elevated p-4" key={label}><p className="text-sm font-medium">{label}</p><p className="mt-2 text-xs text-vds-muted">{taskEvidence(tasks,label) ? "Verified activity available" : "Awaiting first activity."}</p></div>)}</div></section><section className={card} aria-labelledby="insights-title"><p className="text-xs uppercase tracking-[.18em] text-vds-primary">Insights</p><h2 id="insights-title" className="mt-2 text-xl font-semibold">Evidence-backed planning</h2>{activity.length?<ul className="mt-5 space-y-3">{activity.slice(0,3).map((event)=><li className="rounded-2xl bg-vds-elevated p-4 text-sm" key={event.id}>{event.title}: <span className="text-vds-muted">{event.detail}</span></li>)}</ul>:<p className="mt-5 rounded-2xl border border-dashed border-vds-border p-5 text-sm text-vds-muted">Awaiting verified activity before preparing insights.</p>}</section></div>
    <section className={card} aria-labelledby="command-title"><p className="text-xs uppercase tracking-[.18em] text-vds-primary">Command Center</p><h2 id="command-title" className="mt-2 text-xl font-semibold">Work with {item.name}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[[`Talk to ${item.name}`,"#employee-conversation-title"],["Assign Work","/vayon/ai/tasks"],["Review Recommendations","/vayon/approvals"],["Open Calendar","/vayon/calendar"],["Open CRM","/vayon/crm"],["View Performance","#employee-performance"]].map(([label,href])=><Link className="focus-ring rounded-2xl border border-vds-border bg-vds-elevated p-4 text-sm font-medium transition hover:-translate-y-0.5 hover:border-vds-accent-border motion-reduce:transform-none" href={href} key={label}>{label}</Link>)}</div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section id="employee-performance" className={card}><p className="text-xs uppercase tracking-[.18em] text-vds-primary">Performance</p><h2 className="mt-2 text-xl font-semibold">Weekly and Monthly Overview</h2>{completed.length?<p className="mt-5 text-sm text-vds-muted">{completed.length} evidence-backed tasks completed. Additional outcomes appear only when recorded.</p>:<p className="mt-5 text-sm text-vds-muted">Awaiting first activity.</p>}</section><section className={card}><p className="text-xs uppercase tracking-[.18em] text-vds-primary">Team Collaboration</p><h2 className="mt-2 text-xl font-semibold">Recommendations between teammates</h2><p className="mt-5 text-sm text-vds-muted">Collaboration recommendations appear when verified employee activity requests another specialist. No work is executed automatically.</p></section></div>
  </div>;
}

function pipelineFor(code:string) { if(code==="sales-ai") return {title:"Sales Pipeline",items:["Current Deals","Hot Leads","Follow-ups","Appointments","Risk Deals"]}; if(code==="crm-ai") return {title:"Property Pipeline",items:["Matching Queue","Properties Reviewed","Buyer Requests","Availability"]}; if(code==="marketing-ai") return {title:"Marketing Pipeline",items:["Campaigns","Content Queue","Creative Requests","Publishing Schedule"]}; if(code==="operations-ai") return {title:"Operations Pipeline",items:["Tasks","Documents","Automation","Calendar"]}; return {title:"Customer Success Pipeline",items:["Open Conversations","Reviews","Retention","Tickets"]}; }
function taskEvidence(tasks:readonly WorkforceTask[],label:string){const words=label.toLowerCase().split(/\s+/);return tasks.some((task)=>words.some((word)=>word.length>4&&`${task.type} ${task.title}`.toLowerCase().includes(word)));}
