"use client";

import Link from "next/link";
import { useState } from "react";
import type { CollaborationDashboard, RecommendationNode } from "@/features/platform/ai-collaboration";
import type { WorkforceActivity, WorkforceEmployee, WorkforceTask } from "../domain/models";

const card = "rounded-3xl border border-vds-border bg-vds-surface/85 p-5 shadow-xl shadow-vds-shadow/10 backdrop-blur sm:p-6";
const profiles: Record<string, { focus: string; impact: string; goals: readonly string[]; related: string; collaborator: string }> = {
  "sales-ai": { focus: "Following up with high-value buyers", impact: "Revenue Opportunity", goals: ["Complete lead follow-ups", "Schedule buyer appointments", "Progress qualified opportunities"], related: "/vayon/crm", collaborator: "Emma · buyer and property matching" },
  "crm-ai": { focus: "Preparing verified property matches", impact: "Pipeline Health", goals: ["Review buyer requirements", "Prepare property comparisons", "Check listing availability"], related: "/vayon/properties", collaborator: "Sarah · qualified buyer context" },
  "marketing-ai": { focus: "Preparing listing marketing", impact: "Marketing Growth", goals: ["Review active campaigns", "Prepare creative briefs", "Identify content opportunities"], related: "/vayon/marketing", collaborator: "David · campaign schedule coordination" },
  "operations-ai": { focus: "Organizing the upcoming schedule", impact: "Operational Efficiency", goals: ["Review scheduling conflicts", "Prepare operational approvals", "Review calendar commitments"], related: "/vayon/calendar", collaborator: "Olivia · customer meeting coordination" },
  "whatsapp-ai": { focus: "Improving customer engagement", impact: "Customer Satisfaction", goals: ["Review inactive customers", "Prepare customer follow-ups", "Review customer health"], related: "/vayon/communications", collaborator: "David · support scheduling context" },
};

export default function EmployeeDailyWorkspace({ item, tasks, activity, collaboration }: { readonly item: WorkforceEmployee; readonly tasks: readonly WorkforceTask[]; readonly activity: readonly WorkforceActivity[]; readonly collaboration: CollaborationDashboard }) {
  const [query, setQuery] = useState("");
  const profile = profiles[item.code] ?? { focus: "Reviewing verified workspace activity", impact: "Business Health", goals: ["Review current work", "Prepare recommendations", "Organize upcoming priorities"], related: "/vayon", collaborator: "AI Team · shared business context" };
  const recommendations = collaboration.recommendationPipeline.filter((entry) => entry.employee === item.code);
  const active = tasks.filter((task) => task.status === "pending" || task.status === "running");
  const completed = tasks.filter((task) => task.status === "completed");
  const blocked = tasks.filter((task) => task.status === "failed");
  const waiting = tasks.filter((task) => task.approvalState === "pending").length + recommendations.filter((entry) => entry.approvalStatus === "pending").length;
  const score = tasks.length ? Math.round((completed.length / tasks.length) * 100) : 0;
  const filtered = (() => {
    const term = query.trim().toLowerCase();
    if (!term) return { tasks, activity, recommendations };
    return {
      tasks: tasks.filter((entry) => `${entry.title} ${entry.type}`.toLowerCase().includes(term)),
      activity: activity.filter((entry) => `${entry.title} ${entry.detail}`.toLowerCase().includes(term)),
      recommendations: recommendations.filter((entry) => entry.requestedRecommendation.toLowerCase().includes(term)),
    };
  })();
  const evidenceCount = tasks.length + activity.length + recommendations.length;

  return <div className="space-y-6">
    <section className="overflow-hidden rounded-[2rem] border border-vds-accent-border bg-gradient-to-br from-vds-primary-soft/70 via-vds-surface to-vds-elevated p-6 shadow-2xl shadow-vds-shadow/10 sm:p-8" aria-labelledby="daily-workspace-title">
      <p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">{item.name}&apos;s Daily Workspace</p>
      <h1 id="daily-workspace-title" className="mt-3 text-3xl font-semibold sm:text-4xl">Good morning. Here&apos;s today&apos;s work.</h1>
      <p className="mt-3 max-w-3xl text-sm leading-6 text-vds-muted">{evidenceCount ? `${item.name} is organizing ${evidenceCount} verified workspace signal${evidenceCount === 1 ? "" : "s"}.` : `${item.name} is ready to prepare evidence-backed work as your workspace grows.`} Every action remains a recommendation until you approve it.</p>
      <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Current Focus" value={evidenceCount ? profile.focus : "Waiting for workspace activity"}/><Metric label="Today's Progress" value={tasks.length ? `${completed.length} of ${tasks.length} recorded items` : "No work recorded"}/><Metric label="Business Health" value={item.health === "healthy" ? "Ready" : "Needs Attention"}/><Metric label="Waiting Approval" value={`${waiting}`}/></div>
    </section>

    {!evidenceCount ? <section className={`${card} text-center`} aria-labelledby="employee-empty-title"><h2 id="employee-empty-title" className="text-xl font-semibold">I&apos;m ready to begin working.</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-vds-muted">As your workspace grows I&apos;ll continuously prepare recommendations and organize today&apos;s work.</p><div className="mt-5 flex flex-wrap justify-center gap-2"><Link className="focus-ring rounded-xl bg-vds-primary px-4 py-2 text-sm font-medium text-vds-background" href="/vayon/crm?import=1">Import Data</Link><Link className="focus-ring rounded-xl border border-vds-border px-4 py-2 text-sm font-medium" href="/demo">Explore Demo Workspace</Link></div></section> : null}

    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <section className={card} aria-labelledby="daily-score-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Daily Score</p><h2 id="daily-score-title" className="mt-2 text-xl font-semibold">Today&apos;s Goal</h2><div className="mt-6 flex items-center gap-6"><div className="grid size-28 shrink-0 place-items-center rounded-full border-[10px] border-vds-primary-soft text-2xl font-semibold" role="img" aria-label={`${score}% of recorded work completed`}>{score}%</div><dl className="space-y-2 text-sm"><Row label="Completed" value={`${completed.length}`}/><Row label="Remaining" value={`${active.length}`}/><Row label="Confidence" value={recommendationConfidence(recommendations)}/><Row label="Business Impact" value={evidenceCount ? profile.impact : "Not available"}/></dl></div><p className="mt-5 text-xs text-vds-muted">Calculated only from recorded tasks and recommendations.</p></section>
      <section className={card} aria-labelledby="goals-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Today&apos;s Goals</p><h2 id="goals-title" className="mt-2 text-xl font-semibold">Priorities grounded in available work</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{profile.goals.map((goal, index) => <article className="rounded-2xl bg-vds-elevated p-4" key={goal}><p className="text-sm font-medium">{goal}</p><p className="mt-2 text-xs text-vds-muted">{tasks[index] ? `Evidence: ${tasks[index].title}` : "Awaiting supporting workspace evidence"}</p></article>)}</div></section>
    </div>

    <section className={card} aria-labelledby="workload-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Workload</p><h2 id="workload-title" className="mt-2 text-xl font-semibold">Today&apos;s Work</h2></div><span className="text-xs text-vds-muted">Capacity · {active.length > 7 ? "High" : active.length > 3 ? "Balanced" : "Available"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["High Priority", tasks.filter(x => x.priority === "urgent" || x.priority === "high").length],["Medium Priority",tasks.filter(x => x.priority === "normal").length],["Low Priority",tasks.filter(x => x.priority === "low").length],["Completed Today",completed.length],["Waiting Approval",waiting],["Blocked",blocked.length]].map(([label, value]) => <Metric key={label} label={String(label)} value={String(value)}/>)}</div></section>

    <section className={card} aria-labelledby="recommendations-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Today&apos;s Recommendations</p><h2 id="recommendations-title" className="mt-2 text-xl font-semibold">Prepared for your approval</h2></div><Link className="text-sm text-vds-primary" href="/vayon/approvals">View recommendation queue</Link></div>{recommendations.length ? <div className="mt-5 grid gap-4 xl:grid-cols-2">{recommendations.slice(0, 4).map(entry => <Recommendation item={entry} related={profile.related} key={entry.id}/>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-vds-border p-5 text-sm text-vds-muted">No evidence-backed recommendations are waiting. New recommendations appear after verified workspace activity.</p>}</section>

    <div className="grid gap-6 xl:grid-cols-2"><section className={card} aria-labelledby="schedule-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Upcoming Schedule</p><h2 id="schedule-title" className="mt-2 text-xl font-semibold">Meetings, deadlines and follow-ups</h2>{active.some(x => x.deadline || x.type === "Meeting Scheduling") ? <ul className="mt-5 space-y-3">{active.filter(x => x.deadline || x.type === "Meeting Scheduling").slice(0,5).map(x => <li className="rounded-2xl bg-vds-elevated p-4 text-sm" key={x.id}>{x.title}<span className="mt-1 block text-xs text-vds-muted">{x.deadline ? new Date(x.deadline).toLocaleString() : "Scheduling recommendation awaiting approval"}</span></li>)}</ul> : <p className="mt-5 text-sm text-vds-muted">No verified meetings, deadlines or follow-ups are scheduled.</p>}<Link className="mt-5 inline-block text-sm text-vds-primary" href="/vayon/calendar">Open Calendar</Link></section><section className={card} aria-labelledby="achievements-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Recent Achievements</p><h2 id="achievements-title" className="mt-2 text-xl font-semibold">Verified completed work</h2>{completed.length ? <ul className="mt-5 space-y-3">{completed.slice(0,5).map(x => <li className="rounded-2xl bg-vds-elevated p-4 text-sm" key={x.id}>{x.title}<span className="mt-1 block text-xs text-vds-muted">{x.completedAt ? new Date(x.completedAt).toLocaleString() : "Recorded as completed"}</span></li>)}</ul> : <p className="mt-5 text-sm text-vds-muted">Achievements appear only after work is recorded as completed.</p>}</section></div>

    <section className={card} aria-labelledby="activity-title"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Recent Activity</p><h2 id="activity-title" className="mt-2 text-xl font-semibold">Evidence timeline</h2></div><label><span className="sr-only">Search customers, properties, recommendations, tasks and meetings</span><input className="h-10 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm sm:w-80" placeholder="Search today's workspace" value={query} onChange={event => setQuery(event.target.value)}/></label></div><div className="mt-5 grid gap-3">{filtered.activity.slice(0,6).map(x => <article className="border-l-2 border-vds-primary pl-4" key={x.id}><p className="text-sm font-medium">{x.title}</p><p className="mt-1 text-xs text-vds-muted">{x.detail} · {new Date(x.occurredAt).toLocaleString()}</p></article>)}{!filtered.activity.length ? <p className="text-sm text-vds-muted">No matching verified activity.</p> : null}</div><details className="mt-5 rounded-2xl border border-vds-border p-4 [content-visibility:auto]"><summary className="cursor-pointer font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-vds-focus">History</summary><p className="mt-3 text-sm text-vds-muted">{filtered.tasks.length} matching tasks · {filtered.recommendations.length} matching recommendations · {filtered.activity.length} matching activity events.</p></details></section>

    <div className="grid gap-6 xl:grid-cols-2"><section className={card} aria-labelledby="collaboration-daily-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Team Collaboration</p><h2 id="collaboration-daily-title" className="mt-2 text-xl font-semibold">Working with {profile.collaborator}</h2><p className="mt-4 text-sm text-vds-muted">Reason: shared verified workspace context can improve the recommendation. Evidence: {collaboration.timeline.find(event => event.agent === item.code)?.summary ?? "No collaboration event recorded today."}</p><p className="mt-3 text-xs text-vds-muted">Recommendation only · no autonomous handoff or execution.</p></section><KnowledgePanel item={item} tasks={tasks} activity={activity}/></div>

    <section className={card} aria-labelledby="commands-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Employee Commands</p><h2 id="commands-title" className="mt-2 text-xl font-semibold">Work with {item.name}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Review Work","#workload-title"],["View Recommendations","#recommendations-title"],["Today's Queue","/vayon/ai/tasks"],["Related Customers","/vayon/crm"],["Related Properties","/vayon/properties"],["Calendar","/vayon/calendar"],["Activity","#activity-title"],["History","#activity-title"]].map(([label, href]) => <Link className="focus-ring rounded-2xl border border-vds-border bg-vds-elevated p-4 text-sm font-medium transition hover:border-vds-accent-border motion-reduce:transition-none" href={href} key={label}>{label}</Link>)}</div><p className="mt-5 text-xs text-vds-muted">Commands open evidence and approval surfaces. Nothing executes automatically.</p></section>
  </div>;
}

function KnowledgePanel({item,tasks,activity}:{item:WorkforceEmployee;tasks:readonly WorkforceTask[];activity:readonly WorkforceActivity[]}) { const values = [["Customers Known",item.memory.assignedCustomers],["Properties Known",item.code === "crm-ai" ? item.memory.knowledgeReferences : 0],["Campaigns",tasks.filter(x=>x.type === "Campaign Suggestion").length],["Tasks",tasks.length],["Calendar",tasks.filter(x=>x.type === "Meeting Scheduling").length],["Communications",item.memory.conversationCount],["Documents",tasks.filter(x=>x.type === "Document Review").length]] as const; const coverage = values.reduce((sum,[,value])=>sum+Number(value),0); return <section className={card} aria-labelledby="knowledge-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-vds-primary">Knowledge Panel</p><h2 id="knowledge-title" className="mt-2 text-xl font-semibold">Knowledge Coverage · {coverage > 20 ? "Expert" : coverage > 0 ? "Learning" : "Ready"}</h2><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{values.map(([label,value])=><Row label={label} value={`${value}`} key={label}/>)}</dl><p className="mt-4 text-xs text-vds-muted">{activity.length} verified activity event{activity.length===1?"":"s"} available for context.</p></section> }
function Recommendation({item,related}:{item:RecommendationNode;related:string}) { const confidence=item.confidence===null?"Not available":`${Math.round(item.confidence*100)}%`; const approval=`/vayon/approvals?recommendation=${encodeURIComponent(item.id)}`; return <article className="rounded-2xl border border-vds-border bg-vds-elevated p-5"><div className="flex flex-wrap justify-between gap-2"><span className="text-xs font-semibold uppercase tracking-[.14em] text-vds-primary">{item.approvalStatus === "pending" ? "High Priority" : "Reviewed"}</span><span className="text-xs capitalize text-vds-muted">{item.approvalStatus}</span></div><h3 className="mt-3 font-medium">{item.requestedRecommendation}</h3><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2"><Row label="Confidence" value={confidence}/><Row label="Business Impact" value="Evidence dependent"/><Row label="Reason" value="Workspace projection"/><Row label="Approval" value="Required"/></dl><p className="mt-4 text-xs text-vds-muted">Evidence: workspace-scoped recommendation record. Recommended action: review before approval.</p><div className="mt-4 flex flex-wrap gap-3 text-xs"><Link className="text-vds-primary" href={`${approval}&decision=approve`}>Approve</Link><Link className="text-vds-primary" href={`${approval}&decision=modify`}>Modify</Link><Link className="text-vds-primary" href={`${approval}&decision=reject`}>Reject</Link><Link className="text-vds-primary" href={`${related}?recommendation=${encodeURIComponent(item.id)}`}>View Related Record</Link><Link className="text-vds-primary" href={`${approval}&explain=1`}>Explain</Link></div></article> }
function recommendationConfidence(items: readonly RecommendationNode[]) { const values=items.flatMap(item=>item.confidence===null?[]:[item.confidence]); return values.length ? `${Math.round(values.reduce((a,b)=>a+b,0)/values.length*100)}%` : "Not available"; }
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-2xl border border-vds-border bg-vds-surface/70 p-4"><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 font-semibold">{value}</p></div> }
function Row({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4 rounded-xl bg-vds-elevated/70 p-3"><dt className="text-vds-muted">{label}</dt><dd className="font-medium">{value}</dd></div> }
