import Link from "next/link";
import type { CRMAIDashboard } from "@/features/platform/crm-ai/types";
import type { WhatsAppAIDashboard } from "@/features/platform/whatsapp-ai/types";
import type { RecommendationNode } from "@/features/platform/ai-collaboration";
import type { WorkforceTask } from "../domain/models";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";
const unavailable = "Unavailable — supporting customer-success evidence is not connected";
const approvalHref = (intent: string) => `/vayon/approvals?intent=${intent}&source=olivia-customer-success-manager`;

export function OliviaCustomerSuccessManagerDashboard({ crm, whatsapp, tasks, recommendations }: { readonly crm: CRMAIDashboard; readonly whatsapp: WhatsAppAIDashboard; readonly tasks: readonly WorkforceTask[]; readonly recommendations: readonly RecommendationNode[] }) {
  const needsAttention = crm.customers.filter((customer) => customer.segment === "at-risk" || customer.healthScore < 50);
  const healthy = crm.customers.filter((customer) => customer.healthScore >= 75 && customer.segment !== "at-risk");
  const unknown = crm.customers.filter((customer) => !customer.lastContact && customer.lifetimeActivity === 0);
  const referralOpportunities = healthy.filter((customer) => customer.lifetimeActivity > 0);
  const followUps = whatsapp.conversations.filter((conversation) => conversation.health === "no-response" || conversation.health === "cold" || conversation.unansweredQuestions.length > 0);
  const approvalBacklog = recommendations.filter((item) => item.approvalStatus === "pending").length + tasks.filter((task) => task.approvalState === "pending").length;
  const messageDrafts = ["Welcome Message", "Thank You Message", "Registration Congratulations", "Anniversary Message", "Referral Request", "Review Request", "Property Maintenance Reminder"];
  const actions = [["schedule_follow_up", "Schedule Follow-up"], ["request_review", "Request Review"], ["request_referral", "Request Referral"], ["prepare_congratulations_message", "Prepare Congratulations Message"], ["book_customer_meeting", "Book Customer Meeting"], ["assign_relationship_manager", "Assign Relationship Manager"]] as const;

  return <section className="space-y-5" aria-labelledby="olivia-success-title">
    <header className={card}><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Olivia · AI Customer Success Manager</p><h2 id="olivia-success-title" className="mt-2 text-2xl font-semibold">Today&apos;s Customer Success Brief</h2><p className="mt-2 text-sm text-vds-muted">Evidence-backed relationship recommendations only. Olivia never sends messages, schedules meetings, or assigns owners without approval.</p></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Upcoming Follow-ups", followUps.length, "Recorded no-response, cold, or unanswered conversation evidence"], ["Pending Customer Check-ins", whatsapp.pendingFollowUps, "Existing WhatsApp follow-up projection"], ["Closed Transactions Requiring Follow-up", "Unavailable", unavailable], ["Referral Opportunities", referralOpportunities.length, "Customers with high recorded relationship health and prior activity; not a satisfaction claim"], ["Customer Satisfaction Indicators", "Unknown", "No satisfaction or survey repository is connected"], ["Renewal Opportunities", "Unavailable", unavailable], ["Customer Success Risks", needsAttention.length, "CRM at-risk segment or recorded health below 50"], ["Pending Approvals", approvalBacklog, "Workforce and collaboration approval records"],
    ].map(([label, value, evidence]) => <article className={card} key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {evidence}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card} aria-labelledby="post-sale-journey"><h3 id="post-sale-journey" className="font-semibold">Post-Sale Journey</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{["Recently Closed Deals", "Upcoming Handover", "Registration Completed", "Customer Welcome", "After-Sales Follow-up", "Warranty Reminders", "Property Support"].map((label) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 text-xs text-vds-muted">{label === "After-Sales Follow-up" ? `${followUps.length} conversation follow-ups supported` : "Unavailable"}</dd></div>)}</dl><p className="mt-4 text-xs text-vds-muted"><strong>Next Step:</strong> connect transaction and handover evidence. <strong>Expected Outcome:</strong> a verified post-sale commitment.</p></section>
      <section className={card} aria-labelledby="referral-intelligence"><h3 id="referral-intelligence" className="font-semibold">Referral Intelligence</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-vds-elevated p-3"><dt>High Referral Potential</dt><dd className="mt-1">{referralOpportunities.length} evidence-qualified relationships</dd></div>{["Satisfied Clients", "Past Referrals", "Referral Requests Pending", "Referral Follow-up"].map((label) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 text-xs text-vds-muted">Unavailable</dd></div>)}</dl><Link className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href={approvalHref("prepare_referral_request")}>Prepare Referral Request Draft</Link></section></div>
    <section className={card} aria-labelledby="customer-health"><h3 id="customer-health" className="font-semibold">Customer Health</h3><p className="mt-2 text-sm text-vds-muted">Health uses recorded CRM activity and relationship evidence; it does not represent customer satisfaction.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Healthy", healthy.length], ["Needs Attention", needsAttention.length], ["At Risk", crm.customers.filter((customer) => customer.segment === "at-risk").length], ["Unknown", unknown.length]].map(([label, value]) => <div className="rounded-xl bg-vds-elevated p-4" key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div><div className="mt-4 space-y-3">{needsAttention.slice(0, 6).map((customer) => <article className="rounded-xl bg-vds-elevated p-4" key={customer.id}><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{customer.name}</h4><span className="text-xs uppercase">{customer.segment} · {customer.healthScore}/100</span></div><p className="mt-2 text-xs text-vds-muted">Evidence: {customer.summary} · {customer.timelineSummary}</p></article>)}</div></section>
    <section className={card} aria-labelledby="follow-up-assistant"><h3 id="follow-up-assistant" className="font-semibold">Follow-up Assistant</h3><p className="mt-2 text-sm text-vds-muted">Drafts are prepared for review only. Nothing is sent automatically.</p><div className="mt-4 flex flex-wrap gap-2">{messageDrafts.map((label) => <Link className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(`prepare_${label.toLowerCase().replaceAll(/[^a-z0-9]+/g, "_")}`)} key={label}>Prepare {label}</Link>)}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card}><h3 className="font-semibold">Retention Opportunities</h3><ul className="mt-4 grid grid-cols-2 gap-2 text-sm">{["Investment Opportunities", "Upgrade Opportunities", "Rental Opportunities", "Repeat Purchase Opportunities", "Family Referrals", "Corporate Referrals"].map((label) => <li className="rounded-xl bg-vds-elevated p-3" key={label}>{label}: {unavailable}</li>)}</ul></section><section className={card}><h3 className="font-semibold">Customer Success Summary</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-vds-muted">Today&apos;s Summary</dt><dd>{followUps.length} supported follow-ups · {needsAttention.length} relationships need attention</dd></div><div><dt className="text-vds-muted">Weekly Summary</dt><dd>{unavailable}</dd></div><div><dt className="text-vds-muted">Monthly Summary</dt><dd>{unavailable}</dd></div><div><dt className="text-vds-muted">Key Opportunities</dt><dd>{referralOpportunities.length} evidence-qualified relationships for human review</dd></div><div><dt className="text-vds-muted">Key Risks</dt><dd>{needsAttention.length} CRM relationships need attention</dd></div></dl></section></div>
    <section className={card} aria-labelledby="customer-next-actions"><h3 id="customer-next-actions" className="font-semibold">Next Best Actions</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{followUps.slice(0, 6).map((conversation) => <article className="rounded-xl bg-vds-elevated p-4" key={conversation.id}><h4 className="font-medium">{conversation.customerName ?? conversation.subject}</h4><p className="mt-2 text-xs text-vds-muted"><strong>Evidence:</strong> {conversation.reasoning} · {conversation.unansweredQuestions.length} unanswered questions</p><p className="mt-2 text-xs text-vds-muted"><strong>Confidence:</strong> {Math.round(conversation.confidence * 100)}%</p><p className="mt-2 text-xs text-vds-muted"><strong>Expected Outcome:</strong> A reviewed relationship commitment and documented next step.</p><Link className="mt-3 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href={approvalHref("schedule_follow_up")}>Prepare Schedule Follow-up</Link></article>)}</div><div className="mt-4 flex flex-wrap gap-2">{actions.map(([intent, label]) => <Link className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(intent)} key={intent}>{label}</Link>)}</div></section>
  </section>;
}
