import { ArrowLeft, Check, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";
import { BrandLogo } from "@/components/brand";
import { Input } from "@/components/ui/Input";
import { Button, Toast } from "@/features/platform/design-system";
import { PasswordField } from "./PasswordField";

export function AuthShell({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <main className="grid min-h-dvh bg-vds-background text-vds-foreground lg:grid-cols-2"><section className="relative hidden overflow-hidden border-r border-vds-border bg-vds-surface p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 bg-vds-primary-soft opacity-40"/><Link href="/" aria-label="Vayon home" className="vds-focus relative inline-flex w-fit rounded-xl"><BrandLogo size="md" priority/></Link><div className="relative max-w-xl"><div className="inline-flex items-center gap-2 rounded-full border border-vds-accent-border bg-vds-primary-soft px-3 py-1.5 text-xs font-semibold text-vds-primary"><Sparkles className="size-3.5" aria-hidden="true"/>Vayon OS</div><h2 className="mt-6 text-5xl font-semibold leading-[1.02] tracking-[-.055em]">Your business.<br/>One intelligent system.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-vds-muted">Give every team connected AI employees, customer context, workflows, and enterprise governance.</p><ul className="mt-8 space-y-4">{["Workspace and tenant isolation", "Recommendation-only AI governance", "Complete audit and approval trails"].map(item => <li className="flex items-center gap-3 text-sm text-vds-secondary" key={item}><span className="grid size-6 place-items-center rounded-full bg-vds-primary text-vds-on-accent"><Check className="size-3.5" aria-hidden="true"/></span>{item}</li>)}</ul></div><p className="relative flex items-center gap-2 text-xs text-vds-subtle"><ShieldCheck className="size-4" aria-hidden="true"/>Enterprise security by design</p></section><section className="flex min-h-dvh items-center justify-center px-5 py-12 sm:px-10"><div className="w-full max-w-md"><Link href="/" className="vds-focus mb-10 inline-flex items-center gap-2 rounded-lg text-sm text-vds-muted lg:hidden"><ArrowLeft className="size-4" aria-hidden="true"/>Back to Vayon</Link><div className="lg:hidden"><BrandLogo size="md" priority/></div><h1 className="mt-8 text-4xl font-semibold tracking-[-.04em]">{title}</h1><p className="mt-3 text-sm leading-6 text-vds-muted">{description}</p><div className="mt-8 rounded-3xl border border-vds-border bg-vds-surface p-6 shadow-2xl sm:p-8">{children}</div><p className="mt-6 text-center text-xs text-vds-subtle">Protected by secure authentication and workspace isolation.</p></div></section></main>;
}
export function AuthFields({ kind }: { kind: "signup" | "login" | "forgot" | "reset" }) { return <div className="space-y-4">{kind === "signup" && <Input id="name" name="name" label="Full name" autoComplete="name" required/>}{kind !== "reset" && <Input id="email" name="email" type="email" label="Email address" autoComplete="email" required/>}{kind === "login" && <Input id="password" name="password" type="password" label="Password" autoComplete="current-password" required/>}{kind === "signup" && <PasswordField/>}{kind === "reset" && <PasswordField label="New password"/>}{kind === "reset" && <Input id="confirmPassword" name="confirmPassword" type="password" label="Confirm password" autoComplete="new-password" required minLength={8}/>}<Button type="submit" fullWidth>{kind === "signup" ? "Create account" : kind === "login" ? "Sign in" : kind === "forgot" ? "Send reset link" : "Update password"}</Button></div>; }
export function FormNotice({ error, success }: { error?: string; success?: string }) { if (!error && !success) return null; return <div className="mb-4 space-y-2">{error && <Toast title={error} tone="danger"/>}{success && <Toast title={success} tone="success"/>}</div>; }
