import {
  Activity,
  Archive,
  BarChart3,
  Bot,
  Brain,
  Building2,
  CalendarDays,
  CalendarRange,
  CircleDollarSign,
  Code2,
  ContactRound,
  FileSearch,
  FileCode2,
  FileText,
  Palette,
  Gauge,
  Handshake,
  Home,
  Inbox,
  Landmark,
  LineChart,
  LibraryBig,
  Megaphone,
  MessageCircleMore,
  Newspaper,
  Network,
  RadioTower,
  ShieldCheck,
  Settings,
  Share2,
  Sparkles,
  SquareKanban,
  Target,
  Users,
  UsersRound,
  Workflow,
} from "lucide-react";
import type { ShellNavigationGroup } from "./types";

export const shellNavigation: readonly ShellNavigationGroup[] = [
  {
    id: "home",
    label: "Home",
    icon: Home,
    items: [
      {
        label: "Creative Studio",
        href: "/vayon/creative",
        icon: Palette,
        description: "Creative operating system",
      },
      {
        label: "Creative Cloud",
        href: "/vayon/creative/cloud",
        icon: Sparkles,
        description: "Creative operating model",
      },
      {
        label: "Creative Pipelines",
        href: "/vayon/creative/pipelines",
        icon: Workflow,
        description: "Production orchestration",
      },
      {
        label: "Customer Success",
        href: "/vayon/customer-success",
        icon: Sparkles,
        description: "Onboarding and adoption",
      },
      { label: "Dashboard", href: "/vayon/dashboard", icon: Gauge },
      { label: "Executive Home", href: "/vayon/home", icon: Home },
      { label: "Analytics", href: "/vayon/analytics", icon: BarChart3 },
    ],
  },
  {
    id: "crm",
    label: "CRM",
    icon: Building2,
    items: [
      { label: "Properties", href: "/vayon/properties", icon: Building2 },
      { label: "Leads", href: "/vayon/leads", icon: Target },
      { label: "Deals", href: "/vayon/deals", icon: Handshake },
      {
        label: "Contacts",
        href: "/vayon/crm/contacts",
        icon: ContactRound,
        description: "Customer directory",
      },
      {
        label: "Companies",
        href: "/vayon/crm/companies",
        icon: Landmark,
        description: "Account directory",
      },
    ],
  },
  {
    id: "operations",
    label: "Operations",
    icon: CalendarDays,
    items: [
      { label: "Calendar", href: "/vayon/calendar", icon: CalendarDays },
      { label: "Tasks", href: "/vayon/tasks", icon: SquareKanban },
      { label: "Timeline", href: "/vayon/timeline", icon: Activity },
      { label: "Workflows", href: "/vayon/workflows", icon: Workflow },
      { label: "Approvals", href: "/vayon/approvals", icon: ShieldCheck },
    ],
  },
  {
    id: "growth",
    label: "Growth Intelligence",
    icon: Megaphone,
    items: [
      { label: "Overview", href: "/vayon/growth", icon: Gauge },
      { label: "Campaigns", href: "/vayon/growth/campaigns", icon: Megaphone },
      { label: "Content Calendar", href: "/vayon/growth/content-calendar", icon: CalendarRange },
      { label: "Social Media", href: "/vayon/growth/social-media", icon: Share2 },
      { label: "Brand Assets", href: "/vayon/growth/brand-assets", icon: Archive },
      { label: "SEO", href: "/vayon/growth/seo", icon: FileSearch },
      { label: "PR", href: "/vayon/growth/pr", icon: Newspaper },
      { label: "Community", href: "/vayon/growth/community", icon: UsersRound },
      { label: "Influencers", href: "/vayon/growth/influencers", icon: Sparkles },
      { label: "Referrals", href: "/vayon/growth/referrals", icon: Handshake },
      { label: "Analytics", href: "/vayon/growth/analytics", icon: LineChart },
      { label: "Investor Relations", href: "/vayon/growth/investor-relations", icon: Landmark },
      { label: "Settings", href: "/vayon/growth/settings", icon: Settings },
      { label: "Marketing Studio", href: "/vayon/creative-studio", icon: Palette, description: "Licensed campaign creation" },
      { label: "Growth Studio", href: "/vayon/creative-studio/growth", icon: Sparkles, description: "Existing campaign packs" },
    ],
  },
  {
    id: "communications",
    label: "Communications",
    icon: MessageCircleMore,
    items: [
      { label: "Inbox", href: "/vayon/communications", icon: Inbox },
      { label: "Meetings", href: "/vayon/meetings", icon: Users },
    ],
  },
  {
    id: "ai",
    label: "AI Team",
    icon: Sparkles,
    items: [
      { label: "Orchestration Center", href: "/vayon/ai/collaboration", icon: Network, description: "AI executive boardroom" },
      { label: "Founder Approval Center", href: "/vayon/founder/approvals", icon: ShieldCheck, description: "Approval Center · Executive Decisions" },
      { label: "Workforce", href: "/vayon/workforce", icon: Bot },
      { label: "Sarah", href: "/vayon/ai/workforce/sales-ai", icon: Users, description: "Sales Manager" },
      { label: "Emma", href: "/vayon/ai/workforce/crm-ai", icon: Users, description: "Property Advisor" },
      { label: "Alex", href: "/vayon/ai/workforce/marketing-ai", icon: Users, description: "Marketing Director" },
      { label: "David", href: "/vayon/ai/workforce/operations-ai", icon: Users, description: "Operations Manager" },
      { label: "Olivia", href: "/vayon/ai/workforce/whatsapp-ai", icon: Users, description: "Customer Success" },
      {
        label: "VAYON Intelligence",
        href: "/vayon/intelligence",
        icon: Sparkles,
        description: "Success copilot",
      },
    ],
  },
  {
    id: "platform",
    label: "Platform",
    icon: Settings,
    items: [
      { label: "Launch Readiness", href: "/vayon/platform/launch-readiness", icon: Gauge, description: "Beta launch control center" },
      { label: "Team", href: "/vayon/team", icon: UsersRound },
      { label: "Administration", href: "/vayon/admin", icon: ShieldCheck },
      { label: "Knowledge", href: "/vayon/knowledge", icon: LibraryBig },
      {
        label: "Product Intelligence",
        href: "/vayon/settings/product-intelligence",
        icon: BarChart3,
      },
      { label: "Settings", href: "/vayon/settings/appearance", icon: Settings },
      {
        label: "Connected Apps",
        href: "/vayon/settings/integrations",
        icon: Network,
      },
      {
        label: "Billing",
        href: "/vayon/settings/billing",
        icon: CircleDollarSign,
      },
    ],
  },
  {
    id: "developer",
    label: "Developer",
    icon: Code2,
    developer: true,
    items: [
      { label: "Brain", href: "/vayon/brain", icon: Brain },
      { label: "Runtime", href: "/vayon/runtime", icon: RadioTower },
      { label: "Cognitive", href: "/vayon/cognitive", icon: Workflow },
      { label: "Context", href: "/vayon/context", icon: Network },
      { label: "Architecture", href: "/vayon/objects", icon: FileCode2 },
      { label: "Documents", href: "/vayon/storage", icon: FileText },
      { label: "System", href: "/vayon/system", icon: Gauge },
    ],
  },
];

export const breadcrumbGroups = new Map(
  shellNavigation.flatMap((group) =>
    group.items
      .filter((item) => item.href)
      .map((item) => [item.href!, group.label]),
  ),
);
