import {
  Activity,
  BarChart3,
  Bot,
  Building2,
  CalendarDays,
  ContactRound,
  FileSearch,
  Palette,
  Gauge,
  Handshake,
  Home,
  Landmark,
  LineChart,
  Megaphone,
  Network,
  ShieldCheck,
  Settings,
  Share2,
  Sparkles,
  SquareKanban,
  Target,
  Users,
  Workflow,
} from "lucide-react";
import type { ShellNavigationGroup } from "./types";

export const shellNavigation: readonly ShellNavigationGroup[] = [
  {
    id: "home",
    label: "Workspace",
    icon: Home,
    items: [
      { label: "Dashboard", href: "/vayon/dashboard", icon: Gauge },
    ],
  },
  {
    id: "crm",
    label: "CRM",
    icon: Building2,
    items: [
      { label: "Properties", href: "/vayon/properties", icon: Building2 },
      { label: "Leads", href: "/vayon/leads", icon: Target },
      {
        label: "Clients",
        href: "/vayon/crm/contacts",
        icon: ContactRound,
        description: "Buyer and seller directory",
      },
      {
        label: "Agencies / Builders",
        href: "/vayon/crm/companies",
        icon: Landmark,
        description: "Agency and developer directory",
      },
      { label: "Transactions", href: "/vayon/deals", icon: Handshake },
    ],
  },
  {
    id: "operations",
    label: "Operations",
    icon: CalendarDays,
    items: [
      { label: "Enterprise Inbox", href: "/vayon/notifications", icon: Activity },
      { label: "Calendar", href: "/vayon/calendar", icon: CalendarDays },
      { label: "Tasks", href: "/vayon/tasks", icon: SquareKanban },
      { label: "Timeline", href: "/vayon/timeline", icon: Activity },
      { label: "Real Estate Approval Center", href: "/vayon/approvals", icon: ShieldCheck },
    ],
  },
  {
    id: "growth",
    label: "Growth Center",
    icon: Megaphone,
    items: [
      { label: "Overview", href: "/vayon/growth", icon: Gauge },
      { label: "Lead Generation", href: "/vayon/growth/lead-generation", icon: Megaphone },
      { label: "Listing Performance", href: "/vayon/growth/listing-performance", icon: Building2 },
      { label: "Buyer Intelligence", href: "/vayon/growth/buyer-intelligence", icon: Users },
      { label: "Seller Intelligence", href: "/vayon/growth/seller-intelligence", icon: ContactRound },
      { label: "Marketing Analytics", href: "/vayon/growth/marketing-analytics", icon: BarChart3 },
      { label: "Advertising Performance", href: "/vayon/growth/advertising-performance", icon: Megaphone },
      { label: "Social Performance", href: "/vayon/growth/social-performance", icon: Share2 },
      { label: "Property SEO", href: "/vayon/growth/property-seo", icon: FileSearch },
      { label: "Referral Network", href: "/vayon/growth/referral-network", icon: Handshake },
      { label: "Market Intelligence", href: "/vayon/growth/market-intelligence", icon: LineChart },
      { label: "Reports", href: "/vayon/growth/reports", icon: BarChart3 },
    ],
  },
  {
    id: "creative-center",
    label: "AI Creative Center",
    icon: Palette,
    items: [
      { label: "Overview", href: "/vayon/creative", icon: Sparkles },
      { label: "Brand Studio", href: "/vayon/creative/brand", icon: Palette },
      { label: "Campaign Studio", href: "/vayon/creative/campaigns", icon: Megaphone },
      { label: "Image Studio", href: "/vayon/creative/images", icon: Palette },
      { label: "Video Studio", href: "/vayon/creative/videos", icon: Palette },
      { label: "Document Studio", href: "/vayon/creative/documents", icon: FileSearch },
      { label: "Asset Library", href: "/vayon/creative/assets", icon: Building2 },
      { label: "Templates", href: "/vayon/creative/templates", icon: FileSearch },
      { label: "AI Content Calendar", href: "/vayon/creative/calendar", icon: CalendarDays },
    ],
  },
  {
    id: "insights",
    label: "Insights",
    icon: BarChart3,
    items: [
      { label: "Analytics", href: "/vayon/analytics", icon: BarChart3 },
      { label: "AI Assistant", href: "/vayon/intelligence", icon: Sparkles },
    ],
  },
  {
    id: "ai",
    label: "AI Team",
    icon: Sparkles,
    items: [
      { label: "Orchestration Center", href: "/vayon/ai/collaboration", icon: Network, description: "AI executive boardroom" },
      { label: "Workforce", href: "/vayon/ai/workforce", icon: Bot },
      { label: "AI Work Queue", href: "/vayon/ai/work-queue", icon: SquareKanban },
      { label: "AI Goals", href: "/vayon/ai/goals", icon: Target },
      { label: "Smart Automations", href: "/vayon/ai/automations", icon: Workflow },
      { label: "Sarah", href: "/vayon/ai/workforce/sales-ai", icon: Users, description: "Sales Manager" },
      { label: "Emma", href: "/vayon/ai/workforce/crm-ai", icon: Users, description: "Property Advisor" },
      { label: "Alex", href: "/vayon/ai/workforce/marketing-ai", icon: Users, description: "Marketing Director" },
      { label: "David", href: "/vayon/ai/workforce/operations-ai", icon: Users, description: "Operations Manager" },
      { label: "Olivia", href: "/vayon/ai/workforce/whatsapp-ai", icon: Users, description: "Customer Success" },
    ],
  },
  {
    id: "platform",
    label: "Settings",
    icon: Settings,
    items: [
      { label: "Settings", href: "/vayon/settings/appearance", icon: Settings },
      {
        label: "Connected Apps",
        href: "/vayon/settings/integrations",
        icon: Network,
      },
    ],
  },
  {
    id: "founder-platform",
    label: "Platform",
    icon: Settings,
    items: [
      { label: "Workflow Designer", href: "/platform/founder/workflows", icon: Workflow },
      { label: "Platform Analytics", href: "/platform/system-analytics", icon: BarChart3 },
      { label: "Investor Relations", href: "/vayon/growth/investor-relations", icon: Landmark },
      { label: "Platform Marketing", href: "/platform/founder/marketing", icon: Megaphone },
      { label: "Cross Industry Templates", href: "/vayon/workflows", icon: Workflow },
      { label: "Product Intelligence", href: "/vayon/settings/product-intelligence", icon: BarChart3 },
      { label: "AI Playground", href: "/vayon/ai/playground", icon: Bot },
      { label: "Feature Flags", href: "/platform/feature-flags", icon: ShieldCheck },
      { label: "Enterprise Management", href: "/platform/organizations", icon: Building2 },
      { label: "Platform Settings", href: "/platform/settings", icon: Settings },
      { label: "Dashboard", href: "/vayon/dashboard", icon: Home },
      { label: "Founder Approval Center", href: "/vayon/founder/approvals", icon: ShieldCheck, description: "Approval Center · Executive Decisions" },
      { label: "AI Company Orchestration", href: "/vayon/ai/collaboration", icon: Network },
      { label: "Creative Operating System", href: "/vayon/creative", icon: Palette },
      { label: "Creative Cloud", href: "/vayon/creative/cloud", icon: Sparkles, description: "Creative operating model" },
      { label: "Creative Pipelines", href: "/vayon/creative/pipelines", icon: Workflow, description: "Production orchestration" },
      { label: "Customer Success", href: "/vayon/customer-success", icon: Users },
      { label: "Knowledge Engine", href: "/vayon/knowledge", icon: Sparkles },
      { label: "Administration", href: "/vayon/admin", icon: ShieldCheck },
      { label: "System Diagnostics", href: "/vayon/system", icon: Gauge },
    ],
  },
];

export const breadcrumbGroups = new Map(
  shellNavigation.flatMap((group) =>
    group.items
      .filter((item) => item.href)
      .map((item) => [item.href!, group.label]),
  ),
);
