"use client";
import { Button } from "@/features/platform/design-system";
import Link from "next/link";
import { Bot, Building2, CalendarPlus, FileImage, FilePlus2, Film, Handshake, Megaphone, Presentation, SquareCheckBig, Target, Workflow, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { FloatingSurface } from "../floating-layout/FloatingLayoutManager";
import type { PlatformVisibilityContext } from "@/features/platform/visibility/domain";
import { filterVisibleItems } from "@/features/platform/visibility/policy";
const actions=[{label:"Customer",href:"/vayon/leads/new",icon:Target},{label:"Proposal",href:"/vayon/deals/offers",icon:Handshake},{label:"Campaign",href:"/vayon/growth",icon:Megaphone},{label:"AI Employee",href:"/vayon/ai/employees",icon:Bot},{label:"Image",href:"/vayon/creative/images",icon:FileImage},{label:"Video",href:"/vayon/creative/videos",icon:Film},{label:"Meeting",href:"/vayon/meetings",icon:CalendarPlus},{label:"Task",href:"/vayon/tasks",icon:SquareCheckBig},{label:"Workflow",href:"/vayon/workflows",icon:Workflow},{label:"Website",href:"/vayon/growth",icon:Building2},{label:"Presentation",href:"/vayon/creative/documents",icon:Presentation},{label:"Document",href:"/vayon/storage",icon:FilePlus2}]as const;
export function QuickCreate({visibility}:{readonly visibility:PlatformVisibilityContext}){const[open,setOpen]=useState(false),button=useRef<HTMLButtonElement>(null),visibleActions=filterVisibleItems(visibility,actions);useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);button.current?.focus()}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open]);return <FloatingSurface id="quick-create" kind="action" priority={50}><div className="flex flex-col items-end gap-3">{open&&<div role="menu" aria-label="Create something" className="vds-dropdown-enter max-h-[min(32rem,70dvh)] w-56 overflow-y-auto rounded-2xl border border-vds-border bg-vds-elevated p-2 shadow-xl shadow-vds-shadow">{visibleActions.map(({label,href,icon:Icon})=><Link role="menuitem" key={label} href={href} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-vds-muted hover:bg-vds-hover hover:text-vds-foreground"><Icon className="size-4 text-vds-primary"/>{label}</Link>)}</div>}<Button variant="primary" ref={button} type="button" onClick={()=>setOpen(v=>!v)} aria-label={open?"Close Create menu":"Open Create menu"} aria-haspopup="menu" aria-expanded={open} className="rounded-2xl px-4 py-3 text-vds-background shadow-xl shadow-vds-shadow hover:-translate-y-0.5">{open?<X className="size-5"/>:<><SparkleIcon/>Create</>}</Button></div></FloatingSurface>}
function SparkleIcon(){return <span aria-hidden="true">✨</span>}
