"use client";
import { Button } from "@/features/platform/design-system";
import Link from "next/link";
import { Bell, BookOpen, CalendarCheck, CircleHelp, Flag, Keyboard, LifeBuoy, LogOut, MessageSquareText, Palette, PlayCircle, Settings, UserRound, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { logoutAction } from "@/features/authentication/actions/auth.actions";
import type { PlatformVisibilityContext } from "@/features/platform/visibility/domain";
import { canViewPath } from "@/features/platform/visibility/policy";

function useDismiss(open:boolean,close:()=>void,ref:React.RefObject<HTMLDivElement|null>){useEffect(()=>{if(!open)return;function click(event:MouseEvent){if(!ref.current?.contains(event.target as Node))close()}function key(event:KeyboardEvent){if(event.key==="Escape")close()}document.addEventListener("mousedown",click);window.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",click);window.removeEventListener("keydown",key)}},[close,open,ref])}
export function NotificationsMenu(){const[open,setOpen]=useState(false),ref=useRef<HTMLDivElement>(null),close=()=>setOpen(false);useDismiss(open,close,ref);return <div ref={ref} className="relative"><Button variant="control" type="button" onClick={()=>setOpen(v=>!v)} aria-label="Notifications" aria-haspopup="dialog" aria-expanded={open} className="grid size-10 place-items-center rounded-xl text-vds-muted hover:bg-vds-hover hover:text-vds-foreground"><Bell className="size-[18px]"/></Button>{open&&<section role="dialog" aria-label="Notifications" className="vds-dropdown-enter absolute right-0 top-12 z-[70] w-80 rounded-2xl border border-vds-border bg-vds-elevated p-4 shadow-xl shadow-vds-shadow"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Notifications</h2><Button variant="control" onClick={close} aria-label="Close notifications" className="grid size-8 place-items-center rounded-lg text-vds-muted hover:bg-vds-hover"><X className="size-4"/></Button></div><div className="grid min-h-40 place-items-center text-center"><div><Bell className="mx-auto size-6 text-vds-subtle"/><p className="mt-3 text-sm text-vds-muted">No notifications yet.</p><p className="mt-1 text-xs text-vds-subtle">Workspace updates will appear here.</p></div></div></section>}</div>}
export function HelpMenu({visibility}:{readonly visibility:PlatformVisibilityContext}){const[open,setOpen]=useState(false),ref=useRef<HTMLDivElement>(null),close=()=>setOpen(false);useDismiss(open,close,ref);const links=[["Documentation","/docs",BookOpen],["Video Tutorials","/vayon/success-center",PlayCircle],["Contact Support","/contact?intent=support",LifeBuoy],["Book Demo","/contact?intent=demo",CalendarCheck],["Report Issue","/contact?intent=support&topic=issue",Flag],["Keyboard Shortcuts","/vayon/settings/configuration",Keyboard],["Send Feedback","/contact?intent=feedback",MessageSquareText]]as const,visible=links.filter(([,href])=>canViewPath(visibility,href));return <div ref={ref} className="relative"><Button variant="control" type="button" onClick={()=>setOpen(v=>!v)} aria-label="Open Help menu" aria-haspopup="menu" aria-expanded={open} className="grid size-10 place-items-center rounded-xl text-vds-muted hover:bg-vds-hover hover:text-vds-foreground"><CircleHelp className="size-[18px]"/></Button>{open&&<div role="menu" className="vds-dropdown-enter absolute right-0 top-12 z-[70] w-64 rounded-2xl border border-vds-border bg-vds-elevated p-2 shadow-xl shadow-vds-shadow"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-[.16em] text-vds-subtle">Help & feedback</p>{visible.map(([label,href,Icon])=><Link key={label} role="menuitem" href={href} onClick={close} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-vds-muted hover:bg-vds-hover hover:text-vds-foreground"><Icon className="size-4" aria-hidden="true"/>{label}</Link>)}</div>}</div>}
export function ProfileMenu({name,visibility,onOpenChange}:{readonly name:string;readonly visibility:PlatformVisibilityContext;readonly onOpenChange?:(open:boolean)=>void}){const[open,setOpen]=useState(false),ref=useRef<HTMLDivElement>(null),setMenuOpen=(next:boolean)=>{setOpen(next);onOpenChange?.(next)},close=()=>setMenuOpen(false);useDismiss(open,close,ref);const initial=name.trim().charAt(0).toUpperCase()||"V",links=[["Profile","/vayon/team",UserRound],["Appearance","/vayon/settings/appearance",Palette],["Workspace","/vayon/settings/configuration",Settings],["Keyboard Shortcuts","/vayon/settings/configuration",Keyboard],["Help","/vayon/home",CircleHelp]]as const;return <div ref={ref} className="relative"><Button variant="control" type="button" onClick={()=>setMenuOpen(!open)} aria-label="Open profile menu" aria-haspopup="menu" aria-expanded={open} className="grid size-10 place-items-center rounded-xl border border-vds-border bg-vds-input text-xs font-semibold text-vds-primary hover:bg-vds-hover">{initial}</Button>{open&&<div role="menu" className="vds-dropdown-enter absolute right-0 top-12 z-[70] w-64 rounded-2xl border border-vds-border bg-vds-elevated p-2 shadow-xl shadow-vds-shadow"><div className="border-b border-vds-divider px-3 py-3"><p className="truncate text-sm font-medium">{name}</p><p className="mt-1 text-xs text-vds-subtle">Signed in to Vayon OS</p></div>{links.filter(([,href])=>canViewPath(visibility,href)).map(([label,href,Icon])=><MenuLink key={label} href={href} icon={Icon} label={label}/>)}<form action={logoutAction} className="border-t border-vds-divider pt-1"><Button variant="control" type="submit" className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-vds-danger hover:bg-vds-danger-soft"><LogOut className="size-4"/>Sign Out</Button></form></div>}</div>}
function MenuLink({href,icon:Icon,label}:{readonly href:string;readonly icon:typeof UserRound;readonly label:string}){return <Link role="menuitem" href={href} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-vds-muted hover:bg-vds-hover hover:text-vds-foreground"><Icon className="size-4"/>{label}</Link>}
