"use client";
import { Button } from "@/features/platform/design-system";
import Link from "next/link";
import { ChevronDown, ChevronLeft, ChevronRight, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { shellNavigation } from "./navigation";
import { filterNavigationForRole } from "@/features/platform/permissions/runtime/navigation";
import type { WorkspaceRoleCode } from "@/features/platform/organization/config/workspace-role-catalog";
import type { PlatformVisibilityContext } from "@/features/platform/visibility/domain";

export function ShellSidebar({ path, role, visibility, collapsed, mobileOpen, onCollapse, onMobileClose }: { readonly path: string; readonly role: WorkspaceRoleCode; readonly visibility: PlatformVisibilityContext; readonly collapsed: boolean; readonly mobileOpen: boolean; readonly onCollapse: () => void; readonly onMobileClose: () => void }) {
  const [developerOpen, setDeveloperOpen] = useState(false);
  const [aiTeamOpen, setAiTeamOpen] = useState(true);
  const closeButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!mobileOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onMobileClose()};window.addEventListener("keydown",close);requestAnimationFrame(()=>closeButton.current?.focus());return()=>window.removeEventListener("keydown",close)},[mobileOpen,onMobileClose]);
  const navigation=filterNavigationForRole(shellNavigation,role,visibility);
  return <><div aria-hidden="true" onClick={onMobileClose} className={`fixed inset-0 z-[65] bg-vds-overlay backdrop-blur-sm transition lg:hidden ${mobileOpen ? "opacity-100" : "pointer-events-none opacity-0"}`}/><aside id="vayon-sidebar" aria-label="Business navigation" className={`fixed inset-y-0 left-0 z-[70] flex w-72 flex-col border-r border-vds-border bg-vds-surface/95 pt-16 shadow-xl shadow-vds-shadow backdrop-blur-xl transition-[width,transform] duration-200 lg:z-50 lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"} ${collapsed ? "lg:w-20" : "lg:w-64"}`}>
    <Button variant="control" ref={closeButton} type="button" onClick={onMobileClose} aria-label="Close navigation" className="absolute right-3 top-3 grid size-9 place-items-center rounded-xl text-vds-muted hover:bg-vds-hover hover:text-vds-foreground lg:hidden"><X className="size-4"/></Button>
    <nav className="flex-1 overflow-y-auto px-3 py-5">{navigation.map(group => {
      const GroupIcon=group.icon, open=group.developer?developerOpen:group.id==="ai"?aiTeamOpen:true;
      return <section key={group.id} className="mb-5">{group.developer ? <Button variant="control" type="button" onClick={() => setDeveloperOpen(value => !value)} aria-expanded={developerOpen} className={`flex w-full items-center rounded-xl text-vds-muted hover:bg-vds-hover hover:text-vds-foreground ${collapsed ? "justify-center p-2.5" : "gap-2 px-3 py-2"}`} title={collapsed ? group.label : undefined}><GroupIcon className="size-4 shrink-0"/><span className={collapsed ? "sr-only" : "text-[10px] font-semibold uppercase tracking-[.16em]"}>{group.label}</span>{!collapsed&&<ChevronDown className={`ml-auto size-4 transition ${developerOpen?"rotate-180":""}`}/>}</Button> : group.id==="ai" ? <Button variant="control" type="button" onClick={()=>setAiTeamOpen(value=>!value)} aria-expanded={aiTeamOpen} className={`mb-2 flex w-full items-center rounded-xl text-vds-subtle hover:bg-vds-hover ${collapsed?"justify-center p-2.5":"gap-2 px-3 py-2"}`}><GroupIcon className="size-4"/><span className={collapsed?"sr-only":"text-[10px] font-semibold uppercase tracking-[.16em]"}>{group.label}</span>{!collapsed&&<ChevronDown className={`ml-auto size-4 transition motion-reduce:transition-none ${aiTeamOpen?"rotate-180":""}`}/>}</Button> : !collapsed&&<h2 className="mb-2 flex items-center gap-2 px-3 text-[10px] font-semibold uppercase tracking-[.16em] text-vds-subtle"><GroupIcon className="size-4"/>{group.label}</h2>}{open&&<div className="grid gap-1">{group.items.map(item=>{const Icon=item.icon,active=!!item.href&&(path===item.href||item.href!=="/vayon/dashboard"&&path.startsWith(item.href));const content=<><Icon className="size-[18px] shrink-0"/><span className={collapsed?"sr-only":"min-w-0 flex-1 truncate"}>{item.label}</span>{!collapsed&&item.description&&<span className="text-[9px] text-vds-subtle">{item.description}</span>}</>;return item.disabled?<span key={item.label} aria-disabled="true" title={`${item.label} — ${item.description}`} className={`flex cursor-not-allowed items-center rounded-xl text-vds-disabled ${collapsed?"justify-center p-2.5":"gap-3 px-3 py-2.5"}`}>{content}</span>:<Link key={item.label} href={item.href!} onClick={onMobileClose} aria-current={active?"page":undefined} title={collapsed?item.label:undefined} className={`focus-ring relative flex items-center rounded-xl text-sm ${collapsed?"justify-center p-2.5":"gap-3 px-3 py-2.5"} ${active?"bg-vds-primary-soft text-vds-primary":"text-vds-muted hover:bg-vds-hover hover:text-vds-foreground"}`}>{active&&<span className="absolute -left-1 h-5 w-0.5 rounded-full bg-vds-primary"/>}{content}</Link>})}</div>}</section>})}</nav>
    <Button variant="control" type="button" onClick={onCollapse} className="hidden h-14 items-center justify-center gap-2 border-t border-vds-border text-xs text-vds-muted hover:bg-vds-hover hover:text-vds-foreground lg:flex" aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?<ChevronRight className="size-4"/>:<><ChevronLeft className="size-4"/>Collapse</>}</Button>
  </aside></>;
}
