import "server-only";

import { CustomerRepository } from "@/features/platform/customer-success/repositories/customer.repository";
import { HealthRepository } from "@/features/platform/customer-success/repositories/health.repository";
import { founderContext } from "@/features/platform/founder/services/founder-context";
import type { FounderKpi, PlatformMetricRow } from "@/features/platform/founder/types";
import { FounderRepository } from "@/features/platform/founder/repositories/founder.repository";
import { log } from "@/lib/observability/logger";
import { CustomerGrowthRepository } from "../repositories/customer-growth.repository";
import type { CustomerGrowthSnapshot, CustomerHealthClass, OrganizationHealth, RenewalItem } from "../types";

const automations = [["trial", "Trial onboarding", "Trial started"], ["adoption", "Feature adoption nudges", "Adoption falls below target"], ["renewal", "Renewal reminders", "Renewal approaching"], ["check-in", "Customer check-ins", "Health needs attention"], ["expansion", "Expansion campaigns", "Qualified expansion signal"], ["win-back", "Win-back campaigns", "Consent-valid former customer"]].map(([id, name, trigger]) => ({ id: id!, name: name!, trigger: trigger!, consentRequired: true as const, unsubscribeRequired: true as const, approvalRequired: true as const }));
export class CustomerGrowthService {
  async snapshot(): Promise<CustomerGrowthSnapshot> {
    const started = performance.now(), { client, user } = await founderContext(), customerRepo = new CustomerRepository(client), healthRepo = new HealthRepository(client), evidenceRepo = new CustomerGrowthRepository(client), founderRepo = new FounderRepository(client);
    const [customers, storedHealth, subscriptions, invoices, journeyRows, metrics] = await Promise.all([customerRepo.list().catch(() => []), healthRepo.customers().catch(() => []), evidenceRepo.subscriptions().catch(() => []), evidenceRepo.invoices().catch(() => []), evidenceRepo.journey().catch(() => []), founderRepo.metrics().catch(() => [])]);
    const healthByOrg = new Map(storedHealth.map((item) => [item.organizationId, item]));
    const organizations = customers.map((customer): OrganizationHealth => health(customer, healthByOrg.get(customer.id)));
    const renewals = subscriptions.map((row): RenewalItem => { const organizationId = String(row.organization_id), related = invoices.filter((invoice) => String(invoice.organization_id) === organizationId), outstanding = related.filter((invoice) => !["paid", "void"].includes(String(invoice.status))).length, status = String(row.status), autoRenew = row.cancel_at_period_end !== true; return { id: String(row.id), organizationId, status, renewsAt: row.current_period_ends_at ? String(row.current_period_ends_at) : null, autoRenew, outstandingInvoices: outstanding, recommendation: outstanding ? "Resolve outstanding invoices before renewal." : !autoRenew ? "Confirm retention plan before scheduled cancellation." : "Review adoption and executive sponsor before renewal." }; });
    const latest = new Map<string, PlatformMetricRow>(); for (const row of metrics) if (!latest.has(row.metric)) latest.set(row.metric, row); const value = (...keys: readonly string[]) => { for (const key of keys) { const item = latest.get(key)?.value; if (item !== undefined && Number.isFinite(item)) return item; } return null; };
    const count = (status: string) => subscriptions.filter((row) => String(row.status) === status).length, due = renewals.filter((item) => item.renewsAt && new Date(item.renewsAt).getTime() <= Date.now() + 30 * 86_400_000).length;
    const averageHealth = organizations.length ? organizations.reduce((sum, item) => sum + item.score, 0) / organizations.length : null, churnRisk = organizations.length ? organizations.filter((item) => item.classification === "At Risk" || item.classification === "Critical").length / organizations.length * 100 : null;
    const kpis: FounderKpi[] = [metric("trials", "Active Trials", count("trialing"), "count"), metric("trial-paid", "Trial → Paid Conversion", value("trial_conversion", "trial_to_paid_conversion"), "percent"), metric("customers", "Active Customers", count("active"), "count"), metric("renewals-due", "Renewals Due", due, "count"), metric("renewals-completed", "Renewals Completed", value("renewals_completed"), "count"), metric("expansion-revenue", "Expansion Revenue", value("expansion_revenue"), "currency"), metric("health", "Customer Health Score", averageHealth, "ratio"), metric("churn-risk", "Churn Risk", churnRisk, "percent"), metric("nrr", "Net Revenue Retention", value("net_revenue_retention", "nrr"), "percent"), metric("grr", "Gross Revenue Retention", value("gross_revenue_retention", "grr"), "percent"), metric("ltv", "Customer Lifetime Value", value("customer_lifetime_value", "ltv"), "currency"), metric("arpa", "Average Revenue Per Account", value("average_revenue_per_account", "arpa"), "currency"), metric("product-adoption", "Product Adoption", value("product_adoption"), "percent"), metric("feature-adoption", "Feature Adoption", value("feature_adoption"), "percent")];
    const journey = journeyRows.map((row) => ({ id: String(row.id), organizationId: row.organization_id ? String(row.organization_id) : null, category: String(row.event_type ?? "activity"), title: String(row.title ?? "Customer activity"), occurredAt: String(row.occurred_at) }));
    log("founder.customer_growth.viewed", { actorId: user.id, organizations: organizations.length, atRisk: organizations.filter((item) => item.classification === "At Risk" || item.classification === "Critical").length, latencyMs: Math.round(performance.now() - started) });
    return { kpis, metrics, organizations, renewals, journey, automations, reports: ["Daily Customer Success Report", "Weekly Executive Report", "Monthly Growth Report"].map((label) => ({ id: label.toLowerCase().replaceAll(" ", "-"), label, formats: ["PDF", "PowerPoint"] as const })), generatedAt: new Date().toISOString() };
  }
}
function health(customer: { id: string; name: string; plan: string; workspaceCount: number; users: number; aiUsage: number; healthScore: number; supportTickets: number; lastLogin?: string }, stored?: { score: number; churnRisk: string; openIssues: number; expansionOpportunity?: string }): OrganizationHealth { const score = Math.max(0, Math.min(100, stored?.score ?? customer.healthScore)), classification: CustomerHealthClass = score >= 80 ? "Healthy" : score >= 60 ? "Needs Attention" : score >= 40 ? "At Risk" : "Critical", reasons = [customer.lastLogin ? "Login activity recorded" : "No recent login evidence", customer.aiUsage > 0 ? "AI usage recorded" : "No AI usage recorded", customer.workspaceCount > 0 ? "Workspace active" : "No active workspace", customer.users > 1 ? "Team adoption recorded" : "Low team adoption", customer.supportTickets > 0 ? `${customer.supportTickets} support interaction(s)` : "No open support interactions", `Subscription plan: ${customer.plan}`], evidenceCount = [customer.lastLogin, customer.aiUsage > 0, customer.workspaceCount > 0, customer.users > 0, stored].filter(Boolean).length, confidence = Math.min(.95, .45 + evidenceCount * .1), churnProbability = stored?.churnRisk ? riskProbability(stored.churnRisk) : Math.max(.05, Math.min(.95, (100 - score) / 100)), riskFactors = reasons.filter((reason) => /No |Low |support/i.test(reason)), recommendedActions = classification === "Healthy" ? ["Review expansion readiness with the account owner."] : ["Schedule a customer success check-in.", ...(customer.aiUsage ? [] : ["Offer guided AI onboarding."]), ...(customer.users > 1 ? [] : ["Support team invitation and role setup."])], expansionOpportunities = [customer.users >= 3 ? "Additional users" : null, customer.aiUsage > 20 ? "AI feature upgrades" : null, customer.workspaceCount > 1 ? "Higher subscription plans" : null, score >= 80 ? "Enterprise onboarding" : null, "Storage upgrades"].filter(Boolean) as string[]; return { id: customer.id, name: customer.name, plan: customer.plan, score, classification, confidence, reasons, churnProbability, riskFactors, recommendedActions, expectedExpansionValue: null, expansionOpportunities: [...new Set(expansionOpportunities)] }; }
function riskProbability(value: string) { const normalized = value.toLowerCase(); return normalized.includes("critical") ? .9 : normalized.includes("high") ? .75 : normalized.includes("medium") ? .45 : .15; }
function metric(id: string, label: string, value: number | null, unit: string): FounderKpi { return { id, label, value, unit, status: value === null ? "unavailable" : "measured" }; }
