import type { UniversalBarResult } from "../domain/contracts";
export const quickCreateActions: readonly UniversalBarResult[] = [
  {
    id: "create-lead",
    label: "New Lead",
    description: "Open the existing lead capture workflow.",
    href: "/vayon/leads/new",
    scope: "leads",
    kind: "quick-create",
    keywords: ["create", "new", "lead"],
  },
  {
    id: "create-deal",
    label: "New Deal",
    description: "Open the existing deal workflow.",
    href: "/vayon/deals/new",
    scope: "deals",
    kind: "quick-create",
    keywords: ["create", "new", "deal"],
  },
  {
    id: "create-property",
    label: "New Property",
    description: "Open the existing property workflow.",
    href: "/vayon/properties/new",
    scope: "properties",
    kind: "quick-create",
    keywords: ["create", "new", "property"],
  },
  {
    id: "create-campaign",
    label: "New Campaign",
    description: "Open the Growth campaign workspace.",
    href: "/vayon/growth",
    scope: "campaigns",
    kind: "quick-create",
    keywords: ["create", "new", "campaign"],
  },
  {
    id: "create-meeting",
    label: "New Meeting",
    description: "Open the existing meeting workflow.",
    href: "/vayon/meetings",
    scope: "meetings",
    kind: "quick-create",
    keywords: ["create", "schedule", "meeting"],
  },
  {
    id: "create-task",
    label: "New Task",
    description: "Open the existing task workflow.",
    href: "/vayon/tasks",
    scope: "tasks",
    kind: "quick-create",
    keywords: ["create", "new", "task"],
  },
  {
    id: "create-contact",
    label: "New Contact",
    description: "Open the Universal Objects workspace.",
    href: "/vayon/objects",
    scope: "contacts",
    kind: "quick-create",
    keywords: ["create", "new", "contact"],
  },
  {
    id: "create-company",
    label: "New Company",
    description: "Open the Universal Objects workspace.",
    href: "/vayon/objects",
    scope: "companies",
    kind: "quick-create",
    keywords: ["create", "new", "company"],
  },
  {
    id: "create-document",
    label: "New Document",
    description: "Open the governed AI document workflow.",
    href: "/vayon/creative/documents",
    scope: "documents",
    kind: "quick-create",
    keywords: ["create", "new", "proposal", "pitch", "deck", "document"],
  },
  {
    id: "generate-image",
    label: "Generate Image",
    description: "Open AI Image Studio.",
    href: "/vayon/creative/images",
    scope: "creative-assets",
    kind: "quick-create",
    keywords: ["create", "generate", "image"],
  },
  {
    id: "generate-video",
    label: "Generate Video",
    description: "Open AI Video Studio.",
    href: "/vayon/creative/videos",
    scope: "creative-assets",
    kind: "quick-create",
    keywords: ["create", "generate", "video"],
  },
  {
    id: "create-ai-employee",
    label: "Create AI Employee",
    description: "Configure a governed AI Workforce role.",
    href: "/onboarding/ai-workforce",
    scope: "employees",
    kind: "quick-create",
    keywords: ["create", "sales", "marketing", "support", "ai", "employee", "agent"],
  },
  {
    id: "create-workflow",
    label: "Create Workflow",
    description: "Open the preview-first AI Workflow Orchestrator.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["create", "build", "workflow", "orchestrator"],
  },
  {
    id: "run-workflow",
    label: "Run Workflow",
    description: "Preview a workflow before governed confirmation.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["run", "workflow", "preview", "approval"],
  },
  {
    id: "duplicate-workflow",
    label: "Duplicate Workflow",
    description: "Open the planner to prepare a local editable copy.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["duplicate", "copy", "workflow"],
  },
  {
    id: "search-workflow",
    label: "Search Workflow",
    description: "Search the governed workflow library.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["search", "find", "workflow"],
  },
];
