import type { UniversalBarResult } from "../domain/contracts";
export const quickCreateActions: readonly UniversalBarResult[] = [
  { id: "export-report", label: "Export Report", description: "Open the performance report, then choose Export CSV.", href: "/vayon/analytics/executive", scope: "analytics", kind: "quick-create", keywords: ["export", "report", "download", "csv"] },
  { id: "generate-brochure", label: "Generate Brochure", description: "Open the document tool to prepare a property brochure.", href: "/vayon/creative/documents", scope: "documents", kind: "quick-create", keywords: ["generate", "brochure", "marketing", "file"] },
  { id: "invite-team", label: "Invite Team", description: "Open your team and invite a colleague.", href: "/vayon/settings/members", scope: "settings", kind: "quick-create", keywords: ["invite", "team", "colleague", "member"] },
  { id: "schedule-viewing", label: "Schedule Viewing", description: "Choose a property and arrange a viewing.", href: "/vayon/site-visits", scope: "meetings", kind: "quick-create", keywords: ["schedule", "book", "viewing", "visit"] },
  { id: "send-whatsapp", label: "Send WhatsApp", description: "Open conversations to review and send your message.", href: "/vayon/communications", scope: "communications", kind: "quick-create", keywords: ["send", "whatsapp", "message"] },
  {
    id: "create-lead",
    label: "Create Lead",
    description: "Add a lead and their property requirements.",
    href: "/vayon/leads/new",
    scope: "leads",
    kind: "quick-create",
    keywords: ["create", "new", "lead"],
  },
  {
    id: "create-deal",
    label: "Create Deal",
    description: "Connect a buyer and property in a deal.",
    href: "/vayon/deals/new",
    scope: "deals",
    kind: "quick-create",
    keywords: ["create", "new", "deal"],
  },
  {
    id: "create-property",
    label: "Create Property",
    description: "Add a property you want to sell or rent.",
    href: "/vayon/properties/new",
    scope: "properties",
    kind: "quick-create",
    keywords: ["create", "new", "property"],
  },
  {
    id: "create-campaign",
    label: "Create Campaign",
    description: "Plan your campaign and create a draft.",
    href: "/vayon/creative/campaigns",
    scope: "campaigns",
    kind: "quick-create",
    keywords: ["create", "new", "campaign"],
  },
  {
    id: "create-meeting",
    label: "Create Meeting",
    description: "Schedule a meeting with a customer.",
    href: "/vayon/meetings",
    scope: "meetings",
    kind: "quick-create",
    keywords: ["create", "schedule", "meeting"],
  },
  {
    id: "create-task",
    label: "Create Task",
    description: "Set a reminder or plan your next follow-up.",
    href: "/vayon/tasks",
    scope: "tasks",
    kind: "quick-create",
    keywords: ["create", "new", "task", "follow-up", "reminder"],
  },
  {
    id: "create-contact",
    label: "Clients",
    description: "Find clients and their linked CRM records.",
    href: "/vayon/crm/contacts",
    scope: "contacts",
    kind: "navigation",
    keywords: ["client", "contact", "customer"],
  },
  {
    id: "create-company",
    label: "Create Company",
    description: "Create a company and connect its people and deals.",
    href: "/vayon/crm/companies/new",
    scope: "companies",
    kind: "quick-create",
    keywords: ["create", "new", "company"],
  },
  {
    id: "create-document",
    label: "Create Document",
    description: "Prepare a brochure, proposal, or presentation.",
    href: "/vayon/creative/documents",
    scope: "documents",
    kind: "quick-create",
    keywords: ["create", "new", "proposal", "pitch", "deck", "document", "generate", "brochure", "agreement"],
  },
  {
    id: "generate-image",
    label: "Generate Image",
    description: "Open AI Image Studio.",
    href: "/vayon/creative/images",
    scope: "creative-assets",
    kind: "quick-create",
    keywords: ["create", "generate", "image"],
  },
  {
    id: "generate-video",
    label: "Generate Video",
    description: "Open AI Video Studio.",
    href: "/vayon/creative/videos",
    scope: "creative-assets",
    kind: "quick-create",
    keywords: ["create", "generate", "video"],
  },
  {
    id: "create-ai-employee",
    label: "Create AI Employee",
    description: "Set up an AI teammate for your business.",
    href: "/onboarding/ai-workforce",
    scope: "employees",
    kind: "quick-create",
    keywords: ["create", "sales", "marketing", "support", "ai", "employee", "agent"],
  },
  {
    id: "create-workflow",
    label: "Create Workflow",
    description: "Choose a workflow and review its steps.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["create", "build", "workflow", "orchestrator"],
  },
  {
    id: "run-workflow",
    label: "Run Workflow",
    description: "Review a workflow before you run it.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["run", "workflow", "preview", "approval"],
  },
  {
    id: "duplicate-workflow",
    label: "Duplicate Workflow",
    description: "Open the planner to prepare a local editable copy.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["duplicate", "copy", "workflow"],
  },
  {
    id: "search-workflow",
    label: "Search Workflow",
    description: "Find a workflow for your next task.",
    href: "/vayon/workflows",
    scope: "workflows",
    kind: "quick-create",
    keywords: ["search", "find", "workflow"],
  },
];
