export const campaignTypes = ["Launch","Festival","Offer","Inventory Clearance","Price Revision","New Tower","Commercial","Luxury","Rental","Referral","Channel Partner","Corporate","Custom"] as const;
export const audiences = ["First-time buyers","Investors","Luxury buyers","Families","NRIs","Commercial buyers","Channel Partners","Corporate clients","Custom"] as const;
export const creativePlatforms = ["Print","Instagram","Facebook","LinkedIn","WhatsApp","Email","SMS","Website Banner","YouTube","Reels","Stories"] as const;
export const designerFormats = ["A4 Flyer","A5 Flyer","DL Flyer","Leaflet","Poster","Roll-up Banner","Standee","Billboard","Newspaper Advertisement","Magazine Advertisement","Brochure Cover","Sales Handout","Presentation Cover","Project Factsheet","Construction Update Sheet","Offer Sheet","QR Flyer","Open House Flyer"] as const;
export const socialFormats = ["Instagram Post","Carousel","Story","Facebook Post","LinkedIn Post","WhatsApp Status","Festival Creative","Launch Creative","Offer Creative","Property Highlight","Before/After Construction","Customer Testimonial Layout","Pinterest Graphic (placeholder)"] as const;
export const brochurePages = ["Cover","Project Overview","Amenities","Floor Plans","Master Plan","Location","Pricing","Contact","Back Cover"] as const;
export const videoFormats = ["15 Second Promo","30 Second Promo","60 Second Promo","Property Slideshow","Launch Teaser","Offer Video","Luxury Showcase","Construction Progress","YouTube Short","Instagram Reel","TikTok-style Vertical Video"] as const;
export const copyFormats = ["Headline","Subheadline","Description","Property Summary","Facebook Ad Copy","Google Ad Copy","Instagram Caption","LinkedIn Copy","Email Campaign","SMS","WhatsApp Message","Landing Page Copy","Blog Article","SEO Meta","CTA","Hashtags"] as const;
export const growthLanguages = ["English","Hindi","Arabic","Thai","Japanese","Spanish","German","French"] as const;
export const campaignPackFormats = ["Flyer","Leaflet","Poster","Brochure","QR Poster","Standee","Billboard","Instagram Post","Carousel","Story","Facebook Banner","LinkedIn Banner","WhatsApp Creative","15 second Reel","30 second Promo","60 second Promo","Property Slideshow","Video Storyboard","Sales Presentation Cover","Quotation Cover","Email Header","Email Campaign","SMS Copy","WhatsApp Copy","Landing Hero","CTA Banner","SEO Metadata","Landing Page Copy"] as const;
export const landingPageTypes = ["Project Microsite","Coming Soon Page","Offer Page","Booking Page","Campaign Landing Page","Construction Update Page"] as const;
export const salesKitTypes = ["Sales Brochure","Project Factsheet","Investor Deck","NRI Presentation","Channel Partner Kit","Dealer Kit","Sales Presentation","Pricing Presentation"] as const;
export const campaignChannels = ["Instagram","Facebook","LinkedIn","Email","WhatsApp","Website","Internal approvals"] as const;
export const templateCategories = ["Luxury","Premium Apartment","Villa","Commercial","Retail","Office","Affordable Housing","Rental","Investment","Festival","Offer","Corporate","Developer","Brokerage"] as const;
export type CreativeStatus="draft"|"marketing-review"|"sales-review"|"management-approval"|"approved"|"ready-to-publish";
export interface CreativeBrandKit { readonly id:string;readonly name:string;readonly logoPath?:string;readonly secondaryLogoPath?:string;readonly colors:readonly string[];readonly typography:readonly string[];readonly fonts:readonly string[];readonly icons:readonly string[];readonly watermarks:readonly string[];readonly emailSignature?:string;readonly phone?:string;readonly address?:string;readonly website?:string;readonly socialLinks:Readonly<Record<string,string>>;readonly legalDisclaimer?:string;readonly reraInformation?:string;readonly tone:string;readonly version:number; }
/** Phase C1: propertyId (Model A, public.properties) is the campaign's real subject. propertyProjectId (Model B, public.property_projects) is optional richer context -- the two models have no FK relationship to each other. */
export interface CampaignBrief {readonly propertyId:string;readonly propertyProjectId?:string;readonly campaignType:typeof campaignTypes[number];readonly audiences:readonly typeof audiences[number][];readonly platforms:readonly typeof creativePlatforms[number][];readonly language:string;readonly objective:string;}
export interface CreativeContribution {readonly employee:"Marketing Manager"|"Copywriter"|"Designer"|"Campaign Manager"|"Compliance Reviewer"|"Brand Guardian"|"Sales Manager";readonly contribution:string;readonly recommendationOnly:true;}
export interface CreativeScores {readonly overall:number;readonly visual:number;readonly copy:number;readonly brand:number;readonly readability:number;readonly ctaStrength:number;readonly offerVisibility:number;readonly trust:number;readonly suggestions:readonly string[];readonly warnings:readonly string[];}
export interface CreativeVariation {readonly name:"Version A"|"Version B"|"Version C"|"Version D"|"Version E";readonly headline:string;readonly colorDirection:string;readonly layout:string;readonly cta:string;readonly offerPlacement:string;readonly typography:string;}
export interface VideoStoryboard {readonly format:typeof videoFormats[number];readonly scenes:readonly {readonly order:number;readonly visual:string;readonly script:string;readonly captions:readonly string[];readonly assets:readonly string[]}[];readonly voiceover:string;readonly transitions:readonly string[];readonly musicSuggestions:readonly string[];readonly thumbnail:string;readonly assetTimeline:readonly string[];readonly rendering:"placeholder";}
export interface CreativeCampaign {readonly id:string;readonly name:string;readonly propertyId:string;readonly propertyProjectId?:string;readonly projectName:string;readonly developer:string;readonly status:CreativeStatus;readonly brief:CampaignBrief;readonly contributions:readonly CreativeContribution[];readonly variations:readonly CreativeVariation[];readonly scores:CreativeScores;readonly createdAt:string;readonly updatedAt:string;readonly creator:string;}
export interface CreativeAsset {readonly id:string;readonly campaignId:string;readonly propertyId:string;readonly propertyProjectId?:string;readonly name:string;readonly category:"flyer"|"video"|"brochure"|"image"|"social-post"|"presentation";readonly format:string;readonly platform:string;readonly language:string;readonly status:CreativeStatus;readonly version:number;readonly prompt:string;readonly aiEmployee:string;readonly creator:string;readonly approver?:string;readonly edits:readonly string[];readonly exports:readonly string[];readonly publishingHistory:readonly string[];readonly generatedAt:string;readonly storyboard?:VideoStoryboard;}
export type CreativeLayoutStyle="Luxury"|"Modern"|"Minimal"|"Corporate"|"Festival"|"Offer"|"Investment"|"Premium"|"Dark"|"Light";
export interface CreativeGenerationJob {readonly id:string;readonly propertyId:string;readonly propertyProjectId?:string;readonly prompt:string;readonly format:string;readonly layoutStyle:CreativeLayoutStyle;readonly status:"queued"|"processing"|"completed"|"failed";readonly progress:number;readonly attempts:number;readonly maxAttempts:number;readonly assetId?:string;readonly diagnostic?:string;readonly createdAt:string;readonly updatedAt:string;}
export interface EditableCreativeDocument {readonly assetId:string;readonly width:number;readonly height:number;readonly elements:readonly {readonly id:string;readonly type:"text"|"image"|"logo"|"shape"|"qr";readonly x:number;readonly y:number;readonly width:number;readonly height:number;readonly content:string;readonly style:Readonly<Record<string,string|number>>}[];readonly revision:number;}
export interface GrowthCampaignPack {readonly id:string;readonly campaignId:string;readonly propertyId:string;readonly propertyProjectId?:string;readonly name:string;readonly language:typeof growthLanguages[number];readonly status:CreativeStatus;readonly formats:readonly typeof campaignPackFormats[number][];readonly assetCount:number;readonly createdAt:string;}
export interface GrowthScheduleItem {readonly id:string;readonly campaignId:string;readonly channel:typeof campaignChannels[number];readonly scheduledFor:string;readonly state:"draft"|"approval-pending"|"ready";readonly publishingEnabled:false;}
export interface GrowthReview {readonly brandComplianceScore:number;readonly creativeQualityScore:number;readonly visualHierarchy:number;readonly contrast:number;readonly whitespace:number;readonly typography:number;readonly imageQuality:number;readonly ctaVisibility:number;readonly offerProminence:number;readonly audienceSuitability:number;readonly checks:Readonly<Record<"brandColors"|"logoPlacement"|"qrCode"|"offerAccuracy"|"projectInformation"|"pricingConsistency"|"legalDisclaimer"|"reraInformation"|"readability"|"accessibility",boolean>>;readonly suggestions:readonly string[];}
export interface GrowthPlan {readonly campaignLength:string;readonly creativeMix:readonly string[];readonly publishingSequence:readonly string[];readonly assetTypes:readonly string[];readonly audienceMix:readonly string[];readonly measured:false;readonly recommendationOnly:true;}
export interface CreativeSnapshot {readonly campaigns:readonly CreativeCampaign[];readonly assets:readonly CreativeAsset[];readonly brandKits:readonly CreativeBrandKit[];readonly templates:readonly {readonly id:string;readonly category:typeof templateCategories[number];readonly name:string;readonly editable:true}[];readonly analytics:readonly {readonly label:string;readonly value:string;readonly measured:boolean}[];readonly access:{readonly enabled:true;readonly source:"subscription"|"internal"};readonly governance:{readonly draftOnly:true;readonly approvalRequired:true;readonly livePublishing:false;readonly externalRendering:false;readonly tenantScoped:true};}
