import "server-only";
import type {SupabaseClient} from "@supabase/supabase-js";
import type {CreativeStudioRepository} from "./contracts";
import type {CampaignBrief,CreativeAsset,CreativeBrandKit,CreativeCampaign} from "./domain";
type Row=Record<string,unknown>;
const object=(value:unknown):Row=>value&&typeof value==="object"&&!Array.isArray(value)?value as Row:{};
const strings=(value:unknown):string[]=>Array.isArray(value)?value.map(String):[];
// Phase DBV3D: property_project_id is renamed to project_id under Production's
// compatibility shape (DBV3B) -- resolve whichever physical column is
// actually present rather than hardcoding the fresh-chain name.
const resolvePropertyProjectId=(row:Row):string|undefined=>{const v=row.property_project_id??row.project_id;return v?String(v):undefined};
export class SupabaseCreativeStudioRepository implements CreativeStudioRepository {
  constructor(private client:SupabaseClient,private organizationId:string,private workspaceId:string){}
  async campaigns(){const{data,error}=await this.client.from("creative_campaigns").select("*").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).order("updated_at",{ascending:false}).limit(100);if(error)throw error;return((data??[])as Row[]).map((row):CreativeCampaign=>{const payload=object(row.payload),brief=object(row.brief);return{id:String(row.id),name:String(row.name),propertyId:String(row.property_id),propertyProjectId:resolvePropertyProjectId(row),projectName:String(payload.projectName??"Project"),developer:String(payload.developer??"Developer unavailable"),status:String(row.status)as CreativeCampaign["status"],brief:{propertyId:String(row.property_id),propertyProjectId:resolvePropertyProjectId(row),campaignType:String(brief.campaignType??"Custom")as CampaignBrief["campaignType"],audiences:strings(brief.audiences)as CampaignBrief["audiences"],platforms:strings(brief.platforms)as CampaignBrief["platforms"],language:String(brief.language??"English"),objective:String(brief.objective??"")},contributions:(Array.isArray(payload.contributions)?payload.contributions:[])as unknown as CreativeCampaign["contributions"],variations:(Array.isArray(payload.variations)?payload.variations:[])as unknown as CreativeCampaign["variations"],scores:object(payload.scores)as unknown as CreativeCampaign["scores"],createdAt:String(row.created_at),updatedAt:String(row.updated_at),creator:String(row.created_by)}})}
  async assets(){const{data,error}=await this.client.from("creative_assets").select("*").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).order("generated_at",{ascending:false}).limit(200);if(error)throw error;return((data??[])as Row[]).map((row):CreativeAsset=>({id:String(row.id),campaignId:String(row.campaign_id),propertyId:String(row.property_id),propertyProjectId:resolvePropertyProjectId(row),name:String(row.name),category:String(row.category)as CreativeAsset["category"],format:String(row.format),platform:String(row.platform),language:String(row.language),status:String(row.status)as CreativeAsset["status"],version:Number(row.version),prompt:String(row.prompt),aiEmployee:String(row.ai_employee),creator:String(row.created_by),approver:row.approver?String(row.approver):undefined,edits:strings(row.edits),exports:strings(row.exports),publishingHistory:strings(row.publishing_history),generatedAt:String(row.generated_at),storyboard:row.storyboard?object(row.storyboard)as unknown as CreativeAsset["storyboard"]:undefined}))}
  async brandKits(){const{data,error}=await this.client.from("creative_brand_kits").select("*").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).order("updated_at",{ascending:false});if(error)throw error;return((data??[])as Row[]).map((row):CreativeBrandKit=>({id:String(row.id),name:String(row.name),logoPath:row.logo_path?String(row.logo_path):undefined,secondaryLogoPath:row.secondary_logo_path?String(row.secondary_logo_path):undefined,colors:strings(row.colors),typography:strings(row.typography),fonts:strings(row.fonts),icons:strings(row.icons),watermarks:strings(row.watermarks),emailSignature:row.email_signature?String(row.email_signature):undefined,phone:row.phone?String(row.phone):undefined,address:row.address?String(row.address):undefined,website:row.website?String(row.website):undefined,socialLinks:object(row.social_links)as Record<string,string>,legalDisclaimer:row.legal_disclaimer?String(row.legal_disclaimer):undefined,reraInformation:row.rera_information?String(row.rera_information):undefined,tone:String(row.tone),version:Number(row.version)}))}
  async saveDraft(input:Readonly<{brief:CampaignBrief;name:string;projectName:string;developer:string;payload:Record<string,unknown>}>){const{data,error}=await this.client.rpc("create_creative_campaign_draft",{p_input:{name:input.name,propertyId:input.brief.propertyId,propertyProjectId:input.brief.propertyProjectId??null,brief:input.brief,payload:{...input.payload,projectName:input.projectName,developer:input.developer}}});if(error)throw error;return String(data)}
}
