import"server-only";
import{GoogleCalendarService}from"@/features/platform/integrations/google/services/calendar.service";
import{GoogleRepository}from"@/features/platform/integrations/google/repositories/google.repository";
import{operationsContext}from"@/features/vayon/operations/services/context";
type Key="readCalendar"|"createEvents"|"updateEvents"|"meetingSuggestions"|"reminderSuggestions";
export type CalendarPermissions=Readonly<Record<Key,boolean>>;
export type CalendarProductionState=Readonly<{connected:boolean;account:string|null;selectedCalendar:string|null;lastSync:string|null;health:"Connected"|"Needs Attention"|"Not Connected";permissions:CalendarPermissions}>;
const defaults:CalendarPermissions=Object.freeze({readCalendar:true,createEvents:true,updateEvents:true,meetingSuggestions:true,reminderSuggestions:true});
export class CalendarProductionSyncService{
 async state():Promise<CalendarProductionState>{const ctx=await operationsContext(),repository=new GoogleRepository(ctx.client,ctx.organizationId,ctx.workspaceId),[credential,connection,health]=await Promise.all([repository.credential(),ctx.client.from("integration_connections").select("configuration,last_sync_at,integration_providers!inner(code)").eq("workspace_id",ctx.workspaceId).eq("integration_providers.code","google_calendar").is("deleted_at",null).maybeSingle(),ctx.client.from("integration_health").select("status,last_failure_at,integration_providers!inner(code)").eq("workspace_id",ctx.workspaceId).eq("integration_providers.code","google_calendar").maybeSingle()]);if(connection.error)throw connection.error;if(health.error)throw health.error;const configuration=connection.data?.configuration as{permissions?:Partial<CalendarPermissions>;selectedCalendar?:string}|null,permissions=Object.freeze({...defaults,...configuration?.permissions});return{connected:Boolean(credential),account:credential?.email??null,selectedCalendar:configuration?.selectedCalendar??null,lastSync:connection.data?.last_sync_at??null,health:!credential?"Not Connected":health.data?.last_failure_at||health.data?.status==="degraded"?"Needs Attention":"Connected",permissions}}
 async synchronize(){const ctx=await operationsContext(),state=await this.state();if(!state.connected)throw new Error("Google Calendar is not connected.");if(!state.permissions.readCalendar)throw new Error("Enable Read Calendar before synchronizing.");const calendar=new GoogleCalendarService();try{const calendars=await calendar.calendars(),selected=calendars.filter(x=>x.selected||x.primary),ids=(state.selectedCalendar?[state.selectedCalendar]:selected.map(x=>x.id)).slice(0,10),now=Date.now(),timeMin=state.lastSync?new Date(new Date(state.lastSync).getTime()-300000).toISOString():new Date(now-30*86400000).toISOString(),page=await calendar.events({calendarIds:ids.length?ids:["primary"],timeMin,timeMax:new Date(now+365*86400000).toISOString()}),messages=page.events.map(event=>({externalId:event.id,calendarId:event.calendarId,title:event.title,description:event.description,location:event.location,start:event.start,end:event.end,status:event.status,organizer:event.organizer,attendees:event.attendees,conferenceUrl:event.conferenceUrl,allDay:event.allDay,timeZone:event.timeZone})),{data,error}=await ctx.client.rpc("sync_google_calendar_metadata",{p_workspace_id:ctx.workspaceId,p_events:messages,p_selected_calendar:state.selectedCalendar??selected.find(x=>x.primary)?.id??ids[0]??"primary"});if(error)throw error;return data as{imported:number;updated:number;duplicates:number;linked:number}}catch(reason){await ctx.client.rpc("record_google_calendar_sync_failure",{p_workspace_id:ctx.workspaceId,p_reason:(reason instanceof Error?reason.message:"Calendar synchronization failed.").slice(0,240)});throw reason}}
 async permissions(value:CalendarPermissions){const ctx=await operationsContext(),{error}=await ctx.client.rpc("update_google_calendar_permissions",{p_workspace_id:ctx.workspaceId,p_permissions:value});if(error)throw error}
}
