export const deliverableGroups = {
  Branding: [
    "Logo Refresh",
    "Brand Guidelines",
    "Color Update",
    "Typography",
    "QR Assets",
    "Business Cards",
    "Letterhead",
    "Email Signature",
  ],
  Marketing: [
    "Company Profile",
    "Brochure",
    "Flyer",
    "Product Catalogue",
    "Posters",
    "Roll-up Banner",
    "Product Sheet",
    "Case Study",
  ],
  Website: [
    "Landing Page",
    "Contact Page",
    "Thank You Page",
    "Product Pages",
    "Lead Capture",
  ],
  Sales: [
    "Proposal",
    "Pitch Deck",
    "Sales Presentation",
    "Quotation",
    "Pricing Sheet",
    "Product Datasheet",
  ],
  "Social Media": [
    "Facebook",
    "Instagram",
    "LinkedIn",
    "X",
    "YouTube",
    "TikTok",
    "WhatsApp",
  ],
  Advertising: [
    "Google Search",
    "Google Display",
    "Facebook Ads",
    "Instagram Ads",
    "LinkedIn Ads",
    "YouTube Ads",
  ],
  Images: [
    "Product Images",
    "Lifestyle Images",
    "Team Images",
    "Office Images",
    "Architecture",
    "Hero Images",
    "Mockups",
  ],
  Videos: [
    "15 Second Reel",
    "30 Second Commercial",
    "Product Demo",
    "Corporate Video",
    "Website Hero",
    "Investor Video",
    "Shorts",
  ],
  Email: [
    "Welcome Email",
    "Newsletter",
    "Product Launch",
    "Investor Email",
    "Follow-up Sequence",
  ],
  Documents: [
    "Press Release",
    "Whitepaper",
    "FAQ",
    "User Guide",
    "Installation Guide",
  ],
} as const;
export const campaignTemplates = [
  "Product Launch System",
  "Lead Generation Campaign",
  "Investor Readiness Package",
  "Real Estate Launch",
  "Solar Growth Campaign",
  "Healthcare Awareness",
  "Education Enrollment",
  "Hospitality Promotion",
] as const;
