import"server-only";
import{founderContext}from"@/features/platform/founder/services/founder-context";
import{ObservabilityRepository,type EvidenceRows}from"@/features/platform/observability-center/observability.repository";
import{PlatformObservabilityService}from"@/features/platform/observability-center/observability.service";
import type{ObservabilityHealthState}from"@/features/platform/observability-center/types";
import type{AuditRow,DeliveryRow,ErrorGroup,OperationsSnapshot,OperatorStatus,ProviderHealth,SlowOperation}from"./types";
type Row=Record<string,unknown>;
const providerNames=["OpenAI","Google","Gmail","Calendar","Paddle","Transactional Email","WhatsApp"]as const;
const aliases:Record<typeof providerNames[number],readonly string[]>={OpenAI:["openai"],Google:["google"],Gmail:["gmail"],Calendar:["calendar"],Paddle:["paddle"],"Transactional Email":["transactional-email","resend"],WhatsApp:["whatsapp"]};
const operator=(state:ObservabilityHealthState,evidence:string):OperatorStatus=>evidence!=="live"?"Configuration Required":state==="healthy"?"Healthy":state==="degraded"||state==="maintenance"?"Warning":state==="unavailable"?"Unavailable":"Configuration Required";
const number=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?n:null};
const text=(value:unknown,fallback="Unavailable")=>typeof value==="string"&&value.trim()?value.trim():fallback;
const average=(values:readonly(number|null)[])=>{const valid=values.filter((x):x is number=>x!==null);return valid.length?Math.round(valid.reduce((a,b)=>a+b,0)/valid.length):null};
const duration=(start:unknown,end:unknown)=>{const a=Date.parse(text(start,"")),b=Date.parse(text(end,""));return Number.isFinite(a)&&Number.isFinite(b)?Math.max(0,b-a):null};
const safeRoute=(row:Row)=>{const metadata=row.metadata&&typeof row.metadata==="object"?row.metadata as Row:{},raw=text(metadata.route??metadata.path??row.event_name,"Unknown operation").split("?")[0];return raw.replace(/[0-9a-f]{8}-[0-9a-f-]{27,}/gi,"[record]").slice(0,100)};
export class OperationsMonitoringService{
 async snapshot():Promise<OperationsSnapshot>{const{client}=await founderContext(),repository=new ObservabilityRepository(client),[platform,auditEvidence,logs,webhooks,syncs,performance,jobs]=await Promise.all([new PlatformObservabilityService().snapshot(),repository.auditTimeline(),repository.operationalLogs(),repository.webhookDeliveries(),repository.synchronizationHistory(),repository.performanceEvents(),repository.learningJobs()]),applicationState=platform.health.find(x=>x.id==="application"),providers:ProviderHealth[]=providerNames.map(name=>{const item=platform.health.find(x=>(aliases[name]??[]).includes(x.id));return{name,status:item?operator(item.state,item.evidence):"Configuration Required",checkedAt:item?.checkedAt??null,latencyMs:item?.latencyMs??null,diagnostic:item?.diagnostic??"No authoritative provider measurement is available."}}),webhookRows:DeliveryRow[]=webhooks.rows.slice(0,50).map(row=>({event:text(row.event_type,"Webhook delivery"),direction:text(row.direction,"unknown"),status:text(row.status,"unknown"),attempts:number(row.attempts)??0,receivedAt:text(row.received_at,new Date(0).toISOString()),latencyMs:duration(row.received_at,row.processed_at)})),audit:AuditRow[]=auditEvidence.rows.map(row=>({action:text(row.event_type,"platform.activity"),title:text(row.title,"Platform activity recorded"),occurredAt:text(row.occurred_at,new Date(0).toISOString())})),errors=groupErrors(logs),slowOperations=slow(performance,syncs),responseTimes=performance.rows.map(row=>number(row.duration_ms)),syncTimes=syncs.rows.map(row=>number(row.duration_ms)),jobTimes=jobs.rows.map(row=>number(row.latency_ms)??duration(row.started_at,row.completed_at));return{application:{status:applicationState?operator(applicationState.state,applicationState.evidence):"Unavailable",uptimeSeconds:Math.floor(process.uptime()),version:process.env.APP_VERSION??"Not configured",environment:process.env.APP_ENV??process.env.NODE_ENV??"Not configured",buildNumber:process.env.BUILD_NUMBER??process.env.VERCEL_GIT_COMMIT_SHA?.slice(0,8)??"Not configured",deploymentTime:process.env.DEPLOYMENT_TIME??null},platform,providers,webhooks:webhookRows,audit,errors,slowOperations,averageJobDurationMs:average(jobTimes),averageResponseTimeMs:average(responseTimes),averageSyncTimeMs:average(syncTimes),generatedAt:new Date().toISOString()}}
}
function groupErrors(logs:EvidenceRows):ErrorGroup[]{const groups=new Map<string,Row[]>();for(const row of logs.rows.filter(x=>["error","critical","warning"].includes(String(x.level)))){const key=text(row.event,"integration.error");groups.set(key,[...(groups.get(key)??[]),row])}return[...groups].map<ErrorGroup>(([component,rows])=>{const dates=rows.map(row=>text(row.occurred_at,new Date(0).toISOString())).sort();return{component,severity:rows.some(row=>String(row.level)==="critical")?"Critical":"Warning",firstSeen:dates[0]!,lastSeen:dates.at(-1)!,occurrences:rows.length,recovery:Date.now()-Date.parse(dates.at(-1)!)>3600000?"Recovered":"Open"}}).sort((a,b)=>b.lastSeen.localeCompare(a.lastSeen)).slice(0,50)}
function slow(performance:EvidenceRows,syncs:EvidenceRows):SlowOperation[]{const operations:SlowOperation[]=[];for(const row of performance.rows){const durationMs=number(row.duration_ms);if(durationMs!==null&&durationMs>=500)operations.push({label:safeRoute(row),durationMs,kind:safeRoute(row).startsWith("/api/")?"API":"Page"})}for(const row of syncs.rows){const durationMs=number(row.duration_ms);if(durationMs!==null)operations.push({label:text(row.entity_type,"Provider synchronization"),durationMs,kind:"Synchronization"})}return operations.sort((a,b)=>b.durationMs-a.durationMs).slice(0,20)}
