import { Button } from "@/features/platform/design-system";
import { UniversalEmptyState } from "@/features/vayon/empty-states/UniversalEmptyState";
import Link from"next/link";import type{ReactNode}from"react";import type{WorkspaceAction,WorkspaceEvent,WorkspaceMetadata,WorkspaceModel,WorkspaceRelation,WorkspaceSidebarSection,WorkspaceTab,WorkspaceWidget}from"../types";
export function WorkspaceLayout({header,hero,tabs,children,rightPanel,timeline}:{header:ReactNode;hero?:ReactNode;tabs:ReactNode;children:ReactNode;rightPanel:ReactNode;timeline?:ReactNode}){return <main className="mx-auto max-w-[100rem] px-4 py-6 sm:px-6 lg:px-8"><div>{header}</div>{hero}<div className="sticky top-0 z-20 -mx-2 bg-[var(--vds-color-background)]/95 px-2 backdrop-blur">{tabs}</div><div className="grid gap-6 xl:grid-cols-[13rem_minmax(0,1fr)_19rem]"><WorkspaceSidebar/><section className="min-w-0" aria-label="Workspace content">{children}</section>{rightPanel}</div>{timeline&&<section className="mt-8 border-t border-vds-border/[0.07] pt-7" aria-label="Recent timeline">{timeline}</section>}</main>}
export function WorkspaceBreadcrumbs({items}:{items:WorkspaceModel["breadcrumbs"]}){return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap gap-2 text-xs text-vds-muted">{items.map((item,index)=><li key={item.label} className="flex gap-2">{index>0&&<span aria-hidden>›</span>}{item.href?<Link href={item.href} className="hover:text-vds-primary">{item.label}</Link>:<span aria-current="page">{item.label}</span>}</li>)}</ol></nav>}
export function WorkspaceHeader({model,actions}:{model:WorkspaceModel;actions:readonly WorkspaceAction[]}){return <header className="border-b border-vds-border/[0.07] pb-6"><WorkspaceBreadcrumbs items={model.breadcrumbs}/><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><WorkspaceStatus value={model.status}/><Button variant="control" aria-label={model.metadata.favorite?"Remove favorite":"Add favorite"} className="text-vds-warning">{model.metadata.favorite?"★":"☆"}</Button></div><h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">{model.title}</h1><p className="mt-2 text-sm text-vds-muted">{model.subtitle}</p></div><WorkspaceActions actions={actions}/></div><WorkspaceMetadataView metadata={model.metadata}/></header>}
export function WorkspaceHero({children}:{children:ReactNode}){return <section className="my-6 rounded-3xl border border-vds-border/[0.08] bg-gradient-to-br from-vds-surface to-vds-primary/[0.025] p-5 sm:p-6">{children}</section>}
export function WorkspaceStatus({value}:{value:string}){return <span className="rounded-full border border-vds-accent-border bg-vds-primary/[0.07] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-vds-primary">{value.replaceAll("_"," ")}</span>}
export function WorkspaceMetadataView({metadata}:{metadata:WorkspaceMetadata}){return <dl className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-vds-muted">{[["Owner",metadata.owner??"Not assigned"],["Assigned",metadata.assignedUser??"Unassigned"],["Created",new Date(metadata.createdAt).toLocaleDateString()],["Updated",new Date(metadata.updatedAt).toLocaleString()]].map(([k,v])=><div key={k} className="flex gap-2"><dt className="text-vds-subtle">{k}</dt><dd>{v}</dd></div>)}</dl>}
export function WorkspaceTabs({tabs,active,baseHref}:{tabs:readonly WorkspaceTab[];active:string;baseHref:string}){return <nav className="flex gap-1 overflow-x-auto py-4" aria-label="Workspace tabs">{tabs.map(tab=><Link key={tab.id} href={`${baseHref}?tab=${tab.id}`} aria-current={active===tab.id?"page":undefined} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-vds-focus ${active===tab.id?"bg-vds-primary-soft text-vds-primary":"text-vds-muted hover:bg-vds-elevated hover:text-vds-foreground"}`}>{tab.label}</Link>)}</nav>}
export function WorkspaceActions({actions}:{actions:readonly WorkspaceAction[]}){return <div className="flex flex-wrap gap-2 rounded-2xl border border-vds-border/[0.08] bg-[var(--vds-color-surface)]/95 p-2 shadow-xl backdrop-blur lg:border-0 lg:bg-transparent lg:p-0 lg:shadow-none">{actions.slice(0,5).map(action=>action.href?<Link key={action.id} href={action.href} className="rounded-full border border-vds-border px-4 py-2 text-xs hover:border-vds-accent-border">{action.label}</Link>:<Button variant="control" key={action.id} type="button" disabled={action.kind==="placeholder"} title={action.kind==="placeholder"?"Coming soon":undefined} className={`rounded-full border px-4 py-2 text-xs disabled:opacity-40 ${action.destructive?"border-vds-danger text-vds-danger":"border-vds-border"}`}>{action.label}</Button>)}</div>}
export function WorkspaceCommandBar({actions}:{actions:readonly WorkspaceAction[]}){return <div className="flex gap-2 overflow-x-auto rounded-2xl border border-vds-border/[0.07] bg-vds-surface/[0.025] p-3" aria-label="Workspace command bar"><WorkspaceActions actions={actions}/></div>}
export function WorkspaceSidebar(){return <aside className="hidden xl:block"><nav className="sticky top-20 space-y-1 text-xs text-vds-muted" aria-label="Workspace navigation">{["Summary","Details","Relationships","Recent Activity"].map(x=><a key={x} href={`#${x.toLowerCase().replace(" ","-")}`} className="block rounded-xl px-3 py-2 hover:bg-vds-elevated hover:text-vds-foreground">{x}</a>)}</nav></aside>}
export function WorkspaceOverview({widgets}:{widgets:readonly WorkspaceWidget[]}){return <div id="summary" className="grid gap-4 md:grid-cols-2">{[...widgets].sort((a,b)=>a.order-b.order).map(widget=><section key={widget.id} className={`rounded-3xl border border-vds-border/[0.07] bg-vds-surface/[0.03] p-5 ${widget.size==="large"?"md:col-span-2":""}`}><h2 className="text-sm font-semibold">{widget.title}</h2>{widget.value&&<p className="mt-3 text-xl text-vds-primary">{widget.value}</p>}{widget.content??<p className="mt-2 text-sm text-vds-muted">{widget.description}</p>}</section>)}</div>}
export function WorkspaceTimeline({events}:{events:readonly WorkspaceEvent[]}){return <div className="space-y-3">{events.map(event=><article key={event.id} className="flex gap-4 rounded-2xl border border-vds-border/[0.06] p-4"><span className="mt-1 size-2 shrink-0 rounded-full bg-vds-primary/60"/><div><p className="text-sm">{event.title}</p><p className="mt-1 text-xs text-vds-subtle">{event.description??event.type}{event.occurredAt?` · ${new Date(event.occurredAt).toLocaleString()}`:""}</p></div></article>)}</div>}
export function WorkspaceActivity({items}:{items:WorkspaceModel["activities"]}){return <WorkspaceEmptyState title="Activity feed" description={items.length?`${items.length} activities`:"Calls, meetings, emails, WhatsApp, tasks, and comments appear here."}/>}
export function WorkspaceNotes(){return <WorkspaceEmptyState title="Notes" description="Pinned, private, team notes, and future mentions share this workspace."/>}
export function WorkspaceFiles(){return <WorkspaceEmptyState title="Files" description="Unified previews and tenant-aware uploads will appear here."/>}
export function WorkspaceTasks(){return <WorkspaceEmptyState title="Tasks" description="Status, priority, assignee, due date, and reminders are ready for task integration."/>}
export function WorkspaceRelations({relations}:{relations:readonly WorkspaceRelation[]}){return <div className="grid gap-4 sm:grid-cols-2">{relations.map(r=><article key={r.id} className="rounded-3xl border border-vds-border/[0.07] p-5"><h2 className="text-sm font-semibold">{r.label}</h2><p className="mt-2 text-xs text-vds-muted">{r.count??0} linked · {r.description??r.type}</p></article>)}</div>}
export function WorkspaceInsights(){return <WorkspaceEmptyState title="Insights" description="Analytics projections will render through module-provided widgets."/>}
export function WorkspaceAI(){return <section className="rounded-3xl border border-vds-accent-border bg-gradient-to-br from-vds-primary/[0.07] to-vds-info/[0.03] p-6"><p className="text-xs uppercase tracking-widest text-vds-primary">AI Assistant</p><div className="mt-5 grid gap-3 md:grid-cols-2">{["Summary","Insights","Recommendations","Risks","Suggested Actions","Missing Information"].map(x=><div key={x} className="rounded-2xl border border-vds-border/[0.07] bg-vds-input p-4"><h2 className="text-sm">{x}</h2><p className="mt-2 text-xs text-vds-subtle">Ready for approved AI inference.</p></div>)}</div></section>}
export function WorkspaceRightPanel({sections}:{sections:readonly WorkspaceSidebarSection[]}){return <aside className="xl:block"><details className="rounded-3xl border border-vds-border/[0.08] bg-[var(--vds-color-surface)] p-5 xl:open" open><summary className="cursor-pointer text-sm font-semibold">Context panel</summary>{sections.map(section=><section key={section.id} className="mt-5 border-t border-vds-border/[0.06] pt-4"><h2 className="text-xs uppercase tracking-widest text-vds-subtle">{section.title}</h2>{section.items.map(item=><div key={item.label} className="mt-3"><p className="text-xs text-vds-subtle">{item.label}</p><p className="mt-1 text-sm text-vds-secondary">{item.value}</p></div>)}</section>)}</details></aside>}
export function WorkspaceEmptyState({title,description}:{title:string;description:string}){const moduleId=title.toLowerCase().replaceAll(" ","-");return <UniversalEmptyState module={moduleId} title={title} description={description} primary={{label:`Create ${title.replace(/s$/i,"")}`,href:"/vayon/home"}} secondary={{label:"View demo",href:"/demo"}}/>}

