import type { ShellNavigationGroup } from "@/features/vayon/product-shell/types";
import type { WorkspaceRoleCode } from "@/features/platform/organization/config/workspace-role-catalog";
import { evaluateWorkspacePermission } from "./policy";
import type { PermissionModule } from "./types";
import type { PlatformVisibilityContext } from "@/features/platform/visibility/domain";
import { canViewPath } from "@/features/platform/visibility/policy";
const routes:readonly{prefix:string;module:PermissionModule}[]=[
  {prefix:"/vayon/settings/billing",module:"billing"},{prefix:"/vayon/settings/invoices",module:"invoices"},{prefix:"/vayon/settings/integrations",module:"integrations"},{prefix:"/vayon/settings/organization",module:"organization_settings"},{prefix:"/vayon/settings/members",module:"team_management"},{prefix:"/vayon/settings/product-intelligence",module:"analytics"},{prefix:"/vayon/team",module:"team_management"},{prefix:"/vayon/admin",module:"team_management"},{prefix:"/vayon/knowledge",module:"knowledge"},{prefix:"/vayon/creative-studio",module:"creative_studio"},{prefix:"/vayon/creative",module:"creative_studio"},{prefix:"/vayon/workflows",module:"workflow_automation"},{prefix:"/vayon/approvals",module:"workflow_automation"},{prefix:"/vayon/calendar",module:"calendar"},{prefix:"/vayon/tasks",module:"calendar"},{prefix:"/vayon/leads",module:"leads"},{prefix:"/vayon/deals",module:"deals"},{prefix:"/vayon/crm/contacts",module:"contacts"},{prefix:"/vayon/crm/companies",module:"companies"},{prefix:"/vayon/analytics",module:"analytics"},{prefix:"/vayon/customer-success",module:"customer_success"},{prefix:"/vayon/ai",module:"ai_employees"},{prefix:"/vayon/workforce",module:"ai_employees"},{prefix:"/vayon/intelligence",module:"ai_employees"},{prefix:"/vayon/brain",module:"ai_employees"},{prefix:"/vayon/runtime",module:"ai_employees"},{prefix:"/vayon/cognitive",module:"ai_employees"}
];
export function permissionModuleForPath(path:string){return routes.find(route=>path.startsWith(route.prefix))?.module}
export function filterNavigationForRole(groups:readonly ShellNavigationGroup[],role:WorkspaceRoleCode,visibility:PlatformVisibilityContext){return groups.map(group=>({...group,items:group.items.filter(item=>{if(item.href&&!canViewPath(visibility,item.href))return false;const permissionModule=item.href?permissionModuleForPath(item.href):undefined;return visibility.founder||!permissionModule||evaluateWorkspacePermission(role,{module:permissionModule,action:"view"}).allowed})})).filter(group=>group.items.length)}
