"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { GripVertical, Search } from "lucide-react";
import { Button } from "@/features/platform/design-system";
import type { DealBoardData, DealRecord } from "../types";
import { moveDealStageAction } from "../actions/deal.actions";

export function StageBadge({stage}:{stage:string}){return <span className="rounded-full border border-vds-accent-border bg-vds-primary/[0.07] px-2 py-1 text-[10px] uppercase text-vds-primary">{stage.replaceAll("_"," ")}</span>}
export function PipelineStatistics({data}:{data:DealBoardData}){const items=[["Pipeline value",data.totalValue],["Average transaction",data.averageValue],["Conversion",`${data.conversion.toFixed(1)}%`],["Forecast revenue",data.forecastRevenue],["Expected monthly",data.expectedMonthlyRevenue]];return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{items.map(([k,v])=><div key={k} className="rounded-2xl border border-vds-border/[0.07] bg-vds-surface/[0.03] p-4"><p className="text-xs text-vds-subtle">{k}</p><p className="mt-2 text-xl font-semibold">{typeof v==="number"?v.toLocaleString():v}</p></div>)}</div>}
export function DealCard({deal,stages,onDragStart,pending}:{deal:DealRecord;stages:DealBoardData["stages"];onDragStart:(deal:DealRecord)=>void;pending:boolean}){const facts=[["Buyer",deal.leadName??"Not linked"],["Seller","Unavailable"],["Property",deal.propertyName??"Not linked"],["Commission","Unavailable"],["Closing date",deal.closingDate??"Not set"],["Risk","Unavailable"],["Pending tasks","Unavailable"]] as const;return <article draggable={!pending} onDragStart={()=>onDragStart(deal)} data-deal-id={deal.id} data-stage-id={deal.stageId} className="group rounded-2xl border border-vds-border bg-vds-surface p-4 shadow-sm transition hover:border-vds-accent-border motion-reduce:transition-none active:cursor-grabbing"><div className="flex items-start gap-2"><GripVertical className="mt-0.5 size-4 shrink-0 text-vds-subtle" aria-hidden="true"/><div className="min-w-0 flex-1"><Link href={`/vayon/deals/${deal.id}`} className="font-medium hover:text-vds-primary">{deal.name}</Link><p className="mt-1 truncate text-xs text-vds-subtle">{deal.reference} · {deal.stageName}</p></div><span className="rounded-full bg-vds-primary-soft px-2 py-1 text-[10px] font-semibold text-vds-primary">{deal.probability}%</span></div><p className="mt-4 text-sm font-semibold">{deal.value?.amount.toLocaleString()??"Value unavailable"} {deal.value?.currency}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-[10px]">{facts.map(([label,value])=><div key={label}><dt className="text-vds-subtle">{label}</dt><dd className="mt-0.5 truncate text-vds-secondary">{value}</dd></div>)}</dl><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-vds-elevated" aria-label={`${deal.probability}% transaction progress`}><span className="block h-full rounded-full bg-vds-primary" style={{width:`${Math.min(100,Math.max(0,deal.probability))}%`}}/></div><form action={moveDealStageAction} className="mt-3"><input type="hidden" name="dealId" value={deal.id}/><input type="hidden" name="version" value={deal.version}/><select name="stageId" defaultValue={deal.stageId} className="w-full rounded-xl border border-vds-border bg-vds-surface p-2 text-xs" aria-label={`Move ${deal.name} transaction stage`}>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button variant="control" disabled={pending} className="mt-2 text-[10px] text-vds-primary">Update stage</Button></form></article>}
function DealColumn({stage,deals,allStages,onDragStart,onDrop,pending}:{stage:DealBoardData["stages"][number];deals:readonly DealRecord[];allStages:DealBoardData["stages"];onDragStart:(deal:DealRecord)=>void;onDrop:(stageId:string)=>void;pending:boolean}){const value=deals.reduce((s,d)=>s+(d.value?.amount??0),0),forecast=deals.reduce((s,d)=>s+(d.value?.amount??0)*d.probability/100,0);return <section onDragOver={event=>event.preventDefault()} onDrop={()=>onDrop(stage.id)} data-drop-stage={stage.id} className="w-80 shrink-0 rounded-3xl border border-vds-border/[0.07] bg-vds-surface/[0.025] p-3"><header className="flex items-start justify-between px-1 py-2"><div><h2 className="text-sm font-semibold">{stage.name}</h2><p className="mt-1 text-xs text-vds-subtle">{deals.length} transactions · {value.toLocaleString()}</p><p className="mt-1 text-[10px] text-vds-muted">Weighted {forecast.toLocaleString()}</p></div><StageBadge stage={stage.code}/></header><div className="mt-3 min-h-24 space-y-3">{deals.map(d=><DealCard key={d.id} deal={d} stages={allStages} onDragStart={onDragStart} pending={pending}/>)}{!deals.length&&<p className="rounded-2xl border border-dashed border-vds-border p-5 text-center text-xs text-vds-muted">Move a transaction here</p>}</div></section>}
export function DealBoard({data}:{data:DealBoardData}){const[query,setQuery]=useState(""),[owner,setOwner]=useState("all"),[dragged,setDragged]=useState<DealRecord|null>(null),[pending,startTransition]=useTransition(),owners=useMemo(()=>[...new Set(data.deals.map(deal=>deal.assignedAgentName??"Unassigned"))].sort(),[data.deals]),deals=useMemo(()=>data.deals.filter(deal=>(owner==="all"||(deal.assignedAgentName??"Unassigned")===owner)&&[deal.name,deal.reference,deal.propertyName??"",deal.leadName??""].some(value=>value.toLocaleLowerCase().includes(query.toLocaleLowerCase()))),[data.deals,owner,query]);function drop(stageId:string){if(!dragged||dragged.stageId===stageId)return;const form=new FormData();form.set("dealId",dragged.id);form.set("version",String(dragged.version));form.set("stageId",stageId);startTransition(()=>moveDealStageAction(form));setDragged(null)}return <div><div className="mb-5 flex flex-col gap-3 rounded-2xl border border-vds-border bg-vds-surface p-4 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search property transactions</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-vds-muted" aria-hidden="true"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search transactions, clients, properties…" className="h-10 w-full rounded-xl border border-vds-border bg-vds-input pl-10 pr-3 text-sm"/></label><select value={owner} onChange={event=>setOwner(event.target.value)} aria-label="Filter transactions by assigned agent" className="h-10 rounded-xl border border-vds-border bg-vds-input px-3 text-sm"><option value="all">All agents</option>{owners.map(value=><option key={value}>{value}</option>)}</select><span className="self-center text-xs text-vds-muted">{deals.length} visible · drag cards to update stage</span></div><div className="flex gap-4 overflow-x-auto pb-5" aria-label="Property sales pipeline board">{data.stages.map(s=><DealColumn key={s.id} stage={s} deals={deals.filter(d=>d.stageId===s.id)} allStages={data.stages} onDragStart={setDragged} onDrop={drop} pending={pending}/>)}</div></div>}
