import type { HTMLAttributes, ReactNode } from "react";
import { AlertCircle, AlertTriangle, CheckCircle2, CircleDashed, Info, Inbox, LoaderCircle } from "lucide-react";
export function Badge({ children, tone = "neutral", className = "" }: { readonly children: ReactNode; readonly tone?: "neutral" | "info" | "success" | "warning" | "danger"; readonly className?: string }) { const tones = { neutral: "border-vds-border text-[var(--vds-color-muted)]", info: "border-vds-info text-[var(--vds-color-info)]", success: "border-vds-success text-[var(--vds-color-success)]", warning: "border-vds-warning text-[var(--vds-color-warning)]", danger: "border-vds-danger text-[var(--vds-color-danger)]" }; return <span className={`inline-flex rounded-full border bg-vds-surface/[.035] px-2.5 py-1 text-xs ${tones[tone]} ${className}`}>{children}</span> }
export function Avatar({ initials, label, size = "md" }: { readonly initials: string; readonly label: string; readonly size?: "sm" | "md" | "lg" }) { const sizes = { sm: "size-8 text-xs", md: "size-10 text-sm", lg: "size-14 text-base" }; return <span role="img" aria-label={label} className={`inline-grid place-items-center rounded-full border border-vds-border bg-gradient-to-br from-vds-primary-soft to-vds-accent-soft font-semibold text-vds-primary ${sizes[size]}`}>{initials.slice(0, 2).toUpperCase()}</span> }
export function Chip({ children, onRemove }: { readonly children: ReactNode; readonly onRemove?: () => void }) { return <span className="inline-flex items-center gap-2 rounded-full border border-vds-border bg-vds-surface/[.04] px-3 py-1.5 text-xs text-[var(--vds-color-muted)]">{children}{onRemove && <button type="button" onClick={onRemove} aria-label="Remove" className="vds-focus rounded-full text-[var(--vds-color-subtle)]">×</button>}</span> }
export const Tag = Chip;
export function Progress({ value, label = "Progress" }: { readonly value: number; readonly label?: string }) { const safe = Math.min(100, Math.max(0, value)); return <div><div className="mb-1 flex justify-between text-xs text-[var(--vds-color-muted)]"><span>{label}</span><span>{safe}%</span></div><div role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={safe} className="h-2 overflow-hidden rounded-full bg-vds-surface/[.06]"><span className="block h-full rounded-full bg-[var(--vds-color-primary)] transition-[width]" style={{ width: `${safe}%` }}/></div></div> }
export function Skeleton({ className = "", ...props }: HTMLAttributes<HTMLDivElement>) { return <div aria-hidden="true" className={`skeleton rounded-xl ${className}`} {...props}/> }
function State({ icon, title, description, action, role }: { icon: ReactNode; title: string; description: string; action?: ReactNode; role?: "alert" | "status" }) { return <div role={role} className="rounded-2xl border border-dashed border-[var(--vds-color-border)] bg-vds-surface/[.02] p-8 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-vds-primary-soft text-[var(--vds-color-primary)] [&_svg]:size-5">{icon}</span><h3 className="mt-4 text-base font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--vds-color-muted)]">{description}</p>{action && <div className="mt-5 flex flex-wrap justify-center gap-2">{action}</div>}</div> }
export function EmptyState({ title = "Nothing here yet", description, action }: { readonly title?: string; readonly description: string; readonly action?: ReactNode }) { return <State icon={<Inbox className="size-5"/>} title={title} description={description} action={action}/> }
export function ErrorState({ title = "Something went wrong", description, action }: { readonly title?: string; readonly description: string; readonly action?: ReactNode }) { return <State role="alert" icon={<AlertTriangle className="size-5 text-[var(--vds-color-danger)]"/>} title={title} description={description} action={action}/> }
export function LoadingState({ label = "Loading" }: { readonly label?: string }) { return <State role="status" icon={<LoaderCircle className="vds-loading-motion size-5"/>} title={label} description="Please wait while this view becomes available."/> }
export function Toast({ title, description, tone = "info" }: { readonly title: string; readonly description?: string; readonly tone?: "info" | "success" | "warning" | "danger" | "loading" }) { const config = { info: { Icon: Info, color: "text-vds-info", border: "border-vds-info" }, success: { Icon: CheckCircle2, color: "text-vds-success", border: "border-vds-success" }, warning: { Icon: AlertTriangle, color: "text-vds-warning", border: "border-vds-warning" }, danger: { Icon: AlertCircle, color: "text-vds-danger", border: "border-vds-danger" }, loading: { Icon: LoaderCircle, color: "text-vds-primary", border: "border-vds-accent-border" } } as const, { Icon, color, border } = config[tone]; return <div role={tone === "danger" ? "alert" : "status"} aria-live={tone === "danger" ? "assertive" : "polite"} className={`vds-surface vds-raised flex max-w-sm gap-3 rounded-2xl border p-4 ${border}`}><Icon className={`mt-0.5 size-4 shrink-0 ${color} ${tone === "loading" ? "vds-loading-motion" : ""}`} aria-hidden="true"/><div><p className="text-sm font-medium">{title}</p>{description && <p className="mt-1 text-xs text-vds-muted">{description}</p>}</div></div> }
export function StatusDot({ label, active = false }: { readonly label: string; readonly active?: boolean }) { return <span className="inline-flex items-center gap-2 text-xs text-[var(--vds-color-muted)]"><CircleDashed className={`size-4 ${active ? "text-[var(--vds-color-success)]" : "text-[var(--vds-color-subtle)]"}`}/>{label}</span> }
