import type{IntegrationHealthResult,IntegrationProvider}from"./contracts";import{InactiveIntegrationProvider}from"./contracts";
export class ConfiguredIntegrationAdapter extends InactiveIntegrationProvider{constructor(readonly code:string,override readonly authMethod:IntegrationProvider["authMethod"],private readonly variables:readonly string[],override readonly scopes:readonly string[]=[]){super()}override configuration(){return Object.fromEntries(this.variables.map(name=>[name,{required:true,secret:true}]))}override async health():Promise<IntegrationHealthResult>{const configured=this.variables.length>0&&this.variables.every(name=>Boolean(process.env[name]));return configured?{status:"degraded",details:{reason:"Credentials are configured but have not been validated by a live provider request.",connectionTestRequired:true}}:super.health()}}
export class OpenAIIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("openai","api_key",["OPENAI_API_KEY"])}override configuration(){return{OPENAI_API_KEY:{required:true,secret:true},OPENAI_MODEL:{required:false,secret:false}}}}
export class StripeIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("stripe","api_key",["STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET"])}}
export class GmailIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("gmail","oauth2",[],["gmail.readonly"])}}
export class GoogleCalendarIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("google_calendar","oauth2",[],["calendar.readonly"])}}
export class WhatsAppIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("whatsapp_business","webhook_secret",["WHATSAPP_ACCESS_TOKEN","WHATSAPP_WEBHOOK_VERIFY_TOKEN"])}}
export class MapsIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("google_maps","api_key",["GOOGLE_MAPS_API_KEY"])}}
export class StorageIntegrationAdapter extends ConfiguredIntegrationAdapter{constructor(){super("supabase_storage","service_role",["SUPABASE_SERVICE_ROLE_KEY"])}}
