export type ProviderOperation="health"|"connection_test"|"credential_validation"|"incremental_sync"|"full_sync"|"manual_sync"|"scheduled_sync"|"webhook";
export interface IntegrationHealthResult{status:"healthy"|"degraded"|"unavailable";latencyMs?:number;details?:Record<string,unknown>}
export interface ProviderStructuredError{readonly provider:string;readonly operation:ProviderOperation;readonly code:string;readonly category:"authentication"|"authorization"|"rate_limit"|"network"|"timeout"|"configuration"|"provider";readonly retryable:boolean;readonly sanitizedMessage:string}
export interface IntegrationSyncRequest{readonly mode:"incremental"|"full"|"manual"|"scheduled";readonly cursor?:string;readonly signal?:AbortSignal}
export interface IntegrationSyncResult{readonly status:"completed"|"partial"|"failed";readonly cursor?:string;readonly processed:number;readonly conflicts:number;readonly retryable:boolean}
export interface ProviderRateLimiter{acquire(provider:string,operation:ProviderOperation):Promise<{allowed:boolean;retryAfterMs?:number}>}
export interface IntegrationAuditSink{record(input:{provider:string;operation:ProviderOperation;status:string;latencyMs?:number;error?:ProviderStructuredError}):Promise<void>}
export interface IntegrationProvider{readonly code:string;readonly version:string;readonly authMethod:"api_key"|"oauth2"|"service_role"|"webhook_secret"|"none";readonly scopes:readonly string[];health():Promise<IntegrationHealthResult>;testConnection():Promise<IntegrationHealthResult>;validateCredentials():Promise<IntegrationHealthResult>;sync(request:IntegrationSyncRequest):Promise<IntegrationSyncResult>;configuration():Readonly<Record<string,{required:boolean;secret:boolean}>>;validateWebhook?(payload:string,signature:string,timestamp?:string):Promise<boolean>}
export abstract class InactiveIntegrationProvider implements IntegrationProvider{abstract readonly code:string;readonly version="1.0";readonly authMethod:IntegrationProvider["authMethod"]="none";readonly scopes:readonly string[]=[];async health():Promise<IntegrationHealthResult>{return{status:"unavailable",details:{reason:"Provider adapter is disconnected until credentials are configured."}}}async testConnection(){return this.health()}async validateCredentials(){return this.health()}async sync():Promise<IntegrationSyncResult>{return{status:"failed",processed:0,conflicts:0,retryable:false}}configuration(){return{}}}
