import Link from "next/link";
import { forwardRef, type ButtonHTMLAttributes, type ComponentProps } from "react";
export type VdsButtonVariant = "primary" | "secondary" | "outline" | "ghost" | "danger" | "control";
export type VdsButtonSize = "sm" | "md" | "lg";
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { readonly variant?: VdsButtonVariant; readonly size?: VdsButtonSize; readonly fullWidth?: boolean }
const variants: Record<VdsButtonVariant, string> = { primary: "border-transparent bg-[var(--vds-color-primary)] text-vds-on-accent shadow-sm shadow-vds-shadow hover:-translate-y-0.5 hover:brightness-105 active:translate-y-px active:brightness-95", secondary: "border-[var(--vds-color-border)] bg-vds-elevated text-[var(--vds-color-foreground)] hover:border-vds-border-strong hover:bg-vds-hover active:bg-vds-surface", outline: "border-[var(--vds-color-border-strong)] bg-transparent text-[var(--vds-color-foreground)] hover:border-[var(--vds-color-primary)] hover:bg-vds-primary-soft active:bg-vds-hover", ghost: "border-transparent bg-transparent text-[var(--vds-color-muted)] hover:bg-vds-hover hover:text-[var(--vds-color-foreground)] active:bg-vds-surface", danger: "border-transparent bg-[var(--vds-color-danger)] text-vds-on-accent hover:brightness-105 active:brightness-95", control: "border-transparent bg-transparent text-inherit" };
const sizes: Record<VdsButtonSize, string> = { sm: "h-11 px-3 text-xs", md: "h-11 px-4 text-sm", lg: "h-12 px-6 text-base" };
export function buttonClassName(variant: VdsButtonVariant = "primary", size: VdsButtonSize = "md", fullWidth = false, className = "") { const foundation = variant === "control" ? "vds-focus transition duration-200 disabled:pointer-events-none disabled:opacity-50" : `vds-focus inline-flex items-center justify-center gap-2 rounded-xl border font-semibold leading-none transition duration-200 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:size-4 [&_svg]:shrink-0 ${sizes[size]}`; return `${foundation} ${variants[variant]} ${fullWidth ? "w-full" : ""} ${className}`; }
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button({ variant = "primary", size = "md", fullWidth, className = "", type = "button", ...props }, ref) { return <button ref={ref} type={type} className={buttonClassName(variant,size,fullWidth,className)} {...props}/> });
export interface ButtonLinkProps extends Omit<ComponentProps<typeof Link>, "className"> { readonly variant?: Exclude<VdsButtonVariant,"control">; readonly size?: VdsButtonSize; readonly fullWidth?: boolean; readonly className?: string }
export function ButtonLink({ variant="primary",size="md",fullWidth=false,className="",...props }:ButtonLinkProps){return <Link className={buttonClassName(variant,size,fullWidth,className)} {...props}/>}
export interface IconButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { readonly "aria-label": string; readonly size?: VdsButtonSize }
export const IconButton = forwardRef<HTMLButtonElement, IconButtonProps>(function IconButton({ size = "md", className = "", type = "button", ...props }, ref) { return <button ref={ref} type={type} className={`vds-focus inline-grid aspect-square place-items-center rounded-xl border border-[var(--vds-color-border)] bg-vds-surface/[.035] text-[var(--vds-color-muted)] transition duration-200 hover:border-vds-border-strong hover:bg-vds-hover hover:text-[var(--vds-color-foreground)] disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:size-4 [&_svg]:shrink-0 ${sizes[size].split(" ")[0]} ${className}`} {...props}/> });
