import type { WorkforceEmployee, WorkforceMetric } from "../domain/models";
export const capabilities = [
  "Read CRM",
  "Read Deals",
  "Read Properties",
  "Read Calendar",
  "Generate Summaries",
  "Recommend Actions",
  "Schedule Meetings",
  "Analyze Pipeline",
  "Generate Campaigns",
] as const;
export const definitions = [
  [
    "sales-ai",
    "Sarah",
    "Sales Manager",
    "Persistent and relationship-focused, Sarah qualifies buyers, protects follow-ups and prepares the next best sales action.",
    "SR",
  ],
  [
    "crm-ai",
    "Emma",
    "Property Advisor",
    "A property expert with strong buyer-matching and neighborhood knowledge who keeps customer and property context connected.",
    "EM",
  ],
  [
    "whatsapp-ai",
    "Olivia",
    "Customer Success Manager",
    "Warm, attentive and service-led, Olivia prepares customer answers, retention follow-ups and support priorities.",
    "OL",
  ],
  [
    "voice-ai",
    "Voice AI",
    "Call Advisor",
    "Plans call preparation and follow-up recommendations.",
    "VA",
  ],
  [
    "marketing-ai",
    "Alex",
    "Marketing Director",
    "Creative and growth-focused, Alex turns approved business context into campaign and content recommendations.",
    "AL",
  ],
  [
    "operations-ai",
    "David",
    "Operations Manager",
    "Methodical and dependable, David organizes queues, schedules and operational priorities across the business.",
    "DV",
  ],
  [
    "finance-ai",
    "Finance AI",
    "Finance Advisor",
    "Reviews financial context without executing transactions.",
    "FA",
  ],
  [
    "executive-ai",
    "Executive AI",
    "Executive Advisor",
    "Synthesizes approved workspace evidence into governed executive recommendations.",
    "EA",
  ],
] as const;
const departments = {
  "sales-ai": "Sales",
  "crm-ai": "CRM",
  "whatsapp-ai": "Support",
  "voice-ai": "Support",
  "marketing-ai": "Marketing",
  "operations-ai": "Operations",
  "finance-ai": "Finance",
  "executive-ai": "Executive",
} as const;
export const unavailableMetrics = (): readonly WorkforceMetric[] =>
  [
    "Tasks Today",
    "Success Rate",
    "Average Completion Time",
    "Appointments Booked",
    "Leads Assisted",
    "Revenue Influenced",
  ].map((label) => ({ label, value: "Awaiting data", available: false }));
export function configuredEmployee(
  def: (typeof definitions)[number],
): WorkforceEmployee {
  return {
    id: def[0],
    code: def[0],
    name: def[1],
    role: def[2],
    department: departments[def[0]],
    availability: "unavailable",
    description: def[3],
    avatar: def[4],
    status: "idle",
    capabilities,
    permissions: ["Read-only advisory access"],
    kpis: unavailableMetrics(),
    performance: unavailableMetrics(),
    currentQueue: 0,
    memory: {
      customerContext: "No customer context recorded.",
      recentDecisions: "No decisions recorded.",
      learnedPreferences: "No learned preferences recorded.",
      recentOutcomes: "No outcomes recorded.",
      currentObjectives: "No objectives recorded.",
      conversationCount: 0,
      assignedCustomers: 0,
      pendingTasks: 0,
      completedActions: 0,
      knowledgeReferences: 0,
      contextUtilization: 0,
    },
    recentActivity: [],
    health: "unavailable",
    version: 1,
  };
}
