import Link from "next/link";
import type { StableBillingSnapshot } from "../services/billing-stability.service";
const card = "mt-7 rounded-3xl border border-vds-border bg-vds-surface p-6";
export function BillingRecoveryState({ snapshot }: { snapshot: StableBillingSnapshot }) {
  const subscription = snapshot.dashboard.subscription, status = subscription?.status.toLowerCase() ?? "none", configurationRequired = snapshot.provider.paddle === "not_configured";
  let title = "No Subscription Yet", message = "Choose a plan when you are ready. Your workspace is fully available while billing is inactive.";
  if (configurationRequired) { title = "Billing Ready To Configure"; message = "Billing has not yet been activated. Complete Paddle configuration to enable checkout and the customer portal."; }
  else if (status.includes("trial")) { title = "Trial Active"; message = subscription?.trialEndsAt ? `Your trial continues until ${new Date(subscription.trialEndsAt).toLocaleDateString()}.` : "Your trial is active."; }
  else if (status.includes("past_due") || status.includes("past due")) { title = "Payment Failed"; message = "Update the payment method or retry payment from the secure billing portal."; }
  else if (status.includes("cancel")) { title = "Subscription Cancelled"; message = "Your subscription is cancelled. You can reactivate it from the billing portal when available."; }
  else if (subscription) { title = "Billing Active"; message = `${subscription.planName ?? "Your plan"} is active and billing records are available below.`; }
  return <section className={card} aria-labelledby="billing-state-title"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Billing status</p><h2 id="billing-state-title" className="mt-2 text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-vds-muted">{message}</p></div><span className="rounded-full bg-vds-subtle px-3 py-1 text-xs font-semibold text-vds-muted">{snapshot.provider.environment === "unconfigured" ? "Configuration required" : `${snapshot.provider.environment} mode`}</span></div><div className="mt-5 flex flex-wrap gap-3">{configurationRequired ? <><Link className="vds-focus rounded-xl bg-vds-primary px-4 py-3 text-sm font-semibold text-vds-on-accent" href="/vayon/settings/billing/provider-health">Configure Billing</Link><Link className="vds-focus rounded-xl border border-vds-border px-4 py-3 text-sm" href="/docs">Learn More</Link></> : !subscription ? <Link className="vds-focus rounded-xl bg-vds-primary px-4 py-3 text-sm font-semibold text-vds-on-accent" href="/pricing">Choose Your Plan</Link> : <Link className="vds-focus rounded-xl border border-vds-border px-4 py-3 text-sm" href="/vayon/settings/billing/provider-health">Manage Subscription</Link>}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Health label="Paddle" value={snapshot.provider.paddle === "connected" ? "Paddle Connected" : snapshot.provider.paddle === "not_configured" ? "Paddle Not Configured" : "Paddle Unavailable"}/><Health label="Webhook" value={snapshot.provider.webhook === "healthy" ? "Webhook Healthy" : "Webhook Missing"}/><Health label="Portal" value={snapshot.provider.portal === "available" ? "Portal Available" : "Portal Not Configured"}/></div></section>;
}
function Health({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-vds-border bg-vds-subtle p-4"><p className="text-xs uppercase tracking-wide text-vds-muted">{label}</p><p className="mt-2 text-sm font-medium">{value}</p></article>; }
