import "server-only";
import { founderContext } from "@/features/platform/founder/services/founder-context";
import { FounderAIService } from "@/features/platform/founder-ai/services/founder-ai.service";
import { log } from "@/lib/observability/logger";
import { IntelligenceHubRepository } from "../repositories/intelligence-hub.repository";
import type { AgentProgress, IntelligenceHubSnapshot } from "../types";
export class IntelligenceHubService {
  async snapshot(input: { q?: string; organization?: string; workspace?: string; user?: string; module?: string; from?: string; to?: string }): Promise<IntelligenceHubSnapshot> { const started = performance.now(), { client, user } = await founderContext(), repository = new IntelligenceHubRepository(client); const [executive, search, notifications, timeline] = await Promise.all([new FounderAIService().snapshot(), repository.search(input.q ?? ""), repository.notifications(), repository.timeline(input)]), agents: AgentProgress[] = [["Founder AI", "Executive orchestration", "/platform/founder/ai"], ["Marketing AI", "Campaign recommendations", "/platform/founder/marketing"], ["Sales AI", "Pipeline and lead recommendations", "/platform/founder/sales"], ["Customer Success AI", "Health and retention recommendations", "/platform/founder/customer-success"], ["Creative AI", "Governed creative generation", "/vayon/creative-studio/assistant"], ["Knowledge AI", "Trusted knowledge retrieval", "/vayon/knowledge/help"], ["AI Workforce", "Multi-agent recommendation runtime", "/vayon/ai/collaboration"]].map(([agent, capability, href]) => ({ agent: agent!, capability: capability!, status: "idle" as const, evidence: "Ready to receive a governed recommendation task; progress and results remain in the existing runtime.", href: href! })); log("founder.intelligence_hub.viewed", { actorId: user.id, searchResults: search.length, notifications: notifications.length, timelineEvents: timeline.length, latencyMs: Math.round(performance.now() - started) }); return { executive, search, notifications, timeline, agents, reports: ["Daily Business Report", "Weekly Executive Report", "Monthly Board Report", "Quarterly Investor Report", "Annual Company Report"].map((label) => ({ id: label.toLowerCase().replaceAll(" ", "-"), label, formats: ["PDF", "PowerPoint"] as const })), generatedAt: new Date().toISOString() }; }
}
