export type WorkflowStatus = "draft" | "published" | "archived";
export type WorkflowNodeKind = "trigger" | "condition" | "decision" | "delay" | "approval" | "branch" | "loop" | "notification" | "email" | "calendar" | "task" | "communication" | "crm" | "webhook" | "document" | "variable" | "math" | "formatter" | "ai" | "plugin" | "end";
export type TriggerKind = "organization.created"|"organization.user_invited"|"billing.trial_started"|"billing.trial_ending"|"billing.subscription_renewed"|"billing.subscription_expired"|"lead.created"|"lead.qualified"|"lead.updated"|"deal.created"|"deal.stage_changed"|"deal.won"|"site_visit.completed"|"billing.invoice_paid"|"support.ticket_opened"|"campaign.published"|"ai.task_completed"|"contact.created"|"property.created"|"email.received"|"gmail.received"|"whatsapp.received"|"meeting.scheduled"|"billing.payment_succeeded"|"billing.payment_failed"|"billing.subscription_cancelled"|"organization.user_joined"|"organization.role_changed"|"ai.recommendation_generated"|"ai.collaboration_completed"|"ai.executive_alert"|"time.scheduled"|"time.recurring"|"time.reminder"|"time.delay"|"manual"|"webhook";
export type ActionKind = "crm.task.recommend"|"task.create"|"owner.assign"|"notification.create"|"whatsapp.queue"|"sms.queue"|"ai.task.create"|"crm.record.update"|"meeting.schedule"|"report.generate"|"provider.call"|"reminder.create"|"gmail.draft"|"whatsapp.draft"|"meeting.recommend"|"ai.recommend"|"ai.request"|"user.notify"|"email.queue"|"approval.request"|"timeline.update"|"timeline.propose"|"executive.report";
export type ConditionKind="field"|"date_time"|"organization"|"user"|"role"|"tags"|"pipeline_stage"|"ai_confidence"|"business_health"|"subscription_plan"|"custom_variable";
export type VariableScope = "lead" | "deal" | "company" | "contact" | "meeting" | "task" | "campaign" | "property" | "user" | "workspace" | "current-date" | "math" | "string" | "boolean" | "list";

export interface WorkflowPosition { readonly x: number; readonly y: number }
export interface WorkflowNode { readonly id: string; readonly kind: WorkflowNodeKind; readonly label: string; readonly position: WorkflowPosition; readonly configuration: Readonly<Record<string, unknown>>; readonly variableReferences: readonly string[]; readonly groupId?: string }
export interface WorkflowConnection { readonly id: string; readonly sourceNodeId: string; readonly targetNodeId: string; readonly sourcePort?: string; readonly targetPort?: string; readonly label?: string }
export interface WorkflowVariable { readonly id: string; readonly name: string; readonly scope: VariableScope; readonly valueType: "string" | "number" | "boolean" | "date" | "object" | "list"; readonly required: boolean }
export interface WorkflowDefinition { readonly id: string; readonly name: string; readonly description: string; readonly version: number; readonly status: WorkflowStatus; readonly organizationId?: string; readonly workspaceId?: string; readonly nodes: readonly WorkflowNode[]; readonly connections: readonly WorkflowConnection[]; readonly variables: readonly WorkflowVariable[]; readonly createdAt?: string; readonly updatedAt?: string }
export interface WorkflowTemplate { readonly id: string; readonly name: string; readonly description: string; readonly category: string; readonly industryVisibility: readonly import("@/features/platform/visibility/domain").PlatformIndustry[]; readonly roleVisibility: readonly import("@/features/platform/visibility/domain").VisibilityRole[]; readonly definition: WorkflowDefinition }
export interface NodeRegistration { readonly kind: WorkflowNodeKind; readonly label: string; readonly category: "control" | "business" | "integration" | "data" | "intelligence" | "extension"; readonly executable: false }
export interface WorkflowValidationIssue { readonly code: "disconnected_node" | "circular_loop" | "invalid_reference" | "missing_variable" | "duplicate_id" | "missing_trigger"; readonly severity: "error" | "warning"; readonly message: string; readonly subjectId?: string }
export interface WorkflowValidationResult { readonly valid: boolean; readonly issues: readonly WorkflowValidationIssue[] }
export interface PlannedStep { readonly order: number; readonly nodeId: string; readonly kind: WorkflowNodeKind; readonly dependencies: readonly string[]; readonly executable: false }
export interface ExecutionPlan { readonly workflowId: string; readonly workflowVersion: number; readonly valid: boolean; readonly steps: readonly PlannedStep[]; readonly issues: readonly WorkflowValidationIssue[]; readonly mode: "planning-only"; readonly executable: false }
