import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { LeadListQuery,LeadMutationInput,LeadPage,LeadRecord } from "../types";
type Row=Record<string,unknown>;
function map(r:Row):LeadRecord { const evidence=Array.isArray(r.intelligence_evidence)?r.intelligence_evidence as {signal:string;weight:number}[]:[];return{id:String(r.id),organizationId:String(r.organization_id),workspaceId:String(r.workspace_id),contactId:String(r.id),name:String(r.name),phone:String(r.phone),email:r.email?String(r.email):undefined,whatsapp:r.whatsapp?String(r.whatsapp):undefined,preferredLanguage:r.preferred_language?String(r.preferred_language):undefined,source:String(r.source),status:String(r.status),priority:String(r.priority),assignedEmployeeId:r.assigned_agent_id?String(r.assigned_agent_id):undefined,budget:r.budget===null?undefined:{maximum:{amount:Number(r.budget),currency:String(r.currency)}},budgetAmount:r.budget===null?undefined:{amount:Number(r.budget),currency:String(r.currency)},buyingPurpose:r.buying_purpose?String(r.buying_purpose):undefined,propertyType:r.property_type?String(r.property_type):undefined,preferredLocations:Array.isArray(r.preferred_locations)?r.preferred_locations.map(String):[],bedrooms:r.bedrooms===null?undefined:Number(r.bedrooms),timeline:r.timeline?String(r.timeline):undefined,financing:r.financing?String(r.financing):undefined,propertyInterestIds:[],interestedPropertyNames:[],tagIds:[],tags:Array.isArray(r.tags)?r.tags.map(String):[],score:r.lead_score===null?0:Number(r.lead_score),temperature:r.temperature?String(r.temperature):undefined,interestLevel:r.interest_level?String(r.interest_level):"cold",pipelineStage:r.pipeline_stage?String(r.pipeline_stage):"new",nextRecommendedAction:r.next_recommended_action?String(r.next_recommended_action):"Qualify requirements",followUpDueAt:r.follow_up_due_at?String(r.follow_up_due_at):undefined,intelligenceReason:r.intelligence_reason?String(r.intelligence_reason):"More qualification evidence is required.",intelligenceRecommendation:r.intelligence_recommendation?String(r.intelligence_recommendation):"Capture budget, location, and purchase timeline.",intelligenceConfidence:r.intelligence_confidence===null?0:Number(r.intelligence_confidence),intelligenceEvidence:evidence,intelligenceUpdatedAt:r.intelligence_updated_at?String(r.intelligence_updated_at):String(r.updated_at),doNotContact:Boolean(r.do_not_contact),expectedClosing:r.expected_closing?String(r.expected_closing):undefined,lastActivityAt:r.last_activity_at?String(r.last_activity_at):undefined,aiQualified:r.ai_qualified===true,createdAt:String(r.created_at),createdBy:String(r.created_by),updatedAt:String(r.updated_at),updatedBy:String(r.updated_by),version:Number(r.version),archivedAt:r.deleted_at?String(r.deleted_at):undefined,deletedAt:r.deleted_at?String(r.deleted_at):undefined}}
export class LeadRepository { constructor(private client:SupabaseClient,private organizationId:string,private workspaceId:string){}
  async list(q:LeadListQuery):Promise<LeadPage>{let request=this.client.from("leads").select("*",{count:"exact"}).eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).is("deleted_at",null);if(q.search)request=request.or(`name.ilike.%${q.search}%,email.ilike.%${q.search}%,phone.ilike.%${q.search}%`);if(q.status)request=request.eq("status",q.status);if(q.priority)request=request.eq("priority",q.priority);if(q.source)request=request.eq("source",q.source);if(q.assignedAgentId)request=request.eq("assigned_agent_id",q.assignedAgentId);const from=(q.page-1)*q.pageSize,{data,error,count}=await request.order(q.sort,{ascending:q.direction==="asc"}).range(from,from+q.pageSize-1);if(error)throw error;return{items:(data as Row[]).map(map),count:count??0,page:q.page,pageSize:q.pageSize}}
  async detail(id:string){const{data,error}=await this.client.from("leads").select("*").eq("id",id).eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).is("deleted_at",null).maybeSingle();if(error)throw error;if(!data)return null;const lead=map(data as Row),[{data:interests,error:interestError},{data:tags,error:tagError}]=await Promise.all([this.client.from("lead_property_interests").select("property_id,properties(title)").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).eq("lead_id",id),this.client.from("lead_tags").select("tag").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).eq("lead_id",id)]);if(interestError)throw interestError;if(tagError)throw tagError;const rows=(interests??[])as unknown as Array<{property_id:string;properties:{title:string}|null}>;return{...lead,propertyInterestIds:rows.map(r=>r.property_id),interestedPropertyNames:rows.map(r=>r.properties?.title??"Property").filter(Boolean),tags:((tags??[])as Array<{tag:string}>).map(r=>r.tag)}}
  async create(input:LeadMutationInput){const{data,error}=await this.client.rpc("create_lead",{p_workspace_id:this.workspaceId,p_input:input});if(error)throw error;return String(data)}
  async update(id:string,version:number,input:LeadMutationInput){const{error}=await this.client.rpc("update_lead",{p_lead_id:id,p_expected_version:version,p_input:input});if(error)throw error}
  async assign(ids:readonly string[],agentId:string){const{error}=await this.client.rpc("assign_leads",{p_workspace_id:this.workspaceId,p_lead_ids:ids,p_agent_id:agentId});if(error)throw error}
  async changeStatus(ids:readonly string[],status:string){const{error}=await this.client.rpc("change_lead_status",{p_workspace_id:this.workspaceId,p_lead_ids:ids,p_status:status});if(error)throw error}
  async archive(ids:readonly string[]){const{error}=await this.client.rpc("archive_leads",{p_workspace_id:this.workspaceId,p_lead_ids:ids});if(error)throw error}
}
