import Link from "next/link";
import {
  Activity,
  ArrowUpRight,
  Building2,
  Gauge,
  History,
  Layers3,
  ShieldCheck,
  Sparkles,
  Users,
} from "lucide-react";
import { Button } from "@/features/platform/design-system";
import { FounderRealtime } from "@/features/platform/founder/components/FounderRealtime";
import type { TenantManagementSnapshot, TenantRecord } from "../services/tenant-management.service";

const card = "rounded-3xl border border-vds-border/70 bg-vds-surface/75 shadow-xl shadow-vds-shadow/10 backdrop-blur-xl";
const unavailable = "Unavailable — no authoritative tenant measurement";

export function TenantManagementCenter({ data, query, lifecycle }: { data: TenantManagementSnapshot; query: string; lifecycle: string }) {
  const tenants = data.tenants.filter((item) => (!query || `${item.name} ${item.plan} ${item.lifecycle}`.toLowerCase().includes(query.toLowerCase())) && (!lifecycle || item.lifecycle === lifecycle));
  return <main className="relative mx-auto max-w-[120rem] space-y-8 overflow-hidden px-4 py-6 sm:px-6 lg:px-8">
    <div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[36rem] bg-[radial-gradient(circle_at_15%_8%,var(--vds-color-primary-soft),transparent_36%),radial-gradient(circle_at_86%_12%,var(--vds-color-info-soft),transparent_28%)]" aria-hidden="true" />
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.22em] text-vds-primary"><Building2 className="size-4" aria-hidden="true"/>Founder Portal</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Enterprise Tenant Management</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-vds-muted sm:text-base">Govern every VAYON organization, subscription, health signal, lifecycle, and SaaS operation from authoritative platform evidence.</p></div><FounderRealtime/></header>
    <section aria-labelledby="saas-observability"><Heading id="saas-observability" icon={Gauge} title="SaaS observability"/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{data.observability.map((item)=><article className={`${card} p-4`} key={item.id}><p className="text-[10px] uppercase tracking-[.16em] text-vds-subtle">{item.label}</p><p className="mt-3 text-xl font-semibold">{item.value === null ? "—" : item.value.toLocaleString()}</p><p className="mt-1 text-xs text-vds-muted">{item.value === null ? "Unavailable" : item.unit}</p></article>)}</div></section>
    <section aria-labelledby="tenant-directory"><div className="flex flex-wrap items-end justify-between gap-3"><Heading id="tenant-directory" icon={Users} title="Founder tenant center"/><form className="flex flex-wrap gap-2" role="search"><input className="h-11 rounded-xl border border-vds-border bg-vds-input px-3 text-sm" name="query" defaultValue={query} placeholder="Search organizations" aria-label="Search organizations"/><select className="h-11 rounded-xl border border-vds-border bg-vds-input px-3 text-sm" name="lifecycle" defaultValue={lifecycle} aria-label="Filter lifecycle"><option value="">All lifecycle states</option>{data.lifecycle.map((state)=><option key={state} value={state}>{label(state)}</option>)}</select><Button variant="primary" className="h-11 rounded-xl px-4 text-sm font-medium">Filter</Button></form></div><div className="mt-4 overflow-x-auto rounded-3xl border border-vds-border/70"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-vds-elevated text-xs uppercase tracking-wide text-vds-subtle"><tr>{["Organization","Subscription","Users","Usage","Integrations","Health","Last activity"].map((value)=><th className="px-4 py-3" key={value}>{value}</th>)}</tr></thead><tbody>{tenants.map((tenant)=><TenantRow key={tenant.id} tenant={tenant}/>)}</tbody></table>{!tenants.length&&<p className="p-8 text-center text-sm text-vds-muted">No tenants match this view.</p>}</div></section>
    <div className="grid gap-6 xl:grid-cols-2"><section aria-labelledby="usage"><Heading id="usage" icon={Activity} title="Usage analytics"/><div className={`${card} mt-4 p-5`}><p className="text-sm text-vds-muted">AI, active-user, API, storage, workflow, knowledge, marketing, sales, customer-success, and creative usage are presented per tenant. Missing authoritative meters remain unavailable.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.tenants.slice(0,6).map((tenant)=><div className="rounded-2xl bg-vds-elevated p-4" key={tenant.id}><p className="font-medium">{tenant.name}</p><p className="mt-2 text-xs text-vds-muted">AI {tenant.usage.aiTokens?.toLocaleString() ?? unavailable} · Active users {tenant.usage.activeUsers}</p><p className="mt-1 text-xs text-vds-subtle">Storage: {tenant.usage.storageBytes === null ? unavailable : tenant.usage.storageBytes.toLocaleString()}</p></div>)}</div></div></section><section aria-labelledby="provisioning"><Heading id="provisioning" icon={Layers3} title="Provisioning engine"/><div className={`${card} mt-4 divide-y divide-vds-border/70 p-5`}>{data.provisioning.map((item)=><div className="grid gap-1 py-3 sm:grid-cols-[1fr_1fr_auto]" key={item.capability}><p className="font-medium">{item.capability}</p><p className="text-sm text-vds-muted">{item.owner}</p><span className="text-xs text-vds-primary">{item.mode}</span></div>)}</div></section></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section aria-labelledby="audit"><Heading id="audit" icon={History} title="Audit center"/><div className={`${card} mt-4 divide-y divide-vds-border/70 p-5`}>{data.audit.slice(0,12).map((item)=><div className="flex items-center justify-between gap-4 py-3" key={item.id}><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs capitalize text-vds-muted">{item.category}</p></div><time className="text-xs text-vds-subtle" dateTime={item.occurredAt}>{new Date(item.occurredAt).toLocaleString()}</time></div>)}{!data.audit.length&&<p className="text-sm text-vds-muted">No authorized audit activity is available.</p>}</div></section><section aria-labelledby="operations"><Heading id="operations" icon={ShieldCheck} title="Founder operations"/><div className={`${card} mt-4 grid gap-3 p-5`}>{data.operations.map((item)=><Link className="flex min-h-12 items-center justify-between rounded-xl border border-vds-border px-4 py-3 text-sm hover:border-vds-accent-border" href={item.href} key={item.label}><span><span className="font-medium">{item.label}</span><span className="ml-2 text-xs text-vds-muted">{item.confirmationRequired ? "Confirmation required" : "Read only"}</span></span><ArrowUpRight className="size-4" aria-hidden="true"/></Link>)}</div></section></div>
    <p className="flex items-center gap-2 text-xs text-vds-subtle"><Sparkles className="size-4" aria-hidden="true"/>Generated from Founder, Customer Growth, Customer Directory, billing, RBAC, onboarding, and audit evidence at <time dateTime={data.generatedAt}>{new Date(data.generatedAt).toLocaleString()}</time>.</p>
  </main>;
}

function TenantRow({ tenant }: { tenant: TenantRecord }) { return <tr className="border-t border-vds-border/70 align-top"><td className="px-4 py-4"><Link className="font-medium text-vds-primary" href={`/platform/customers/${tenant.id}`}>{tenant.name}</Link><p className="mt-1 text-xs capitalize text-vds-muted">{label(tenant.lifecycle)} · {tenant.workspaces} workspace(s)</p></td><td className="px-4 py-4"><p>{tenant.plan}</p><p className="mt-1 text-xs text-vds-muted">{tenant.billingStatus} · {tenant.renewalDate ? new Date(tenant.renewalDate).toLocaleDateString() : "Renewal unavailable"}</p></td><td className="px-4 py-4">{tenant.users}</td><td className="px-4 py-4"><p>AI {tenant.usage.aiTokens?.toLocaleString() ?? "—"}</p><p className="mt-1 text-xs text-vds-muted">Storage {tenant.usage.storageBytes === null ? "Unavailable" : tenant.usage.storageBytes.toLocaleString()}</p></td><td className="px-4 py-4">{tenant.integrations ?? "Unavailable"}</td><td className="px-4 py-4"><p>{tenant.health}/100 · {tenant.healthClass}</p><p className="mt-1 text-xs text-vds-muted">{Math.round(tenant.healthConfidence * 100)}% confidence · {tenant.supportLoad} support</p></td><td className="px-4 py-4 text-xs">{tenant.lastActivity ? new Date(tenant.lastActivity).toLocaleString() : "Unavailable"}</td></tr>; }
function Heading({ id, icon: Icon, title }: { id: string; icon: typeof Building2; title: string }) { return <div className="flex items-center gap-2"><Icon className="size-5 text-vds-primary" aria-hidden="true"/><h2 className="text-lg font-semibold" id={id}>{title}</h2></div>; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
