import { Button } from "@/features/platform/design-system";
import type { OrganizationSnapshot } from "../types";
import { updateOrganizationAction } from "../actions/organization.actions";
export { EnterpriseMembersManagement as MembersManagement, EnterpriseRolesView as RolesView } from "./RoleManagementUI";
const card="rounded-3xl border border-vds-border bg-vds-surface p-5";
const input="mt-2 h-11 w-full rounded-xl border border-vds-border bg-vds-input px-3 text-sm";
export function OrganizationHeader({title,description}:{title:string;description:string}){return <header><p className="text-xs font-semibold uppercase tracking-[.22em] text-vds-primary">Enterprise organization</p><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 max-w-3xl text-sm text-vds-muted">{description}</p></header>}
export function OrganizationSettingsForm({snapshot}:{snapshot:OrganizationSnapshot}){const item=snapshot.profile,weekday=item.businessHours.monday??{open:"09:00",close:"18:00"};return <form action={updateOrganizationAction} className={`${card} mt-7 grid gap-4 md:grid-cols-2`} encType="multipart/form-data"><label>Company name<input className={input} name="name" defaultValue={item.name} required/></label><label>Business email<input className={input} type="email" name="businessEmail" defaultValue={item.businessEmail??""} required/></label><label>Phone<input className={input} name="phone" defaultValue={item.phone??""}/></label><label>Website<input className={input} type="url" name="website" defaultValue={item.website??""}/></label><label>Timezone<input className={input} name="timezone" defaultValue={item.timezone} required/></label><label>Locale<input className={input} name="locale" defaultValue={item.locale} required/></label><label>Currency<input className={input} name="currency" defaultValue={item.currency} maxLength={3} required/></label><label>Country<input className={input} name="country" defaultValue={item.address.country??""} maxLength={2} required/></label><label>Business opens<input className={input} type="time" name="businessOpen" defaultValue={weekday.open} required/></label><label>Business closes<input className={input} type="time" name="businessClose" defaultValue={weekday.close} required/></label><label>Date format<select className={input} name="dateFormat" defaultValue={item.regionalSettings.dateFormat??"DD/MM/YYYY"}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label>Week starts<select className={input} name="weekStart" defaultValue={item.regionalSettings.weekStart??"Monday"}><option>Monday</option><option>Sunday</option></select></label><label>Address line 1<input className={input} name="line1" defaultValue={item.address.line1??""}/></label><label>Address line 2<input className={input} name="line2" defaultValue={item.address.line2??""}/></label><label>City<input className={input} name="city" defaultValue={item.address.city??""}/></label><label>Region<input className={input} name="region" defaultValue={item.address.region??""}/></label><label>Postal code<input className={input} name="postalCode" defaultValue={item.address.postalCode??""}/></label><label>Primary color<input className={input} name="primary" defaultValue={item.branding.primary??""} placeholder="Hex color"/></label><label>Accent color<input className={input} name="accent" defaultValue={item.branding.accent??""} placeholder="Hex color"/></label><label>Company logo<input className={input} type="file" name="logo" accept="image/png,image/jpeg,image/webp"/></label><div className="md:col-span-2"><Button disabled={!snapshot.canManage}>Save organization</Button></div></form>}
export function ActivityLog({snapshot}:{snapshot:OrganizationSnapshot}){return <div className={`${card} mt-7`}><div className="space-y-3">{snapshot.activity.map(event=><article className="border-t border-vds-border pt-3" key={event.id}><div className="flex justify-between gap-4"><p className="font-medium capitalize">{event.eventType.replaceAll("."," ")}</p><time className="text-xs text-vds-muted">{new Date(event.occurredAt).toLocaleString()}</time></div><p className="mt-1 text-xs text-vds-muted">Actor {event.actorId.slice(0,8)} · Subject {event.subjectId?.slice(0,8)??"organization"}</p></article>)}{!snapshot.activity.length&&<p className="text-sm text-vds-muted">No organization activity recorded.</p>}</div></div>}
