import Link from "next/link";
import { Activity, Bot, BriefcaseBusiness, ChartNoAxesCombined, HeartPulse, Lightbulb, ShieldCheck, Sparkles, Target } from "lucide-react";
import { Button } from "@/features/platform/design-system";
import { FounderRealtime } from "@/features/platform/founder/components/FounderRealtime";
import { FounderReportExports } from "@/features/platform/founder/components/FounderReportExports";
import { LazyFounderCharts } from "@/features/platform/founder/components/LazyFounderCharts";
import type { FounderKpi } from "@/features/platform/founder/types";
import type { OpenAIHealth } from "@/features/platform/openai/domain/models";
import { WorkforceChatPanel } from "@/features/platform/openai/runtime/ChatPanel";
import type { ConversationSnapshot } from "@/features/platform/openai/runtime/models";
import type { FounderAISnapshot } from "../types";

const card = "rounded-3xl border border-vds-border/70 bg-vds-surface/70 shadow-xl shadow-vds-shadow/10 backdrop-blur-xl";
export function FounderAIHome({ data, history, health, question, greeting }: { data: FounderAISnapshot; history: ConversationSnapshot; health: OpenAIHealth; question: string; greeting: string }) {
  const brief = data.morningBrief;
  return <main className="relative mx-auto max-w-[120rem] space-y-8 overflow-hidden px-4 py-6 sm:px-6 lg:px-8"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[38rem] bg-[radial-gradient(circle_at_15%_8%,var(--vds-color-primary-soft),transparent_36%),radial-gradient(circle_at_82%_12%,var(--vds-color-info-soft),transparent_30%)]" aria-hidden="true"/><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.22em] text-vds-primary"><Sparkles className="size-4" aria-hidden="true"/>Founder Portal · Executive CEO Copilot</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">{greeting}</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-vds-muted sm:text-base">{data.summary}</p></div><div className="flex flex-col items-end gap-2"><FounderRealtime/><Link className="text-xs text-vds-primary" href="/platform/founder">← Founder Operating System</Link></div></header>
    <section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><article className={`${card} p-5 sm:p-7`}><div className="flex items-center gap-2"><BriefcaseBusiness className="size-5 text-vds-primary" aria-hidden="true"/><h2 className="text-lg font-semibold">Executive summary</h2></div><p className="mt-4 text-base leading-7 text-vds-muted">{data.summary}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Snapshot label="Revenue" item={brief.revenue}/><Snapshot label="Marketing" item={data.marketing.kpis.find((item) => item.id === "roi") ?? null}/><Snapshot label="Sales forecast" item={brief.pipelineForecast}/><Snapshot label="Customer health" item={data.customerSuccess.kpis.find((item) => item.id === "health") ?? null}/></div></article><article className={`${card} p-5 sm:p-7`}><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.14em] text-vds-subtle">Business Health Score</p><p className="mt-3 text-5xl font-semibold">{data.healthScore ?? "—"}<span className="text-lg text-vds-muted">/100</span></p></div><HeartPulse className="size-10 text-vds-primary" aria-hidden="true"/></div><div className="mt-5 space-y-3">{data.healthSignals.map((signal) => <div key={signal.name}><div className="flex justify-between text-xs"><span>{signal.name} · {Math.round(signal.weight * 100)}%</span><span>{signal.score === null ? "Unavailable" : Math.round(signal.score)}</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-vds-elevated"><span className="block h-full rounded-full bg-vds-primary" style={{ width: `${signal.score ?? 0}%` }}/></div><p className="sr-only">{signal.reason}</p></div>)}</div><details className="mt-4 text-xs"><summary className="cursor-pointer text-vds-primary">How this score is derived</summary><ul className="mt-2 space-y-1 text-vds-muted">{data.healthSignals.map((signal) => <li key={signal.name}>• {signal.name}: {signal.reason}</li>)}</ul></details></article></section>
    <section><Heading icon={Target} title="Today's priorities"/><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.priorities.map((item, index) => <article className={`${card} p-5 motion-safe:animate-[fade-in_.45s_ease-out_both]`} style={{ animationDelay: `${index * 45}ms` }} key={item.id}><div className="flex justify-between gap-3"><h3 className="font-medium">{item.title}</h3><span className="text-[10px] uppercase text-vds-primary">{item.impact}</span></div><p className="mt-3 text-sm text-vds-muted">{item.evidence}</p><div className="mt-4 flex justify-between text-xs"><span>Impact {item.expectedImpact.toFixed(0)}</span><span>{Math.round(item.confidence * 100)}% confidence</span></div><p className="mt-3 text-[10px] uppercase tracking-[.13em] text-vds-subtle">Recommendation only</p></article>)}</div></section>
    <section><Heading icon={Activity} title="Morning brief"/><div className={`${card} mt-4 grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-6`}>{[["Revenue",brief.revenue],["MRR",brief.mrr],["ARR",brief.arr],["New organizations",brief.newOrganizations],["New users",brief.newUsers],["Trials started",brief.trialsStarted],["Trials converted",brief.trialsConverted],["Renewals due",brief.renewalsDue],["Renewals completed",brief.renewalsCompleted],["Pipeline forecast",brief.pipelineForecast],["Upcoming tasks",brief.upcomingTasks]].map(([label,item]) => <Snapshot label={label as string} item={item as FounderKpi | null} key={label as string}/>) }<Snapshot label="Churn risks" value={brief.churnRisks}/><Snapshot label="Top campaign" value={brief.topCampaign}/><Snapshot label="Support" value={brief.supportSummary}/><Snapshot label="Platform alerts" value={brief.platformAlerts}/><Snapshot label="System health" value={`${brief.systemHealth.filter((item) => item.state === "healthy").length}/${brief.systemHealth.length} healthy`}/></div></section>
    <section><Heading icon={ChartNoAxesCombined} title="Revenue, growth, product, and platform trends"/><div className="mt-4"><LazyFounderCharts charts={data.founder.charts}/></div></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className={`${card} p-5`}><Heading icon={Lightbulb} title="Cross-module insights"/><div className="mt-4 space-y-4">{data.correlations.map((item) => <div className="rounded-2xl border border-vds-border bg-vds-elevated/50 p-4" key={item.id}><p className="text-sm font-medium">{item.statement}</p><p className="mt-2 text-xs leading-5 text-vds-muted">{item.evidence}</p><p className="mt-2 text-[10px] uppercase tracking-[.12em] text-vds-subtle">Observed correlation · no causation claimed · {Math.round(item.confidence * 100)}% confidence</p></div>)}</div></article><article className={`${card} p-5`}><Heading icon={ShieldCheck} title="Product and platform health"/><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.founder.health.map((item) => <div className="rounded-2xl border border-vds-border bg-vds-elevated/50 p-4" key={item.name}><div className="flex justify-between gap-3"><p className="text-sm font-medium">{item.name}</p><span className={`size-2 rounded-full ${item.state === "healthy" ? "bg-vds-success" : item.state === "degraded" ? "bg-vds-danger" : "bg-vds-subtle"}`} aria-label={item.state}/></div><p className="mt-2 text-xs text-vds-muted">{item.value}</p></div>)}</div></article></section>
    <section><Heading icon={Bot} title="Executive chat"/><div className={`${card} my-4 p-5`}><form method="get"><label className="text-sm font-medium" htmlFor="founder-question">Ask Founder AI about performance, priorities, customers, conversions, risks, MRR, campaigns, AI employees, or board preparation</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input className="h-11 flex-1 rounded-xl border border-vds-border bg-vds-input px-3 text-sm" id="founder-question" name="question" defaultValue={question} maxLength={1000} placeholder="What should I focus on today?"/><Button type="submit">Prepare executive context</Button></div></form><div className="mt-3 flex flex-wrap gap-2">{["How is the business performing?","Which customers need attention?","Show me our biggest risks.","How can we increase MRR?","Prepare a board meeting summary."].map((prompt) => <Link className="rounded-full border border-vds-border px-3 py-1.5 text-xs text-vds-muted hover:text-vds-primary" href={`?question=${encodeURIComponent(prompt)}`} key={prompt}>{prompt}</Link>)}</div></div><WorkforceChatPanel employee="executive-ai" initial={history} health={health} initialPrompt={question ? `Act as Founder AI, the recommendation-only CEO Copilot. Answer using authoritative VAYON evidence across revenue, marketing, sales, customer success, product, platform, billing, support, growth, and AI workforce: ${question}. Include supporting evidence where available, distinguish measured facts from recommendations and observed correlations, state unavailable data, never overstate causation, and do not execute actions.` : ""}/></section>
    <section><Heading icon={BriefcaseBusiness} title="Board reports"/><div className="mt-4"><FounderReportExports title="Founder AI" generatedAt={data.generatedAt} kpis={data.reportKpis} reports={data.reports}/></div></section>
  </main>;
}
function Snapshot({ label, item, value }: { label: string; item?: FounderKpi | null; value?: string | number }) { const display = value ?? (item?.value === null || item?.value === undefined ? "Unavailable" : `${item.unit === "currency" ? "$" : ""}${item.value.toLocaleString(undefined, { maximumFractionDigits: 2 })}${item.unit === "percent" ? "%" : ""}`); return <div><p className="text-[10px] uppercase tracking-[.12em] text-vds-subtle">{label}</p><p className="mt-2 text-sm font-semibold">{display}</p></div>; }
function Heading({ icon: Icon, title }: { icon: typeof Sparkles; title: string }) { return <div className="flex items-center gap-2"><Icon className="size-4 text-vds-primary" aria-hidden="true"/><h2 className="text-lg font-semibold">{title}</h2></div>; }
