import type { AiDepartment, ApprovalStage, StudioContract } from "./types";
export const approvalLifecycle: readonly ApprovalStage[] = [
  "Draft",
  "Internal Review",
  "Brand Review",
  "Legal Review",
  "Marketing Approval",
  "Founder Approval",
  "Published",
];
const studio = (
  id: StudioContract["id"],
  name: string,
  purpose: string,
  route: string | null,
  implementation: StudioContract["implementation"],
  assets: readonly string[],
  providers: StudioContract["providerRequirements"],
): StudioContract => ({
  id,
  name,
  purpose,
  route,
  implementation,
  inputs: [
    "Unified creative prompt",
    "Workspace context",
    "Project context",
    "Campaign context",
    "Brand defaults",
  ],
  outputs: [
    "Planned creative artifacts",
    "Metadata",
    "Review evidence",
    "Approval request",
  ],
  supportedAssets: assets,
  pipelineDependencies: [
    "Creative Pipeline Engine",
    "Ordered dependencies",
    "Review gates",
  ],
  brandDependencies: [
    "Default brand",
    "Colour system",
    "Typography",
    "Tone",
    "Legal disclaimers",
  ],
  approvalFlow: approvalLifecycle,
  permissionRequirements: [
    "creative_studio.view",
    "creative_studio.create",
    "creative_studio.approve",
    "creative_studio.export",
  ],
  exportFormats: ["Provider-dependent", "Editable Project"],
  providerRequirements: providers,
});
export const creativeCloudStudios: readonly StudioContract[] = [
  studio(
    "brand",
    "Brand Studio",
    "Define permanent organization identity.",
    "/vayon/creative/brand",
    "available",
    ["Brand", "Logo", "Guidelines"],
    ["create_logos", "vector"],
  ),
  studio(
    "campaign",
    "Campaign Studio",
    "Plan complete multi-channel campaigns.",
    "/vayon/creative/campaigns",
    "available",
    ["Campaign", "Brief", "Blueprint"],
    [],
  ),
  studio(
    "image",
    "Image Studio",
    "Plan, edit, inspect, and organize visuals.",
    "/vayon/creative/images",
    "available",
    ["Image", "Mockup", "Illustration"],
    ["generate_images", "edit_images"],
  ),
  studio(
    "video",
    "Video Studio",
    "Plan motion, voice, music, and video production.",
    "/vayon/creative/videos",
    "available",
    ["Video", "Storyboard", "Audio"],
    ["generate_video"],
  ),
  studio(
    "document",
    "Document Studio",
    "Assemble governed business documents.",
    null,
    "foundation",
    ["Document", "PDF", "DOCX"],
    [],
  ),
  studio(
    "presentation",
    "Presentation Studio",
    "Create narrative presentation systems.",
    null,
    "architecture",
    ["Presentation", "Chart", "Speaker Notes"],
    [],
  ),
  studio(
    "website",
    "Website Studio",
    "Plan accessible, performant web experiences.",
    null,
    "architecture",
    ["Website", "Landing Page", "Component"],
    [],
  ),
  studio(
    "social",
    "Social Studio",
    "Coordinate channel-native social campaigns.",
    null,
    "architecture",
    ["Social Post", "Calendar", "Community Brief"],
    [],
  ),
  studio(
    "email",
    "Email Studio",
    "Plan consent-aware lifecycle communications.",
    null,
    "architecture",
    ["Email", "Sequence", "Newsletter"],
    [],
  ),
  studio(
    "advertising",
    "Advertising Studio",
    "Plan governed paid-media packages.",
    null,
    "architecture",
    ["Advertisement", "Audience", "Creative Set"],
    [],
  ),
  studio(
    "templates",
    "Template Marketplace",
    "Distribute reusable creative systems.",
    "/vayon/creative-studio/templates",
    "available",
    ["Template", "Template Version"],
    [],
  ),
  studio(
    "assets",
    "Asset Library",
    "Manage creative assets and lineage.",
    "/vayon/creative-studio/assets",
    "available",
    ["Asset", "Collection", "Folder"],
    [],
  ),
  studio(
    "runtime",
    "Creative Runtime",
    "Route capabilities through future adapters.",
    "/vayon/creative/runtime",
    "available",
    ["Job", "Provider Output"],
    [],
  ),
  studio(
    "pipelines",
    "Creative Pipelines",
    "Orchestrate ordered production stages.",
    "/vayon/creative/pipelines",
    "available",
    ["Pipeline", "Node", "Document Plan"],
    [],
  ),
  studio(
    "director",
    "Creative Director",
    "Coordinate every department and approval.",
    "/vayon/creative/campaigns",
    "foundation",
    ["Objective", "Task", "Blueprint"],
    [],
  ),
];
const department = (
  id: string,
  name: string,
  parentId: string | null,
  studioId: AiDepartment["studioId"],
  specialists: readonly string[],
): AiDepartment => ({
  id,
  name,
  parentId,
  studioId,
  specialists,
  execution: "orchestrated_only",
});
export const creativeDepartments: readonly AiDepartment[] = [
  department("creative-director", "Creative Director", null, "director", []),
  department("brand-director", "Brand Director", "creative-director", "brand", [
    "Brand Strategist",
    "Logo Designer",
    "Identity Designer",
    "Typography Specialist",
    "Colour Specialist",
    "Brand Reviewer",
  ]),
  department("image-director", "Image Director", "creative-director", "image", [
    "Photographer",
    "Product Photographer",
    "Architectural Photographer",
    "Food Photographer",
    "Interior Designer",
    "Fashion Photographer",
    "Retoucher",
    "Image Editor",
    "Background Specialist",
    "Mockup Specialist",
  ]),
  department("video-director", "Video Director", "creative-director", "video", [
    "Script Writer",
    "Storyboard Artist",
    "Voice Artist",
    "Motion Designer",
    "Video Editor",
    "Subtitle Specialist",
    "Music Producer",
    "Animation Specialist",
  ]),
  department(
    "document-director",
    "Document Director",
    "creative-director",
    "document",
    [
      "Copywriter",
      "Technical Writer",
      "Layout Designer",
      "Graphic Designer",
      "Brand Reviewer",
      "Publisher",
    ],
  ),
  department(
    "presentation-director",
    "Presentation Director",
    "creative-director",
    "presentation",
    [
      "Presentation Designer",
      "Chart Designer",
      "Data Visualizer",
      "Speaker Notes Writer",
      "Animation Specialist",
    ],
  ),
  department(
    "website-director",
    "Website Director",
    "creative-director",
    "website",
    [
      "UX Designer",
      "UI Designer",
      "Frontend Designer",
      "SEO Specialist",
      "Accessibility Specialist",
      "Performance Specialist",
    ],
  ),
  department(
    "social-director",
    "Social Director",
    "creative-director",
    "social",
    [
      "Instagram Specialist",
      "Facebook Specialist",
      "LinkedIn Specialist",
      "TikTok Specialist",
      "YouTube Specialist",
      "Community Manager",
    ],
  ),
  department(
    "advertising-director",
    "Advertising Director",
    "creative-director",
    "advertising",
    [
      "Google Ads Specialist",
      "Meta Ads Specialist",
      "LinkedIn Ads Specialist",
      "YouTube Ads Specialist",
      "Campaign Optimizer",
    ],
  ),
  department(
    "publishing-director",
    "Publishing Director",
    "creative-director",
    "assets",
    ["Publisher", "Approval Coordinator", "Asset Librarian"],
  ),
];
