import"server-only";import Stripe from"stripe";import type{BillingProvider,BillingProviderChangeInput,BillingProviderCheckoutInput,BillingProviderPortalInput}from"./billing-provider";
const supportedEvents=new Set(["checkout.session.completed","customer.subscription.created","customer.subscription.updated","customer.subscription.deleted","invoice.paid","invoice.payment_failed","invoice.finalized","customer.subscription.trial_will_end","payment_method.attached","payment_method.detached","customer.updated"]);
export class StripeWebhookSignatureError extends Error{constructor(){super("Stripe webhook signature verification failed.");this.name="StripeWebhookSignatureError"}}
function stripe(){const key=process.env.STRIPE_SECRET_KEY;if(!key)throw new Error("STRIPE_SECRET_KEY is required.");return new Stripe(key,{maxNetworkRetries:2,timeout:30000})}
function configuredPrice(planCode:string){const price=process.env[`STRIPE_PRICE_${planCode.toUpperCase()}`];if(!price)throw new Error(`Stripe price is not configured for ${planCode}.`);return price}
export class StripeBillingProvider implements BillingProvider{readonly id="stripe";
async createCheckout(input:BillingProviderCheckoutInput){const customer=await this.customer(input.organizationId),session=await stripe().checkout.sessions.create({mode:"subscription",customer,line_items:[{price:configuredPrice(input.planCode),quantity:input.seatQuantity}],success_url:input.successUrl,cancel_url:input.cancelUrl,allow_promotion_codes:true,automatic_tax:{enabled:true},tax_id_collection:{enabled:true},customer_update:{address:"auto",name:"auto"},client_reference_id:input.organizationId,subscription_data:{trial_period_days:Number(process.env.STRIPE_TRIAL_DAYS??14),metadata:{organization_id:input.organizationId,workspace_id:input.workspaceId,plan_code:input.planCode}},metadata:{organization_id:input.organizationId,workspace_id:input.workspaceId,plan_code:input.planCode}});if(!session.url)throw new Error("Stripe did not return a Checkout URL.");return{url:session.url}}
async createCustomerPortal(input:BillingProviderPortalInput){const customer=await this.customer(input.organizationId),session=await stripe().billingPortal.sessions.create({customer,return_url:input.returnUrl});return{url:session.url}}
async changeSubscription(input:BillingProviderChangeInput){const subscription=await stripe().subscriptions.retrieve(input.subscriptionId);const item=subscription.items.data[0];if(!item)throw new Error("Stripe subscription has no billable item.");await stripe().subscriptions.update(input.subscriptionId,{items:[{id:item.id,price:input.priceId,quantity:input.quantity}],metadata:{...subscription.metadata,plan_code:input.planCode},proration_behavior:input.prorationBehavior})}
async cancelSubscription(subscriptionId:string){await stripe().subscriptions.update(subscriptionId,{cancel_at_period_end:true})}
async reactivateSubscription(subscriptionId:string){await stripe().subscriptions.update(subscriptionId,{cancel_at_period_end:false})}
async recordUsage(customerId:string,metric:string,quantity:number,idempotencyKey:string){if(!Number.isFinite(quantity)||quantity<=0)throw new Error("Usage quantity must be positive.");await stripe().billing.meterEvents.create({event_name:`vayon_${metric}`,identifier:idempotencyKey,payload:{stripe_customer_id:customerId,value:String(quantity)}})}
async verifyWebhook(payload:string,signature:string){const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)throw new Error("STRIPE_WEBHOOK_SECRET is required.");try{const event=stripe().webhooks.constructEvent(payload,signature,secret);return{eventId:event.id,type:supportedEvents.has(event.type)?event.type:event.type,data:event.data.object}}catch{throw new StripeWebhookSignatureError()}}
private async customer(organizationId:string){const list=await stripe().customers.search({query:`metadata['organization_id']:'${organizationId}'`,limit:1});if(list.data[0])return list.data[0].id;return(await stripe().customers.create({metadata:{organization_id:organizationId}})).id}}
