import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { log } from "@/lib/observability/logger";
import type { CompanyInput,CompanyPage,CompanyProfile,CompanyRecord,CompanyRelatedItem,ContactRecord,SalespersonOption } from "./domain";
type Row=Record<string,unknown>;
const value=(v:unknown)=>v==null?"":String(v);
type RepositoryError={code?:string;message?:string;details?:string};
const optionalCrmReadCodes=new Set(["42P01","PGRST205"]);
export function isUnavailableCrmRelation(error:unknown){const e=error as RepositoryError|null;if(!e)return false;const message=`${e.message??""} ${e.details??""}`.toLowerCase();return optionalCrmReadCodes.has(e.code??"")||(message.includes("schema cache")&&message.includes("crm_"))||(message.includes("relation")&&message.includes("crm_")&&message.includes("does not exist"))}
export class CrmCompanyRepository {
  constructor(private client:SupabaseClient,private organizationId:string,private workspaceId:string){}
  private scoped(table:string){return this.client.from(table).select("*").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId)}
  private map(row:Row,owners:ReadonlyMap<string,string>):CompanyRecord{return{id:value(row.id),name:value(row.name),logoPath:value(row.logo_path)||undefined,industry:value(row.industry)||undefined,website:value(row.website)||undefined,email:value(row.email)||undefined,phone:value(row.phone)||undefined,employees:row.employees==null?undefined:Number(row.employees),revenue:row.revenue==null?undefined:Number(row.revenue),currency:value(row.currency)||"USD",address:value(row.address)||undefined,country:value(row.country)||undefined,ownerId:value(row.owner_id)||undefined,ownerName:owners.get(value(row.owner_id))??"Unassigned",notes:value(row.notes)||undefined,createdAt:value(row.created_at),updatedAt:value(row.updated_at),version:Number(row.version)}}
  async list(search:string|undefined,page:number,pageSize:number):Promise<CompanyPage>{let q=this.client.from("crm_companies").select("*",{count:"exact"}).eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).is("deleted_at",null);if(search)q=q.or(`name.ilike.%${search}%,industry.ilike.%${search}%,email.ilike.%${search}%`);const from=(page-1)*pageSize,{data,error,count}=await q.order("updated_at",{ascending:false}).range(from,from+pageSize-1);if(error){if(this.recoverUnavailableRelation("crm_companies",error))return{items:[],count:0,page,pageSize};throw error}const rows=(data??[])as Row[],owners=await this.ownerNames(rows.map(r=>value(r.owner_id)).filter(Boolean));return{items:rows.map(r=>this.map(r,owners)),count:count??rows.length,page,pageSize}}
  async detail(id:string):Promise<CompanyProfile|null>{const{data,error}=await this.scoped("crm_companies").eq("id",id).is("deleted_at",null).maybeSingle();if(error)throw error;if(!data)return null;const row=data as Row,owners=await this.ownerNames([value(row.owner_id)]),related=await Promise.all([this.related("crm_contacts",id,"name","relationship"),this.related("leads",id,"name","status"),this.related("properties",id,"title","status"),this.related("deals",id,"name","stage_id"),this.client.from("activity_events").select("id,title,event_type,occurred_at").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).eq("related_type","company").eq("related_id",id).order("occurred_at",{ascending:false}).limit(50)]);if(related[4].error)throw related[4].error;const activities=((related[4].data??[])as Row[]).map(r=>({id:value(r.id),title:value(r.title),status:value(r.event_type),meta:value(r.occurred_at)})),contacts=related[0] as CompanyRelatedItem[],leads=related[1] as CompanyRelatedItem[],properties=related[2] as CompanyRelatedItem[],deals=related[3] as CompanyRelatedItem[],revenue=deals.filter(item=>item.status==="completed"||item.status==="won").reduce((sum,item)=>sum+Number(item.meta??0),0),won=deals.filter(item=>item.status==="completed"||item.status==="won"),lost=deals.filter(item=>item.status==="lost"||item.status==="cancelled"),active=deals.filter(item=>!["completed","won","lost","cancelled"].includes(item.status)),created=new Date(value(row.created_at)).getTime(),velocity=won.length?Math.max(0,Math.round((Date.now()-created)/86400000)):0;return{company:this.map(row,owners),contacts,leads,properties,deals,activities,revenue,metrics:{totalLeads:leads.length,activeDeals:active.length,wonDeals:won.length,lostDeals:lost.length,propertiesSold:properties.filter(item=>item.status==="sold").length,averageDealSize:won.length?revenue/won.length:0,salesVelocityDays:velocity,conversion:deals.length?won.length/deals.length*100:0,assignedAgents:value(row.owner_id)?1:0}}}
  async salespeople():Promise<readonly SalespersonOption[]>{const{data,error}=await this.client.from("workspace_members").select("user_id,roles(code)").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).eq("status","active");if(error)throw error;const members=(data??[])as unknown as Array<{user_id:string;roles:{code:string}|null}>,ids=members.map(r=>r.user_id),{data:profiles,error:profileError}=ids.length?await this.client.from("user_profiles").select("user_id,name,email,department").in("user_id",ids):{data:[],error:null};if(profileError)throw profileError;const map=new Map(((profiles??[])as Row[]).map(r=>[value(r.user_id),r]));return members.map(r=>{const p=map.get(r.user_id);return{id:r.user_id,name:value(p?.name)||value(p?.email)||"Team member",email:value(p?.email),role:r.roles?.code??"member",team:value(p?.department)||"Sales"}})}
  async contacts(search?:string):Promise<readonly ContactRecord[]>{let q=this.scoped("crm_contacts").is("deleted_at",null);if(search)q=q.or(`name.ilike.%${search}%,email.ilike.%${search}%,phone.ilike.%${search}%`);const{data,error}=await q.order("updated_at",{ascending:false}).limit(100);if(error){if(this.recoverUnavailableRelation("crm_contacts",error))return[];throw error}const rows=(data??[])as Row[],companyIds=rows.map(r=>value(r.company_id)).filter(Boolean),ownerIds=rows.map(r=>value(r.owner_id)).filter(Boolean),[owners,companies]=await Promise.all([this.ownerNames(ownerIds),this.companyNames(companyIds)]);return rows.map(r=>({id:value(r.id),leadId:value(r.lead_id)||undefined,name:value(r.name),email:value(r.email)||undefined,phone:value(r.phone)||undefined,companyName:companies.get(value(r.company_id))??"No primary company",position:value(r.position)||undefined,department:value(r.department)||undefined,relationship:value(r.relationship)||"Contact",ownerName:owners.get(value(r.owner_id))??"Unassigned",updatedAt:value(r.updated_at)}))}
  async contact(id:string):Promise<ContactRecord|null>{const{data,error}=await this.scoped("crm_contacts").eq("id",id).is("deleted_at",null).maybeSingle();if(error)throw error;if(!data)return null;const row=data as Row,[owners,companies]=await Promise.all([this.ownerNames([value(row.owner_id)]),this.companyNames([value(row.company_id)])]);return{id:value(row.id),leadId:value(row.lead_id)||undefined,name:value(row.name),email:value(row.email)||undefined,phone:value(row.phone)||undefined,companyName:companies.get(value(row.company_id))??"No primary company",position:value(row.position)||undefined,department:value(row.department)||undefined,relationship:value(row.relationship)||"Contact",ownerName:owners.get(value(row.owner_id))??"Unassigned",updatedAt:value(row.updated_at)}}
  create(input:CompanyInput){return this.client.rpc("create_crm_company",{p_workspace_id:this.workspaceId,p_input:input})}
  update(id:string,version:number,input:CompanyInput){return this.client.rpc("update_crm_company",{p_company_id:id,p_expected_version:version,p_input:input})}
  archive(id:string,version:number){return this.client.rpc("archive_crm_company",{p_company_id:id,p_expected_version:version})}
  private async ownerNames(ids:readonly string[]){if(!ids.length)return new Map<string,string>();const{data}=await this.client.from("user_profiles").select("user_id,name,email").in("user_id",[...new Set(ids)]);return new Map(((data??[])as Row[]).map(r=>[value(r.user_id),value(r.name)||value(r.email)]))}
  private async companyNames(ids:readonly string[]){if(!ids.length)return new Map<string,string>();const{data,error}=await this.client.from("crm_companies").select("id,name").eq("organization_id",this.organizationId).eq("workspace_id",this.workspaceId).in("id",[...new Set(ids)]);if(error){if(this.recoverUnavailableRelation("crm_companies",error))return new Map<string,string>();throw error}return new Map(((data??[])as Row[]).map(r=>[value(r.id),value(r.name)]))}
  private recoverUnavailableRelation(table:"crm_companies"|"crm_contacts",error:unknown){if(!isUnavailableCrmRelation(error))return false;const e=error as RepositoryError;log("crm.optional_relation.unavailable",{organizationId:this.organizationId,workspaceId:this.workspaceId,table,code:e.code??"unknown"});return true}
  private async related(table:string,id:string,title:string,status:string){const{data,error}=await this.scoped(table).eq("company_id",id).is("deleted_at",null);if(error)throw error;return((data??[])as Row[]).map(r=>({id:value(r.id),title:value(r[title]),status:value(r[status])||"recorded",meta:table==="deals"?value(r.value):undefined}))}
}
