import type { AIEmployeeCode } from "@/features/platform/openai/domain/models";

export type CollaborationScenario = "lead-created" | "deal-at-risk" | "new-customer" | "custom";
export type CollaborationStatus = "active" | "completed" | "error";
export type ApprovalStatus = "pending" | "approved" | "rejected";
export interface CollaborationMemory { readonly customer: readonly Record<string, unknown>[]; readonly leads: readonly Record<string, unknown>[]; readonly deals: readonly Record<string, unknown>[]; readonly properties: readonly Record<string, unknown>[]; readonly communications: readonly Record<string, unknown>[]; readonly meetings: readonly Record<string, unknown>[]; readonly organization: Record<string, unknown> | null; readonly recommendations: readonly Record<string, unknown>[]; readonly executiveSummaries: readonly Record<string, unknown>[]; }
export interface CollaborationEvent { readonly id: string; readonly runId: string; readonly agent: AIEmployeeCode; readonly summary: string; readonly occurredAt: string; }
export interface RecommendationNode { readonly id: string; readonly runId: string; readonly employee: AIEmployeeCode; readonly requestedRecommendation: string; readonly provider: string; readonly confidence: number | null; readonly approvalStatus: ApprovalStatus; readonly relatedCustomer: string | null; readonly createdAt: string; readonly promptTokens: number; readonly completionTokens: number; readonly latencyMs: number | null; readonly estimatedCost: number; readonly model: string | null; }
export interface CollaborationRun { readonly id: string; readonly scenario: CollaborationScenario; readonly requestedBy: AIEmployeeCode; readonly status: CollaborationStatus; readonly createdAt: string; }
export interface CollaborationDashboard { readonly activeCollaborations: number; readonly topContributors: readonly { agent: AIEmployeeCode; requests: number }[]; readonly departmentCollaboration: readonly { department: string; requests: number }[]; readonly recommendationPipeline: readonly RecommendationNode[]; readonly pendingApprovals: number; readonly timeline: readonly CollaborationEvent[]; readonly observability: { readonly requestCount: number; readonly promptTokens: number; readonly completionTokens: number; readonly averageLatencyMs: number | null; readonly estimatedCost: number; readonly models: readonly string[]; readonly averageConfidence: number | null; }; }
export interface CollaborationRequest { readonly requestedBy: AIEmployeeCode; readonly scenario: CollaborationScenario; readonly objective: string; readonly relatedCustomerId?: string; readonly agents?: readonly AIEmployeeCode[]; }
