"use server";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { EnterpriseOrganizationService } from "../services/organization.service";
import { departmentSchema, idSchema, invitationSchema, profileSchema, roleSchema, teamSchema, transferSchema } from "../validation";
const value=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const refresh=()=>{revalidatePath("/vayon/settings/organization");revalidatePath("/vayon/settings/members");revalidatePath("/vayon/settings/roles");revalidatePath("/vayon/settings/activity");revalidatePath("/vayon/settings/departments");revalidatePath("/vayon/settings/teams")};
function failure(reason:unknown):never{redirect(`/vayon/settings/members?error=${encodeURIComponent(reason instanceof Error?reason.message:String(reason))}`)}
async function origin(){const requestHeaders=await headers();return requestHeaders.get("origin")??process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000"}
export async function updateOrganizationAction(form:FormData){const open=value(form,"businessOpen"),close=value(form,"businessClose"),parsed=profileSchema.safeParse({name:value(form,"name"),businessEmail:value(form,"businessEmail"),phone:value(form,"phone"),website:value(form,"website"),timezone:value(form,"timezone"),locale:value(form,"locale"),currency:value(form,"currency").toUpperCase(),address:{line1:value(form,"line1"),line2:value(form,"line2"),city:value(form,"city"),region:value(form,"region"),postalCode:value(form,"postalCode"),country:value(form,"country").toUpperCase()},branding:{primary:value(form,"primary"),accent:value(form,"accent")},businessHours:Object.fromEntries(["monday","tuesday","wednesday","thursday","friday"].map(day=>[day,{open,close}])),regionalSettings:{dateFormat:value(form,"dateFormat"),weekStart:value(form,"weekStart")}});if(!parsed.success)redirect(`/vayon/settings/organization?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid organization")}`);await new EnterpriseOrganizationService().updateProfile(parsed.data);const logo=form.get("logo");if(logo instanceof File&&logo.size)await new EnterpriseOrganizationService().uploadLogo(logo);refresh();redirect("/vayon/settings/organization?success=Organization%20updated")}
export async function inviteMemberAction(form:FormData){const parsed=invitationSchema.safeParse({name:value(form,"name"),email:value(form,"email"),role:value(form,"role")});if(!parsed.success)failure(parsed.error.issues[0]?.message);let error:unknown;try{await new EnterpriseOrganizationService().invite(parsed.data,await origin());refresh()}catch(reason){error=reason}if(error)failure(error);redirect("/vayon/settings/members?success=Invitation%20sent")}
export async function invitationAction(form:FormData){const id=idSchema.safeParse(value(form,"invitationId")),intent=value(form,"intent");if(!id.success||!["resend","cancel"].includes(intent))failure("Invalid invitation request.");let error:unknown;try{const service=new EnterpriseOrganizationService();if(intent==="resend")await service.resend(id.data,await origin());else await service.cancelInvitation(id.data);refresh()}catch(reason){error=reason}if(error)failure(error);redirect(`/vayon/settings/members?success=Invitation%20${intent}ed`)}
export async function memberAction(form:FormData){const id=idSchema.safeParse(value(form,"memberId")),intent=value(form,"intent");if(!id.success)failure("Invalid member.");let error:unknown;try{const service=new EnterpriseOrganizationService();if(intent==="suspend")await service.setMemberStatus(id.data,"suspended");else if(intent==="reactivate")await service.setMemberStatus(id.data,"active");else if(intent==="remove")await service.removeMember(id.data);else if(intent==="role"){const role=roleSchema.parse(value(form,"role"));await service.changeRole(id.data,role)}else throw new Error("Invalid member action.");refresh()}catch(reason){error=reason}if(error)failure(error);redirect("/vayon/settings/members?success=Member%20updated")}
export async function transferOwnershipAction(form:FormData){const parsed=transferSchema.safeParse({memberId:value(form,"memberId"),confirmation:value(form,"confirmation")});if(!parsed.success)failure("Type TRANSFER to confirm ownership transfer.");let error:unknown;try{await new EnterpriseOrganizationService().transferOwnership(parsed.data.memberId,parsed.data.confirmation);refresh()}catch(reason){error=reason}if(error)failure(error);redirect("/vayon/settings/members?success=Ownership%20transferred")}
export async function acceptInvitationAction(){let error:unknown;try{await new EnterpriseOrganizationService().acceptInvitation();refresh()}catch(reason){error=reason}if(error)redirect(`/accept-invitation?error=${encodeURIComponent(error instanceof Error?error.message:String(error))}`);redirect("/vayon?invitation=accepted")}
export async function departmentAction(form:FormData){const intent=value(form,"intent")as"create"|"update"|"archive",id=value(form,"departmentId")||null,parsed=departmentSchema.safeParse({name:value(form,"name"),managerMemberId:value(form,"managerMemberId"),kpis:value(form,"kpis").split(",").map(item=>item.trim()).filter(Boolean),permissions:value(form,"permissions").split(",").map(item=>item.trim()).filter(Boolean)});if(!["create","update","archive"].includes(intent)||(intent!=="create"&&!idSchema.safeParse(id).success)||(intent!=="archive"&&!parsed.success))redirect("/vayon/settings/departments?error=Invalid%20department");await new EnterpriseOrganizationService().manageDepartment(intent,id,parsed.success?parsed.data:{});refresh();redirect("/vayon/settings/departments?success=Department%20updated")}
export async function teamAction(form:FormData){const intent=value(form,"intent")as"create"|"update"|"archive",id=value(form,"teamId")||null,parsed=teamSchema.safeParse({name:value(form,"name"),departmentId:value(form,"departmentId"),managerMemberId:value(form,"managerMemberId"),capacity:value(form,"capacity"),memberIds:form.getAll("memberIds").map(String)});if(!["create","update","archive"].includes(intent)||(intent!=="create"&&!idSchema.safeParse(id).success)||(intent!=="archive"&&!parsed.success))redirect("/vayon/settings/teams?error=Invalid%20team");await new EnterpriseOrganizationService().manageTeam(intent,id,parsed.success?parsed.data:{});refresh();redirect("/vayon/settings/teams?success=Team%20updated")}
