import { ButtonLink } from "@/features/platform/design-system";
import { DealBoard, PipelineStatistics } from "@/features/vayon/deal/components/DealBoard";
import { ContextualRealEstateRecommendations } from "@/features/vayon/real-estate-experience/RealEstateSurfaces";
import { transactionStages } from "@/features/vayon/real-estate-experience/catalog";
import { PipelineService } from "@/features/vayon/deal/services/pipeline.service";

export default async function Page() {
  const data = await new PipelineService().board();
  return <main className="mx-auto max-w-[110rem] px-5 py-8"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-vds-primary">Transaction Center</p><h1 className="mt-2 text-3xl font-semibold">Property Sales Pipeline</h1><p className="mt-2 text-sm text-vds-muted">Move buyers and sellers from qualification through viewing, offer, legal verification, registration, and completion.</p></div><ButtonLink href="/vayon/deals/new" className="rounded-full">New transaction</ButtonLink></div><nav aria-label="Transaction stages" className="mt-6 flex snap-x gap-2 overflow-x-auto pb-2">{transactionStages.map((stage) => <span className="shrink-0 snap-start rounded-full border border-vds-border bg-vds-surface px-3 py-2 text-xs" key={stage}>{stage}</span>)}</nav><div className="mt-7"><PipelineStatistics data={data}/></div><div className="mt-7">{!data.deals.length ? <div className="rounded-3xl border border-dashed border-vds-border p-10 text-center"><h2 className="text-xl font-semibold">No Transactions</h2><p className="mt-2 text-sm text-vds-muted">Your transactions will appear here once buyers begin making offers.</p><div className="mt-5 flex flex-wrap justify-center gap-3"><ButtonLink href="/vayon/leads">Review qualified leads</ButtonLink><ButtonLink href="/vayon/properties" variant="secondary">Review properties</ButtonLink></div></div> : <DealBoard data={data} />}</div><ContextualRealEstateRecommendations kind="transaction" /></main>;
}
