-- VERSION1_PRODUCTION_PATCH.sql is a review manifest, not an executable monolith.
-- Execute only the independently reviewed stages in DEPLOYMENT_EXECUTION_ORDER.md.
-- 001_core_schema.sql
-- 002_columns.sql
-- 003_indexes.sql
-- 004_functions.sql
-- 005_rls.sql
-- 006_storage.sql
-- 007_seed.sql
-- 008_validation.sql
-- Parser issue removed: no psql meta-command and no accidental prose.
-- Additive contracts: CREATE TABLE IF NOT EXISTS; ALTER TABLE ... ADD COLUMN IF NOT EXISTS.
-- Catalog reconciliation surfaces: pg_policies, pg_proc, pg_trigger.
