import Link from "next/link";
import type {ReactNode} from "react";
import {Button} from "@/features/platform/design-system";
import {createCreativeDraftAction} from "../actions";
import {audiences,campaignTypes,copyFormats,creativePlatforms,designerFormats,socialFormats,videoFormats,type CreativeSnapshot} from "../domain";
import type {InventoryProject} from "@/features/vayon/property-platform/inventory/domain";
const card="rounded-2xl border border-vds-border bg-vds-surface p-5";
const links=[["Dashboard","/vayon/creative-studio"],["AI Growth Studio","/vayon/creative-studio/growth"],["AI Creative Assistant","/vayon/creative-studio/assistant"],["Campaign Packs","/vayon/creative-studio/packs"],["Campaign Calendar","/vayon/creative-studio/calendar"],["Campaign Wizard","/vayon/creative-studio/wizard"],["Assets","/vayon/creative-studio/assets"],["Brand Kits","/vayon/creative-studio/brand-kits"],["Templates","/vayon/creative-studio/templates"],["Analytics","/vayon/creative-studio/analytics"]]as const;
export function StudioShell({title,description,children}:{title:string;description:string;children:ReactNode}){return <main className="mx-auto max-w-[96rem] px-4 py-7 sm:px-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Marketing Studio</p><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 max-w-3xl text-sm text-vds-muted">{description}</p></div><span className="rounded-full bg-vds-warning-soft px-3 py-1 text-xs font-medium text-vds-warning">Draft only · approval required</span></header><nav aria-label="Marketing Studio" className="my-5 flex gap-1 overflow-x-auto border-y border-vds-border py-3">{links.map(([label,href])=><Link className="vds-focus shrink-0 rounded-lg px-3 py-2 text-sm text-vds-muted hover:bg-vds-hover" href={href} key={href}>{label}</Link>)}</nav>{children}</main>}
export function StudioDashboard({snapshot}:{snapshot:CreativeSnapshot}){return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{snapshot.analytics.map(item=><article className={card} key={item.label}><p className="text-xs text-vds-muted">{item.label}</p><p className={`mt-3 text-xl font-semibold ${item.measured?"":"text-vds-muted"}`}>{item.value}</p></article>)}</section><div className="grid gap-5 lg:grid-cols-2"><section className={card}><div className="flex justify-between"><h2 className="font-semibold">Recent Campaigns</h2><Link href="/vayon/creative-studio/wizard" className="text-sm text-vds-primary">New draft</Link></div><List items={snapshot.campaigns.slice(0,6).map(x=>`${x.name} · ${x.status}`)} empty="No campaigns yet. Start with an authoritative inventory project."/></section><section className={card}><h2 className="font-semibold">Recent Assets</h2><List items={snapshot.assets.slice(0,6).map(x=>`${x.name} · v${x.version} · ${x.status}`)} empty="Generated draft assets will appear here."/></section></div><section className={card}><h2 className="font-semibold">Governance and publishing</h2><p className="mt-3 text-sm text-vds-muted">Every campaign, copy variation, design, social creative and storyboard remains a draft through Marketing Review → Sales Review → Management Approval → Approved → Ready to Publish. Meta, Instagram, Facebook, LinkedIn, WhatsApp, Email, Website and Google Ads adapters remain disabled until an approved production connector is enabled.</p><p className="mt-3 text-xs text-vds-muted">Access: {snapshot.access.source} · Tenant scoped · External rendering disabled</p></section></div>}
export function CampaignWizard({projects,initialObjective=""}:{projects:readonly InventoryProject[];initialObjective?:string}){return <form action={createCreativeDraftAction} className="space-y-5"><WizardStep number="1" title="Choose Project"><select required name="projectId" className="vds-focus h-11 w-full rounded-xl border border-vds-border bg-vds-elevated px-3"><option value="">Select authoritative inventory project</option>{projects.map(x=><option value={x.id} key={x.id}>{x.name} · {x.developer} · {x.city}</option>)}</select><p className="mt-3 text-xs text-vds-muted">Developer, location, live inventory, pricing, offers, amenities, approved images, logo, brand colors, floor plans, contact details and QR references load through existing repositories.</p></WizardStep><WizardStep number="2" title="Campaign Type"><RadioGrid name="campaignType" values={campaignTypes}/></WizardStep><WizardStep number="3" title="Audience"><CheckGrid name="audience" values={audiences}/></WizardStep><WizardStep number="4" title="Platforms"><CheckGrid name="platform" values={creativePlatforms}/></WizardStep><WizardStep number="5" title="AI Draft Package"><div className="grid gap-4 md:grid-cols-2"><input required maxLength={160} name="name" placeholder="Campaign name" className="vds-focus h-11 rounded-xl border border-vds-border bg-vds-elevated px-3"/><input name="language" defaultValue="English" maxLength={40} placeholder="Language" className="vds-focus h-11 rounded-xl border border-vds-border bg-vds-elevated px-3"/><textarea name="objective" defaultValue={initialObjective} maxLength={1000} placeholder="Campaign objective" className="vds-focus min-h-28 rounded-xl border border-vds-border bg-vds-elevated p-3 md:col-span-2"/></div><p className="mt-4 text-sm text-vds-muted">Marketing Manager, Copywriter, Designer, Campaign Manager, Compliance Reviewer, Brand Guardian and Sales Manager prepare three recommendation-only variations. Nothing is sent or published.</p><Button className="mt-5" type="submit">Generate governed draft</Button></WizardStep></form>}
export function CapabilityCatalog(){const sections=[["AI Designer",designerFormats],["AI Social Studio",socialFormats],["AI Video Storyboard Studio · Preview",videoFormats],["AI Copywriter",copyFormats]]as const;return <div className="grid gap-5 lg:grid-cols-2">{sections.map(([title,items])=><section className={card} key={title}><h2 className="font-semibold">{title}</h2><div className="mt-4 flex flex-wrap gap-2">{items.map(item=><span className="rounded-full bg-vds-elevated px-3 py-1.5 text-xs" key={item}>{item}</span>)}</div>{title.includes("Video")&&<p className="mt-4 text-xs text-vds-warning">Preview includes editable storyboard, scene list, script, voiceover, captions and asset references. Video rendering is not connected.</p>}</section>)}</div>}
export function AssetLibrary({snapshot,query=""}:{snapshot:CreativeSnapshot;query?:string}){const term=query.toLowerCase(),items=snapshot.assets.filter(x=>!term||[x.name,x.platform,x.language,x.status,x.format,x.creator].filter(Boolean).some(value=>String(value).toLowerCase().includes(term)));return <><form className="mb-5 flex gap-3"><input name="q" defaultValue={query} aria-label="Search creative assets" placeholder="Search project, campaign, platform, language, status, version or creator" className="vds-focus h-11 flex-1 rounded-xl border border-vds-border bg-vds-elevated px-3"/><Button type="submit">Search</Button></form><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(x=><article className={card} key={x.id}><p className="text-xs text-vds-primary">{x.category} · {x.platform}</p><h2 className="mt-2 font-semibold">{x.name}</h2><p className="mt-3 text-sm text-vds-muted">{x.format} · {x.language} · Version {x.version}</p><p className="mt-2 text-xs capitalize text-vds-warning">{x.status}</p><p className="mt-3 text-xs text-vds-muted">AI: {x.aiEmployee} · Generated {new Date(x.generatedAt).toLocaleString()}</p><p className="mt-2 text-xs text-vds-muted">Exports: PNG · JPEG · PDF · Print-ready PDF · Editable Project placeholder · PowerPoint placeholder</p></article>)}{!items.length&&<Empty text="No creative assets match this view."/>}</div></>}
export function BrandKits({snapshot}:{snapshot:CreativeSnapshot}){return <div className="grid gap-4 md:grid-cols-2">{snapshot.brandKits.map(x=><article className={card} key={x.id}><h2 className="font-semibold">{x.name}</h2><dl className="mt-4 grid gap-3 text-sm"><Row label="Logos" value={[x.logoPath,x.secondaryLogoPath].filter(Boolean).join(" · ")||"Not configured"}/><Row label="Colors" value={x.colors.join(" · ")||"Not configured"}/><Row label="Typography / fonts" value={[...x.typography,...x.fonts].join(" · ")||"Not configured"}/><Row label="Contact" value={[x.phone,x.address,x.website].filter(Boolean).join(" · ")||"Not configured"}/><Row label="Legal / RERA" value={[x.legalDisclaimer,x.reraInformation].filter(Boolean).join(" · ")||"Requires compliance review"}/><Row label="Brand tone" value={x.tone}/></dl></article>)}{!snapshot.brandKits.length&&<Empty text="No dedicated Brand Kit exists. Campaign previews inherit the Organization profile until a kit is approved."/>}</div>}
function WizardStep({number,title,children}:{number:string;title:string;children:ReactNode}){return <section className={card}><p className="text-xs text-vds-primary">Step {number}</p><h2 className="mt-1 text-lg font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
function RadioGrid({name,values}:{name:string;values:readonly string[]}){return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{values.map((x,index)=><label className="flex items-center gap-2 rounded-xl border border-vds-border p-3 text-sm" key={x}><input type="radio" required={index===0} name={name} value={x}/>{x}</label>)}</div>}
function CheckGrid({name,values}:{name:string;values:readonly string[]}){return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{values.map(x=><label className="flex items-center gap-2 rounded-xl border border-vds-border p-3 text-sm" key={x}><input type="checkbox" name={name} value={x}/>{x}</label>)}</div>}
function List({items,empty}:{items:readonly string[];empty:string}){return items.length?<ul className="mt-3 divide-y divide-vds-border text-sm">{items.map(x=><li className="py-3" key={x}>{x}</li>)}</ul>:<p className="mt-6 text-sm text-vds-muted">{empty}</p>}
function Row({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-vds-muted">{label}</dt><dd className="mt-1">{value}</dd></div>}
function Empty({text}:{text:string}){return <div className="col-span-full rounded-2xl border border-dashed border-vds-border p-10 text-center text-sm text-vds-muted">{text}</div>}
