import Link from "next/link";
import type { MarketingAIDashboard } from "../types";

const card = "rounded-2xl border border-vds-border bg-vds-surface p-5";
const unavailable = "Unavailable — property or campaign performance evidence is not connected";
const approvalHref = (intent: string) => `/vayon/approvals?intent=${intent}&source=emma-marketing-manager`;

export function EmmaMarketingManagerDashboard({ data }: { data: MarketingAIDashboard }) {
  const bestSource = data.leadSources.slice().sort((a, b) => b.conversionRate - a.conversionRate)[0];
  const opportunities = data.leadSources.filter((source) => source.highIntent > 0 && source.won < source.highIntent);
  const campaignDrafts = ["Facebook Campaign", "Instagram Campaign", "Google Ads", "WhatsApp Campaign", "Email Campaign", "Referral Campaign", "Open House Campaign", "Luxury Property Campaign", "Rental Campaign"];
  const socialDrafts = ["Instagram Caption", "Facebook Caption", "LinkedIn Post", "X Post", "Property Reel Script", "Video Description", "Hashtag Suggestions", "Call-To-Action"];
  const descriptionDrafts = ["Listing Headline", "Short Description", "Long Description", "Luxury Version", "Investment Version", "Rental Version", "Family Version", "Commercial Version"];
  const brochures = ["Luxury Brochure", "Buyer Brochure", "Seller Brochure", "Investment Summary", "Open House Flyer", "QR Flyer"];
  const prepare = (label: string, group: string) => <Link key={label} className="min-h-11 rounded-xl border border-vds-border px-3 py-3 text-sm focus-ring" href={approvalHref(`prepare_${group}_${label.toLowerCase().replaceAll(/[^a-z0-9]+/g, "_")}`)}>Prepare {label}</Link>;

  return <section className="space-y-5" aria-labelledby="emma-marketing-title">
    <header className={card}><p className="text-xs font-semibold uppercase tracking-[.2em] text-vds-primary">Emma · AI Marketing Manager</p><h2 id="emma-marketing-title" className="mt-2 text-2xl font-semibold">Today&apos;s Marketing Brief</h2><p className="mt-2 text-sm text-vds-muted">Evidence-backed real estate marketing recommendations and approval-ready drafts. Emma never publishes, sends, or changes ad spend.</p></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Campaign Performance", data.campaignHealth.available ? data.campaignHealth.value : "Unavailable", data.campaignHealth.reason], ["Listings Needing Promotion", "Unavailable", unavailable], ["Listings With Low Engagement", "Unavailable", unavailable], ["Best Performing Listings", "Unavailable", unavailable], ["Properties With Zero Enquiries", "Unavailable", unavailable], ["Marketing Opportunities", opportunities.length, `${opportunities.length} lead sources have recorded high intent not yet won`], ["Urgent Marketing Tasks", data.contentCalendar.length, "Existing evidence-backed planning slots"], ["Best Lead Source", bestSource?.source ?? "Unavailable", bestSource ? `${(bestSource.conversionRate * 100).toFixed(1)}% recorded conversion` : "No lead-source evidence"],
    ].map(([label, value, evidence]) => <article className={card} key={label}><p className="text-xs text-vds-muted">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><p className="mt-2 text-xs text-vds-muted">Evidence: {evidence}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card} aria-labelledby="listing-review"><h3 id="listing-review" className="font-semibold">Listing Marketing Review</h3><p className="mt-2 text-sm text-vds-muted">Select a property to evaluate its verified listing content. Scores remain unavailable until the listing repository supplies the evidence.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{["Photo Quality", "Description Quality", "Headline Quality", "Missing Information", "Pricing Presentation", "Feature Completeness", "CTA Quality", "Overall Marketing Score"].map((label) => <div className="rounded-xl bg-vds-elevated p-3" key={label}><dt>{label}</dt><dd className="mt-1 text-xs text-vds-muted">Unavailable · listing evidence required</dd></div>)}</dl><Link className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-vds-border px-3 text-sm focus-ring" href="/vayon/properties">Select a property</Link></section>
      <section className={card} aria-labelledby="photo-advisor"><h3 id="photo-advisor" className="font-semibold">Photo Improvement Advisor</h3><p className="mt-2 text-sm text-vds-muted">Recommendations activate only after verified media metadata is available.</p><ul className="mt-4 grid grid-cols-2 gap-2 text-sm">{["Additional photos", "Better cover image", "Missing room photos", "Exterior photos", "Drone photos", "Virtual Tour", "Video Walkthrough"].map((label) => <li className="rounded-xl bg-vds-elevated p-3" key={label}>{label} · Unavailable</li>)}</ul></section></div>
    <section className={card} aria-labelledby="campaign-assistant"><h3 id="campaign-assistant" className="font-semibold">Campaign Assistant</h3><p className="mt-2 text-sm text-vds-muted">Draft preparation only. Publishing and sending require approval.</p><div className="mt-4 flex flex-wrap gap-2">{campaignDrafts.map((label) => prepare(label, "campaign"))}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card}><h3 className="font-semibold">Social Content</h3><div className="mt-4 flex flex-wrap gap-2">{socialDrafts.map((label) => prepare(label, "social"))}</div></section><section className={card}><h3 className="font-semibold">Property Description Copilot</h3><div className="mt-4 flex flex-wrap gap-2">{descriptionDrafts.map((label) => prepare(label, "description"))}</div></section></div>
    <section className={card} aria-labelledby="marketing-insights"><h3 id="marketing-insights" className="font-semibold">Marketing Insights &amp; Priorities</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><div><h4 className="text-sm font-medium">Today&apos;s Priorities</h4><ul className="mt-2 space-y-2 text-xs text-vds-muted">{data.contentCalendar.slice(0, 3).map((item) => <li key={item.title}>• {item.title} · {item.channel}</li>)}{!data.contentCalendar.length && <li>No evidence-backed priority.</li>}</ul></div><div><h4 className="text-sm font-medium">This Week / This Month</h4><p className="mt-2 text-xs text-vds-muted">Unavailable — campaign schedules and listing promotion dates are not connected.</p></div><div><h4 className="text-sm font-medium">Organic, Paid &amp; Referral</h4><p className="mt-2 text-xs text-vds-muted">{data.roi.reason} Channel attribution remains unavailable.</p></div></div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card}><h3 className="font-semibold">Brochure Preparation</h3><div className="mt-4 flex flex-wrap gap-2">{brochures.map((label) => prepare(label, "brochure"))}</div></section><section className={card}><h3 className="font-semibold">Content Library</h3><p className="mt-2 text-sm text-vds-muted">Reusable draft metadata stays in the existing governed recommendation and asset architecture. No new content is stored from this view.</p><p className="mt-4 text-xs text-vds-muted">{data.recommendations.length} existing recommendation metadata records · {data.contentCalendar.length} planning metadata records</p></section></div>
  </section>;
}
