-- Sprint 194: additive real-estate CRM intelligence and automation.
alter table public.leads add column if not exists pipeline_stage text not null default 'new' check(pipeline_stage in('new','contacted','qualified','interested','site_visit','negotiation','offer','won','lost'));
alter table public.leads add column if not exists next_recommended_action text not null default 'Qualify requirements';
alter table public.leads add column if not exists follow_up_due_at timestamptz;
create index if not exists leads_pipeline_followup_idx on public.leads(workspace_id,pipeline_stage,follow_up_due_at) where deleted_at is null;

create table if not exists public.crm_property_recommendations(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),workspace_id uuid not null references public.workspaces(id),
  lead_id uuid not null references public.leads(id) on delete cascade,property_id uuid not null references public.properties(id) on delete cascade,
  overall_score integer not null check(overall_score between 0 and 100),budget_score integer not null check(budget_score between 0 and 100),
  location_score integer not null check(location_score between 0 and 100),bedroom_score integer not null check(bedroom_score between 0 and 100),
  property_type_score integer not null check(property_type_score between 0 and 100),availability_score integer not null check(availability_score between 0 and 100),
  investment_score integer not null check(investment_score between 0 and 100),rental_score integer not null check(rental_score between 0 and 100),
  lifestyle_score integer not null check(lifestyle_score between 0 and 100),recommendation text not null,evidence jsonb not null default '[]'::jsonb,
  calculated_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(lead_id,property_id)
);
create index if not exists crm_recommendations_lead_score_idx on public.crm_property_recommendations(organization_id,workspace_id,lead_id,overall_score desc);
create index if not exists crm_recommendations_property_score_idx on public.crm_property_recommendations(organization_id,workspace_id,property_id,overall_score desc);
alter table public.crm_property_recommendations enable row level security;
create policy "crm_recommendations_workspace_read" on public.crm_property_recommendations for select to authenticated using(public.is_organization_member(organization_id)and public.current_workspace_role(workspace_id)is not null);

create or replace function public.refresh_lead_property_recommendations(p_lead_id uuid)returns integer language plpgsql security definer set search_path=public as $$declare l public.leads%rowtype;n integer;begin select*into l from public.leads where id=p_lead_id and deleted_at is null;if not found then return 0;end if;if auth.uid()is not null and public.current_workspace_role(l.workspace_id)is null then raise exception'insufficient CRM permission';end if;insert into public.crm_property_recommendations(organization_id,workspace_id,lead_id,property_id,overall_score,budget_score,location_score,bedroom_score,property_type_score,availability_score,investment_score,rental_score,lifestyle_score,recommendation,evidence,calculated_at,updated_at)
select l.organization_id,l.workspace_id,l.id,p.id,
round((budget_score*.22+location_score*.2+bedroom_score*.12+type_score*.14+availability_score*.12+investment_score*.07+rental_score*.06+lifestyle_score*.07))::integer,
budget_score,location_score,bedroom_score,type_score,availability_score,investment_score,rental_score,lifestyle_score,
case when round((budget_score*.22+location_score*.2+bedroom_score*.12+type_score*.14+availability_score*.12+investment_score*.07+rental_score*.06+lifestyle_score*.07))>=80 then'Excellent match — prioritize a viewing.'when round((budget_score*.22+location_score*.2+bedroom_score*.12+type_score*.14+availability_score*.12+investment_score*.07+rental_score*.06+lifestyle_score*.07))>=60 then'Strong match — share details and confirm interest.'else'Possible match — review trade-offs before sharing.'end,
jsonb_build_array(jsonb_build_object('factor','budget','score',budget_score),jsonb_build_object('factor','location','score',location_score),jsonb_build_object('factor','bedrooms','score',bedroom_score),jsonb_build_object('factor','property_type','score',type_score),jsonb_build_object('factor','availability','score',availability_score)),now(),now()
from public.properties p cross join lateral(select case when l.budget is null then 50 when coalesce(p.sale_price,p.rental_price)<=l.budget then 100 when coalesce(p.sale_price,p.rental_price)<=l.budget*1.15 then 70 else 20 end budget_score,case when cardinality(l.preferred_locations)=0 then 50 when exists(select 1 from unnest(l.preferred_locations)x where lower(x)=lower(p.city)or lower(x)=lower(coalesce(p.locality,'')))then 100 else 20 end location_score,case when l.bedrooms is null then 50 when p.bedrooms=l.bedrooms then 100 when abs(coalesce(p.bedrooms,0)-l.bedrooms)=1 then 65 else 20 end bedroom_score,case when l.property_type is null then 50 when lower(l.property_type)=lower(p.property_type)then 100 else 20 end type_score,case when p.status='available'then 100 when p.status in('reserved','under_negotiation')then 45 else 0 end availability_score,case when lower(coalesce(l.buying_purpose,''))like'%invest%'then 85 else 55 end investment_score,case when p.listing_type='rent'or lower(coalesce(l.buying_purpose,''))like'%rental%'then 90 else 50 end rental_score,least(100,40+cardinality(p.amenities)*8)lifestyle_score)s
where p.organization_id=l.organization_id and p.workspace_id=l.workspace_id and p.deleted_at is null and p.status<>'archived'
on conflict(lead_id,property_id)do update set overall_score=excluded.overall_score,budget_score=excluded.budget_score,location_score=excluded.location_score,bedroom_score=excluded.bedroom_score,property_type_score=excluded.property_type_score,availability_score=excluded.availability_score,investment_score=excluded.investment_score,rental_score=excluded.rental_score,lifestyle_score=excluded.lifestyle_score,recommendation=excluded.recommendation,evidence=excluded.evidence,calculated_at=now(),updated_at=now();get diagnostics n=row_count;delete from public.crm_property_recommendations r where r.lead_id=l.id and not exists(select 1 from public.properties p where p.id=r.property_id and p.deleted_at is null and p.status<>'archived');return n;end$$;

create or replace function public.refresh_crm_recommendations_after_lead()returns trigger language plpgsql security definer set search_path=public as $$begin perform public.refresh_lead_property_recommendations(new.id);return new;end$$;
create or replace function public.refresh_crm_recommendations_after_property()returns trigger language plpgsql security definer set search_path=public as $$declare l record;begin for l in select id from public.leads where organization_id=new.organization_id and workspace_id=new.workspace_id and deleted_at is null loop perform public.refresh_lead_property_recommendations(l.id);end loop;return new;end$$;
drop trigger if exists refresh_crm_recommendations_lead on public.leads;create trigger refresh_crm_recommendations_lead after insert or update of budget,preferred_locations,bedrooms,property_type,buying_purpose on public.leads for each row execute function public.refresh_crm_recommendations_after_lead();
drop trigger if exists refresh_crm_recommendations_property on public.properties;create trigger refresh_crm_recommendations_property after insert or update of sale_price,rental_price,city,locality,bedrooms,property_type,status,amenities,deleted_at on public.properties for each row execute function public.refresh_crm_recommendations_after_property();

create or replace function public.prevent_crm_duplicates()returns trigger language plpgsql set search_path=public as $$begin if exists(select 1 from public.leads l where l.organization_id=new.organization_id and l.workspace_id=new.workspace_id and l.id<>coalesce(new.id,gen_random_uuid())and l.deleted_at is null and((new.email is not null and lower(l.email)=lower(new.email))or regexp_replace(l.phone,'\D','','g')=regexp_replace(new.phone,'\D','','g')or(new.whatsapp is not null and regexp_replace(l.whatsapp,'\D','','g')=regexp_replace(new.whatsapp,'\D','','g'))))then raise exception'DUPLICATE_LEAD_DETECTED';end if;return new;end$$;
drop trigger if exists prevent_duplicate_lead_write on public.leads;create trigger prevent_duplicate_lead_write before insert or update of email,phone,whatsapp on public.leads for each row execute function public.prevent_crm_duplicates();
create or replace function public.prevent_duplicate_crm_company()returns trigger language plpgsql set search_path=public as $$begin if exists(select 1 from public.crm_companies c where c.organization_id=new.organization_id and c.workspace_id=new.workspace_id and c.id<>coalesce(new.id,gen_random_uuid())and c.deleted_at is null and(lower(c.name)=lower(new.name)or(new.email is not null and lower(c.email)=lower(new.email))))then raise exception'DUPLICATE_COMPANY_DETECTED';end if;return new;end$$;
drop trigger if exists prevent_duplicate_company_write on public.crm_companies;create trigger prevent_duplicate_company_write before insert or update of name,email on public.crm_companies for each row execute function public.prevent_duplicate_crm_company();
create or replace function public.detect_crm_duplicates(p_workspace_id uuid,p_kind text,p_email text default null,p_phone text default null,p_whatsapp text default null,p_name text default null,p_exclude_id uuid default null)returns jsonb language plpgsql security definer set search_path=public as $$declare found_rows jsonb;begin if public.current_workspace_role(p_workspace_id)is null then raise exception'insufficient CRM permission';end if;if p_kind='lead'then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'matchedOn',case when p_email is not null and lower(email)=lower(p_email)then'email'when p_phone is not null and regexp_replace(phone,'\D','','g')=regexp_replace(p_phone,'\D','','g')then'phone'else'whatsapp'end)),'[]')into found_rows from public.leads where workspace_id=p_workspace_id and id<>coalesce(p_exclude_id,gen_random_uuid())and deleted_at is null and((p_email is not null and lower(email)=lower(p_email))or(p_phone is not null and regexp_replace(phone,'\D','','g')=regexp_replace(p_phone,'\D','','g'))or(p_whatsapp is not null and regexp_replace(whatsapp,'\D','','g')=regexp_replace(p_whatsapp,'\D','','g')));else select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'matchedOn',case when p_name is not null and lower(name)=lower(p_name)then'name'else'email'end)),'[]')into found_rows from public.crm_companies where workspace_id=p_workspace_id and id<>coalesce(p_exclude_id,gen_random_uuid())and deleted_at is null and((p_name is not null and lower(name)=lower(p_name))or(p_email is not null and lower(email)=lower(p_email)));end if;return jsonb_build_object('duplicate',jsonb_array_length(found_rows)>0,'matches',found_rows);end$$;

create or replace function public.automate_lead_projection()returns trigger language plpgsql security definer set search_path=public as $$declare title text;begin if tg_op='INSERT'then title:='Lead Created';else if old.status is distinct from new.status then title:='Status Changed';elsif old.company_id is distinct from new.company_id then title:='Company Assigned';elsif old.assigned_agent_id is distinct from new.assigned_agent_id then title:='Assignment Changed';elsif old.lead_score is distinct from new.lead_score then title:='Score Changed';end if;end if;if title is not null then insert into public.activity_events(organization_id,workspace_id,event_type,title,description,actor_id,related_type,related_id,metadata)values(new.organization_id,new.workspace_id,lower(replace(title,' ','.')),title,case when tg_op='UPDATE'then concat('CRM value changed from ',coalesce(old.status,old.pipeline_stage,'unassigned'),' to ',coalesce(new.status,new.pipeline_stage,'unassigned'))else'Lead entered the CRM' end,auth.uid(),'lead',new.id,jsonb_build_object('pipeline_stage',new.pipeline_stage,'score',new.lead_score));end if;new.pipeline_stage:=case new.status when'new'then'new'when'contacted'then'contacted'when'qualified'then'qualified'when'meeting_scheduled'then'interested'when'viewing_scheduled'then'site_visit'when'negotiation'then'negotiation'when'won'then'won'when'lost'then'lost'else new.pipeline_stage end;new.next_recommended_action:=case new.pipeline_stage when'new'then'Call Today'when'contacted'then'Schedule Follow-up'when'qualified'then'Send Brochure'when'interested'then'Book Site Visit'when'site_visit'then'Request Documents'when'negotiation'then'Negotiate Price'when'offer'then'Close Deal'when'lost'then'Mark Lost'when'won'then'Close Deal'else'Qualify requirements'end;new.follow_up_due_at:=case when new.pipeline_stage in('won','lost')then null else coalesce(new.follow_up_due_at,now()+interval'1 day')end;return new;end$$;
drop trigger if exists automate_lead_projection_before_write on public.leads;create trigger automate_lead_projection_before_write before insert or update of status,company_id,assigned_agent_id,lead_score on public.leads for each row execute function public.automate_lead_projection();

create or replace function public.automate_site_visit_lead()returns trigger language plpgsql security definer set search_path=public as $$begin if new.lead_id is not null then update public.leads set pipeline_stage='site_visit',next_recommended_action='Request Documents',last_activity_at=now()where id=new.lead_id and pipeline_stage not in('won','lost');insert into public.activity_events(organization_id,workspace_id,event_type,title,actor_id,related_type,related_id,metadata)values(new.organization_id,new.workspace_id,'property.viewed','Property Viewed',auth.uid(),'lead',new.lead_id,jsonb_build_object('property_id',new.property_id,'site_visit_id',new.id));end if;return new;end$$;
drop trigger if exists automate_site_visit_lead_after_write on public.site_visits;create trigger automate_site_visit_lead_after_write after insert or update of status on public.site_visits for each row execute function public.automate_site_visit_lead();

do $$declare l record;begin for l in select id from public.leads where deleted_at is null loop perform public.refresh_lead_property_recommendations(l.id);end loop;end$$;
revoke all on function public.refresh_lead_property_recommendations(uuid),public.detect_crm_duplicates(uuid,text,text,text,text,text,uuid)from public;
grant execute on function public.refresh_lead_property_recommendations(uuid),public.detect_crm_duplicates(uuid,text,text,text,text,text,uuid)to authenticated;
