-- Sprint 86.4: consent-aware, anonymized, tenant-scoped product intelligence.
create table if not exists public.product_intelligence_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,event_name text not null check(event_name in('page_viewed','feature_opened','lead_created','inventory_imported','campaign_generated','proposal_exported','site_visit_booked','report_exported','knowledge_article_opened','quick_action_used','ai_suggestion_accepted','ai_suggestion_dismissed','search_performed','feedback_submitted','error_recovered','retry_completed')),module text not null,path text not null,duration_ms integer,outcome text check(outcome in('success','failure','abandoned')),session_hash text not null,metadata jsonb not null default'{}',occurred_at timestamptz not null default now());
create table if not exists public.product_feedback(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,user_id uuid references auth.users(id),kind text not null check(kind in('bug_report','feature_request','improvement_idea','ux_issue','knowledge_correction','general_feedback')),title text not null,description text not null,priority text not null check(priority in('low','medium','high','critical')),rating integer check(rating between 1 and 5),resolution_quality integer check(resolution_quality between 1 and 5),screenshot_path text,status text not null default'open'check(status in('open','reviewing','planned','resolved','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists product_intelligence_scope_idx on public.product_intelligence_events(organization_id,workspace_id,occurred_at desc)include(event_name,module,duration_ms,outcome);
create index if not exists product_intelligence_module_idx on public.product_intelligence_events(workspace_id,module,event_name,occurred_at desc);
create index if not exists product_feedback_trends_idx on public.product_feedback(organization_id,workspace_id,kind,priority,created_at desc);
alter table public.product_intelligence_events enable row level security;
alter table public.product_feedback enable row level security;
revoke all on public.product_intelligence_events,public.product_feedback from anon,authenticated;
create policy "product intelligence admin read"on public.product_intelligence_events for select to authenticated using(public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','manager'));
create policy "product feedback admin read"on public.product_feedback for select to authenticated using(public.current_workspace_role(workspace_id)in('organization_owner','organization_admin','manager'));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('product-feedback','product-feedback',false,5242880,array['image/png','image/jpeg','image/webp'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "product feedback screenshot create"on storage.objects for insert to authenticated with check(bucket_id='product-feedback'and public.current_workspace_role((storage.foldername(name))[2]::uuid)is not null);
create policy "product feedback screenshot admin read"on storage.objects for select to authenticated using(bucket_id='product-feedback'and public.current_workspace_role((storage.foldername(name))[2]::uuid)in('organization_owner','organization_admin','manager'));

create or replace function public.record_product_intelligence_events(p_workspace_id uuid,p_events jsonb)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid;v_event jsonb;v_count integer:=0;v_session text;v_metadata jsonb;begin select organization_id into v_org from public.workspace_members where workspace_id=p_workspace_id and user_id=auth.uid()and status='active';if v_org is null then raise exception'workspace access required';end if;if jsonb_typeof(p_events)<>'array'or jsonb_array_length(p_events)<1 or jsonb_array_length(p_events)>50 then raise exception'invalid event batch';end if;for v_event in select*from jsonb_array_elements(p_events)loop if v_event->>'name'not in('page_viewed','feature_opened','lead_created','inventory_imported','campaign_generated','proposal_exported','site_visit_booked','report_exported','knowledge_article_opened','quick_action_used','ai_suggestion_accepted','ai_suggestion_dismissed','search_performed','feedback_submitted','error_recovered','retry_completed')or coalesce(v_event->>'path','')not like'/vayon/%'or coalesce(v_event->>'module','')!~'^[a-z0-9-]{1,60}$'then raise exception'invalid product event';end if;v_session=encode(extensions.digest(left(v_event->>'anonymousSessionId',200),'sha256'),'hex');v_metadata=jsonb_strip_nulls(jsonb_build_object('action',v_event->'metadata'->'action','topic',v_event->'metadata'->'topic','confidence',v_event->'metadata'->'confidence','contextRelevance',v_event->'metadata'->'contextRelevance','intent',v_event->'metadata'->'intent'));insert into public.product_intelligence_events(organization_id,workspace_id,event_name,module,path,duration_ms,outcome,session_hash,metadata)values(v_org,p_workspace_id,v_event->>'name',v_event->>'module',left(v_event->>'path',300),least(86400000,greatest(0,coalesce((v_event->>'durationMs')::integer,0))),nullif(v_event->>'outcome',''),v_session,v_metadata);v_count=v_count+1;end loop;insert into public.organization_audit_events(organization_id,workspace_id,actor_id,event_type,metadata)values(v_org,p_workspace_id,auth.uid(),'product_intelligence.batch_recorded',jsonb_build_object('event_count',v_count));end$$;

create or replace function public.submit_product_feedback(p_workspace_id uuid,p_feedback jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare v_org uuid;v_id uuid;v_kind text:=p_feedback->>'kind';v_screenshot text:=nullif(p_feedback->>'screenshotPath','');begin select organization_id into v_org from public.workspace_members where workspace_id=p_workspace_id and user_id=auth.uid()and status='active';if v_org is null then raise exception'workspace access required';end if;if v_kind not in('bug_report','feature_request','improvement_idea','ux_issue','knowledge_correction','general_feedback')or length(trim(p_feedback->>'title'))not between 3 and 160 or length(trim(p_feedback->>'description'))not between 10 and 4000 or p_feedback->>'priority'not in('low','medium','high','critical')then raise exception'invalid feedback';end if;if v_screenshot is not null and v_screenshot not like v_org::text||'/'||p_workspace_id::text||'/%'then raise exception'invalid screenshot scope';end if;insert into public.product_feedback(organization_id,workspace_id,user_id,kind,title,description,priority,rating,resolution_quality,screenshot_path)values(v_org,p_workspace_id,auth.uid(),v_kind,trim(p_feedback->>'title'),trim(p_feedback->>'description'),p_feedback->>'priority',nullif(p_feedback->>'rating','')::integer,nullif(p_feedback->>'resolutionQuality','')::integer,v_screenshot)returning id into v_id;insert into public.product_intelligence_events(organization_id,workspace_id,event_name,module,path,outcome,session_hash,metadata)values(v_org,p_workspace_id,'feedback_submitted','product-intelligence','/vayon/settings/product-intelligence','success',encode(extensions.digest(v_id::text,'sha256'),'hex'),jsonb_build_object('kind',v_kind,'priority',p_feedback->>'priority'));insert into public.organization_audit_events(organization_id,workspace_id,actor_id,event_type,subject_id,metadata)values(v_org,p_workspace_id,auth.uid(),'product_feedback.submitted',v_id,jsonb_build_object('kind',v_kind,'priority',p_feedback->>'priority','has_screenshot',v_screenshot is not null));return v_id;end$$;
revoke all on function public.record_product_intelligence_events(uuid,jsonb),public.submit_product_feedback(uuid,jsonb)from public;
grant execute on function public.record_product_intelligence_events(uuid,jsonb),public.submit_product_feedback(uuid,jsonb)to authenticated;
