-- Sprint 181: secure Google Calendar synchronization using existing scheduling tables.
create or replace function public.update_google_calendar_permissions(p_workspace_id uuid,p_permissions jsonb)returns void language plpgsql security definer set search_path=public as $$
declare v_org uuid;v_provider uuid;begin
 if not public.can_manage_integrations(p_workspace_id)then raise exception'insufficient integration permission';end if;
 if not(p_permissions?&array['readCalendar','createEvents','updateEvents','meetingSuggestions','reminderSuggestions'])then raise exception'invalid Calendar permissions';end if;
 select organization_id into v_org from public.workspaces where id=p_workspace_id;select id into v_provider from public.integration_providers where code='google_calendar'and active;
 update public.integration_connections set configuration=jsonb_set(configuration,'{permissions}',p_permissions,true),updated_by=auth.uid(),updated_at=now(),version=version+1 where organization_id=v_org and workspace_id=p_workspace_id and provider_id=v_provider and deleted_at is null;
 insert into public.integration_logs(organization_id,workspace_id,provider_id,actor_id,level,event,message,audit_event)values(v_org,p_workspace_id,v_provider,auth.uid(),'audit','google_calendar.permissions.updated','Google Calendar permissions updated',true);
end$$;

create or replace function public.sync_google_calendar_metadata(p_workspace_id uuid,p_events jsonb,p_selected_calendar text)returns jsonb language plpgsql security definer set search_path=public as $$
declare v_org uuid;v_provider uuid;v_actor uuid:=auth.uid();v_event jsonb;v_meeting uuid;v_existing uuid;v_lead uuid;v_deal uuid;v_property uuid;v_imported int:=0;v_updated int:=0;v_duplicates int:=0;v_linked int:=0;v_started timestamptz:=clock_timestamp();v_emails text[];v_metadata jsonb;
begin
 select organization_id into v_org from public.workspace_members where workspace_id=p_workspace_id and user_id=v_actor and status='active';if v_org is null or not public.can_use_operations(p_workspace_id)then raise exception'insufficient Calendar permission';end if;
 select id into v_provider from public.integration_providers where code='google_calendar'and active;if v_provider is null then raise exception'Google Calendar provider is unavailable';end if;
 if jsonb_typeof(p_events)<>'array'or jsonb_array_length(p_events)>1000 then raise exception'invalid Calendar synchronization batch';end if;
 for v_event in select value from jsonb_array_elements(p_events)loop
  if coalesce(v_event->>'externalId','')=''or coalesce(v_event->>'calendarId','')=''or nullif(v_event->>'start','')is null or nullif(v_event->>'end','')is null then continue;end if;
  select related_id into v_existing from public.activity_events where organization_id=v_org and workspace_id=p_workspace_id and event_type='google_calendar.event.synced'and metadata->>'google_event_id'=v_event->>'externalId'and metadata->>'google_calendar_id'=v_event->>'calendarId'order by occurred_at desc limit 1;
  select coalesce(array_agg(lower(value->>'email')),array[]::text[])into v_emails from jsonb_array_elements(coalesce(v_event->'attendees','[]'));
  select id into v_lead from public.leads where organization_id=v_org and workspace_id=p_workspace_id and deleted_at is null and lower(email)=any(v_emails)order by updated_at desc limit 1;
  select id,property_id into v_deal,v_property from public.deals where organization_id=v_org and workspace_id=p_workspace_id and lead_id=v_lead and deleted_at is null order by updated_at desc limit 1;
  v_metadata=jsonb_build_object('google_event_id',v_event->>'externalId','google_calendar_id',v_event->>'calendarId','organizer',v_event->>'organizer','attendees',v_event->'attendees','location',v_event->>'location','conference_url',v_event->>'conferenceUrl','time_zone',v_event->>'timeZone','all_day',coalesce((v_event->>'allDay')::boolean,false),'invitation_pending',exists(select 1 from jsonb_array_elements(coalesce(v_event->'attendees','[]'))a where a->>'responseStatus'='needsAction'),'lead_id',v_lead,'deal_id',v_deal,'property_id',v_property,'task_ids',coalesce((select jsonb_agg(id)from public.tasks where organization_id=v_org and workspace_id=p_workspace_id and deleted_at is null and((related_type='lead'and related_id=v_lead)or(related_type='deal'and related_id=v_deal)or(related_type='property'and related_id=v_property))),'[]'::jsonb));
  if v_existing is null then
   insert into public.meetings(organization_id,workspace_id,title,meeting_type,starts_at,ends_at,status,related_type,related_id,notes,created_by,updated_by)values(v_org,p_workspace_id,left(coalesce(nullif(v_event->>'title',''),'Calendar event'),500),case when lower(coalesce(v_event->>'title',''))~'(viewing|inspection|open house)'then'customer'when v_lead is not null then'customer'else'internal'end,(v_event->>'start')::timestamptz,(v_event->>'end')::timestamptz,case when v_event->>'status'='cancelled'then'cancelled'else'scheduled'end,case when v_property is not null then'property'when v_deal is not null then'deal'when v_lead is not null then'lead'else null end,coalesce(v_property,v_deal,v_lead),nullif(v_event->>'description',''),v_actor,v_actor)returning id into v_meeting;
   insert into public.calendar_entries(organization_id,workspace_id,entry_type,source_id,title,starts_at,ends_at,status)values(v_org,p_workspace_id,'meeting',v_meeting,left(coalesce(nullif(v_event->>'title',''),'Calendar event'),500),(v_event->>'start')::timestamptz,(v_event->>'end')::timestamptz,case when v_event->>'status'='cancelled'then'cancelled'else'scheduled'end);
   insert into public.activity_events(organization_id,workspace_id,event_type,title,description,actor_id,related_type,related_id,metadata,occurred_at)values(v_org,p_workspace_id,'google_calendar.event.synced','Google Calendar event synchronized','Calendar metadata synchronized for scheduling and CRM context.',v_actor,'meeting',v_meeting,v_metadata,now());v_imported:=v_imported+1;
  else
   select id into v_meeting from public.meetings where id=v_existing and workspace_id=p_workspace_id and deleted_at is null;
   if v_meeting is null then v_duplicates:=v_duplicates+1;continue;end if;
   if exists(select 1 from public.meetings where id=v_meeting and title=left(coalesce(nullif(v_event->>'title',''),'Calendar event'),500)and starts_at=(v_event->>'start')::timestamptz and ends_at=(v_event->>'end')::timestamptz and status=case when v_event->>'status'='cancelled'then'cancelled'else'scheduled'end and notes is not distinct from nullif(v_event->>'description',''))then v_duplicates:=v_duplicates+1;else
    update public.meetings set title=left(coalesce(nullif(v_event->>'title',''),'Calendar event'),500),starts_at=(v_event->>'start')::timestamptz,ends_at=(v_event->>'end')::timestamptz,status=case when v_event->>'status'='cancelled'then'cancelled'else'scheduled'end,related_type=case when v_property is not null then'property'when v_deal is not null then'deal'when v_lead is not null then'lead'else related_type end,related_id=coalesce(v_property,v_deal,v_lead,related_id),notes=nullif(v_event->>'description',''),updated_by=v_actor,updated_at=now(),version=version+1 where id=v_meeting;
    update public.calendar_entries set title=left(coalesce(nullif(v_event->>'title',''),'Calendar event'),500),starts_at=(v_event->>'start')::timestamptz,ends_at=(v_event->>'end')::timestamptz,status=case when v_event->>'status'='cancelled'then'cancelled'else'scheduled'end,updated_at=now(),version=version+1 where entry_type='meeting'and source_id=v_meeting;v_updated:=v_updated+1;
   end if;
   update public.activity_events set metadata=v_metadata,occurred_at=now()where organization_id=v_org and workspace_id=p_workspace_id and event_type='google_calendar.event.synced'and related_id=v_meeting;
  end if;
  if v_lead is not null then v_linked:=v_linked+1;end if;
 end loop;
 update public.integration_connections set status='connected',last_sync_at=now(),configuration=jsonb_set(configuration,'{selectedCalendar}',to_jsonb(coalesce(nullif(p_selected_calendar,''),'primary')),true),updated_by=v_actor,updated_at=now(),version=version+1 where workspace_id=p_workspace_id and provider_id=v_provider and deleted_at is null;
 update public.integration_health set status='healthy',last_success_at=now(),last_failure_at=null,checked_at=now(),details=jsonb_build_object('incremental',true,'records_processed',v_imported+v_updated+v_duplicates)where workspace_id=p_workspace_id and provider_id=v_provider;
 insert into public.integration_sync_history(organization_id,workspace_id,provider_id,entity_type,direction,started_at,completed_at,duration_ms,status,records_processed)values(v_org,p_workspace_id,v_provider,'calendar_events','inbound',v_started,clock_timestamp(),extract(milliseconds from clock_timestamp()-v_started)::int,'completed',v_imported+v_updated);
 return jsonb_build_object('imported',v_imported,'updated',v_updated,'duplicates',v_duplicates,'linked',v_linked);
end$$;

create or replace function public.record_google_calendar_sync_failure(p_workspace_id uuid,p_reason text)returns void language plpgsql security definer set search_path=public as $$declare v_org uuid;v_provider uuid;begin if not public.can_use_operations(p_workspace_id)then raise exception'insufficient Calendar permission';end if;select organization_id into v_org from public.workspaces where id=p_workspace_id;select id into v_provider from public.integration_providers where code='google_calendar';update public.integration_health set status='degraded',last_failure_at=now(),checked_at=now(),retry_count=retry_count+1,details=jsonb_build_object('recovery','Retry synchronization or reconnect Google Calendar.','reason',left(p_reason,240))where workspace_id=p_workspace_id and provider_id=v_provider;insert into public.integration_logs(organization_id,workspace_id,provider_id,actor_id,level,event,message,audit_event)values(v_org,p_workspace_id,v_provider,auth.uid(),'error','google_calendar.sync.failed','Google Calendar synchronization needs attention',false);end$$;
revoke all on function public.update_google_calendar_permissions(uuid,jsonb),public.sync_google_calendar_metadata(uuid,jsonb,text),public.record_google_calendar_sync_failure(uuid,text)from public;
grant execute on function public.update_google_calendar_permissions(uuid,jsonb),public.sync_google_calendar_metadata(uuid,jsonb,text),public.record_google_calendar_sync_failure(uuid,text)to authenticated;
