export type ExecutionState="queued"|"running"|"waiting"|"paused"|"completed"|"cancelled"|"failed"|"timed_out"|"skipped";
export type ApprovalState="approval_required"|"approved"|"rejected"|"escalated"|"timed_out";
export type RuntimeAction="task.create"|"owner.assign"|"notification.create"|"email.queue"|"whatsapp.queue"|"sms.queue"|"ai.task.create"|"crm.record.update"|"meeting.schedule"|"report.generate"|"meeting.create"|"timeline.submit_proposal"|"email.send"|"calendar.create"|"document.reference"|`provider.${string}`;
export interface RetryPolicy{readonly maxAttempts:number;readonly baseDelayMs:number;readonly maxDelayMs:number;readonly retryableCodes:readonly string[]}
export interface ExecutionContext{readonly organizationId:string;readonly workspaceId:string;readonly actorId:string;readonly correlationId:string;readonly trigger:"manual"|"schedule"|"event";readonly triggeredAt:string;readonly permissions:readonly string[];readonly variables:Readonly<Record<string,unknown>>}
export interface RuntimeStep{readonly id:string;readonly nodeId:string;readonly action:RuntimeAction;readonly input:Readonly<Record<string,unknown>>;readonly dependencies:readonly string[];readonly approvalRequired:boolean;readonly timeoutMs:number;readonly retryPolicy:RetryPolicy}
export interface RuntimePlan{readonly workflowId:string;readonly workflowVersion:number;readonly published:true;readonly steps:readonly RuntimeStep[]}
export interface ExecutionCheckpoint{readonly sessionId:string;readonly stepId:string;readonly sequence:number;readonly state:ExecutionState;readonly outputs:Readonly<Record<string,unknown>>;readonly recordedAt:string}
export interface ExecutionHistoryEntry{readonly id:string;readonly sessionId:string;readonly sequence:number;readonly type:"started"|"step_started"|"step_completed"|"completed"|"failed"|"cancelled"|"approval_required"|"approved"|"rejected"|"escalated"|"timed_out"|"retry_scheduled"|"resumed";readonly occurredAt:string;readonly stepId?:string;readonly durationMs?:number;readonly attempt?:number;readonly code?:string;readonly metadata:Readonly<Record<string,unknown>>}
export interface ApprovalRecord{readonly id:string;readonly sessionId:string;readonly stepId:string;readonly state:ApprovalState;readonly requestedAt:string;readonly decidedAt?:string;readonly decidedBy?:string;readonly reason?:string}
export interface ExecutionSession{readonly id:string;readonly plan:RuntimePlan;readonly context:ExecutionContext;readonly state:ExecutionState;readonly currentStepId?:string;readonly attempts:Readonly<Record<string,number>>;readonly outputs:Readonly<Record<string,unknown>>;readonly createdAt:string;readonly updatedAt:string;readonly completedAt?:string;readonly cancelledAt?:string;readonly failure?:{readonly code:string;readonly message:string}}
export interface ActionResult{readonly status:"completed"|"waiting"|"skipped";readonly output:Readonly<Record<string,unknown>>;readonly providerLatencyMs?:number}
