"use client";
import { useState } from "react";
import { Button } from "@/features/platform/design-system";
import type { AuditCheck, LaunchReadinessSnapshot } from "../contracts";
const card = "rounded-3xl border border-vds-border bg-vds-surface p-5 backdrop-blur-xl";
export default function LaunchReadinessSecondary({ data }: { data: LaunchReadinessSnapshot }) { const [section, setSection] = useState<"journey"|"providers"|"production"|"issues">("journey"); return <section aria-labelledby="diagnostics-title" className={card}><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-vds-subtle">Readiness diagnostics</p><h2 id="diagnostics-title" className="mt-1 text-xl font-semibold">Evidence behind the score</h2></div><div className="flex flex-wrap gap-1 rounded-xl bg-vds-subtle p-1" role="tablist" aria-label="Readiness diagnostics">{(["journey","providers","production","issues"] as const).map((item) => <Button key={item} role="tab" variant={section === item ? "secondary" : "ghost"} size="sm" aria-selected={section === item} onClick={() => setSection(item)} className="capitalize">{item}</Button>)}</div></div><div className="mt-5" role="tabpanel">{section === "journey" && <Journey checks={data.journey}/>} {section === "providers" && <Grid checks={data.providerHealth.map((item) => ({ title:item.component, state:item.state === "healthy" ? "Complete" : item.state === "misconfigured" ? "Blocked" : "Needs Attention", detail:item.diagnostic }))}/>} {section === "production" && <Grid checks={[{title:"Environment",state:"Complete",detail:data.build.environment},{title:"Version",state:"Complete",detail:data.build.version},...data.checks.filter((item) => ["Deployment","Performance","Security"].includes(item.category)).slice(0,12).map(view)]}/>} {section === "issues" && <Issues data={data}/>}</div></section>; }
function Journey({ checks }: { checks: readonly AuditCheck[] }) { const wanted = ["Signup","Workspace Creation","Onboarding","AI Setup","First AI Recommendation"], selected = wanted.map((label) => checks.find((item) => item.label === label)).filter((item): item is AuditCheck => Boolean(item)).map(view); return <Grid checks={[...selected,{title:"Founder Dashboard",state:"Needs Attention",detail:"Route and service coverage exists; production end-to-end execution remains release-gated."},{title:"Business Connections",state:"Needs Attention",detail:"Connection telemetry requires live production verification."},{title:"AI Conversations",state:"Needs Attention",detail:"Governed runtime coverage exists; beta-session acceptance remains outstanding."},{title:"Approval Center",state:"Needs Attention",detail:"Regression coverage exists; live acceptance remains outstanding."}]}/>; }
function Issues({ data }: { data: LaunchReadinessSnapshot }) { const issues = data.checks.filter((item) => item.status !== "pass").slice(0,18).map(view); return issues.length ? <Grid checks={issues}/> : <div className="rounded-2xl border border-vds-success bg-vds-success-soft p-8 text-center"><h3 className="text-lg font-semibold">Congratulations.</h3><p className="mt-2 text-sm text-vds-muted">Your platform is almost ready for launch. Complete the remaining production tasks before inviting customers.</p></div>; }
function Grid({ checks }: { checks: readonly {title:string;state:string;detail:string}[] }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{checks.map((item, index) => <article className="rounded-2xl border border-vds-border bg-vds-subtle p-4" key={`${item.title}-${index}`}><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-medium">{item.title}</h3><span className={`shrink-0 text-[11px] font-semibold uppercase ${item.state === "Complete" ? "text-vds-success" : item.state === "Blocked" ? "text-vds-danger" : "text-vds-warning"}`}>{item.state}</span></div><p className="mt-2 text-xs leading-5 text-vds-muted">{item.detail}</p></article>)}</div>; }
function view(item: AuditCheck) { return { title:item.label, state:item.status === "pass" ? "Complete" : item.status === "fail" ? "Blocked" : "Needs Attention", detail:item.evidence }; }
