import dynamic from "next/dynamic";
import { runLaunchReadinessAuditAction } from "../actions";
import { Button, ButtonLink } from "@/features/platform/design-system";
import type { AuditCheck, LaunchReadinessSnapshot } from "../contracts";

const Secondary = dynamic(() => import("./LaunchReadinessSecondary"));
const card = "rounded-3xl border border-vds-border bg-vds-surface p-5 shadow-vds-shadow backdrop-blur-xl";

export function LaunchReadinessDashboard({ data }: { data: LaunchReadinessSnapshot }) {
  const category = (name: string) => data.checks.filter((item) => item.category === name);
  const providerScore = data.providerHealth.length ? Math.round(data.providerHealth.filter((item) => item.state === "healthy").length / data.providerHealth.length * 100) : 0;
  const journeyScore = score(data.journey), securityScore = score(category("Security")), performanceScore = score(category("Performance"));
  const commercial = score(data.checks.filter((item) => item.category === "SEO" || item.category === "Launch checklist"));
  const documentation = checkScore(data, ["documentation", "support", "legal", "privacy", "terms"]);
  const aiReadiness = checkScore(data, ["openai", "ai workforce", "recommendation", "approval", "executive"]);
  const launchScore = Math.round((data.score + journeyScore + commercial + providerScore) / 4);
  const status = data.blockers.length ? "Launch blocked" : launchScore >= 85 ? "Ready for closed beta" : "Needs attention";
  return <main className="min-h-screen space-y-8 bg-vds-background p-4 text-vds-foreground sm:p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-5"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.24em] text-vds-primary">Founder operations · Beta launch</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Launch Readiness Center</h1><p className="mt-3 text-sm leading-6 text-vds-muted">One evidence-backed view of customer activation, production health, commercial readiness, and the work remaining before VAYON welcomes beta customers.</p><p className="sr-only">Production Score · Outstanding blockers · Provider health · Technical debt · Readiness history</p></div><div className="flex flex-wrap gap-2"><form action={runLaunchReadinessAuditAction}><Button type="submit">Run and record audit</Button></form><ButtonLink href="/api/launch-readiness/report" variant="outline">Export launch checklist</ButtonLink></div></header>
    <section aria-label="Launch decision" className={`${card} grid gap-6 lg:grid-cols-[220px_1fr]`}><ScoreRing score={launchScore} /><div className="self-center"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${data.blockers.length ? "bg-vds-danger-soft text-vds-danger" : "bg-vds-warning-soft text-vds-warning"}`}>{status}</span><h2 className="mt-4 text-2xl font-semibold">{data.blockers.length ? `${data.blockers.length} required ${data.blockers.length === 1 ? "blocker" : "blockers"} must be resolved.` : "VAYON is approaching customer-ready."}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-vds-muted">Scores only reflect recorded checks. Unverified production journeys remain visible and never count as complete.</p><p className="mt-4 text-xs text-vds-subtle">Evidence generated {new Date(data.generatedAt).toLocaleString()}</p></div></section>
    <section aria-label="Readiness scorecards" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Production" value={data.score} detail={data.build.environment}/><Metric label="Commercial readiness" value={commercial} detail="Website, legal, support and billing"/><Metric label="Security" value={securityScore} detail={`${category("Security").filter((item) => item.status === "pass").length} verified controls`}/><Metric label="Performance" value={performanceScore} detail="Measured budgets only"/><Metric label="AI readiness" value={aiReadiness} detail="Runtime, recommendations and approvals"/><Metric label="Integrations" value={providerScore} detail={`${data.providerHealth.filter((item) => item.state === "healthy").length}/${data.providerHealth.length} healthy`}/><Metric label="Customer journey" value={journeyScore} detail="Signup through approval"/><Metric label="Documentation & support" value={documentation} detail="Customer trust surfaces"/></section>
    <section className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><div className={card}><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-vds-subtle">Production checklist</p><h2 className="mt-1 text-xl font-semibold">What needs attention now</h2></div><span className="text-sm text-vds-muted">{data.checks.filter((item) => item.status !== "pass").length} open</span></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{priorityChecks(data).map((item) => <CheckRow key={item.id} item={item}/>)}</div></div><aside className={card} aria-label="Founder actions"><p className="text-xs uppercase tracking-[.18em] text-vds-subtle">Founder actions</p><h2 className="mt-1 text-xl font-semibold">Move launch forward</h2><nav className="mt-5 grid gap-2"><Action href="/platform/founder/integrations" label="Connect OpenAI and providers"/><Action href="/vayon/settings/billing/provider-health" label="Verify billing"/><Action href="/platform/operations" label="Open monitoring"/><Action href="/vayon/founder/approvals" label="Review Approval Center"/><Action href="/vayon/settings/members" label="Invite beta users"/><Action href="/vayon/dashboard" label="Launch demo workspace"/></nav></aside></section>
    <Secondary data={data}/>
  </main>;
}

function Metric({ label, value, detail }: { label: string; value: number; detail: string }) { return <article className={card}><div className="flex items-baseline justify-between gap-3"><h2 className="text-sm text-vds-muted">{label}</h2><strong className="text-2xl">{value}%</strong></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-vds-subtle" aria-label={`${label}: ${value}%`} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><div className="h-full rounded-full bg-vds-primary motion-reduce:transition-none" style={{ width: `${value}%` }}/></div><p className="mt-3 text-xs text-vds-subtle">{detail}</p></article>; }
function ScoreRing({ score: value }: { score: number }) { return <div className="relative mx-auto grid size-44 place-items-center rounded-full border-8 border-vds-accent-border bg-vds-elevated" role="img" aria-label={`Overall launch score: ${value}%`}><div className="text-center"><strong className="text-4xl text-vds-primary">{value}</strong><p className="mt-1 text-xs text-vds-subtle">out of 100</p></div></div>; }
function CheckRow({ item }: { item: AuditCheck }) { const label = item.status === "pass" ? "Complete" : item.status === "fail" ? "Blocked" : "Needs attention"; return <article className="rounded-2xl border border-vds-border bg-vds-subtle p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-medium">{item.label}</h3><span className={`shrink-0 text-[11px] font-semibold uppercase ${item.status === "pass" ? "text-vds-success" : item.status === "fail" ? "text-vds-danger" : "text-vds-warning"}`}>{label}</span></div><p className="mt-2 text-xs leading-5 text-vds-muted">{item.evidence}</p></article>; }
function Action({ href, label }: { href: string; label: string }) { return <a className="rounded-xl border border-vds-border bg-vds-subtle px-4 py-3 text-sm transition hover:border-vds-accent-border hover:bg-vds-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-vds-primary motion-reduce:transition-none" href={href}>{label}<span aria-hidden="true" className="float-right">→</span></a>; }
function points(status: AuditCheck["status"]) { return ({ pass: 100, warning: 60, not_verified: 25, fail: 0 })[status]; }
function score(checks: readonly AuditCheck[]) { return checks.length ? Math.round(checks.reduce((total, item) => total + points(item.status), 0) / checks.length) : 0; }
function checkScore(data: LaunchReadinessSnapshot, terms: readonly string[]) { return score(data.checks.filter((item) => terms.some((term) => `${item.label} ${item.id}`.toLowerCase().includes(term)))); }
function priorityChecks(data: LaunchReadinessSnapshot) { const preferred = ["OpenAI", "WhatsApp", "Billing", "Google", "Monitoring", "AI Workforce", "Documentation", "Support email", "Privacy Policy", "Terms"]; const matched = preferred.flatMap((label) => data.checks.filter((item) => item.label === label)); return [...data.blockers, ...matched].filter((item, index, all) => all.findIndex((candidate) => candidate.id === item.id) === index).slice(0, 12); }
