import "server-only";
import { founderContext } from "@/features/platform/founder/services/founder-context";
import { WorkflowAutomationService } from "@/features/platform/workflows/services/automation.service";
import { log } from "@/lib/observability/logger";
import { enterpriseWorkflowActions, enterpriseWorkflowTriggers, orchestrationAgents, sensitiveApprovalPolicies } from "../contracts";
export class WorkflowOrchestrationService {
  async snapshot(){const started=performance.now(),{user}=await founderContext(),workflow=await new WorkflowAutomationService().snapshot(),terminal=workflow.executions.filter(item=>["completed","failed"].includes(item.status)),failed=workflow.executions.filter(item=>item.status==="failed"),retries=workflow.executions.reduce((sum,item)=>sum+item.retryCount,0),running=workflow.executions.filter(item=>item.status==="running").length,waiting=workflow.executions.filter(item=>item.status==="waiting"||item.approvalStatus==="pending").length,queueDepth=workflow.executions.filter(item=>item.status==="queued").length,lastExecution=workflow.executions[0]?.startedAt??null,errorSummaries=failed.slice(0,6).map(item=>({id:item.id,workflow:item.workflowName,reason:item.failureReason??"Sanitized workflow failure",at:item.startedAt})),agents=orchestrationAgents.map((name,index)=>({name,status:running&&index===0?"running"as const:"idle"as const,taskCount:workflow.executions.filter(item=>item.aiParticipation&&item.id.charCodeAt(0)%orchestrationAgents.length===index).length,evidence:"Tasks use the existing tenant-scoped workflow and AI recommendation runtimes."}));const observability={successRate:workflow.metrics.successRate,failureRate:terminal.length?Math.round(failed.length/terminal.length*100):null,averageExecutionMs:workflow.metrics.averageDurationMs,retryCount:retries,queueDepth,lastExecution,errorSummaries,running,waiting,failed:failed.length};log("founder.workflow_orchestration.viewed",{actorId:user.id,workflows:workflow.definitions.length,executions:workflow.executions.length,latencyMs:Math.round(performance.now()-started)});return{workflow,triggers:enterpriseWorkflowTriggers,actions:enterpriseWorkflowActions,agents,policies:sensitiveApprovalPolicies,observability,generatedAt:new Date().toISOString()}}
}
export type WorkflowOrchestrationSnapshot=Awaited<ReturnType<WorkflowOrchestrationService["snapshot"]>>;
